### ISSUE TITLE
Contour based segmentation and DICOM-RT map conversion

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#1]
Contour based segmentation &amp; Radio therapy map conversion

**Comment by sarthakpati** [comment]
Will be dealt with post migration.

**Comment by sarthakpati** [comment]
There is an ITK program that can do this: http://insight-journal.org/browse/publication/887

Any chance this can be incorporated, @ashishsingh18, @AlexanderGetka-cbica?
