### ISSUE TITLE
Drawing tab extra space should be removed

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#1001]
**Describe the bug**
See screenshot.

**Screenshot of problematic UI**
![Untitled](https://user-images.githubusercontent.com/11719673/79695021-4678dd80-8242-11ea-95b1-07b548a87812.png)

**Expected UI**
![image](https://user-images.githubusercontent.com/11719673/79695065-82ac3e00-8242-11ea-90f6-0788240e8b09.png)

**CaPTk Version**
1.7.6 and current master

**Comment by ashishsingh18** [comment]
Things will look stretched if we try to remove the extra space. Here's how it would look:

![image](https://user-images.githubusercontent.com/43445206/87972858-a24b4080-ca95-11ea-9726-8438e669bf46.png)

**Comment by sarthakpati** [comment]
Okay, closing.
