### ISSUE TITLE
Geodesic training segmentation for brain tumor fails in v. 1.7.6 of CaPTK

### ISSUE THREAD

**Issue by mdv63oda** [CBICA/CaPTk#1005]
**Describe the bug**
Hi, I installed CaPTK v 1.7.6 recently because I had problems with loading several image sets in v 1.6.
I could do segmentation for three regions in the previous version I had, but now nothing happens when I run the training segmentation. It does not happen to finish and even prevents me close the application.
(I have minimal information for codes and I use the application for research purpose)

**To Reproduce**

1. draw in 3 colors.
2. run Geodesic training segmentation

**Windows 10.18362 64

**Comment by dboun** [comment]
Hi @mdv63oda 

I tried "Geodesic Training Segmentation" in 1.7.6 on Windows and it works. It is also pretty much the same implementation as in v1.6.

What I think happens here is that _it does not fail_, but that it is _slow_ for you. The execution tends to be slower if your images has >10M voxels and if they don't have isotropic spacing. Regardless on a decent machine it shouldn't take more than 4-5 minutes to run on any data. "Decent" here would be an i5+ processor with at least 8GB of RAM.

Also the less "seeding" you do, the faster it will run, but that's probably not the best place to cut corners. 

Please try to resample your images to isotropic spacing + not huge resolution, if that is ok with your study.

**Comment by mdv63oda** [comment]
Hi, Thats correct. I understood that most details is worst for training. So the segmentation should begin for the least obvious cuts. Thanks
