### ISSUE TITLE
Headers should be added in all feature files

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#1008]
In all the feature files, including raw feature files, scaled feature files, and selected feature files, appropriate feature and patient names should be added.
Needs to happen in SurvivalPredictor, Pseudoprogression, EGFRvIII, Recurrence

**Comment by ashishsingh18** [comment]
headers added in EGFRvIII and SurvivalPredictor, courtesy @saimarathore

**Comment by saimarathore** [comment]
headers should also be added in the following modules:
recurrence
training module
molecular subtypes

**Comment by saimarathore** [comment]
Added in SurvivalPredictor, Molecular subtype, Pseudo-progression, and EGFR. Since the features in recurrence are voel-based (instead of patient-based), it does not make sense to write data in feature files.

**Comment by saimarathore** [comment]
Added in SurvivalPredictor, Molecular subtype, Pseudo-progression, and EGFR. Since the features in recurrence are voxel-based (instead of patient-based), it does not make sense to write data in feature files.
