### ISSUE TITLE
4D non-perfusion images display only the first image of a sequence

### ISSUE THREAD

**Issue by sbakas** [CBICA/CaPTk#101]
Example image can be found in: https://www.dropbox.com/s/o2lv4a7q9xjlals/BRATS_703_img.nii.gz?dl=0

**Comment by sarthakpati** [comment]
This is working. As the specified image only has 4 "time points" (it is actually a stacked image containing the 4 structural modalities), the time-bar needs to be moved further to scroll through the image(s).
