### ISSUE TITLE
API in PerfusionDerivatives class should change to use cbica Utilities function

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#1012]
As long as all references to ```GetOneVolumeImage``` in the ```PerfusionDerivatives``` class are replaced with ```cbica::GetExtractedImages```, this issue will be fixed. The problem is in [this](https://github.com/CBICA/CaPTk/blob/master/src/applications/PerfusionDerivatives.h#L167) line. 

**We have tested utilities that should be used instead of per-class implementations.**

There is, however, a much bigger concern in this class. At [this](https://github.com/CBICA/CaPTk/blob/master/src/applications/PerfusionDerivatives.h#L375) location, the **6th** timepoint is getting processed. Why? Perhaps @saimarathore can shed some light on this.

Tagging @ashishsingh18 @MarkBergman-cbica

_Originally posted by @sarthakpati in https://github.com/CBICA/CaPTk/issues/1009#issuecomment-620356288_

**Comment by sarthakpati** [comment]
Tagging @saimarathore @ashishsingh18 @chiharusako

**Comment by ashishsingh18** [comment]
I believe this is fixed. Please re-open if needed.
