### ISSUE TITLE
Training Module requires label file and training parameters for testing mode

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#1025]
**Describe the bug**
Training module requires a label file and training parameters (-c, -s, -k,-p,-r)  for testing mode

**To Reproduce**
$ Training Module -f features.csv -m $modeldir -n 4 -o $outputdir

The required parameter 'l' is missing from the command line arguments you provided. See 'TrainingModule --help' for extended help.

$ Training Module -f features.csv -l labels.csv -m $modeldir -n 4 -o $outputdir 
The required parameter 'c' is missing from the command line arguments you provided. See 'TrainingModule --help' for extended help.

**Expected behavior**
Testing should only require the feature file, model dir, output dir, and -n 4

**CaPTk Version**
1.7.7nonrelease

**Desktop (please complete the following information):**
cbica-cluster

**Comment by saimarathore** [comment]
fixed this issue. Testing mode now requires feature file, model dir, output dir, and -n 4.
