### ISSUE TITLE
Graphics card conflict when installing CaPTk

### ISSUE THREAD

**Issue by sarahi03** [CBICA/CaPTk#103]
Installing this software caused conflict with my graphics card in Ubuntu 16.04, first the display flicked and then it was blank (maybe some conflict with nvidia GPU drivers, CUDA & cuDNN?), at the beginning I thought that had been another thing which caused the problem but I installed the software twice and the same issue happened.

My system:
Ubuntu 16.04 64 bits
$ lspci | grep -i nvidia
3b:00.0 VGA compatible controller: NVIDIA Corporation GP102 [TITAN Xp] (rev a1)
3b:00.1 Audio device: NVIDIA Corporation GP102 HDMI Audio Controller (rev a1)
%%%
Using nvidia binary driver version 384.130 from nvidia-384 (propietary, tested)
cuda-toolkit-9-0
cuDNN v7.0
%%%
CaPTk has been installed into:
          /usr/local/CaPTk_1.5/dir

**Comment by surrsurus** [comment]
Interesting issue, I've been using Nvidia cards for builds/runs and I haven't encountered any errors thus far but I do have some theories. I know for a fact that Nvidia support on linux is extremely lacking, and I would not be surprised if this is purely a driver issue.

My first suggestion would be to install more recent drivers from Nvidia, you can find them on their website. [Use this website](https://www.nvidia.com/Download/index.aspx?lang=en-us) and manually make sure to download the right drivers for your Titan xp, install those drivers, and then reboot and try again.

**Comment by surrsurus** [comment]
Actually @sarahi03 forget all of that for a second, you're using CaPTk version 1.5, you should really upgrade that to the latest linux release candidate for 1.6. Linux support is much better on the newest versions. download the latest RC here: https://www.nitrc.org/frs/downloadlink.php/11012. Install that and try again.

If after that it doesn't work, THEN upgrade your drivers.

**Comment by sarthakpati** [comment]
@sarahi03 the new version of CaPTk uses Qt5 versus Qt4 compared to the older version. This has fixed a lot of the Linux-specific issues we were seeing before and might go a long way towards mitigating whatever you were seeing as well.

**Comment by sarthakpati** [comment]
Hi @sarahi03 could you take a look at the new CaPTk 1.6.1 to see if it helps you regarding this? https://www.nitrc.org/frs/downloadlink.php/11131

**Comment by sarthakpati** [comment]
No update since 1.6.1 release; closing issue. Please reopen if this persists.
