### ISSUE TITLE
Self-hosted macOS build issues

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#1031]
**Describe the bug**

All details are for this run: https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=1463&view=logs&jobId=79636c1a-aae7-5b3a-7853-8a6d3a41631c&j=79636c1a-aae7-5b3a-7853-8a6d3a41631c&t=97e6077b-5065-54f1-420d-a225053560e5

**Comment by PhucNgo1711** [comment]
I've found the cause. I'm working on a fix for this. The self-hosted build created a new folder structure outside of the root CaPTk source and CMake was picking up the old structure.

**Comment by PhucNgo1711** [comment]
This is now fixed.
