### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#104]
The following (paraphrased) are coming up. These are essentially carry-overs from the previous version of VTK which should be fixed.

```
VTKIS_PICK macro redefinition
QVTKWidget deprecated
```

**Comment by sarthakpati** [comment]
> VTKIS_PICK

has been resolved. The latter is also related to the following message coming up when CaPTk is launched:

>Generic Warning: In e:\libscaptk\vtk-source\guisupport\qt\qvtkwidget.cxx, line 83
>QVTKWidget was deprecated for VTK 8.1 and will be removed in a future version.
> 
>Generic Warning: In e:\libscaptk\vtk-source\guisupport\qt\qvtkpaintengine.cxx, line 25
>QVTKPaintEngine was deprecated for VTK 8.1 and will be removed in a future version.

**Comment by ashishsingh18** [comment]
QVTKWidget is now replaced with QVTKOpenGLWidget. 
So the compiler warning for QVTKWidget is not an issue anymore.

**Comment by sarthakpati** [comment]
Closing this issue since the latest PR makes this irrelevant.
