### ISSUE TITLE
Breast mammograph file loads but I can not do any function on it

### ISSUE THREAD

**Issue by mdv63oda** [CBICA/CaPTk#1044]
I load the DICOM file.  LIBRA single image does not work correctly. 

**To Reproduce**
1- preprocessing or LIBRA single image
2-CaPTK exits with this message
![image](https://user-images.githubusercontent.com/64196091/82813330-af5b0300-9e49-11ea-978e-ef8a30f57823.png)

what should I do?

**CaPTk Version= latest**
Version information is found on Help > About

**Desktop (please complete the following information):**
 - OS: Windows 10
 

**Additional context**

**Comment by sarthakpati** [comment]
Could you please mention the version?

**Comment by sarthakpati** [comment]
Unable to replicate on 1.8.0.Alpha (I tried with all sample data):

![image](https://user-images.githubusercontent.com/11719673/83074233-d5e28f00-a03f-11ea-95fe-f2b1b00e5889.png)

**Comment by mdv63oda** [comment]
> Could you please mention the version?

1. 7. 6

**Comment by sarthakpati** [comment]
> > Could you please mention the version?
> 
> 1.7.6

Thank you. If you don't mind, could you also try in the latest test version?

https://github.com/CBICA/CaPTk#test-build-180alpha

If you are using your own data, it might be a function of something DICOM-related that we might need to dig in further.

**Comment by mdv63oda** [comment]
> Could you please mention the version?
> 
> 1.7.6
> 
> Thank you. If you don't mind, could you also try in the latest test version?
> https://github.com/CBICA/CaPTk#test-build-180alpha
> If you are using your own data, it might be a function of something DICOM-related that we might need to dig in further.

The same happens with the newer version.
Yes it is my own DICOM data

**Comment by omaghsoudi** [comment]
Thank you for your comment. As @sarthakpati mentioned, this should be related to your images and DICOM headers. 

Can you please do the follwoing two items?
1) Provide us a sample **anonymized** image by emailing it for us: software@cbica.upenn.edu
2) Try the sample image below:
[Case1.zip](https://github.com/CBICA/CaPTk/files/4704109/Case1.zip)

If it works for the sample image; we need to dig more into the problem as your images might be missing some needed information for LIBRA.

Thank you!

**Comment by mdv63oda** [comment]
Hi
The same error message appears with the sample image.
preprocessing also fails.

![image](https://user-images.githubusercontent.com/64196091/83345230-8b724400-a2c5-11ea-8f66-dc5a43b5024f.png)

**Comment by mdv63oda** [comment]
I changed the name of my folder to "breast" and it initialized!?

![image](https://user-images.githubusercontent.com/64196091/83345404-8c0bda00-a2c7-11ea-8719-3f1c4b2329d7.png)

**Comment by sarthakpati** [comment]
> and of course I had to rename it to *.dcm

I think this might have done it. I wonder if this is an effect of the way we are processing DICOM images.

**Comment by sarthakpati** [comment]
@mdv63oda, could you please reply to the question posted by @ashishsingh18 [[ref](https://github.com/CBICA/CaPTk/issues/1054#issuecomment-637031084)] (our resident DICOM expert) in #1054?

**Comment by ashishsingh18** [comment]
I see that the data is loaded by captk in all the screenshots attached in this issue.

**Comment by sarthakpati** [comment]
Closing because of lack of response. Please re-open with further clarifications.

**Comment by mdv63oda** [comment]
> Closing because of lack of response. Please re-open with further clarifications.

Hi, sorry for my very late response. The problem was resolved with the directory change and adding .dcm.
 Thank you.
