### ISSUE TITLE
BraTS pipeline as a standalone application

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#1045]
**Is your feature request related to a problem? Please describe.**
Having a stronger tie with the BraTS challenge will be great for participants and for CaPTk.

**Describe the solution you'd like**
A single CLI (maybe GUI as well) that takes 4 structural brain images and runs through the entire BraTS pipeline.

**Comment by sarthakpati** [comment]
Tagging @chiharusako

**Comment by chiharusako** [comment]
Below is the flow of the pipeline


  1.  Dicom to Nifti
  2.  LPS reorientation
  3.  N4 bias correction (intermediate step)
     *   No mask
     *   shrinkFactor=4
  4.  Registration (Greedy)
     *   N4-biascorrected t1/t2/flair to N4-biascorrected t1ce, save matrix
     *   Registration of N4-biascorrected LPS t1ce to SRI, save matrix
     *   Registration of LPS t1/t1ce/t2/flair (output of step 2) to SRI space using transformation matrix saved from 4a 4b. (only 1 interpolation for  all modalities)
  5.  Generating brain mask (for BraTS, we QC here, and correct if needed)
  6.  Skull stripping of registered Images

**Comment by sarthakpati** [comment]
>  5.  Generating brain mask (for BraTS, we QC here, and correct if needed)
>  6.  Skull stripping of registered Images

Based on discussions, it was decided that we will perform skull-stripping and let the user perform manual QC afterwards.

**Comment by sarthakpati** [comment]
Documentation added in https://github.com/CBICA/CaPTk/commit/c6992b9b4f4b90543b991c8c6d112984217715bc.

**Comment by sarthakpati** [comment]
Additional functionality: skip process if file exists.

**Comment by sarthakpati** [comment]
Additional functionality: put brain mask back to patient space.

**Comment by sarthakpati** [comment]
Additional functionality: brain tumor segmentation.

**Comment by sarthakpati** [comment]
Additional functionality: GUI option

**Comment by sarthakpati** [comment]
Add option to **not** do skull stripping and brain tumor extraction

**Comment by sarthakpati** [comment]
Done.
