### ISSUE TITLE
[Z-Scoring Normalization][CLI]  cannot run z scoring normalization from CLI as per documentation

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#1048]
**Describe the bug**
Cannot run z scoring normalization from CLI as per [documentation](https://cbica.github.io/CaPTk/preprocessing_zScoreNorm.html)

**To Reproduce**
1. From the command line, run the command as in example given in the document: https://cbica.github.io/CaPTk/preprocessing_zScoreNorm.html
2. See the error in attached screenshot below

**Expected behavior**
application should run and produce result

**Screenshots**
![image](https://user-images.githubusercontent.com/43445206/83188405-a1cda380-a0fd-11ea-934a-1e22b9b25658.png)

**CaPTk Version** 1.8.0 Alpha

**Desktop (please complete the following information):**
 - OS: Win 10 Enterprise, x64

**Comment by sarthakpati** [comment]
Done.
