### ISSUE TITLE
[z-scoring normalization][GUI] cannot run z-scoring normalization from GUI without mask

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#1049]
**Describe the bug**
Cannot run z-scoring normalization from GUI without mask.

**To Reproduce**
1. Open z-scoring normlization window from Preprocessing->z-scoring normalizer
2. Select Input image
3. Do not select mask( the [documentation ](https://cbica.github.io/CaPTk/preprocessing_zScoreNorm.html)says mask is optional)
4. Provide output path
5. Click on 'confirm'
6. See error as in screenshot below

**Expected behavior**
The application should run and produce result. The documentation says mask is optional.

**Screenshots**
![image](https://user-images.githubusercontent.com/43445206/83189025-93cc5280-a0fe-11ea-899f-83b10f2d3400.png)

**CaPTk Version**
1.8.0 alpha

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise, x64

**Comment by ashishsingh18** [comment]
If mask is required then documentation should be updated.

**Comment by sarthakpati** [comment]
Done.
