### ISSUE TITLE
Linux installer: re-word instructions

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#1050]
After running the Linux installer, there is an message about how to run CaPTk. Please change:

<To run CaPTk, locate to where CaPTk is installed and enter the command>

To:

<To run CaPTk, change to the directory where CaPTk is installed and enter the command>

**Comment by AlexanderGetka-cbica** [comment]
As a note, this change is included in Phuc's PR: https://github.com/CBICA/CaPTk/pull/1043
But that branch might not be merged for a while. This will be in my next PR just to ensure it gets into 1.8.0
