### ISSUE TITLE
[Deep Learning Segmentation][GUI] multiple popup messages about long running application

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#1051]
**Describe the bug**
Application throws multiple pop up messages about 'long running application'

**To Reproduce**
1. Go to Application->Deep Learning segmentation
2. Select 'Brain Tumor Segmentation'
3. Specify output directory
4. See popup messages (screenshots below)

**Expected behavior**
Only 1 popup message should be shown.

**Screenshots**
First popup message
![image](https://user-images.githubusercontent.com/43445206/83281368-fdec0280-a1a5-11ea-9dcc-8bdca53c74ee.png)

Second popup message
![image](https://user-images.githubusercontent.com/43445206/83281402-0cd2b500-a1a6-11ea-8c8f-819353046d5a.png)

**CaPTk Version** 1.8.0 Alpha

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise x64

**Comment by sarthakpati** [comment]
Done.
