### ISSUE TITLE
[Skull Stripping DeepLearning][GUI] multiple popup messages about long running application

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#1052]
**Describe the bug**
Application throws multiple popup messages about long running application.

**To Reproduce**
Same as #1051

**Expected behavior**
same as #1051

**Screenshots**
same as #1051

**CaPTk Version**: 1.8.0Alpha

**Desktop (please complete the following information):**
 - OS: Windows 10 enterprise x64

**Comment by sarthakpati** [comment]
Done.
