### ISSUE TITLE
DICOM files not getting read if not ending in ".dcm"

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#1054]
> and of course I had to rename it to *.dcm

I think this might have done it. I wonder if this is an effect of the way we are processing DICOM images.

_Originally posted by @sarthakpati in https://github.com/CBICA/CaPTk/issues/1044#issuecomment-636498769_

**Comment by ashishsingh18** [comment]
I am able to load dicom files without .dcm extension just fine in CaPTk. Tried this with Libra data. 
Is there a specific dicom file that is not loading?

**Comment by ashishsingh18** [comment]
This is not an issue. The original issue is #1044 for which we don't need to create another issue. Closing.
