### ISSUE TITLE
[Deep Learning Segmentation][CLI] Example given in documentation doesn't work

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#1057]
**Describe the bug**
 Example to run Deep Learning segmentation from command line, as shown in documentation doesn't work. 

**To Reproduce**
1. Replicate the example given [here](https://cbica.github.io/CaPTk/seg_DL.html)
2. See the error (screenshot attached)->It expects the output argument to be a directory, whereas the example shows it to be a specific file.

**Expected behavior**
Example should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/43445206/83434895-4f47fc00-a409-11ea-9b55-36c56effdfcc.png)

**CaPTk Version**: 1.8.0 Alpha

**Desktop (please complete the following information):**
 - OS: Win 10 Enterprise, x64

**Comment by AlexanderGetka-cbica** [comment]
Is this a documentation issue? Can we just change the docs to show an output directory, or do we need to add additional checks to the code? From the current code in DeepMedic.cxx it seems like the print statement here shouldn't even be happening... Did someone already address this?

**Comment by sarthakpati** [comment]
Providing screenshots is not helpful for CLI applications as there is no way for the developer to copy-paste and replicate the command and one needs to have the screenshot open in a tab and copy the command one-by-one in a rather painful process. 

In any case, https://github.com/CBICA/CaPTk/commit/afcce41e04022c8c9487bdbfb1ee1c0ea3bd23ea should have fixed it. Reopen if persists after next alpha.
