### ISSUE TITLE
Feature Extraction batch processing prepends the first subject name to all header fields

### ISSUE THREAD

**Issue by AlexanderGetka-cbica** [CBICA/CaPTk#1059]
**Describe the bug**
Batch-processed feature extraction output column headers all have the first subject ID prepended.

** To Reproduce ** 
1. create a csv file to pass as input to FeatureExtraction for batch processing (see attached -- I added to the template)
[batch_featureExtraction_4subjects_test.zip](https://github.com/CBICA/CaPTk/files/4714015/batch_featureExtraction_4subjects_test.zip)

2. Run feature extraction with e.g. 
FeatureExtraction.exe -b F:\work\batch_featureExtraction_4subjects_test.csv -o F:\work\FE-batchtest-out.csv -p F:\CaPTk_Full\1.8.0.Alpha\data\features\1_params_default.csv

3. Open output, see what's depicted in the screenshot below.

**Expected behavior**
I don't think the headers should have a specific subject name, especially not if it applies to every column. In part because it doesn't make sense for AAAB to have an AAAA-specific field, and in part because it makes the columns even harder to read at a glance.

**Screenshots**
Below screenshot shows the output -- the column headers (all of them, i checked) include AAAA0 despite presumably being applicable to all 4 subjects.
![image](https://user-images.githubusercontent.com/59709326/83465991-b682a200-a443-11ea-8c02-7ccc047c3890.png)

**CaPTk Version**
1.8.0.Alpha

**Desktop (please complete the following information):**
Windows 7 Home x64

**Comment by sarthakpati** [comment]
This is done.
