### ISSUE TITLE
only single-image dicom to nifti works on CLI

### ISSUE THREAD

**Issue by AlexanderGetka-cbica** [CBICA/CaPTk#1060]
**Describe the bug**
Running Dicom to Nifti on the GUI works fine -- it forces you to select the input and output as directories. But when running from CLI, only single file-to-file dicom to nifti conversion works. It fails if I put the input as  a directory , as is done in the documentation.
**To Reproduce**
1. run dicom to nifti as listed in the documentation:
```
Utilities.exe -i F:\work\SampleData\LIBRA_1.6.0\2\
 -o F:\work\SampleData\LIBRA_1.6.0\2\dicom-2-nifti-test-output.nii.gz -d2n
```

2. Receive error message:
`Input file 'F:\work\SampleData\LIBRA_1.6.0\2\' not found.`
Note: This is meant to be a directory, not a file, and the directory does exist.

**Expected behavior**
Like it is on the gui -- selecting a directory as input converts the file(s) inside it into a nifti image.

**CaPTk Version**
1.8.0.Alpha

**Desktop (please complete the following information):**
Windows 7 Home x64

**Comment by sarthakpati** [comment]
So, the correct usage for this is:

```powershell
Utilities.exe -i F:\work\SampleData\LIBRA_1.6.0\2\1.dcm -o F:\work\SampleData\LIBRA_1.6.0\2\dicom-2-nifti-test-output.nii.gz -d2n
```

Perhaps we should put a check when the user is passing a directory...

**Comment by sarthakpati** [comment]
Done.
