### ISSUE TITLE
Population Atlases application doesn't run on sample data

### ISSUE THREAD

**Issue by AlexanderGetka-cbica** [CBICA/CaPTk#1062]
**Describe the bug**
I tried running Population Atlases on the corresponding sample data, using [the documentation](https://cbica.github.io/CaPTk/Glioblastoma_Atlas.html) ) as a reference.

**To Reproduce**
GUI:
1. Download population atlas sample data
2. Select Population Atlases from the GUI
3. Try to click the browse button for the input and see that no file browser pops up. 
4. Manually type in the path to the csv.
5. Click the browse button for the atlas file and see nothing (seems to want a nifti image, provided atlasfile is a .gz)
6. Manually enter the atlasfile.gz path into the second line.
7. Specify an output directory (this part works fine.
8.  See error ("Please specify atleast one label for the atlases.")

CLI:
1. Run the command using the sample data csv as input, atlasfile.gz as atlas file, and some output dir.
e.g. 
```
PopulationAtlases.exe -i F:\work\SampleData\Popula
tionAtlases_1.6.1\input\labels.csv -a F:\work\SampleData\PopulationAtlases_1.6.1
\atlasfile.gz -o F:\work\SampleData\PopulationAtlases_1.6.1\test_output
```
2. Receive error: 
```
input file parsed. Number of entries: 51
Please specify atleast one label for the atlases.
```

**Expected behavior**
on GUI:
Browse buttons should do something when clicked. I assume the atlas file browse button should allow users to look for .gz files like the one included with the sample data.

on CLI: 
I should get a result. Or, if I'm doing it wrong, a more helpful error message.

The documentation seems a little unclear to me -- if this error is due to my misunderstanding it, perhaps it should be more specific/explicit about which files are used for what. 

**CaPTk Version**
1.8.0.Alpha

**Desktop (please complete the following information):**
Windows 7 Home x64

**Comment by saimarathore** [comment]
Thank you for providing detailed feedback. In response, i have:
1. fixed the button issue on the GUI
2. updated the sample data
3. improved the documentation 
4. tested both from CLI and GUI with updated sample data. it works. 

Please test with the updated data next time and let me know if there is any problem. i will then re-open the issue.
