### ISSUE TITLE
[Breast Segmentation][CLI][Documentation] cannot run breast segmentation from command line

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#1064]
**Describe the bug**
Cannot run breast segmentation from command line. Cannot find any documentation for this. The documentation [here](https://cbica.github.io/CaPTk/BreastCancer_breastSegmentation.html) doens't say anything about CLI.

**Expected behavior**
running from CLI should be possible

**CaPTk Version**: 1.8.0 Alpha

**Desktop (please complete the following information):**
 - OS: Win 10 Enterprise, x64

**Comment by sarthakpati** [comment]
Tagging @omaghsoudi

**Comment by omaghsoudi** [comment]
Do you mean running LIBRA (LIBRA module for breast density) or texture feature extraction (breast feature module)?

**Comment by ashishsingh18** [comment]
I mean Breast Segmentation. Please see the screenshot below

![image](https://user-images.githubusercontent.com/43445206/83574511-9adad280-a4fb-11ea-9559-768825d530a9.png)

Can this be run from command line?

**Comment by omaghsoudi** [comment]
In CLI, I cannot find breast segmentation module or LIBRA.
The only one, that I can find, is “BreastTexturePipeline”. Can you please clarify what is the module for the breast segmentation?

Thank you!
Bests,
Omid

**Comment by sarthakpati** [comment]
Hey Omid, perhaps this link is what you are looking for?

https://cbica.github.io/CaPTk/BreastCancer_breastSegmentation.html

**Comment by omaghsoudi** [comment]
Nope! That is for GUI.
What do you run on cluster to have this module (which should be LIBRA)?
For breast texture pipeline, we use:
captk BreastTexturePipeline

Bests,
Omid

**Comment by sarthakpati** [comment]
The command is [here](https://github.com/CBICA/CaPTk/blob/master/src/applications/BreastTexturePipeline/src/BreastTexturePipeline.cxx#L111), which basically translates to the following:

Windows:
```powershell
${libraExecutable} ${inputImage} ${outputDirectory}/temp/${inputImageName} true true
```

Linux:
```powershell
${libraExecutable} ${inputImage} ${outputDirectory}/temp/${inputImageName}
```

**Comment by omaghsoudi** [comment]
So, we do not have a module for that, do we? It needs path to be defined.

If that is the case, it can be so complicated for users to use it. We might need to make an executable module like others.

**Comment by sarthakpati** [comment]
> It needs path to be defined.

For MATLAB? We do this using the batch and shell scripts.

**Comment by omaghsoudi** [comment]
Can we have a module like “BreastTexturePipeline” to run it?
captk BreastTexturePipeline $input $mask $parameter OTHER-parameters

Lets say typing the following and working:
captk libra $input $output OTHER-parameters

**Comment by sarthakpati** [comment]
> We do not have such module for CLI

This ensures this particular issue can be closed. If a new CLI module named ```BreastSegmentation``` is needed, that can be explored in a separate feature request.

**Comment by ashishsingh18** [comment]
This issue was created because I was asked to test Breast Segmentation from the CLI as a part of our 1.8.0Alpha testing. It is fine that this is only available from the GUI, but perhaps we should update the documentation that this feature is only available from GUI, so the end user is not looking for it.

**Comment by sarthakpati** [comment]
> I was asked to test Breast Segmentation from the CLI

This is the source of confusion and it is mea culpa. I basically copy-pasted for all applications and didn't realize that this one didn't have a CLI. The [documentation](https://cbica.github.io/CaPTk/BreastCancer_breastSegmentation.html) has no references to a CLI, so that's fine.
