### ISSUE TITLE
[Utilities][CLI] Utilities need examples showing usage

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#1065]
**Describe the bug**
All of the Utilities need example usage information. Without this it is quite difficult for an end user to understand how to run some of these. The documentation [here](https://cbica.github.io/CaPTk/ht_utilities.html) doesn't have any usage examples. 

The documentation provided by running 
```Utilities -h ```
also needs clarity

**Expected behavior**
end user should have some examples to follow when using utilities

**CaPTk Version**: 1.8.0Alpha

**Desktop (please complete the following information):**
 - OS: Win 10 Enterprise, x64

**Comment by ashishsingh18** [comment]
I am looking at the webpage below and don't see any examples there. It would be good to have the examples here as we have for other applications.

![image](https://user-images.githubusercontent.com/43445206/83566475-1170d380-a4ee-11ea-91cc-c89dc831ff8e.png)

For example: if I want to find an example for resample, it is a pain to search through the list you posted.

If I look at help for resampling, I see this:
![image](https://user-images.githubusercontent.com/43445206/83567074-07030980-a4ef-11ea-9509-9bf5cb54aa37.png)

This is not clear enough. It doesn't show me an example, doesn't tell me what are required inputs, etc.

**Comment by sarthakpati** [comment]
In that screenshot, you left out the 2 following lines:

![image](https://user-images.githubusercontent.com/11719673/83568504-26029b00-a4f1-11ea-936c-3a4aa624ece5.png)

So you'd want to see the result of ```-h``` in the documentation? If yes, please go ahead and do so.

**Comment by sarthakpati** [comment]
Will add single example command for every function available under utilities, with specific examples for BraTS.

**Comment by sarthakpati** [comment]
Done.
