### ISSUE TITLE
[Training Module][GUI] Selecting Split train/Split Test configuration results in an error message

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#1068]
**Describe the bug**
Selecting Split train/Split Test configuration results in an error message as shown in attached screenshot

**To Reproduce**
1. Open training module from Applications->Training Module
2. Select Input data
3. Select SVM Classification Kernel to either Linear or RBF
4. Select configuration to either 'Split Train' or 'Split Test' using the radiobuttons
5. Select output directory
6. Click confirm->see error message to select crossvalidation, train test [none of these can be selected along with step 4 selection since they are all part of same radio button group]

**Expected behavior**
application should work

**Screenshots**
![image](https://user-images.githubusercontent.com/43445206/83555325-1d539a00-a4dc-11ea-9ad7-7d8de90c0db6.png)

**CaPTk Version**: 1.8.0 Alpha

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise, x64

**Comment by AlexanderGetka-cbica** [comment]
At a first glance, this seems like a purely GUI problem rather than algorithmic. 

I'll self-assign this for now and page @saimarathore if it turns out to run deeper than the UI.

**Comment by AlexanderGetka-cbica** [comment]
I believe this is fixed. Closing.
