### ISSUE TITLE
[Training Module][CLI] running from command line gives opencv error

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#1069]
**Describe the bug**
Running from command line with different parameters gives opencv error. Please see screenshots for 3 cases attached.

**To Reproduce**
1. Please see attached screenshots

**Expected behavior**
Application should run

**Screenshots**
case 1:
![image](https://user-images.githubusercontent.com/43445206/83557818-4d9d3780-a4e0-11ea-93c1-84ae99178723.png)

case 2:
![image](https://user-images.githubusercontent.com/43445206/83558422-06637680-a4e1-11ea-850b-d74893b85a4c.png)

case 3:
![image](https://user-images.githubusercontent.com/43445206/83558876-aa4d2200-a4e1-11ea-8386-721c2c6df538.png)

**CaPTk Version** :1.8.0 Alpha

**Desktop (please complete the following information):**
 - OS:Windows 10 Enterprise, x64

**Comment by saimarathore** [comment]
fixed the problem.

**Comment by sarthakpati** [comment]
Works after #1089
