### ISSUE TITLE
N3 bias correction produces an empty (or almost empty) image, also N4 not really available on GUI

### ISSUE THREAD

**Issue by AlexanderGetka-cbica** [CBICA/CaPTk#1072]
**Describe the bug**
Running bias correction (n3, n4 on gui, n3 on cli) creates a nearly-blank image rather than the expected bias-corrected image. 

Note: I found during this that GUI was internally calling n3 regardless of chosen type (my bad on that one, forgot to replace the default). This explains the difference in gui/cli behavior here, but not the blank image.

**To Reproduce**
From GUI:
1. Load an image
2. Click on Bias Correction
3. Select a mode and output path. Hit Confirm.
4. Wait for bias correction to finish. A blank image will be shown (actually, there are some values at the bottom, for me, but there is clearly something wrong with the output.)

**Expected behavior**
Bias corrected image should generally resemble its input, but with changes in intensity.

**CaPTk Version**
1.8.0.Alpha
**Desktop (please complete the following information):**
Windows 7 Home x64

**Additional context**
Fix is inbound for this, I found what was causing both problems.

**Comment by sarthakpati** [comment]
N4 on CLI also takes a very long time.

**Comment by AlexanderGetka-cbica** [comment]
My next PR has fixes for the issues mentioned here. I'm also trying to address #963 and hopefully get it into 1.8. 

> 
> 
> N4 on CLI also takes a very long time.

Unfortunately yes. I expected N3 to be significantly faster than N4, for reasons specified in #963 which I am also attempting to address. For testing purposes I turned down the parameters to lower the execution time, which revealed something I didn't expect: the CLI N4 is way, _way_ faster than the GUI N4. I'm particularly confused since it's invoking the same code in almost identical fashion. 

If anyone has any ideas why this might be slower on GUI, please let me know.
