### ISSUE TITLE
Population Atlas GUI issue

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#1075]
**Describe the bug**
Clicking on "Browse" does nothing.

**To Reproduce**
1. Open Applications > Population Atlas
2. Click on ```Browse```
3. See nothing

Ref: https://cbica.github.io/CaPTk/Glioblastoma_Atlas.html

**Expected behavior**
File browser should open up.

**CaPTk Version**
1.8.0.Alpha

**Comment by AlexanderGetka-cbica** [comment]
See #1062

**Comment by sarthakpati** [comment]
> See #1062

I guess Saima has fixed this, closing.
