### ISSUE TITLE
Population Atlas didn't run from CLI

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#1076]
**Describe the bug**
Tried with sample data.

**To Reproduce**
Command that I ran:
```powershell
.\PopulationAtlases.exe -i "C:\PopulationAtlases\atlas" -a "C:\PopulationAtlases\jakob_stripped_with_cere_lps_256256128.nii.gz" -o "C:\PopulationAtlases\test"
```

Ref: https://cbica.github.io/CaPTk/Glioblastoma_Atlas.html

**Expected behavior**
It should finish successfully.

**CaPTk Version**
1.8.0.Alpha

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10.18363

**Comment by saimarathore** [comment]
I could not understand what the output was, however, i tested on 1.8.0. Seems to be running from the CLI. Closing this issue.
