### ISSUE TITLE
Molecular subtype does not work in either GUI or CLI

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#1077]
**Describe the bug**
Followed documentation on sample data and didn't get any results.

**To Reproduce**
1. Selected the input directory.
2. Selected output directory
3. Click confirm and check results

Command:
```powershell
./MolecularSubtypePredictor.exe -t 0 -i C:/MolecularSubtypeInput -o C:/MolecularSubtypeModel
```
Ref: https://cbica.github.io/CaPTk/Glioblastoma_Molecular.html

**CaPTk Version**
1.8.0.Alpha

**Comment by MarkBergman-cbica** [comment]
Low priority

**Comment by saimarathore** [comment]
Fixed.
