### ISSUE TITLE
Pseudoprogression estimator does not work on either GUI or CLI

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#1078]
**Describe the bug**
Followed documentation on sample data and didn't get any results.

**To Reproduce**
1. Select the "Training Directory"
2. Select the "Output Directory" 
3. Click on 'Confirm'.
4. Output directory is empty (for both training and testing)

Command for Training:

```powershell
./PseudoProgressionEstimator.exe -t 0 -i C:/PseudoprogressionInputDirectory -o C:/outputDir
```

Command for Testing:

```powershell
./PseudoProgressionEstimator.exe -t 1 -i C:/PseudoprogressionInputDirectory -m C:/PseudoprogressionInputModelDirectory -o C:/outputDir
```

Ref: https://cbica.github.io/CaPTk/Glioblastoma_Pseudoprogression.html

**CaPTk Version**
1.8.0.Alpha

**Comment by sarthakpati** [comment]
I don't have any screenshots but I have added more information.

**Comment by sarthakpati** [comment]
The results folder is empty, as I have said in the report. Do you want a screenshot of an empty directory?

I just told you the full command I posted, which is far more helpful than posting screenshots of the terminal.

**Comment by ashishsingh18** [comment]
I want a screenshot of what you did on the GUI so I can reproduce. 

And the same thing on the command window. This should take you about 10 sec each.

**Comment by sarthakpati** [comment]
GUI:

![image](https://user-images.githubusercontent.com/11719673/83680278-c36fd480-a5ae-11ea-8285-d7f4687b109d.png)

![image](https://user-images.githubusercontent.com/11719673/83680426-f1edaf80-a5ae-11ea-9b9b-1b2f8cf663f7.png)

![image](https://user-images.githubusercontent.com/11719673/83680471-00d46200-a5af-11ea-9571-0f6a69e76a0b.png)

I am still not sure how this will help compared to the actual commands and steps I have illustrated on my original report.

**Comment by ashishsingh18** [comment]
For the cmd your screenshot doesn't show what happens when you run the commands.

However, this helped for the GUI side. I was able to run this and can confirm that this works and produces results. I am not sure what is not working on your side or if you forgot to click on 'confirm'.

**Comment by sarthakpati** [comment]
On the CLI:

![image](https://user-images.githubusercontent.com/11719673/83690549-f02be800-a5be-11ea-9d02-dc5abb8d4c5a.png)

On the GUI, I just saw the message "finished successfully" without any files in the output directory in either GUI or CLI mode.

I am not sure what I have _forgotten_ in this particular scenario.

**Comment by saimarathore** [comment]
@sarthakpati 
based on the screenshot that you have provided (Glioblastoma Pseudo-Progression Estimator), it seems like that you flipped model and test data folders when you ran from the GUI.

**Comment by sarthakpati** [comment]
> @sarthakpati
> based on the screenshot that you have provided (Glioblastoma Pseudo-Progression Estimator), it seems like that you flipped model and test data folders when you ran from the GUI.

That was a typo when I was trying to take a _screenshot_ in the middle of doing 10 other things. Anyway, here is what I actually used:

![image](https://user-images.githubusercontent.com/11719673/83755997-61f64700-a63c-11ea-8bfa-baaa5ddad9b1.png)

**Comment by sarthakpati** [comment]
The PR #1185 does **not** fix this.

**Comment by sarthakpati** [comment]
One of the reasons why testing is not working is this line: 

https://github.com/CBICA/CaPTk/blob/master/src/applications/PseudoProgressionEstimator.cpp#L276

Which looks for the file `chiharu_featurefile.csv` in the output directory, which it should not.

**Comment by sarthakpati** [comment]
> One of the reasons why testing is not working is this line:
> 
> https://github.com/CBICA/CaPTk/blob/master/src/applications/PseudoProgressionEstimator.cpp#L276
> 
> Which looks for the file `chiharu_featurefile.csv` in the output directory, which it should not.

This has now changed. Will post after I do a train session on the cluster.

**Comment by saimarathore** [comment]
this has been fixed
