### ISSUE TITLE
Silent crash whenever loading dicom images from the GUI

### ISSUE THREAD

**Issue by AlexanderGetka-cbica** [CBICA/CaPTk#1124]
**Describe the bug**
Loading dicom images, but not nifti images, from the GUI seems to crash CaPTk without any exception or error message.

**To Reproduce**
1. Start CaPTk GUI.
2. Go to File -> Load -> Image
3. Select any DICOM. I used the cases from the LIBRA sample data.
4. CaPTk GUI closes instantly, no popup, no error dialog, nothing.

**Expected behavior**
Expected DICOM to load in as it does normally, or to crash with some sort of alert.

**CaPTk Version**
Current master, and also Phuc's most recent PR build artifact (found [here](https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=1678&view=artifacts&type=publishedArtifacts))
**This issue is not present/replicable in 1.8.0.Alpha for me.**

**Desktop (please complete the following information):**
- OS: Windows 7 Home, x64

**Additional context**
I've tracked this down to occurring somewhere early on in guessImageType, defined starting at line 112 of CaPTkUtils.h. It calls cbica::getFilenameBase(). Looking at the implementation in cbicaUtilities.cpp, that function calls exit(EXIT_FAILURE) if the given filename doesn't exist. This causes the entire program to exit if it isn't found, which is sort of odd behavior.
Additionally, when I select Case4.dcm from the LIBRA sample data as the file, the "filename" passed to getFilenameBase() is "F:/work/SampleData/LIBRA_1.6.0/4", which is a directory, hence why it fails the "fileExists" check.

**Comment by AlexanderGetka-cbica** [comment]
@CBICA/devteam Can someone try to replicate this if you get a chance? I'd guess this is due to ambiguity in how dicoms can be loaded, either as a dir or individual file. In the morning I'll trace back to see where this starts using the directory rather than the user-selected file path.

**Comment by AlexanderGetka-cbica** [comment]
I just tried Pseudoprogression and this had the same silent exit symptom.
` fMainWindow::LoadQualifiedSubjectsFromGivenDirectoryForPseudoProgression` calls guessImageType() which in turn calls getFilenameBase(). But it seems like guessImageType() in this case is being fed just a filename, rather than an actual path. 

It seems like the reason for that is that Pseudoprogression is calling cbica::filesInDirectory with "returnFullPath" set to false, then passing the filename directly to guessImageType().

I may need someone to try to replicate this also (I did this by running pseudoprogression in testing mode), but it seems like others are getting past this step successfully...

**Comment by sarthakpati** [comment]
I am able to reproduce this in master.

**Comment by sarthakpati** [comment]
This was introduced as a fix for https://github.com/CBICA/CaPTk/issues/1067.

I have a workaround that touches the CBICA Toolkit (basically added a check for a directory), but need confirmation that it works. I will initiate a PR to get the build going.

**Comment by sarthakpati** [comment]
> This was introduced as a fix for #1067.
> 
> I have a workaround that touches the CBICA Toolkit (basically added a check for a directory), but need confirmation that it works. I will initiate a PR to get the build going.

Builds are ready: https://github.com/CBICA/CaPTk/pull/1125#issuecomment-644793543

**Comment by sarthakpati** [comment]
As mentioned by Alex [[ref](https://github.com/CBICA/CaPTk/pull/1125#issuecomment-644796017)], this has been fixed.
