### ISSUE TITLE
MASK/ROI images displaying as flipped

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#113]
MASK/ROI images loaded from File->Load->ROI or via LoadSlicerImages method show up as flipped. Possibly due to orientation mismatch in the rendering pipeline. Issue is seen in SBRT Lung Field workflow where mask image is manually loaded from File->Load->ROI followed by the computation. The generated image rendering is flipped.
Please see the image below.
![captkissue-flippedmaskdisplay](https://user-images.githubusercontent.com/43445206/46768336-cfaa6e00-ccb5-11e8-85de-0e253bec312a.PNG)

**Comment by sarthakpati** [comment]
@saimarathore also faced this issue.

**Comment by sarthakpati** [comment]
Possibly related to #102

**Comment by PhucNgo1711** [comment]
@sarthakpati @saimarathore  is this fixed yet?

**Comment by sarthakpati** [comment]
Fixed.
