### ISSUE TITLE
segmentation fault in FeatureExtraction module

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#1132]
Got the segmentation fault while extracting features from the following image.

**CaPTk Version**
1.8.0.Alpha

**Desktop (please complete the following information):**
 - OS: Windows

PATIENT_ID = ABHB_2014.12.14 
 Images= /cbica/home/rathores/Projects/MGMT/ChiharuSheets/FeatureExtraction/scaleddata/ABHB_2014.12.14/ABHB_2014.12.14_t1.nii.gz|/cbica/home/rathores/Projects/MGMT/ChiharuSheets/FeatureExtraction/scaleddata/ABHB_2014.12.14/ABHB_2014.12.14_t1Gd.nii.gz|/cbica/home/rathores/Projects/MGMT/ChiharuSheets/FeatureExtraction/scaleddata/ABHB_2014.12.14/ABHB_2014.12.14_t2.nii.gz|/cbica/home/rathores/Projects/MGMT/ChiharuSheets/FeatureExtraction/scaleddata/ABHB_2014.12.14/ABHB_2014.12.14_flair.nii.gz

MODALITIES = T1|T1CE|T2|FLAIR

ROIFILE =  /cbica/projects/brain_tumor/Brain_Tumor_2020/Projects/20200528_MGMT_heterogeneity_analysis/Data/ABHB_2014.12.14/ABHB_2014.12.14_LPS_rSRI_segmdm.nii.gz

SELECTED_ROI = 1|2|4
ROI_LABEL = NC|ED|ET

**Comment by sarthakpati** [comment]
Hey, it seems like you are trying to run a batch extraction for this image, is that right? 

If so, have you tried extracting this on a single-image mode?

**Comment by sarthakpati** [comment]
Tried with single image mode:

```
>$ /cbica/home/patis/testing/captkMyFork_1.8.0.Alpha/bin/FeatureExtraction -i /cbica/home/rathores/Projects/MGMT/ChiharuSheets/FeatureExtraction/scaleddata/ABHB_2014.12.14/ABHB_2014.12.14_t1.nii.gz,/cbica/home/rathores/Projects/MGMT/ChiharuSheets/FeatureExtraction/scaleddata/ABHB_2014.12.14/ABHB_2014.12.14_t1Gd.nii.gz,/cbica/home/rathores/Projects/MGMT/ChiharuSheets/FeatureExtraction/scaleddata/ABHB_2014.12.14/ABHB_2014.12.14_t2.nii.gz,/cbica/home/rathores/Projects/MGMT/ChiharuSheets/FeatureExtraction/scaleddata/ABHB_2014.12.14/ABHB_2014.12.14_flair.nii.gz -m /cbica/projects/brain_tumor/Brain_Tumor_2020/Projects/20200528_MGMT_heterogeneity_analysis/Data/ABHB_2014.12.14/ABHB_2014.12.14_LPS_rSRI_segmdm.nii.gz -t 1,2,3,4 -n Test -o ../../test_out.csv -d 1 -p ../data/features/1_params_default.csv
```
And I got the seg-fault as well:
```
[SNIP!]
2020:06:18,09:17:15;FeatureExtraction;patis;GLRLM Features for modality '4' and ROI '1_Full' calculated in 5532 milliseconds
Segmentation fault
```

**Comment by sarthakpati** [comment]
I have localized the error to the flair image.

**Comment by sarthakpati** [comment]
The issue is coming from GLSZM. If that feature family is disabled, this works without a hitch. I will continue investigating.

**Comment by sarthakpati** [comment]
> The issue is coming from GLSZM. If that feature family is disabled, this works without a hitch. I will continue investigating.

For whatever reason, GLSZM is coming out to be nans and infs, which is causing the assertion checks to get triggered. I would advise you to remove this feature family and conduct the analysis with out it (if not for the entire study then definitely for this _particular_ subject.

**Comment by sarthakpati** [comment]
Added some checks.
