### ISSUE TITLE
Alpha 1.8.0 Feature Extraction for Breast Image/Mask "itk::ERROR", exits with signal 9

### ISSUE THREAD

**Issue by ShyamDesai** [CBICA/CaPTk#1137]
I am trying to run Feature Extraction for a single 2d breast nifty image and mask. When I execute the Feature Extraction from command line, I receive the following output (with debug option):

[DEBUG] Performing dos2unix using CBICA TK function; doesn't do anything in Windows machines.
Single subject computation selected.
[DEBUG] Patient ID: XX
[DEBUG] Images: standardized_nii/4110623/4110623_L_CC_1.nii.gz
[DEBUG] Modalities: XXX
[DEBUG] Mask File: region_masks/4110623/4110623_L_CC_1/4110623_L_CC_1_lower.nii.gz
[DEBUG] ROI Values: all
[DEBUG] ROI Labels: all
No ROI values have been selected for patient_id 'XX', computation shall be done on all ROIs present in mask.
No ROI labels have been provided for patient_id 'XX', the ROI values will be used as labels instead.
[DEBUG] Initializing FE class.
2020:06:18,00:39:41;FeatureExtraction;desaish;ROI Values: all
2020:06:18,00:39:41;FeatureExtraction;desaish;ROI Values Size: 0
2020:06:18,00:39:41;FeatureExtraction;desaish;ROI Labels: all
2020:06:18,00:39:41;FeatureExtraction;desaish;ROI Labels Size: 0
[DEBUG] Checking if selected ROIs are present in mask or not.
[DEBUG] Param File: RaceSorting/captk_lattice_3D.csv
2020:06:18,00:39:41;FeatureExtraction;desaish;Checking mask validity (whether it is empty or not)
Unsupported binning type selected; defaulting to FixedBinNumber.
[DEBUG] Performing resampling of image(s) and mask.
[DEBUG] Writing resampled image(s) to the output directory.
Error occurred while trying to write the image 'features/image_XXX_resampled_0.065000-Linear_20200618003941_2e894c46.nii.gz': /cbica/home/patis/libs/captkDepends_dcmtk/ITK-source/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx:1375:
itk::ERROR: NiftiImageIO(0x3190520): Dimension(0) = 126031 is greater than maximum possible dimension 32767

**To Reproduce**
1. ssh -X username@cubic-login
2. module unload captk
3. module load captk/1.8.0.Alpha
4. FeatureExtraction -o features/features.csv -i standardized_nii/4110623/4110623_L_CC_1.nii.gz -m region_masks/4110623/4110623_L_CC_1/4110623_L_CC_1_lower.nii.gz -p RaceSorting/captk_lattice_3D.csv -n XX -t XXX -d 1
5. Above output, eventually terminates with signal 9

**Expected behavior**
Feature extraction should output to CSV, given a valid mask, image, and parameter file. 

**CaPTk Version**
CaPTk Alpha 1.8.0
/cbica/software/lab/captk/centos7/1.8.0.Alpha/bin/FeatureExtraction

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version 1809, OS Build 17763.1158

Please let me know if you need anymore information, thanks.

**Comment by sarthakpati** [comment]
Thanks for the report, @ShyamDesai!

I would like to _specifically_ thank for you pasting the command and error message you have used, which made it much easier to parse the message.

I have seen this issue before with Pathology images [[ref](https://github.com/CBICA/HistoReg/issues/5)] and the conclusion was that NIfTI standard has such a limitation and switching to a different format (MetaIO, NRRD) could be helpful. I am closing this issue, but feel free to respond the conversation and if it turns to something we can address with further development, we can reopen it.
