### ISSUE TITLE
Build documentation: incorrect order

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#1143]
**Describe the bug**
The Linux build documentation in 5_TechReference.txt has steps in the wrong order.

**To Reproduce**
```
[bergman@cubic-login2 comp_space]$ mkdir CaPTk && cd CaPTk 
[bergman@cubic-login2 CaPTk]$ git clone https://github.com/CBICA/CaPTk.git
[bergman@cubic-login2 CaPTk]$ git lfs fetch --all
Not in a git repository.
```

The next step in the documentation is "`cd CaPTk`" (the directory cloned from git).

**Expected behavior**
The "`git lfs`" command succeeds.

**Fix**

Change into the CaPTk directory (working directory cloned from the git repo) before running "`git lfs`".

**Comment by sarthakpati** [comment]
Done.
