### ISSUE TITLE
Bugs and features opens up 2 tabs

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#1145]
**Describe the bug**
Clicking on the "bugs and features" option opens up 2 tabs, which is confusion for users.

**To Reproduce**
1. Help > Support Links > Bugs and Features
2. 2 tabs open on browser

**Expected behavior**
Only the issues page should open.

**CaPTk Version**
Current Master

**Comment by sarthakpati** [comment]
Unsure if this can be replicated on other machines; need some help @CBICA/devteam

**Comment by PhucNgo1711** [comment]
I also got 2 tabs
https://github.com/CBICA/CaPTk/issues/new/choose
and 
https://github.com/CBICA/CaPTk/issues

**Comment by sarthakpati** [comment]
So the code is calling a single link: https://github.com/CBICA/CaPTk/blob/master/src/view/gui/fMainWindow.cpp#L1156

Confused why 2 tabs are opening up.

**Comment by ashishsingh18** [comment]
This happening because 2 signals are being thrown. One is as @sarthakpati pointed in earlier comment. The other is coming from:
https://github.com/CBICA/CaPTk/blob/c599167693746c54f48a9acba0f2364a01d27904/data/links.yaml#L7

Which one do we want to keep?

**Comment by sarthakpati** [comment]
The one from the file.

**Comment by ashishsingh18** [comment]
Sorry, which file? links.yaml?

**Comment by sarthakpati** [comment]
> Sorry, which file? links.yaml?

Ah yes, that one. Sorry, should have been clearer in my reply.
