### ISSUE TITLE
Linux LIBRA mask will not autoload

### ISSUE THREAD

**Issue by surrsurus** [CBICA/CaPTk#115]
When using LIBRA the mask will not load immediately after completion

**Comment by sarthakpati** [comment]
LIne **4963** of **fMainWindow.cpp** is reading the mask after LIBRA processing is done. Unsure why this is not working on Linux.

**Comment by surrsurus** [comment]
Will definitely take a look at this one today. There appears to be another issue on linux where LIBRA isn't even put in the install paths.

**Comment by sarthakpati** [comment]
This is a rendering issue (mask appears fine after a single click on the panel). Closing

**Comment by surrsurus** [comment]
I'm going to add a fix so that the on that line after the mask is loaded, a render is forced for unix operating systems. Will re-open until change is pushed.

**Comment by surrsurus** [comment]
Okay took me WAY longer than expected. Turns out simply forcing an `UpdateRenderWindows()` wouldn't cut it. You have to signal that the mask has been modified THEN render the slice. Now it works seamlessly as intended.

**Comment by surrsurus** [comment]
Fix pushed as of revision 4546
