### ISSUE TITLE
1.8.0-Alpha2, Linux: no preferences file created

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#1156]
**Describe the bug**
No preferences file is created in ~/.CaPTk.

Each invocation of CaPTk checks for OpenGL.

CaPTk works correctly if the preferences file already exists.

**To Reproduce**

`rm -rf ~/.CaPTk && _/path/to/_captk`

**Comment by AlexanderGetka-cbica** [comment]
Hmm, when I was adding the warning message I didn't notice that we only save on success...
Perhaps it's a good thing to keep checking for openGL until it's found? Not sure.

Some clarifying questions:
Do you have OpenGL > 3.2 on this machine? 
Are you running this from the CLI or GUI? (Usually the GUI saves preferences when closed).

**Comment by ashishsingh18** [comment]
@MarkBergman-cbica What flavor of Linux is this?

@AlexanderGetka-cbica OpenGL checks are not handled by QSettings preferences. See here: 
https://github.com/CBICA/CaPTk/blob/08415d4fb2dff88b61a04d6234b023c6795242df/src/CaPTk.cxx#L188

**Comment by MarkBergman-cbica** [comment]
I'm launching CaPTk from the command-line, but running the GUI.

I think that in the past, running CaPTk produced that warning about the OpenGL version only once, so I believe that either the required version of OpenGL has changed, or the behavior of not saving the negative result has changed.

Re. the version of Linux, version of OpenGL, etc.... it sure would be nice if https://github.com/CBICA/CaPTk/issues/418 was resolved, so I could supply all the info you need, in single step, in a machine-parsable format.

--------------------------
```
[bergman@huajiao ~]$ cat /etc/redhat-release 
Fedora release 30 (Thirty)
[bergman@huajiao ~]$ uname -a
Linux huajiao 5.6.13-100.fc30.x86_64 #1 SMP Fri May 15 00:36:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[bergman@huajiao ~]$ rpm -qa | egrep "google-chrome|firefox"
firefox-76.0-2.fc30.x86_64
google-chrome-stable-83.0.4103.116-1.x86_64
[bergman@huajiao ~]$ xdg-settings get default-web-browser
firefox.desktop
[bergman@huajiao ~]$ xdg-settings get default-url-scheme-handler
[bergman@huajiao ~]$ 
```

I'm using KDE 5, OpenGL 3.0 (Mesa 19.1.8).

**Comment by ashishsingh18** [comment]
Preference file is created at: $HOME/.config/
#418 is resolved.
