### ISSUE TITLE
Include OpenGL info in CaPTk log file

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#1160]
When launching the GUI, if the minimum version of OpenGL is not found, CaPTk displays a very informative error message.

The technical content of that message (OpenGl version info, etc) should be included in the CaPTk log file to enable users to easily supply accurate and comprehensive debugging info.

**Comment by MarkBergman-cbica** [comment]
Is this request met by https://github.com/CBICA/CaPTk/pull/1190

**Comment by ashishsingh18** [comment]
No, #1190 was not about writing info to log file. It can be easily added to the log though.

@AlexanderGetka-cbica Have you already done this? Or do you want me to take care of this?

**Comment by ashishsingh18** [comment]
This is done.
