### ISSUE TITLE
PerfusionPCA training is not working

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#1165]
**Describe the bug**
When trying to train a new model, there is virtually no messages on the console and the program exits without producing any output.

**To Reproduce**
```bash
(base) patis@/cbica/home/patis/testing/captkMyFork_1.8.0.Alpha2/bin>$ ./PerfusionPCA -t 0 -i ~/CaPTk/SampleData/PerfusionPCA/samples/ -o ~/testing/test_perfusionpca -n 5
Input File:/cbica/home/patis/CaPTk/SampleData/PerfusionPCA/samples/
Output Directory:/cbica/home/patis/testing/test_perfusionpca
```

**Expected behavior**
If there is an error encountered, a message should come up.

**CaPTk Version**
1.8.0.Alpha2

**Additional context**
- Using the sample data
- Can replicate on GUI

**Comment by ashishsingh18** [comment]
GUI side: When trying with new data, it says atleast 20 patients are needed.
![image](https://user-images.githubusercontent.com/43445206/86812471-0fe67e00-c04d-11ea-9f8e-a757b06b6862.png)

Tagging @saimarathore

**Comment by ashishsingh18** [comment]
CLI side: When trying with new data, this finished successfully.
![image](https://user-images.githubusercontent.com/43445206/86814290-31e10000-c04f-11ea-9f2d-3ca2b3ecacd3.png)
