### ISSUE TITLE
[Glioblastoma Survival Prediction Index ] Unable to download sample data

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#1169]
**Describe the bug**
Unable to download sample data for Glioblastoma Survival Prediction Index 

**To Reproduce**
1. Click on Help->Sample Data->Survival Predictor
2. See result -> nothing happens

**Expected behavior**
Sample data download should begin

**CaPTk Version**: 1.8.0Alpha2

**Desktop: Windows 10 x64

**Comment by sarthakpati** [comment]
Hey, can you try again? It might have been an intermittent NITRC issue.

**Comment by ashishsingh18** [comment]
> 
> 
> Hey, can you try again? It might have been an intermittent NITRC issue.

Looks like that. Working now.
