### ISSUE TITLE
[Survival][GUI] Training New model throws error

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#1170]
**Describe the bug**
Training new model for Survival throws error.

**To Reproduce**
1. Click on Application->Glioblastoma Survival Prediction Index
2. Select 'Train New Model'
3. Select sample data and output directory
4. Click Confirm 
5. This writes model to output directory, but we cannot close the dialog due to an error message popup [see screenshots]

**Expected behavior**
Training should complete without any errors

**Screenshots**

![image](https://user-images.githubusercontent.com/43445206/86523431-3bdde580-be3a-11ea-8b9c-edf04d5e1597.png)

![image](https://user-images.githubusercontent.com/43445206/86523422-28cb1580-be3a-11ea-80fc-aa1bf6859aa6.png)

**CaPTk Version**: 1.8.0Alpha2

OS: Windows 10 x64

Additional Info: log message
```
2020:07:04,21:01:44;CaPTk;SinghAs;Training on the given subjects failed. Error code : OpenCV(3.4.7) e:\libscaptk\opencv-source\modules\core\src\matrix.cpp:235: error: (-215:Assertion failed) s >= 0 in function 'cv::setSize'
```

**Comment by saimarathore** [comment]
@ashishsingh18 fixed the training part as well. will come in the next PR.

**Comment by ashishsingh18** [comment]
This now works from both GUI and CLI in Alpha3.
