### ISSUE TITLE
[Population Atlas][CLI+GUI] "Given data in the .csv file does not exist" on sample data

### ISSUE THREAD

**Issue by AlexanderGetka-cbica** [CBICA/CaPTk#1174]
**Describe the bug**
Running Population Atlases from the CLI or GUI using the current sample data does not produce output, and instead gives the message "Given data in the .csv file does not exist."

**To Reproduce**
1. Download the Population Atlases sample data (or continue if you already have it)
2. On CaPTk GUI go to Applications -> Population Atlases
3. Enter the labels.csv file in the sample data as input file, atlasfile.nii.gz as atlas file, and a new directory as output directory.
4. Hit confirm, see error.

This also happens from the cli using -i, -a, and -o params to set the above.

**Expected behavior**
Should produce output on sample data. 

**CaPTk Version**
1.8.0.Alpha2

**Desktop (please complete the following information):**
Windows 10 Pro x64

**Additional context**
The images that are looked for in the .csv file are in the images subdirectory of the sample -- but obviously the sample data csv contains a relative path to find those files since an absolute path wouldn't work among different computers.  Can we perhaps change it so that the code searches for these files relative to the location of the csv or atlas file if the path is relative?

**Comment by saimarathore** [comment]
this is mentioned in the documentation. user is intended to provide full paths to the images.
