### ISSUE TITLE
[DiffusionDerivatives][CLI] No output if specified output dir doesn't exist yet

### ISSUE THREAD

**Issue by AlexanderGetka-cbica** [CBICA/CaPTk#1175]
**Describe the bug**
Running diffusion derivatives from the CLI, if the output directory requested doesn't exist, then running the command creates it but does not produce other output. If it does exist, the application works correctly.

**To Reproduce**
1. Run diffusion derivatives with standard command: `.\DiffusionDerivatives.exe -i F:\work\SampleData\DiffusionDerivatives_1.6.1\AAAA_2007.01.21_dti_LPS.nii.gz -m F:\work\SampleData\DiffusionDerivatives_1.6.1\AAAA_2007.01.21_mask_LPS.nii.gz -b F:\work\SampleData\DiffusionDerivatives_1.6.1\AAAA_2007.01.21_dti_LPS.bval -g F:\work\SampleData\DiffusionDerivatives_1.6.1\AAAA_2007.01.21_dti_LPS.bvec -a 1 -f 1 -r 1 -t 1 -o F:\work\SampleData\DiffusionDerivatives_1.6.1\test-output`

If test-output dir doesn't exist, the program will create it and exit without performing any additional operation.

**Expected behavior**
It should create the folder as necessary and then place output in that folder.

**CaPTk Version**
1.8.0.Alpha2

**Desktop (please complete the following information):**
Windows 10 Pro x64

**Comment by sarthakpati** [comment]
Done.
