### ISSUE TITLE
[Utilities] File format conversion does not produce output

### ISSUE THREAD

**Issue by AlexanderGetka-cbica** [CBICA/CaPTk#1177]
**Describe the bug**
Running file format conversion as given in the How-To guide at https://cbica.github.io/CaPTk/ht_utilities.html produces no output. The usage suggests that merely specifying an output file with a different extension will perform this. But no operation is performed.

**To Reproduce**
`.\Utilities.exe -i F:\work\SampleData\PseudoProgressionEstimator\ABEM\CONVENTIONAL\ABEM_flair_pp.nii.gz -o F:\work\SampleData\PseudoProgressionEstimator\ABEM\TEST-FILEFORMAT-CONVERT.mha`

**Expected behavior**
Expected output of an .mha file, or at least an error message why it cannot be created.

**CaPTk Version**
1.8.0.Alpha2

**Desktop (please complete the following information):**
Windows 10 Pro x64

**Comment by sarthakpati** [comment]
The command had a `-cov` missing; I have updated the documentation (will update HTML during Beta).
