### ISSUE TITLE
[Utilities] j2e usage unclear

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#1179]
**Describe the bug**
Utilities j2e usage unclear. I tried it multiple times, but it gives an error. Perhaps my usage is incorrect. Not sure what input image it is expecting. See screenshots below.

Input 3D images:
![image](https://user-images.githubusercontent.com/43445206/86548540-caba3300-bf0a-11ea-9132-23de517f5ee8.png)

Input 4D image : output folder was empty in this case
![image](https://user-images.githubusercontent.com/43445206/86548574-e9202e80-bf0a-11ea-9c24-fa79ba177cde.png)

**Expected behavior**
It should run. If input  image is incorrect, it should not accept that input and give a message. When it finishes, it should show a 'successfully finished' message.

**CaPTk Version**
1.8.0Alpha2

**Desktop (please complete the following information):**
 - OS:Win 10 x64

**Comment by sarthakpati** [comment]
This is actually a simple issue with the usage. I have made some minor fixes and the following (along with their corresponding ones in Linux) work now:

```powershell
Utilities.exe -i C:\PseudoProgressionEstimator\ABEM\PERFUSION\ABEM_perfusion.nii.gz \
-o C:\test_j2e\ \ # folder that does not exist and output is written as C:\test_j2e\extractedImage_${slice}.nii.gz
-j2e 1

Utilities.exe -i C:\PseudoProgressionEstimator\ABEM\PERFUSION\ABEM_perfusion.nii.gz \
-o C:\test_j2e # output base name, so the outputs are written as 'test_j2e_${slice}.nii.gz
-j2e 1
```
