### ISSUE TITLE
[Nifti-to-Dicom] Nifti mask to Dicom-Seg produces error, crashes

### ISSUE THREAD

**Issue by AlexanderGetka-cbica** [CBICA/CaPTk#1183]
**Describe the bug**
Running the conversion from nifti mask to dicom-seg produces a rather confusing error message.
I first ran Dicom2Nifti to create a nifti file corresponding to Case1.dcm in the LIBRA sample data, then drew a mask and saved that to use as input to Nifti-to-DicomSeg.
The error I received was:

> W: DcmItem: Length of element (0b00,d6ec) is odd
E: DcmElement: Unknown Tag & Data (0b00,d6ec) larger (18632123) than remaining bytes in file
W: DcmItem: Dataset not in ascending tag order, at element (0b00,d6ec)
Failed to read F:\work\SampleData\LIBRA_1.6.0\1\mask.nii.gz. Skipping it.
E: DcmElement: Unknown Tag & Data (0a7b,2020) larger (1852785442) than remaining bytes in file
Failed to read F:\work\SampleData\LIBRA_1.6.0\1\Session1.json. Skipping it.
W: FrameOfReferenceUID (0020,0052) absent in FrameOfReferenceModule (type 1)
W: PositionReferenceIndicator (0020,1040) absent in FrameOfReferenceModule (type 2)
Condition failed: Tag not found in e:\vsts\_work\1\s\src\applications\utilities\dcmqi\include\dcmqi\converterbase.h:283

**To Reproduce**
JSON file (in zip format because GitHub is picky...):
[Session1.zip](https://github.com/CBICA/CaPTk/files/4879940/Session1.zip)
1. Using any method within CaPTk, run a dicom-to-nifti conversion on any DICOM file. I used LIBRA sample data. Draw a mask on the resulting NIFTI and save it.
2. Run the command using the nifti mask as -i, the original DICOM folder or image as -ds (it complains if it's not a directory but otherwise the output is the same if you specify an image), any output location as -o, and the JSON generated by http://qiicr.org/dcmqi/#/seg. (attached above):
`F:\CaPTk_Full\1.8.0.Alpha2\bin> .\Utilities.exe -i F:\work\SampleData\dcm2nifti-test-output\mask.nii.gz -o F:\work\SampleData\LIBRA_1.6.0\1\test-nifti-2-dicom-output\dicomsegoutput -ds F:\work\SampleData\LIBRA_1.6.0\1\ -dsJ F:\work\SampleData\LIBRA_1.6.0\1\Session1.json`

3. See error, see utilities.exe crash.

**Expected behavior**
Creation of output DicomSeg, or perhaps more helpful output. 
From the output, I gather that it rightfully recognizes that the .json and nifti mask are not dicom files to be read as part of -ds. But I have no idea what a "tag" is, or why this combination of files doesn't work otherwise.

**CaPTk Version**
1.8.0.Alpha2

**Desktop (please complete the following information):**
Windows 10 64-bit

**Comment by sarthakpati** [comment]
Ah yes, the DICOM-Seg conversion needs to the JSON to be defined "in conjunction" with the reference DICOM. I will add this information in the documentation, as well.

**Comment by sarthakpati** [comment]
So, all the errors are from deep within DCMQI and out of scope for us. I have added relevant links for DCMQI in the documentation.
