### ISSUE TITLE
PerfusionPCA[GUI] Training new model asks for atleast 20 subjects

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#1186]
GUI side: When trying with new data, it says atleast 20 patients are needed.
![image](https://user-images.githubusercontent.com/43445206/86812471-0fe67e00-c04d-11ea-9f8e-a757b06b6862.png)

Tagging @saimarathore

_Originally posted by @ashishsingh18 in https://github.com/CBICA/CaPTk/issues/1165#issuecomment-654978984_

**Comment by sarthakpati** [comment]
I don't think this is a bug (there are no crashes nor empty output generated). It is by algorithmic design that this application requires a minimum of **X** patients for a _somewhat_ accurate model. Closing.

**Comment by sarthakpati** [comment]
Didn't realize the the [CLI-side had changed](https://github.com/CBICA/CaPTk/issues/1165#issuecomment-654986166); reopening.

**Comment by saimarathore** [comment]
> GUI side: When trying with new data, it says atleast 20 patients are needed.
> ![image](https://user-images.githubusercontent.com/43445206/86812471-0fe67e00-c04d-11ea-9f8e-a757b06b6862.png)
> 
> Tagging @saimarathore
> 
> _Originally posted by @ashishsingh18 in [#1165 (comment)](https://github.com/CBICA/CaPTk/issues/1165#issuecomment-654978984)_

i have removed this check from GUI side and fixed the file naming convention problem in perfusionPCA. will come in the next PR.

**Comment by saimarathore** [comment]
fixed.
