### ISSUE TITLE
OpenMP for Mac OSX

### ISSUE THREAD

**Issue by muschellij2** [CBICA/CaPTk#119]
Trying to compile with `clang` from source on Mac OSX (version 10.12.6 (16G1510)).  OpenMP isn't installed on clang by default I do not believe: https://stackoverflow.com/questions/20321988/error-enabling-openmp-ld-library-not-found-for-lgomp-and-clang-errors.

I am upgrading to CMake 3.12 (used 3.10) to see if this will work: https://iscinumpy.gitlab.io/post/omp-on-high-sierra/

**Comment by sarthakpati** [comment]
Hey @muschellij2, we will have a macOS version of CaPTk out in our next release, which is slated for this year's RSNA. Giving a shout out to @PhucNgo1711, the developer working on the macOS deployment.

**Comment by PhucNgo1711** [comment]
Hi @muschellij2,

The macOS version of CaPTk will handle that issue. We are finalizing a few final steps for the macOS release. I will keep you posted.

**Comment by PhucNgo1711** [comment]
yes

**Comment by PhucNgo1711** [comment]
I'm trying something with the native gcc. I'll let you know if it works.
