### ISSUE TITLE
no browser shown when attempting download

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#1203]
**Describe the bug**
Linux (fedora 32), 1.8.0 A3.

> Going to Help => Sample Data => _any  selection_

results in nothing -- no browser window or tab is opened, no error message.

When attempting the download, bot Chrome & Firefox were open, both are able to connect to ftp://nitrc

```
[bergman@huajiao 1.8.0.Alpha3]$ xdg-settings get  default-url-scheme-handler
[bergman@huajiao 1.8.0.Alpha3]$ xdg-settings get  default-web-browser
firefox.desktop
```

**Comment by AlexanderGetka-cbica** [comment]
As a note, I cannot replicate this on my machine running Linux Ubuntu 18.04.

**Comment by ashishsingh18** [comment]
Browser won't be shown with the new download mechanism.
