### ISSUE TITLE
PerfusionDerivatives on GUI does nothing

### ISSUE THREAD

**Issue by AlexanderGetka-cbica** [CBICA/CaPTk#1211]
**Describe the bug**
Running PerfusionDerivatives from the CaPTk GUI brings up a dialog to enter information, but upon confirming doesn't execute anything or produce any errors.

**To Reproduce**
1. Open CaPTk GUI.
2. Select Applications -> Perfusion Derivatives
3. Enter input image and output directory as normal. I used the sample data.
4. Hit "Confirm". The dialog just closes with no other activity and output is not created.

**Expected behavior**
Some sort of indication that anything is happening -- a dialog saying "Perfusion Derivatives is now running, please wait", a progress indicator, or in the worst case, the program hanging until the algorithm is done (to be fair to this, the dialog does tell users that they will not be able to interact with CaPTk while it runs...)

**CaPTk Version**
Definitely occurs on:
1.8.0.Alpha3
1.8.0.Beta

**Desktop (please complete the following information):**
Windows 10 Pro x64 version 10.0.1.19041.1

**Additional context**
There is nothing logged in the global CaPTk log file for this session either. 
Also, worth noting: PerfusionDerivatives on the CLI typically finishes without a user-visible error if memory usage is too high to load the image. I checked for this -- this is not occurring/ is not the reason for this issue from the GUI.

**Comment by sarthakpati** [comment]
Can you provide the amount of memory available on the machine? I guess that would be useful information for @saimarathore

**Comment by AlexanderGetka-cbica** [comment]
Sure. I have 16GB total memory, 7GB of which is available just before I hit confirm.
I haven't determined an exact threshold that causes the CLI to fail, but closing my other programs (Firefox...) is sufficient. As I noted, though, the "out of memory" failure the CLI experiences writes log messages in the CaPTk session log. The "nothing happens" error when calling it from GUI doesn't do this.

**Comment by sarthakpati** [comment]
And I assume this is with the sample data?

**Comment by AlexanderGetka-cbica** [comment]
Yes -- Editing my original message to reflect that.

**Comment by saimarathore** [comment]
fixed the GUI issue.

**Comment by saimarathore** [comment]
also added the code to log error message.
