### ISSUE TITLE
DeepMedic not working on cluster CLI

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#1220]
**Describe the bug**
Skull-stripping using DeepMedic doesn't produce a mask

**To Reproduce**
Files are in: /cbica/home/sakoc/comp_space/lab/captk/180b/DM_ss

/cbica/software/lab/captk/centos7/1.8.0.Beta/bin/captk DeepMedic -i /cbica/home/sakoc/comp_space/lab/captk/180b/DM_ss/input/AAAC_2008.03.30_t1_LPS_rSRI.nii.gz,/cbica/home/sakoc/comp_space/lab/captk/180b/DM_ss/input/AAAC_2008.03.30_t1ce_LPS_rSRI.nii.gz,/cbica/home/sakoc/comp_space/lab/captk/180b/DM_ss/input/AAAC_2008.03.30_t2_LPS_rSRI.nii.gz,/cbica/home/sakoc/comp_space/lab/captk/180b/DM_ss/input/AAAC_2008.03.30_flair_LPS_rSRI.nii.gz -o /cbica/home/sakoc/comp_space/lab/captk/180b/DM_ss/output -md /cbica/software/lab/captk/centos7/1.8.0.Beta/data/deepMedic/saved_models/skullStripping

The program starts, normalizes images, then gets an ERROR here
ERROR: Caught exception from main process: Expected int32, got Dimension(48) of type 'Dimension' instead.
Traceback (most recent call last):
  File "deepMedic_test_cmdLnApi.py", line 241, in <module>
  File "deepmedic/frontEnd/testSession.py", line 92, in run_session
  File "deepmedic/neuralnet/cnn3d.py", line 460, in make_cnn_model
  File "deepmedic/neuralnet/pathways.py", line 320, in upsampleOutputToNormalRes
  File "deepmedic/neuralnet/pathways.py", line 64, in upsampleRcz5DimArrayAndOptionalCrop
  File "deepmedic/neuralnet/pathways.py", line 47, in repeatRcz5DimArrayByFactor
  File "site-packages/tensorflow/python/ops/gen_array_ops.py", line 2451, in reshape
  File "site-packages/tensorflow/python/framework/op_def_library.py", line 493, in apply_op
  File "site-packages/tensorflow/python/framework/op_def_library.py", line 490, in apply_op
  File "site-packages/tensorflow/python/framework/ops.py", line 741, in internal_convert_to_tensor
  File "site-packages/tensorflow/python/ops/array_ops.py", line 919, in _autopacking_conversion_function
  File "site-packages/tensorflow/python/ops/array_ops.py", line 881, in _autopacking_helper
  File "site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
  File "site-packages/tensorflow/python/framework/tensor_util.py", line 374, in make_tensor_proto
  File "site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
TypeError: Expected int32, got Dimension(48) of type 'Dimension' instead.

**Expected behavior**
generates a brain mask

**CaPTk Version**
1.8.0Beta

**Desktop (please complete the following information):**
cbica-cluster, cubic-login4

**Additional context**
input - 4 images in
/cbica/home/sakoc/comp_space/lab/captk/180b/DM_ss/input
log file
/cbica/home/sakoc/comp_space/lab/captk/180b/DM_ss/20200803_dm.log
produced output 
/cbica/home/sakoc/comp_space/lab/captk/180b/DM_ss/output

**Comment by chiharusako** [comment]
Also, same error using the brainTumorSegmentation model

**Comment by sarthakpati** [comment]
Are you seeing this issue on your local machine, as well?

**Comment by chiharusako** [comment]
It worked fine on Mac CLI

**Comment by sarthakpati** [comment]
> It worked fine on Mac CLI

That is very helpful information, thank you.

**Comment by MarkBergman-cbica** [comment]
Same error under Fedora 32, using the CaPTk 1.8.0Beta installer.

**Comment by sarthakpati** [comment]
> It worked fine on Mac CLI

Same for Windows GUI and CLI.

**Comment by sarthakpati** [comment]
I am not able to figure out what the error is referring to. I have reached out the original algorithm developer (Kostas from ICL) for clarification.

**Comment by sarthakpati** [comment]
I am getting this error even when the DM inference executable has been created on the cluster, as well. But on an Ubuntu machine, it seems to be working as expected.

**Comment by Kamnitsask** [comment]
Hello,

The main error, coming from TensorFlow, is this:

ERROR: Caught exception from main process: Expected int32, got Dimension(48) of type 'Dimension' instead.

thrown by a call of the TF "reshape" function, called by DeepMedic somewhere:
File "deepmedic/neuralnet/pathways.py", line 47, in repeatRcz5DimArrayByFactor
File "site-packages/tensorflow/python/ops/gen_array_ops.py", line 2451, in reshape

reshape expects an int32. Instead, it gets an argument that is of type "Dimension(48)". The type "Dimension" is a Tensorflow type, that TF uses to manage the dimensions of its tensors.

I am guessing that this has to do with the version of TensorFlow used, in combination with the version of DeepMedic used (the two being incompatible).

Can you please provide here what TensorFlow version is used in the Environment where the error occurs?

And, can you also provide the version of DeepMedic used in that environment?
(For DM, you can find version within the ./setup.py file of DM, or by providing here the number of the commit)

**Comment by sarthakpati** [comment]
> Can you please provide here what TensorFlow version is used in the Environment where the error occurs?

1.13.2

> And, can you also provide the version of DeepMedic used in that environment?

https://github.com/deepmedic/deepmedic/tree/436dd088df663c6ebaff83054c642529ad536707

The weird thing is, the *exact* setup is working for Windows and macOS.

**Comment by sarthakpati** [comment]
So, I made a [new executable](https://1drv.ms/u/s!AgvRZZtXCbbOnN8Ky_5MuuUhL9QcKw?e=h68xxy) but it unfortunately doesn't work on CentOS7. The failure is related to the appropriate version of GLIBC not getting found:
```bash
ImportError: /usr/lib64/libc.so.6: version `GLIBC_2.18' not found (required by /scratch/patis/_MEIO5uID2/libstdc++.so.6)
```

Anyway, I am trying to recompile this on CentOS7 to see if it helps.

**Comment by Kamnitsask** [comment]
Oh, so, we are talking about a single executable / package, exactly the same version of the tool and wrapped libraries (Tensorflow, DM, python, etc), but just tried on different OS? Interesting. I will have a look at the code if I notice anything, but this sounds weird.

**Comment by MarkBergman-cbica** [comment]
If DM (or, really tensorflow) requires GLIBC_2.18 (or higher), then why not create a containerized version (native Singularity container, or Docker container that can be imported into Singularity on the cluster)? That'll provide a different version of glibc.

**Comment by sarthakpati** [comment]
> If DM (or, really tensorflow) requires GLIBC_2.18 (or higher), then why not create a containerized version (native Singularity container, or Docker container that can be imported into Singularity on the cluster)? That'll provide a different version of glibc.

At this point, we are looking at a completely different deployment for the cluster, which I'd rather avoid...

**Comment by sarthakpati** [comment]
> Anyway, I am trying to recompile this on CentOS7 to see if it helps.

Tried this with the exact same version of libraries and I got the same error. ☹️

**Comment by MarkBergman-cbica** [comment]
> > If DM (or, really tensorflow) requires GLIBC_2.18 (or higher), then why not create a containerized version (native Singularity container, or Docker container that can be imported into Singularity on the cluster)? That'll provide a different version of glibc.
> 
> At this point, we are looking at a completely different deployment for the cluster, which I'd rather avoid...

Nope. I'm suggesting make the creation of {Docker|Singularity} containers a standard target.

**Comment by sarthakpati** [comment]
> > > If DM (or, really tensorflow) requires GLIBC_2.18 (or higher), then why not create a containerized version (native Singularity container, or Docker container that can be imported into Singularity on the cluster)? That'll provide a different version of glibc.
> > 
> > 
> > At this point, we are looking at a completely different deployment for the cluster, which I'd rather avoid...
> 
> Nope. I'm suggesting make the creation of {Docker|Singularity} containers a standard target.

That would mean putting the onus on the user to have the capability to run Docker/Singularity, which is pretty immense, to be honest...

**Comment by MarkBergman-cbica** [comment]
> > Nope. I'm suggesting make the creation of {Docker|Singularity} containers a standard target.
> 
> That would mean putting the onus on the user to have the capability to run Docker/Singularity, which is pretty immense, to be honest...

Apart from any issues I've got with Docker, it **is** widely used as a target.

I'm thinking that we offer:

- native platform builds, each a set of binaries that'll work a range of systems (Win 7 & up, Ubuntu 18.04 -- 20.04, Mac  OSX High Sierra [10.30] and Mojave [10.14])
- Docker (a single image, usable on any platform that runs Docker -- up to the end user to provide that prerequisite)
- source

The Docker build would extend our OS version reach both forward & backward, with a lower barrier to entry than a source build.

**Comment by sarthakpati** [comment]
I have updated the inference engine using TensorFlow 1.12.0 (had to revert to an older version of Python, Pip and **all** associated libraries) to make it work. Anyway, I tested it on cluster and 16.04 and it worked fine.

**Comment by sarthakpati** [comment]
This should be part of the new builds, will re-open if this issue comes up again.
