### ISSUE TITLE
Utilities crashes (core dump) doing BraTS stats

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#1221]
See:
https://cbica-portal.uphs.upenn.edu/rt/Ticket/Display.html?id=2776

Please contact end-user for copies of input data.

**NOTE** The crash was reported against Sarthak's branch: `captkMyFork_1.8.0.nonRelease.20200630.3d40a50` -- the same issue might (not?) be present in the public 1.8.0Beta.

**Comment by sarthakpati** [comment]
The sanity check is present in the code that generates BraTS similarity metrics [[ref](https://github.com/CBICA/CaPTk/blob/master/src/applications/Utilities/src/Utilities.cxx#L898)], but the error is generated in the IPP wrappers. Closing this because it is unrelated to actual CaPTk development.
