### ISSUE TITLE
EGFRvIIIIndexPredictor gives inf values in Loc_Mean_Ratio and Loc_Max_Ratio + Feature file header missing subject ID

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#1231]
**Describe the bug**
In the EGFRvIIIIndexPredictor application, the 2 features Loc_Mean_Ratio and Loc_Max_Ratio get an "inf" value when there is no overlap with the one of the atlases. This causes the predicted distance to become inf, and the result Mutant. In our test cases, all these were EGFRvIII negative (wildtype) cases, thus decreasing the overall accuracy.

Also, the the following output files are missing 'SubjectName' in the 1st column so the features and header don't align

- RawFeatures.csv
- ScaledFeatures.csv
- ScaledSelectedFeatures.csv

**To Reproduce**
Files are here (need brain_tumor project read permission for input):
```
dir=/cbica/home/sakoc/comp_space/lab/captk/180b/egfrvIII-svm
qsub -j y -b y -l h_vmem=128G -o $dir/captk_test_\$JOB_ID.log \
        /cbica/software/lab/captk/centos7/1.8.0.Beta/bin/EGFRvIIIIndexPredictor \
        -t 1 \
       -i $dir/input \
        -m /cbica/home/sakoc/CaPTk/PretrainedModels/EGFRvIIIIndexPredictor_PretrainedModel_1.8.0 \
        -o $dir/output_test
```
Output demonstrating this. AAAA_2007.01.21 is an example of getting an inf score.
```
$ head -n 3 $dir/output_test/results.csv
SubjectName,Score, Result 
AAAA_2007.01.21,inf, Mutant 
AAAB_2006.10.28,-4.722425, Wildtype 

$ cut -d, -f1,4-6 $dir/output_test/RawFeatures.csv | head -n3
Age,Loc_Mean_Ratio,Loc_Max_Ratio,ET_PatientSpace (<----header shifted one as noted below)
AAAA_2007.01.21,64.285713,inf,inf
AAAB_2006.10.28,0.000000,8.283625,1.000000
```
For the header, it's simply missing one column (SubjectName) in the header as you can see from the number of columns. Same for the ScaledFeatures.csv and ScaledSelectedFeatures.csv
```
$ awk -F, '{print NF}' $dir/output_test/RawFeatures.csv | head -n 5
448    (<---this is the header line)
449
449
449
449
```

**Expected behavior**
Gives out predicted scores for all subjects

**Desktop (please complete the following information):**
1.8.0.Beta on cluster

**Additional context**
This is a simple error due to dividing by zero. I understand the old code added an epsilon to avoid this.

**Comment by saimarathore** [comment]
@chiharusako Dividing by a small number leads to very large value of the feature, which might lead to wrong result. instead of that, I have printed 'Not determined' error message both in csv and on CLI in case of infinite score (zero overlap). I have also fixed the header in the files. 
will go in next PR.

**Comment by chiharusako** [comment]
Saima, I agree that dividing by a small number is not ideal as a feature. How were these handled when training the current model? I’m copying Hamed.

I looked at the cases that are getting the inf value, and these were ALL Wildtype cases which the TC (correct? You only calculate the overlap for TC, not including ED, right?) didn’t have overlap with the positive/Mutant probability map. Doesn’t that make it much more ‘likely to be wildtype’? I just think it’s unfortunate to exclude 8 out of 129 because of this. If we don’t want to divide by a small number, can the feature give a specific number, like the maximum possible when no overlap with positive map?
