### ISSUE TITLE
PseudoProgressionEstimator header missing a column in features files

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#1232]
**Describe the bug**
The header is missing the column SubjectName in the output features files, thus the header and features don't align.

- PSU_ScaledSelectedFeatures.csv
- RawFeatures.csv
- REC_ScaledSelectedFeatures.csv
- ScaledFeatures.csv
- SelectedFeatures_PSU.csv
- SelectedFeatures_REC.csv

**To Reproduce**
Files are here:
```
dir=/cbica/home/sakoc/comp_space/lab/captk/180b/psp
/cbica/software/lab/captk/centos7/1.8.0.Beta/bin/PseudoProgressionEstimator \
        -t 1 \
        -i $dir/input \
        -m /cbica/home/sakoc/CaPTk/PretrainedModels/PseudoProgressionEstimator_PretrainedModel_1.8.0 \
        -o $dir/output_test
```

printing out number of columns to demonstrate. First row is the header for all. Same for training output.
```
$ for i in output_test/*Features*.csv; do echo $i; awk -F, '{print NF}'  $i| head -n3; done
output_test/PSU_ScaledSelectedFeatures.csv
40
41
41
output_test/RawFeatures.csv
1040
1041
1041
output_test/REC_ScaledSelectedFeatures.csv
26
27
27
output_test/ScaledFeatures.csv
1040
1041
1041
```

**Expected**
Feature values align with the respective headers

**CaPTk Version**
1.8.0.Beta on the cbica-cluster

**Additional context**
The feature values itself are consistent with previous calculations

**Comment by sarthakpati** [comment]
Also reported by Hamed.

**Comment by saimarathore** [comment]
fixed.
