### ISSUE TITLE
Font sizes are totally out-of-whack

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#124]
![image](https://user-images.githubusercontent.com/11719673/47937521-62a28680-deb7-11e8-934d-c38c2efa6889.png)

![image](https://user-images.githubusercontent.com/11719673/47937697-eceaea80-deb7-11e8-8543-be1aab769970.png)

![image](https://user-images.githubusercontent.com/11719673/47951570-d5077b00-df38-11e8-91b7-a9b071123672.png)

Probably related #122

**Comment by sarthakpati** [comment]
![image](https://user-images.githubusercontent.com/11719673/47937697-eceaea80-deb7-11e8-8543-be1aab769970.png)

**Comment by sarthakpati** [comment]
Probably related #122

**Comment by ashishsingh18** [comment]
Could you give more details as to what resolution are you seeing this on?

**Comment by sarthakpati** [comment]
Resolution: 3240 x 2160
Screen size: 15"

**Comment by sarthakpati** [comment]
Display Settings (Surface Book 2):

![image](https://user-images.githubusercontent.com/11719673/48024619-236e7280-e10f-11e8-9dae-8a4cdc76b4e4.png)


![image](https://user-images.githubusercontent.com/11719673/48024450-a93dee00-e10e-11e8-8add-d7e7bb1b71de.png)

![image](https://user-images.githubusercontent.com/11719673/48024461-ae9b3880-e10e-11e8-9a56-79b9b34e2927.png)

![image](https://user-images.githubusercontent.com/11719673/48024467-b1962900-e10e-11e8-9e43-ac6f6be0d9f9.png)

![image](https://user-images.githubusercontent.com/11719673/48024474-b4911980-e10e-11e8-8b96-dee7f8b63f47.png)

![image](https://user-images.githubusercontent.com/11719673/48024503-d4284200-e10e-11e8-8b59-3b6cee75fa95.png)

![image](https://user-images.githubusercontent.com/11719673/48024577-0b96ee80-e10f-11e8-972a-ef891f81e42e.png)

1280x1024 @ 150% scaling:
![image](https://user-images.githubusercontent.com/11719673/48024957-156d2180-e110-11e8-83a0-d18f0faff50f.png)

2560x1600 @ 200% scaling:
![image](https://user-images.githubusercontent.com/11719673/48024998-37ff3a80-e110-11e8-891c-417fbb8be595.png)

1920x1080 @ 150% scaling:
![image](https://user-images.githubusercontent.com/11719673/48025059-64b35200-e110-11e8-9070-d3daf3de1877.png)
![image](https://user-images.githubusercontent.com/11719673/48025081-6e3cba00-e110-11e8-8b39-b5b1cf7642f3.png)

**Comment by sarthakpati** [comment]
![image](https://user-images.githubusercontent.com/11719673/48064727-aa1a6280-e196-11e8-93a6-a236da2bfcb8.png)

Even the menu items are working fine.

**Comment by ashishsingh18** [comment]
Great. Let's check on Mac as well before closing the issue. What about the renderwindow? Is that also working fine now?

**Comment by PhucNgo1711** [comment]
@sarthakpati is this fixed yet?

**Comment by sarthakpati** [comment]
This is no longer an issue; closing.
