### ISSUE TITLE
Registration output matrix file naming is confusing

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#1241]
**Describe the bug**
When registering images in Preprocessing, the order of names in the matrix file/deformation is opposite

**To Reproduce**
Example of registering a t1 image to SRI atlas (spgr_unstrip-RAI.nii.gz), using Rigid and Deformable
```
$ dir=/cbica/home/sakoc/comp_space/lab/captk/180b/reg/
$ t=AAAC_2008.03.30
$ Preprocessing \
           -i input/${t}_t1_LPS.nii.gz \
 	   -reg Rigid \
 	   -rFI input/spgr_unstrip-RAI.nii.gz \
 	   -o out_rigid/${t}_t1_LPS_rSRI.nii.gz \
 	   -rME NMI -rNI 100,50,10 -rIS 1
$ Preprocessing \
           -i input/${t}_t1_LPS.nii.gz \
 	   -reg Deformable \
 	   -rFI input/spgr_unstrip-RAI.nii.gz \
 	   -o out_deform/${t}_t1_LPS_rSRI_deform.nii.gz \
 	   -rME NMI -rNI 100,50,10 -rIS 1
```
output
```
$ ls out*
out_rigid:
AAAC_2008.03.30_t1_LPS_rSRI.nii.gz
affine_spgr_unstrip-RAITOAAAC_2008.03.30_t1_LPS_NMI.mat

out_deform:
AAAC_2008.03.30_t1_LPS_rSRI_deform_inv.nii.gz
AAAC_2008.03.30_t1_LPS_rSRI_deform.nii.gz
affine_spgr_unstrip-RAITOAAAC_2008.03.30_t1_LPS_NMI.mat
deformInv_AAAC_2008.03.30_t1_LPSTOspgr_unstrip-RAI_NMI.nii.gz
deform_spgr_unstrip-RAITOAAAC_2008.03.30_t1_LPS_NMI.nii.gz
```
**Expected behavior**
For Rigid:
Since I'm registering t1 to SRI, the .mat files should be named AAAC_2008.03.01_t1_LPS to spgr_unstrip_RAI . mat
For Deformable:
It's more confusing as you're providing the inverse transformation

**CaPTk Version**
1.8.0.Beta on cluster

**Desktop (please complete the following information):**
 - OS: centos 7

**Additional context**
What is this file produced when doing deformable? It's empty. 
AAAC_2008.03.30_t1_LPS_rSRI_deform_inv.nii.gz

Finally - if I try to use the output of Deformation to a new image it produces a reasonable output but also gives an error, which seems irrelevant.

```
$ Preprocessing \
           -i input/${t}_t1_LPS.nii.gz \
	   -reg Deformable \
	   -rFI input/spgr_unstrip-RAI.nii.gz \
	   -o out_deform/${t}_${m}_LPS_rSRI_deform_2.nii.gz	
 	   -rIA out_deform/affine_spgr_unstrip-RAITOAAAC_2008.03.30_t1_LPS_NMI.mat \
	   -rID out_deform/deform_spgr_unstrip-RAITOAAAC_2008.03.30_t1_LPS_NMI.nii.gz \
           -rIS 1
Executing with the default number of threads: 1
ABORTING PROGRAM DUE TO RUNTIME EXCEPTION -- File 'output_reg_deform//deform_spgr_unstrip-RAITOAAAC_2008.03.30_t1_LPS_NMI-Inv.nii.gz' does not exist
Something went wrong when calling Greedy Reslice Deform-Inverse.
```

Registration itself is working

**Comment by sarthakpati** [comment]
Fixed the name.

**Comment by sarthakpati** [comment]
The second message seems to be coming from greedy itself. Investigating.

**Comment by sarthakpati** [comment]
Done.
