### ISSUE TITLE
Incorrect Usage description: Glioblastoma Infiltration Index 

### ISSUE THREAD

**Issue by anahitafk** [CBICA/CaPTk#1248]
Incorrect description in the Usage : "Brain Cancer: Glioblastoma Infiltration Index (Recurrence)"
Under "REQUIREMENTS:", item 4: features.csv (this shouldn't be a requirement; the sample data doesn't include it either)

**Comment by ashishsingh18** [comment]
@anahitafk Thank you for reporting this inconsistency. 

@saimarathore Is it okay to remove item 4 (as above) from docs?

**Comment by saimarathore** [comment]
documentation updated.
