### ISSUE TITLE
Module Failure (CLI): Glioblastoma Infiltration Index

### ISSUE THREAD

**Issue by anahitafk** [CBICA/CaPTk#1249]
**Describe the bug**
CLI error for a new test subject. For a new test subject, it works in GUI. It works with captk sample data in CLI. The new test data is organized exactly as required by the Usage and according to the sample data.

**To Reproduce**
.\RecurrenceEstimator.exe -t 1 -i C:\Users\Anahita\Downloads\CaPTk\data_recur\test_samples\ -o C:\Users\Anahita\Downloads\CaPTk\data_recur\out\ -m C:\Users\Anahita\Downloads\CaPTk\RecurrenceEstimator_Model

**Expected behavior**
A recurrence map to be generated for the test subject

**Screenshots**
![image](https://user-images.githubusercontent.com/45635727/90077417-1a410b00-dcd0-11ea-9354-04bc2507c018.png)

**CaPTk Version**
Cancer Imaging Phenomics Toolkit (CaPTk) v.1.8.0.Beta

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10.0.17134 Build 17134

**Additional context**

**Comment by AlexanderGetka-cbica** [comment]
Hi @anahitafk, thanks for the bug report. Can you please provide the input data you used for both training and testing? This will help investigate this.

**Comment by AlexanderGetka-cbica** [comment]
Closing due to lack of response.
