### ISSUE TITLE
links in recurrence documentation point to wrong file

### ISSUE THREAD

**Issue by AlexanderGetka-cbica** [CBICA/CaPTk#1277]
**Describe the bug**
Documentation hyperlinks to ftp://www.nitrc.org/home/groups/captk/downloads/models/recurrence.zip

But CaPTk internally hyperlinks to:
ftp://www.nitrc.org/home/groups/captk/downloads/models/RecurrenceEstimator_Model.zip

**To Reproduce**
1. Go to https://cbica.github.io/CaPTk/Glioblastoma_Recurrence.html
2. Scroll through and find the link to the HUP model
3. You are directed to ftp://www.nitrc.org/home/groups/captk/downloads/models/recurrence.zip

**Expected behavior**
Should be the correct path.

**CaPTk Version**
Most recent documentation.

It's possible I'm forgetting that a fix for this was pushed, in that case I'll close. But we should check the other applications as well.

**Comment by saimarathore** [comment]
@AlexanderGetka-cbica Thanks. the correct link will be in links.yaml file. seems like you have already fixed it.
