### ISSUE TITLE
PerfusionAlignment missing from links.yaml, selecting it from sample data menu causes a crash

### ISSUE THREAD

**Issue by AlexanderGetka-cbica** [CBICA/CaPTk#1278]
**Describe the bug**
See title -- selecting Perfusion Alignment from the Help-> Sample Data menu instantly crashes captk with the following:

terminate called after throwing an instance of 'YAML::TypedBadConversion<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >'
  what():  bad conversion
Received signal 6
#0 0x7f7f6fb33a4f <unknown>
#1 0x7f7f6fb33e4b <unknown>
#2 0x7f7f6fb344ce <unknown>
#3 0x7f7f6b5aa8a0 <unknown>
#4 0x7f7f69a45f47 gsignal
#5 0x7f7f69a478b1 abort
#6 0x7f7f6a2c0957 <unknown>
#7 0x7f7f6a2c6ae6 <unknown>
#8 0x7f7f6a2c6b21 std::terminate()
#9 0x7f7f6a2c6d54 __cxa_throw
#10 0x000000b35f0e <unknown>
#11 0x0000009acee9 <unknown>
#12 0x000000f9c99f <unknown>
#13 0x7f7f6bc728a9 QMetaObject::activate()
#14 0x7f7f6cc50532 QMenu::triggered()
#15 0x7f7f6cc53621 QMenuPrivate::_q_actionTriggered()
#16 0x7f7f6cc5c821 QMenu::qt_static_metacall()
#17 0x7f7f6bc728a9 QMetaObject::activate()
#18 0x7f7f6cae6b62 QAction::triggered()
#19 0x7f7f6cae8f80 QAction::activate()
#20 0x7f7f6cc51cba QMenuPrivate::activateCausedStack()
#21 0x7f7f6cc58dc6 QMenuPrivate::activateAction()
#22 0x7f7f6cc59df9 QMenu::mouseReleaseEvent()
#23 0x7f7f6cb2a828 QWidget::event()
#24 0x7f7f6cc5c30b QMenu::event()
#25 0x7f7f6caecb3c QApplicationPrivate::notify_helper()
#26 0x7f7f6caf430f QApplication::notify()
#27 0x7f7f6bc46e28 QCoreApplication::notifyInternal2()
#28 0x7f7f6caf324a QApplicationPrivate::sendMouseEvent()
#29 0x7f7f6cb44730 QWidgetWindow::handleMouseEvent()
#30 0x7f7f6cb46eeb QWidgetWindow::event()
#31 0x7f7f6caecb3c QApplicationPrivate::notify_helper()
#32 0x7f7f6caf3d30 QApplication::notify()
#33 0x7f7f6bc46e28 QCoreApplication::notifyInternal2()
#34 0x7f7f6c2b0767 QGuiApplicationPrivate::processMouseEvent()
#35 0x7f7f6c2b1d15 QGuiApplicationPrivate::processWindowSystemEvent()
#36 0x7f7f6c28d9fb QWindowSystemInterface::sendWindowSystemEvents()
#37 0x7f7f5fc5081a xcbSourceDispatch()
#38 0x7f7f62c02417 g_main_context_dispatch
#39 0x7f7f62c02650 <unknown>
#40 0x7f7f62c026dc g_main_context_iteration
#41 0x7f7f6bc9e1ef QEventDispatcherGlib::processEvents()
#42 0x7f7f6bc4578a QEventLoop::exec()
#43 0x7f7f6bc4e190 QCoreApplication::exec()
#44 0x00000044402a <unknown>
#45 0x7f7f69a28b97 __libc_start_main
#46 0x00000047e7d9 <unknown>
  r8: 0000000000000000  r9: 00007ffc881b5ec0 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007f7f580099e0 r13: 00007ffc881b61d0 r14: 0000000008f2bac0 r15: 00007ffc881b6300
  di: 0000000000000002  si: 00007ffc881b5ec0  bp: 0000000004fa26c0  bx: 0000000008e41c68
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f7f69a45f47  sp: 00007ffc881b5ec0
  ip: 00007f7f69a45f47 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
 

**Expected behavior**
Selecting it opens the file select/download menu like the other entries in the list.

**CaPTk Version**
Latest master, tested on both Ashish's PR #1275 and on my local build.

**Desktop (please complete the following information):**
 Occurs on windows and linux machines.

**Comment by sarthakpati** [comment]
NITRC FTP is down right now (I am not able to check which files are present, for some reason), maybe that's why?

**Comment by sarthakpati** [comment]
Done.
