### ISSUE TITLE
Perfusion Derivatives gives segmentation fault on some images

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#1281]
**Describe the bug**
Perfusion Derivatives gives segmentation fault on some input images

**To Reproduce**
Below are test on 14 input images, and 4 (ACPN,ACST,ACUS,ACVE) gave segmentation faults.
All input are 45tp DSC images and the drop falls between baseline/recovery.
```
$ dir="/cbica/home/sakoc/comp_space/lab/captk/180b/perfd"
$ for i in *_perf_LPS.nii.gz; do echo $i; PerfusionDerivatives -i $i -o out_$s -p 1 -pH 1 -r 1 > out_${i::4}/log; done
ABFE_2014.01.14_perf_LPS.nii.gz
ABWY_2017.07.19_perf_LPS.nii.gz
ACGB_2019.06.05_perf_LPS.nii.gz
ACKJ_2019.07.19_perf_LPS.nii.gz
ACPA_2019.09.10_perf_LPS.nii.gz
ACPN_2019.11.09_perf_LPS.nii.gz
Segmentation fault
ACST_2019.08.29_perf_LPS.nii.gz
Segmentation fault
ACTL_2019.08.21_perf_LPS.nii.gz
ACTX_2020.02.02_perf_LPS.nii.gz
ACUS_2019.08.27_perf_LPS.nii.gz
Segmentation fault
ACVE_2019.07.11_perf_LPS.nii.gz
Segmentation fault
ACXO_2019.07.13_perf_LPS.nii.gz
ACYC_2019.08.22_perf_LPS.nii.gz
ACZS_2020.02.20_perf_LPS.nii.gz

```
**Expected behavior**
All images produce derivatives

**CaPTk Version**
1.8.0.Beta on cbica cluster

**Desktop (please complete the following information):**
cubic-login3

**Additional context**
I do notice that many images have negative values in intensity, which I thought is the issue when taking the log in the rCBV. I tested this by removing the negative intensity from the input, and it indeed produces results without errors. However, I am confused as other input images that produced results also had negative intensities, and I am concerned about the results. 

```
$ for t in ACPN_2019.11.09 ACST_2019.08.29 ACUS_2019.08.27 ACVE_2019.07.11; 
$ do 
$     3dcalc -a ${t}_perf_LPS.nii.gz -expr 'a*ispositive(a)' -prefix ${t}_perf_LPS_removednegative.nii.gz; 
$     s=${t::4};
$     mkdir -pv out_removednegative_$s;
$     PerfusionDerivatives -i $i -o out_removednegative_$s -p 1 -pH 1 -r 1 > out_removednegative_$s/log;
$ done
```
To reiterate, **many** of our images have negative intensities.
```
$ for i in *_perf_LPS.nii.gz; do echo $i,`fslstats $i -R`; done
ABFE_2014.01.14_perf_LPS.nii.gz,-20.000000 1489.000000
ABWY_2017.07.19_perf_LPS.nii.gz,0.000000 13226.000000
ACGB_2019.06.05_perf_LPS.nii.gz,-19.000000 1929.000000
ACKJ_2019.07.19_perf_LPS.nii.gz,-18.000000 1399.000000
ACPA_2019.09.10_perf_LPS.nii.gz,-23.000000 1653.000000
ACPN_2019.11.09_perf_LPS.nii.gz,-19.000000 1780.000000
ACST_2019.08.29_perf_LPS.nii.gz,-59.000000 2093.000000
ACTL_2019.08.21_perf_LPS.nii.gz,-12.000000 1841.000000
ACTX_2020.02.02_perf_LPS.nii.gz,-35.000000 1611.000000
ACUS_2019.08.27_perf_LPS.nii.gz,-17.000000 1426.000000
ACVE_2019.07.11_perf_LPS.nii.gz,-39.000000 1267.000000
ACXO_2019.07.13_perf_LPS.nii.gz,-4.000000 1369.000000
ACYC_2019.08.22_perf_LPS.nii.gz,-7.000000 1637.000000
```

**Comment by chiharusako** [comment]
Adding 2 more minor issues while we're at it.
1. It saves a file "AeragePerfusionCurve.csv". Typo should be fixed to AveragePerfusionCurve.csv
2. in the -h, it says -p -pH -r options are all 1 by default but it still needs to be specified. Otherwise you get a parameter missing message and won't run.

**Comment by ashishsingh18** [comment]
Some of these images are producing results on Windows.

```
C:\CaPTk_Full\1.8.0.Beta\bin>PerfusionDerivatives.exe -o C:\workspace\Data\1.8.betaTesting\issue_1281\out -i C:\workspace\Data\1.8.betaTesting\issue_1281\ABFE_2014.01.14_perf_LPS.nii.gz -p 1 -pH 1 -r 1
Input File:C:\workspace\Data\1.8.betaTesting\issue_1281\ABFE_2014.01.14_perf_LPS.nii.gz
Output Directory:C:\workspace\Data\1.8.betaTesting\issue_1281\out
Number of time-points: 45
Baseline start: 0
Baseline end: 9
Recovery start: 29
Recovery end: 39
Drop location: 26
Perfusion curve validated!!!
Min:0
Max:2326.46
Perfusion derivatives written to the specified location.
Finished successfully.
```
```
C:\CaPTk_Full\1.8.0.Beta\bin>PerfusionDerivatives.exe -o C:\workspace\Data\1.8.betaTesting\issue_1281\out -i C:\workspace\Data\1.8.betaTesting\issue_1281\ACPA_2019.09.10_perf_LPS.nii.gz -p 1 -pH 1 -r 1
Input File:C:\workspace\Data\1.8.betaTesting\issue_1281\ACPA_2019.09.10_perf_LPS.nii.gz
Output Directory:C:\workspace\Data\1.8.betaTesting\issue_1281\out
Number of time-points: 45
Baseline start: 0
Baseline end: 9
Recovery start: 29
Recovery end: 39
Drop location: 17
Perfusion curve validated!!!
Min:0
Max:7897.62
Perfusion derivatives written to the specified location.
Finished successfully.
```

**Comment by ashishsingh18** [comment]
Some debugging info for @saimarathore 

This crashes on Windows for dataset `ACST_2019.08.29_perf_LPS.nii.gz`.

On debugging, the crash happens in the following function in file `PerfusionDerivatives.h`
`typename ImageType::Pointer PerfusionDerivatives::CalculateRCBV(typename PerfusionImageType::Pointer perfImagePointerNifti)`

The error we get is `vector subscript out of range` on this line: https://github.com/CBICA/CaPTk/blob/abc094c052f5dadd499665424ef7a3587e556e00/src/applications/PerfusionDerivatives.h#L699

and earlier on we get a `nan` value from here:https://github.com/CBICA/CaPTk/blob/abc094c052f5dadd499665424ef7a3587e556e00/src/applications/PerfusionDerivatives.h#L638

**Comment by AlexanderGetka-cbica** [comment]
I get crashes on the same images that Chiharu gets segfaults on on Windows. Also can confirm Ashish's statement -- in fact, if you turn off generation of apRCBV this crash doesn't occur.
Seems like meanPerfusionAfterMaximum must be zero-length for this to happen on lines 693-698. 

More information coming tonight.

**Comment by AlexanderGetka-cbica** [comment]
Also confirming that only images with negative values caused crashes, but that some images with negative values did not cause a crash.

**Comment by chiharusako** [comment]
Thanks for troubleshooting @AlexanderGetka-cbica and @ashishsingh18 
I noticed the negative values are getting introduced when aligning the images. While in general I think it's good to have a protection for taking a log on negative values, I can take care of this during the aligning as well. @saimarathore - Can we have a quick call when you have time? I'd like to get your opinion on this. Thanks again.

**Comment by AlexanderGetka-cbica** [comment]
@chiharusako We are having a discussion about this in our weekly meeting and the approach being considered is to shift up the values of the input perfusion image by whatever the lowest value is before we perform the operation -- so the lowest negative value (if any) in the user-provided input increases to 0, and the rest of the values are shifted up by that same amount. Of course we will only do this if the user agrees to / acknowledges this. Do you think this is appropriate / makes sense?

**Comment by chiharusako** [comment]
@AlexanderGetka-cbica I think shifting is not correct as it will affect all further calculations. I think it should error out with such an error message if there are any negative values.
Again, sorry I didn't notice initially that I was introducing the negative values when resampling/interpolating in time. I can explain more if needed but I think error output is appropriate.

**Comment by sarthakpati** [comment]
> introducing the negative values when resampling/interpolating in time

Were you using CaPTk's resampling? If so, we might need to look into why negative numbers are getting introduced to begin with and what can the potential solution be.

**Comment by chiharusako** [comment]
>> introducing the negative values when resampling/interpolating in time
> Were you using CaPTk's resampling? If so, we might need to look into why negative numbers are getting introduced to begin with and what can the potential solution be.

No, outside of CaPTk, so you're all good.

**Comment by sarthakpati** [comment]
> > introducing the negative values when resampling/interpolating in time Were you using CaPTk's resampling? If so, we might need to look into why negative numbers are getting introduced to begin with and what can the potential solution be.
> No, outside of CaPTk, so you're all good.

Oh okay. Do you think you could try CaPTk's resample as a sanity check for this? `Utilities -rr` is what you should be looking for. Tagging @AlexanderGetka-cbica to give it a whirl, too.

**Comment by chiharusako** [comment]
Does CaPTk resample in time direction? If not, I don’t think it needs to be so no worries.
That aside, if you’re only doing linear interpolation you should be fine. Mine had negative values because I did cubic spline…

**Comment by sarthakpati** [comment]
> Does CaPTk resample in time direction?

Yes, if you pass the 4th dimension into `-rr` like this: `-rr 1,1,1,1`, which would resample the image to `1,1,1` along `X,Y,Z` and `1` along the 4th dimension. You can also pass a reference image with `-rf` if you want the output spacings to match the reference image.

> if you’re only doing linear interpolation you should be fine

In CaPTk, Linear is default and the user can select other interpolation types, as needed.

**Comment by sarthakpati** [comment]
In case where the perfusion derivatives are not calculated, the CLI still prints `Finished successfully` before exiting, which it should not.

**Comment by AlexanderGetka-cbica** [comment]
Taking a run-through of our utilities -rr to see if I can get negative values, will update here with more info.,

**Comment by sarthakpati** [comment]
From @sbakas:

- For negative values in image:
  - **Warning addition**: we should assess all values included in the input image and if negative values are found we should use a warning to inform the user that there are negative values in the input perfusion scan and then stop the application.
  - **Also documentation**: we need to document that negative values should not exist for this application
- For identifying the drop:
  - **For now we need a warning and documentation** relating to handling multiple timepoints, but not identifying the drop automatically/smartly. We can deal with this at a patch later on if we want to.
  - **Reveal** the “20%” as an argument/variable to the user for the baseline (at least in the CLI).

**Comment by ashishsingh18** [comment]
Handling negative values via a separate issue #1308
