### ISSUE TITLE
Dicom2Nifti conversion works in GUI but not CLI

### ISSUE THREAD

**Issue by jvbelenky** [CBICA/CaPTk#1312]
Attempting to construct niftis from dicoms; worked on a set of CT images, but none of the PET images. 

Ran this input on local machine: 
`C:\CaPTk_Full\1.8.0.Beta\bin\Utilities.exe -i Z:\Acrin_FLT\001001_4277_6688\20091113\PET_AC\IM-0005-0001.dcm -o Z:\Acrin_FLT\001001_4277_6688\Case_001001_20091113_PET_AC.nii -d2n`

Received error 'Dicom Load Failed'

Running this analogous input on cluster produced a segmentation fault:
`/cbica/software/lab/captk/centos7/1.8.0.Beta/bin/Utilities -i ~/Acrin_FLT/001001_4277_6688/20091113/PET_AC/IM-0005-0001.dcm -o ~/Acrin_FLT/001001_4277_6688/Case_001001_20091113_PET_AC.nii -d2n`

However, running d2n within the GUI worked fine.
Also--is it possible to run this feature in the GUI to produce uncompressed .nii files?

**Comment by sarthakpati** [comment]
Hey @jvbelenky, could you provide an example image somewhere with global read access? Without this, we cannot debug this issue:

```bash
(base) patis@/cbica/home/patis/testing/captkMyFork_1.8.0.nonRelease.20200916.596fd79/bin>$ ./Utilities -inf -i ~belenkyv/Acrin_FLT/00
1001_4277_6688/20091113/PET_AC/IM-0005-0001.dcm
Input file '/cbica/home/belenkyv/Acrin_FLT/001001_4277_6688/20091113/PET_AC/IM-0005-0001.dcm' not found.
(base) patis@/cbica/home/patis/testing/captkMyFork_1.8.0.nonRelease.20200916.596fd79/bin>$ ls /cbica/home/belenkyv/Acrin_FLT/001001_4277_6688/
ls: cannot open directory /cbica/home/belenkyv/Acrin_FLT/001001_4277_6688/: Permission denied
```

**Comment by jvbelenky** [comment]
I'm not sure I have write access to anywhere that has global read access. This ACRIN-FLT project is also located in the cbica/projects directory but I currently can't log into my remote workstation to double check the full filepath.

**Comment by sarthakpati** [comment]
Generally, our "comp_space" is global read.

**Comment by sarthakpati** [comment]
Regarding your second part of the question
> Also--is it possible to run this feature in the GUI to produce uncompressed .nii files?

Technically, it is possible, but the size of uncompressed NIfTI files is significantly large without any advantage as all I/O libraries (ITK, Nibabel, etc.) can read directly read the compressed NIfTI files.

**Comment by ashishsingh18** [comment]
@jvbelenky This might already work with the latest master. If you could try this with the binaries that @sarthakpati shared, we would know. Alternatively, if you can share the dicom data via comp-space, we can try it.

**Comment by jvbelenky** [comment]
I tried the new build, but I'm still getting a segmentation fault--most likely the same error as before.

I've copied the Acrin_FLT folder to my comp_space directory, so the path to the problem dicom with global read access should now be:

`~/cbica/comp_space/belenkyv/Acrin_FLT/001001_4277_6688/20091113/PET_AC/IM-0005-0001.dcm`

**Comment by ashishsingh18** [comment]
@jvbelenky I am unable to access the data you shared in comp_space, can you check the permissions?
![image](https://user-images.githubusercontent.com/43445206/93828916-6588fa80-fc3a-11ea-8327-1a34c86bc506.png)

**Comment by jvbelenky** [comment]
Okay, I just set +rwx permission for the comp_space/belenkyv/ directory--try now?
Also, I thought that the new server was cubic.login, not cubic-share?

**Comment by sarthakpati** [comment]
@jvbelenky: that file is not present:
```bash
(base) patis@/cbica/home/patis/testing/captkMyFork_1.8.0.nonRelease.20200630.3d40a50/bin>$ file /cbica/home/belenkyv/comp_space/Acrin_FLT/20091113/PET_AC/IM-0005-0001.dcm
/cbica/home/belenkyv/comp_space/Acrin_FLT/20091113/PET_AC/IM-0005-0001.dcm: cannot open (No such file or directory)
```
And I am not able to access any folder in that location, either:
```bash
(base) patis@/cbica/home/patis/testing/captkMyFork_1.8.0.nonRelease.20200630.3d40a50/bin>$ ls -lt ~belenkyv/comp_space/Acrin_FLT/014003_4227_6688
ls: cannot open directory /cbica/home/belenkyv/comp_space/Acrin_FLT/014003_4227_6688: Permission denied
```

**Comment by sarthakpati** [comment]
Hi @jvbelenky, after you changed the permissions on the folder, I was able to access it without problem and I was also able to do the conversion successfully:

```bash
(base) patis@/cbica/home/patis/testing/captkMyFork_1.8.0.nonRelease.20200922.52ae0cc/bin>$ ./Utilities -i /cbica/home/belenkyv/comp_space/Acrin_FLT/001001_4277_6688/20091113/PET_AC/IM-0005-0001.dcm -o ~/testing/Acrin_FLT_001001_4277_6688_20091113_PET_AC.nii.gz -d2n
Chris Rorden's dcm2niiX version v1.0.20200331  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 (64-bit Linux)
Found 239 DICOM file(s)
Convert 239 DICOM as /cbica/home/patis/.cbicaTemp/tmp_12397177688148061436/PET_AC_PET_AC_20091113151201_2288214489 (128x128x239x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/cbica/home/patis/.cbicaTemp/tmp_12397177688148061436/PET_AC_PET_AC_20091113151201_2288214489.nii"
Conversion required 1.044336 seconds (0.260000 for core code).
(base) patis@/cbica/home/patis/testing/captkMyFork_1.8.0.nonRelease.20200922.52ae0cc/bin>$ ./Utilities ~/testing/Acrin_FLT_001001_4277_6688_20091113_PET_AC.nii.gz
Input file '' not found.
(base) patis@/cbica/home/patis/testing/captkMyFork_1.8.0.nonRelease.20200922.52ae0cc/bin>$ ./Utilities -inf -i ~/testing/Acrin_FLT_001001_4277_6688_20091113_PET_AC.nii.gz
ITK Image information:.
Property,Value
Dimensions,3
Size,128x128x239
Total,3915776
Origin,-250.000000x246.093750x-1026.500000
Spacing,3.906250x3.906250x4.250000
Component,float
Pixel Type,scalar
Directions,[1.000000x-0.000000x0.000000;-0.000000x-1.000000x0.000000;0.000000x0.000000x1.000000]
```

When you mentioned that you tried the new build, could you tell me which version you had tried? For instance, [this is the latest build for Windows](https://dev.azure.com/CBICA/_apis/resources/Containers/5554717/CBICA.CaPTk_installer_Windows?itemPath=CBICA.CaPTk_installer_Windows%2FCaPTk_1.8.0.nonRelease.20200923.2b132ae3_Installer.exe).

**Comment by ashishsingh18** [comment]
@jvbelenky I am also able to access the data now and the conversion is working fine without any errors. Can you please try with installer shared by @sarthakpati ?

**Comment by jvbelenky** [comment]
Using that build, I can't run that command as a bash process--I get the `No such file or directory` error-- and running the utilities executable directly still produces a segmentation fault. 

I also can't access the link; I receive this message:
`{"$id":"1","innerException":null,"message":"TF400813: The user '58e32bb7-141e-4bae-af01-f29f2a6613c2\\BelenkyV@pennmedicine.upenn.edu' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}`

**Comment by sarthakpati** [comment]
> Using that build, I can't run that command as a bash process--I get the No such file or directory error

Could you please tell me the command you are trying to run? 

> I also can't access the link

Apologies, I thought the builds were open to download from anywhere. Check the following link:

ftp://www.nitrc.org/home/groups/captk/downloads/CaPTk_1.8.0.nonRelease.20200923.2b132ae3_Installer.exe

**Comment by jvbelenky** [comment]
The command I used that produced a segfault was this one:
`cbica/home/patis/testing/captkMyFork_1.8.0.nonRelease.20200922.52ae0cc/bin/Utilities -i /cbica/home/belenkyv/comp_space/Acrin_FLT/001001_4277_6688/20091113/PET_AC/IM-0005-0001.dcm -o ~/Acrin_FLT/Acrin_FLT_001001_4277_6688_20091113_PET_AC.nii.gz -d2n`

I'll try the new installer in the meantime.

**Comment by sarthakpati** [comment]
> cbica/home/patis/testing/captkMyFork_1.8.0.nonRelease.20200922.52ae0cc/bin/Utilities

It should be:
**/cbica/home/patis/testing/captkMyFork_1.8.0.nonRelease.20200922.52ae0cc/bin/Utilities**

Or 
`~patis/testing/captkMyFork_1.8.0.nonRelease.20200922.52ae0cc/bin/Utilities`

**Comment by jvbelenky** [comment]
Ok--that one worked. Thanks! Is there a particular reason that running Utilities after doing `cd cbica/home/patis/testing/captkMyFork_1.8.0.nonRelease.20200922.52ae0cc/bin/` would produce a segfault but passing the whole path wouldn't?

**Comment by sarthakpati** [comment]
> Ok--that one worked. Thanks! Is there a particular reason that running Utilities after doing `cd cbica/home/patis/testing/captkMyFork_1.8.0.nonRelease.20200922.52ae0cc/bin/` would produce a segfault but passing the whole path wouldn't?

That is because there was a missing "/" in the beginning of the full path. 😄

**Comment by sarthakpati** [comment]
Closing because the issue seems to be fixed. Please reopen if it comes up. :)

**Comment by jvbelenky** [comment]
Perhaps this should be a new issue, but it seems the test build, while it can load the PET dicoms, only produces corrupted niftis. Both compressed and uncompressed nii files have the issues. Reverting to the 1.8.0 beta fixes the issue but only for CT files. Attempts to open in ITK-SNAP yield this error:
![image](https://user-images.githubusercontent.com/35495855/94977576-66961380-04e7-11eb-8c15-8df5b9cfc77f.png)
This seems to be affect all images in the series. Example located here:
`/cbica/home/belenkyv/Acrin_FLT/002005_4221_6688/Case_002005_20110318_e+1_3Dosem_6i28s_7Ga_AxStd_55dFOV.nii`
