### ISSUE TITLE
Add popup message to Perfusion Alignment

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#1320]
Add popup message to Perfusion Alignment. 

**Describe the solution you'd like**
The popup should appear on clicking the 'Perfusion Alignment' menu. It should let the user know that this is work in progress and new releases are coming with more features soon. It should have an 'Ok'' button. On clicking 'Ok' it should continue with the current functionality.

**Comment by ashishsingh18** [comment]
@sbakas I have the changes ready for this and just waiting for the correct message to push the PR.

What I have added is: 

> This application is a work-in-progress and new features will come out in future releases, which can be downloaded from here[link to downloads]

Does this look okay ?

**Comment by sbakas** [comment]
The message appearing prior to showing the main application menu could be the following:

"We are actively working on the incorporation of cost-function tumor masking for the alignment of individual subject perfusion curves, towards producing a more refined and robust alignment result. We expect this to be completed, validated, and released in our next patch release, expected in Q4 2020."

**Comment by sbakas** [comment]
The executive decision is that the functionality of perfusion alignment will be disabled from both GUI and CLI of this release and appear again in the next patch release. The application will exist for the time being in the menu and once a user clicks on it the following message should appear: 
"This functionality has been removed from this CaPTk release, and we are actively testing an optimized robust implementation that would enable generalization in multi-institutional data. We expect this to be released in our next patch release, expected in Q4 2020."

**Comment by sbakas** [comment]
@sarthakpati could chime in if more details are needed
