### ISSUE TITLE
1.8.0 release: Pseudo-progression prediction: documentation

### ISSUE THREAD

**Issue by sbakas** [CBICA/CaPTk#1335]
Documentation should refer to to "Glioblastoma Pseudo-progression Index "

The only help text included in the documentation should be: "This functionality has been removed from this CaPTk release, and we are actively working on an optimized robust implementation that should enable generalization in multi-institutional data. We expect this to be released in our next patch release, in Q4 2020."

**Comment by sarthakpati** [comment]
Done.
