### ISSUE TITLE
1.8.0 release: Recurrence prediction: disabled

### ISSUE THREAD

**Issue by sbakas** [CBICA/CaPTk#1338]
The application is removed from this release.
The functionality will be disabled from both GUI and CLI of this release and will appear again after conclusion of the model retraining using a superset of the previous data.

The application will remain in the GUI menu.

Once a user clicks on the application the following message should appear: "This functionality has been removed from this CaPTk release, and we are actively working on a more optimized robust implementation that should enable generalization in multi-institutional data."

**Comment by sarthakpati** [comment]
Done.
