### ISSUE TITLE
Technical Reference Documentation

### ISSUE THREAD

**Issue by ShyamDesai** [CBICA/CaPTk#1340]
**Describe the bug**
Duplicate specific feature "variance" within GLCM feature family documentation 

**To Reproduce**
1. https://cbica.github.io/CaPTk/tr_FeatureExtraction.html
2. In the GLCM feature family column
3. Specific Feature "variance" is listed twice

Not sure if this was a documentation typo, please let me know if otherwise! Thanks.

**Comment by sarthakpati** [comment]
Thanks for reporting. Done.
