### ISSUE TITLE
Test build producing corrupt niftis from dicoms with dicom2nifti

### ISSUE THREAD

**Issue by jvbelenky** [CBICA/CaPTk#1347]
Following instructions located [here](https://github.com/CBICA/CaPTk/issues/1312#issuecomment-698385842) , using test build captkMyFork_1.8.0.nonRelease.20200922.52ae0cc to convert dicoms to nifti following failure of 1.8.0 beta to load PET dicoms. 
Using this command, C is local drive and Z is cluster drive:
` C:/CaPTk_Full/1.8.0.nonRelease.20200923.2b132ae3/bin/Utilities.exe -i Z:\Acrin_FLT\002005_4221_6688\20110318\e+1_3Dosem_6i28s_7Ga_AxStd_55dFOV\IM-0006-0001.dcm -o Z:\Acrin_FLT\002005_4221_6688\Case_002005_20110318_e+1_3Dosem_6i28s_7Ga_AxStd_55dFOV.nii -d2n`

This build produces corrupt .niis--attempts to load with ITK-SNAP produce this error:
![image](https://user-images.githubusercontent.com/35495855/94977735-22574300-04e8-11eb-8765-749453107c8b.png)

Attempts to load with MATLAB produce this error
`Error using load_nii_hdr (line 77)
File "Z:\Acrin_FLT\002005_4221_6688\Case_002005_20110318_e+1_3Dosem_6i28s_7Ga_AxStd_55dFOV.nii" is
corrupted.`

Seems to affect all images, but here is an example:
`/cbica/home/belenkyv/Acrin_FLT/002005_4221_6688/Case_002005_20110318_e+1_3Dosem_6i28s_7Ga_AxStd_55dFOV.nii`

**Comment by sarthakpati** [comment]
Hi @jvbelenky, unfortunately, saying "Z:" corresponds to the "cluster drive" doesn't tell us anything. Please provide the **actual** path on the cluster in order for us to debug.

**Comment by sarthakpati** [comment]
Assuming it is in a similar location as the previous ticket, I do not have the required permissions:

```bash
(base) patis@/cbica/home/patis/testing/captkMyFork_1.8.0/bin>$ ls /cbica/home/belenkyv/comp_space/Acrin_FLT/002005_4221_6688/20110318/
ls: cannot open directory /cbica/home/belenkyv/comp_space/Acrin_FLT/002005_4221_6688/20110318/: Permission denied
```

**Comment by ashishsingh18** [comment]
@jvbelenky This is happening because the output nifti is compressed but the extension says '.nii' only, This confuses the other softwares such as ITK-Snap. Could you try a few things?

1) Install the latest CaPTk release 1.8 from: https://github.com/CBICA/CaPTk 
2) After installing the new release try running the following command:
`Utilities.exe -i [path_to_a_dicom_image] -o [path_to_output_folder] -d2n`

It will create a Nifti file with an auto generated name based on information in the dicom header.

or you could try renaming your existing output 

> Case_002005_20110318_e+1_3Dosem_6i28s_7Ga_AxStd_55dFOV.nii

 to 

> Case_002005_20110318_e+1_3Dosem_6i28s_7Ga_AxStd_55dFOV.nii.gz

Can you let me know if this works?

**Comment by jvbelenky** [comment]
Okay--this seems to be resolved in 1.8.0. However, some images give this output in the nonrelease and 1.8.0 (but not the 1.8.0.Beta): `Warning: Slice timing appears corrupted (range 0..0, TR=0 ms)` . In what situations would this likely become a problem?

Sarthak--I'm not sure why you don't have permissions; I thought I changed the permissions for the entire folder. I've done this again just in case; the command I used was `chmod -R 755 ~/Acrin_FLT/`

**Comment by ashishsingh18** [comment]
> 
> 
> Okay--this seems to be resolved in 1.8.0. However, some images give this output in the nonrelease and 1.8.0 (but not the 1.8.0.Beta): `Warning: Slice timing appears corrupted (range 0..0, TR=0 ms)` . In what situations would this likely become a problem?

Great!! Could you point me to the dicom that gives this error?

**Comment by sarthakpati** [comment]
Glad to hear the new build solved your issue. I'll leave the advanced error message in the capable hands of Ashish.

**Comment by jvbelenky** [comment]
Ashish-- /cbica/home/belenkyv/Acrin_FLT/002005_4221_6688/20110318/e+1_3Dosem_6i28s_7Ga_AxStd_55dFOV/IM-0006-0001.dcm has this issue. You _should_ have permission--let me know if that's not the case.

**Comment by ashishsingh18** [comment]
@jvbelenky Can you check if your input dicoms are not corrupt? Are you getting the exact number of axial slices as you should? This message is coming from the internal tool that we use for dicom to nifti conversion ( dcm2niix ) . When I look at the input dicom folder you shared, it shows half the dicom files of size 1KB - this seems incorrect.
The warning points to the repetition time. It could be that these fields were overwritten during anonymization or it could be an error from the modality side. These are just warnings though and you may want to check if you need this information for your computation.

**Comment by jvbelenky** [comment]
Gotcha, thanks so much! That's probably okay, then.

**Comment by ashishsingh18** [comment]
> 
> 
> Gotcha, thanks so much! That's probably okay, then.

Perfect!! Thank you..
