### ISSUE TITLE
The updated dependency manager does not build with llvm clang

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#135]
The updated dependency manager builds if the c and c++ compilers point to the native Apple clang and clang++, but switching over to llvm clang and clang++ will cause the following errors:

```
/usr/local/Cellar/llvm/6.0.1/lib/clang/6.0.1/include/stddef.h:51:26: error: cannot combine with previous 'int' declaration specifier typedef _PTRDIFF_TYPE_ ptrdiff_t;
                         
/Users/Desktop/CaPTk/dependency_manager/bin/VTK-build/ThirdParty/netcdf/vtknetcdf/config.h:116:19: note: expanded from macro 'ptrdiff_t' #define ptrdiff_t int
```

and 

```
In file included from /usr/local/Cellar/llvm/6.0.1/include/c++/v1/stdio.h:108:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/stdio.h:338:6: error: declaration of '_TIFF_snprintf_f' has a different language linkage int snprintf(char * __restrict __str, size_t __size, const char * __restrict __format, ...) __printfli...
```

**Comment by sarthakpati** [comment]
Did you try changing your environment variables **CC** and **CXX** to point to the correct ones?

**Comment by PhucNgo1711** [comment]
Yes changing the CC and CXX to the native apple clang works, but then I'll have to change them back to LLVM to build CaPTk.

**Comment by sarthakpati** [comment]
I am not sure how I can replicate this. But does changing the compilers work for you?

**Comment by PhucNgo1711** [comment]
Yes. I used CMake GUI to point the compilers to the native version, while keeping the CC and CXX flags pointing to LLVM.

I'm just not sure whether this should be a temporary workaround or a long-term solution.

**Comment by sarthakpati** [comment]
I don't think this is going to be viable long-term. Once the CI/CD (#107) stuff starts, we will need an integrated solution. Maybe @surrsurus can help with this?

**Comment by PhucNgo1711** [comment]
Looks like the superbuild would get pass this issue, but I'm not sure if it has anything to do with the opencv/opencl issue afterward

**Comment by sarthakpati** [comment]
I am curious why this issue has cropped up so suddenly. Could you please open up a new issue so that we can keep a track of it?

**Comment by PhucNgo1711** [comment]
So a new issue for the old standalone dependency manager?

**Comment by sarthakpati** [comment]
Just create an issue referring to the Superbuild.

**Comment by PhucNgo1711** [comment]
This is resolved on mac by just using the native gcc for the superbuild/dependency manager, then switch to llvm for CaPTk build
