### ISSUE TITLE
CaPTk not rendered correctly on certain screen sizes in macOS

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#137]
In a 1280 x 800 screen size (detected by `QApplication::desktop()->screenGeometry()`), CaPTk only renders partially correct in low-resolution mode. A small portion of the right side of the screen is cut off in low-resolution mode, while in default screen size, the whole GUI is mixed up. 

### **Low-resolution mode**
<img width="641" alt="lowressmall" src="https://user-images.githubusercontent.com/14838084/48108359-dc68a600-e210-11e8-819c-59454a6342a3.png">

### **Default**
<img width="1278" alt="highressmall" src="https://user-images.githubusercontent.com/14838084/48108364-e094c380-e210-11e8-8ca7-d3e851074b09.png">

---
In a 1920 x 1080 screen size, CaPTk renders correctly in both default and low-resolution mode. The GUI is rendered perfectly in both a maximized window frame, or a "shrinked" window frame.

### **Low-resolution mode**
![lowresbig1](https://user-images.githubusercontent.com/14838084/48108862-091dbd00-e213-11e8-8abf-ae6ffbd4ae7a.png)

![lowresbig2](https://user-images.githubusercontent.com/14838084/48108863-0ae78080-e213-11e8-9648-b45dcc44701a.png)

### **Default**
![highresbig1](https://user-images.githubusercontent.com/14838084/48108904-3b2f1f00-e213-11e8-8065-d5c9cffdd2cc.png)
![highresbig2](https://user-images.githubusercontent.com/14838084/48108905-3d917900-e213-11e8-8fcc-1739bba4d6f6.png)

**Comment by surrsurus** [comment]
For me I actually don't have this issue at all. It might be a Mac resolution thing? I see you are running a newer release than mine though I'm not sure if that change was introduced between this version and yours. Maybe check out the RC in the email and see if the issue still persists there.

Specs:
MacBook Pro 2017, 2560 x 1600 with the RC candidate 4523 low res mode.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9388076/48134680-a8b96a80-e268-11e8-84fc-f8cdb41cad27.png">

**Comment by PhucNgo1711** [comment]
@surrsurus Can you run the executable in `CaPTk.app/Contents/MacOS/` and see what's your screen size it prints out on the command line. It should be different from the native size 2560 x 1600.

I actually have a 2560 x 1600 native screen size too but CaPTk picks up the actual default display, which is in 1280 x 800. 

You can also see what your actual screen size by going to `Apple Icon > System Preference > Displays > Scaled`, then see what the default screen size is

**Comment by surrsurus** [comment]
Turns out my scaled display is 1440x900, which isn't the 1280x800 that is causing issues.

**Comment by PhucNgo1711** [comment]
I'm still trying to build it locally

**Comment by PhucNgo1711** [comment]
This issue is now fixed with the new changes
