### ISSUE TITLE
Visualization of specified labels within an ROI (instead of every
value)

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#14]
Visualization of specified labels within an ROI (instead of every
value)

**Comment by sarthakpati** [comment]
Needs connection between mMask in vtk and itk data structures and use the itk for doing the change

**Comment by sarthakpati** [comment]
Functionality added and controlled using keyboard

Control + <label number> visualizes only the selected label number 

Alt + <label number> adds selected label number (if present) to current visualization
