### ISSUE TITLE
[RC4523] DeepMedic not working (exiting with error code !=0)

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#140]
This was due to an overwritten executable and has been fixed.

**Comment by pefs44** [comment]
I'm getting this same message on 1.6.1

**Comment by PhucNgo1711** [comment]
I'm getting this error with the latest Beta release

![Screen Shot 2019-11-11 at 12 49 52 PM](https://user-images.githubusercontent.com/14838084/68608906-0ab33e00-0482-11ea-8e6d-b969d699719c.png)

**Comment by sarthakpati** [comment]
Is it working from the command line?

**Comment by PhucNgo1711** [comment]
Running through the command line doesn't throw any error but a cmd window pops up and disappears.

**Comment by sarthakpati** [comment]
Hmm. I am just running it on my machine now. We can debug once you are here in person, I guess?

**Comment by sarthakpati** [comment]
This seems to have been fixed with the newer releases. Re-open if needed.
