### ISSUE TITLE
Change Opacity is not working in Ubuntu 18.04

### ISSUE THREAD

**Issue by ujjwalbaid0408** [CBICA/CaPTk#1401]
When you try to scroll the Change Opacity bar, there is no variation in the intensity of the label.

Observed on Ubuntu 18.04 in CaPTk v1.8.1

**Comment by sarthakpati** [comment]
Tagging @AlexanderGetka-cbica

**Comment by AlexanderGetka-cbica** [comment]
Hi @ujjwalbaid0408 Thanks for the bug report. Just to confirm: You are talking about the "Change Opacity" bar at the top of the GUI when you are on the "Images" tab, correct? If so, does the "Marker Opacity" drop-down box on the Drawing tab work for you?

Looking at both of these issues now.

**Comment by ujjwalbaid0408** [comment]
Yes, this is for "Change Opacity" bar at the top of the GUI.
the "Marker Opacity" drop-down box on the Drawing tab is working properly for me.
