### ISSUE TITLE
The download address seems to be invalid.

### ISSUE THREAD

**Issue by yctulip** [CBICA/CaPTk#1402]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**CaPTk Version**
Version information is found on Help > About

**Desktop (please complete the following information):**
 - OS: [e.g. Windows/Linux (include detailed distro information)/macOS]
 - Version (including Build information, if any): [e.g. Fedora 22 or Windows 10.1803]

**Additional context**

**Comment by sarthakpati** [comment]
Hi,

Thanks for reporting this! 

I just moved all [stable releases](https://github.com/CBICA/CaPTk#latest-stable-181) to the https site and they should now be operational.

Cheers,
Sarthak
