### ISSUE TITLE
Core Dump message when using .cwl FeatureExtraction aplication in linux

### ISSUE THREAD

**Issue by rafaloz** [CBICA/CaPTk#1408]
**Describe the bug**
Core dump message when using the FeatureExtraction.cwl app in linux Ubuntu 20.04. Also appears when using batch processing. Nonetheless, I can extract the features case by case using the GUI.

**To Reproduce**
1. Install CaPTk
2. Use FeatureExtraction.cwl

**Expected behavior**
Feature extraction of the case. 

**Screenshots**
![Screenshot from 2021-04-07 20-05-53](https://user-images.githubusercontent.com/19437794/113914395-cb576100-97dd-11eb-9204-fd1f1a297e05.png)

**CaPTk Version**
CaPTk 1.8.1

**Desktop (please complete the following information):**
 - OS: Linux
 - Ubuntu 20.04.2 LTS
   Kernel: Linux 5.4.0-70-generic
   Architecture: x86-64

**Comment by AlexanderGetka-cbica** [comment]
Pinging @sarthakpati

**Comment by sarthakpati** [comment]
Hi @rafaloz,

Thank you for your interest in CaPTk!

Would it be possible to share the parameter file and the mask (not the images) so that we can debug this?

Cheers,
Sarthak

**Comment by rafaloz** [comment]
Sure! The parameter file is the default one with resampling = 1. I attach both, the file and the mask to this message. 
[Files_debugging.tar.gz](https://github.com/CBICA/CaPTk/files/6274072/Files_debugging.tar.gz)

**Comment by sarthakpati** [comment]
Thank you. I will debug and keep you posted.

**Comment by sarthakpati** [comment]
Hi @rafaloz,

Could you please try with the default parameter file in https://github.com/CBICA/CaPTk/blob/master/src/applications/FeatureExtraction/data/1_params_default.csv?

I believe there are a few values that are needed but are missing. I will put an error check for those, thank you!

**Comment by rafaloz** [comment]
Tested. 
![Screenshot from 2021-04-08 18-25-45](https://user-images.githubusercontent.com/19437794/114062752-28afe880-9898-11eb-9bb2-da1b3cdca19f.png)

I didn't checked the part:

_Histogram binning type needs to be defined in the parameter file, please see default parameter file for example.
Quantization extent needs to be defined in the parameter file, please see default parameter file for example._

since I was using almost the exact parameter file I thought It was not that important

I'll read more carefully next time, thanks for your time sry!

**Comment by sarthakpati** [comment]
Thank you for making the error checking on our end better! Closing this issue out, please feel free to either re-open this or open a new one if you run into issues. 😄

**Comment by rafaloz** [comment]
I am having problems using the .cwl still... is there any working parameter file available?

**Comment by sarthakpati** [comment]
Hi, you can use this: https://github.com/CBICA/CaPTk/blob/master/src/applications/FeatureExtraction/data/1_params_default.csv
