### ISSUE TITLE
multimodal registration PET/MRI

### ISSUE THREAD

**Issue by xav69ier** [CBICA/CaPTk#1411]
I aim at co-registering classical 4xMRI (T1/T2/T1CE/FLAIR) with 1xPET (PET scans have a companion CT for attenuation correction). The BRATS pipeline offers co-registration for the first set (MRI). I wonder how to enlarge that pipeline to include multimodal co-registration. I guess I should co-register PET > CT > T1CE > SRI-24 (https://www.nitrc.org/projects/sri24/) to end up with a set of 6 co-registered images (instead of the 4x of the BRATS pipeline).

Many thanks in advance for any ideas
xavier

**Comment by sarthakpati** [comment]
Hi @xav69ier,

Thank you for your interest in CaPTk!

I would recommend doing a [rigid registration](https://cbica.github.io/CaPTk/preprocessing_reg.html) of PET/CT > T1CE > SRI.

Reopen this issue or post in discussion if you have more questions!

Cheers,
Sarthak
