### ISSUE TITLE
CaPTk Feature Extraction Error on Cluster

### ISSUE THREAD

**Issue by sherjeel275** [CBICA/CaPTk#1417]
**Describe the bug**
I am running the FeatureExtraction module of CaPTk on CBICA Cluster, but the output I'm getting is significantly different from the output I get when I run the FeatureExtraction locally on my pc. The output from the cluster has numerous variables that are different. I'm not sure why the variables being generated on the cluster are different.

**To Reproduce**
1. Run FeatureExtraction module on local pc
2. Run FeatureExtraction module on cluster
3. Compare the two outputs

Cluster Command:
`FeatureExtraction -b batch.csv -p params.csv -o output.csv`

Local Command:
`C:\CaPTk_Full\1.8.1\bin\FeatureExtraction -b batch.csv -p params.csv -o output.csv`

**Expected behavior**
The 2 outputs should be the same and should have the exact same features inside the csv files that get generated.

**CaPTk Version**
I'm using version 1.8.1

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by sarthakpati** [comment]
Hey,

What is the version of CaPTk you are running on the cluster? Also, can you post the parameter file you are using?

**Comment by sherjeel275** [comment]
I think I'm using v1.8.1 on the cluster. I did `module load captk/1.8.1` before running FeatureExtraction on the cluster.

**Comment by sarthakpati** [comment]
Okay. Could you add the following lines before you call FeatureExtraction as a sanity check?

```bash
which FeatureExtraction 
FeatureExtraction -v
```

I have seen your email with the parameter file, thanks.

**Comment by sarthakpati** [comment]
Hi,,

Based on the data you had sent, I found a single source of difference, which I consider negligible:
![image](https://user-images.githubusercontent.com/11719673/121959214-7d595f00-cd32-11eb-90b1-eb27d7ac1229.png)

[outputs.zip](https://github.com/CBICA/CaPTk/files/6651261/outputs.zip)

Added the outputs for reference. I extracted the features using v1.8.1 from my local Windows and from the cluster.

Closing the ticket, please re-open if you have further questions.

Cheers,
Sarthak
