### ISSUE TITLE
linux: installer multiple issues

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#145]
1. Send the license agreement through a pager.

2. Make the license agreement loop a limited number of times (3?) on responses that are not "y" or "n" before defaulting to "n".

3. More robust handling if the ~/CaPTk/ **directory** cannot be created. Exit at that moment...do **not** overwrite the file named ~/CaPTk. (The test for failure to create ~/CaPTk/ would also cover cases where there is insufficent disk space, incorrect permissions, etc). For example:

```
mv ~/SomeReallyImportantResearchDataFile.txt ~/CaPTk
 /tmp/CaPTk_1.6.0_RC_4603.bin
........
I accept the above license (y/n): y
Installing... -chmod: cannot access '/datil/home/bergman/CaPTk/CaPTk.bin': Not a directory
CaPTk.bin moved to ~/CaPTk.
Run the binary by navigating to the ~/CaPTk directory and running './CaPTk.bin' in the console
[bergman@huajiao ~]$ ls ~/CaPTk
/datil/home/bergman/CaPTk*
[bergman@huajiao ~]$ file !$
file ~/CaPTk
/datil/home/bergman/CaPTk: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, stripped
```

4. More robust handling if the file ~/CaPTk/CaPTk.bin cannot be created or is truncated:

[bergman@huajiao ~]$ df -hl ~
Filesystem         Size  Used Avail Use% Mounted on
```
/dev/mapper/datil  849G  849G   15M 100% /datil
I accept the above license (y/n): y
Installing... \CaPTk.bin moved to ~/CaPTk.
Run the binary by navigating to the ~/CaPTk directory and running './CaPTk.bin' in the console
[bergman@huajiao ~]$ ls -l ~/CaPTk/CaPTk.bin 
-rwx--x--x. 1 bergman bergman 15486976 Nov 12 12:04 /datil/home/bergman/CaPTk/CaPTk.bin*
[bergman@huajiao ~]$ file !$
file ~/CaPTk/CaPTk.bin
/datil/home/bergman/CaPTk/CaPTk.bin: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, stripped
[bergman@huajiao ~]$ !$
~/CaPTk/CaPTk.bin
Something went wrong trying to read the squashfs image.

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
[bergman@huajiao ~]$ 
```

5. Rename installer to CaPTk_1.6.0_installer, to reduce user confusion that they are executing the application.

**Comment by surrsurus** [comment]
1. License is now being piped through `more`
2. License agreement now uses `select` which prompts for an explicit yes no answer before looping. It will continue to loop until a recognized input is given. If you think more should be done feel free to reopen this issue.
3. Explicit checks to verify if either the file or directory `~/CaPTk` has been added.
4. Program checks to see if there is enough disk space for the binary. I'm not sure what else there is to be done here.
5. Installer is generated with the correct version number.

Committed to trunk as of rev 4625. Installer can still be built via `./scripts/captk-pkg` and running that script from the root of the project.
