### ISSUE TITLE
BratsPipeline crushes after "Starting bias correction for modality 'FL'."

### ISSUE THREAD

**Issue by kondratevakate** [CBICA/CaPTk#1453]
**Describe the bug**
BratsPipeline crushes after "Starting bias correction for modality 'FL'." in log. So I use the docker version and attach the folder with 4 *nii files for preprocessing and prediction.

**To Reproduce**
1. run BratsPipeline inside Captk docker
2. `docker run -it --rm --name "bratspipeline" --cpuset-cpus="1-8" --gpus=all -v /input/:/input -v /output/
:/output kondrateva/captk:0.0.1 -t1 /input/T1.nii.gz -t1c /input/CT1.nii.gz -t2 /input/T2.nii.gz -fl /input/FLAIR.nii.gz
 -o /output`

3.  Execution stopped after "Starting bias correction for modality 'FL'."

**Expected behavior**
I did the same for other files, and it never stopped like this. Maybe smth is wrong with my *nii files?

**Screenshots**
![image](https://user-images.githubusercontent.com/34157226/141477518-b879655c-d27c-4f30-9afc-85eb5fdc3b87.png)

**CaPTk Version**
`docker pull cbica/captk`

**Desktop (please complete the following information):**
 - linux cluster

**Comment by AlexanderGetka-cbica** [comment]
Hi @kondratevakate, and thank you for the issue report.
To help us diagnose this issue, is it possible for you to provide the input you used and show what files were produced, if any? And just to be sure, is there any other text output when you run the command?

If that isn't possible, then please run CaPTk's image info on the provided inputs and upload the corresponding output here.
It should be usable by calling the Utilities executable, like:
Utilities -inf -i /input/T1.nii.gz

But it may need you to change the entrypoint on the container -- please let me know if you have any trouble with this and I'll be happy to assist.

**Comment by kondratevakate** [comment]
I found out, it is not about the data - it's about my script. This one worked for me earlier to run BratsPipeline, I've changed the entry point in DockerFile to:

`ENTRYPOINT ["/work/CaPTk/bin/install/appdir/usr/bin/BraTSPipeline"]`

Maybe you can suggest another approach to run BratsPipeline in docker interactive?

**Comment by AlexanderGetka-cbica** [comment]
That entry point seems correct -- what do you mean when you say it's your script? Does this happen with any other data?

You could run your image with "--entrypoint /bin/bash" to get a shell inside the container, then run the BraTSPipeline from inside the container like that.

**Comment by kondratevakate** [comment]
yes, all operating. thanks! the one working for me:

```docker run -it --rm --cpuset-cpus='19-24'  --name "bratspipeline" -v /input/:/input -v /output/:/output --entrypoint /bin/bash captk:0.0.1 

CaPTk/bin/BraTSPipeline -t1 /input/t1.nii.gz -t1c /input/t1c.nii.gz -t2 /input/t2.nii.gz -fl /input/flair.nii.gz -o /output/brats_out/
```

**Comment by AlexanderGetka-cbica** [comment]
OK, great! Closing this issue. Please feel free to open another issue if you come across anything else.
