### ISSUE TITLE
[1.8.2.Alpha] PerfusionPCA disabled from CLI, not working from GUI

### ISSUE THREAD

**Issue by AlexanderGetka-cbica** [CBICA/CaPTk#1458]
**Describe the bug**
From the CLI, attempting to use PerfusionPCA yields the following message:
`This functionality has been removed from this CaPTk release, and we are actively testing an optimized robust implementation that would enable generalization in multi-institutional data. We expect this to be released in our next patch release, expected in Q4 2020`

From the GUI, the application will not run, or complains about missing inputs. (Waiting on clarification about this).

**To Reproduce**
1. Run PerfusionPCA from CLI, with any parameters
2. See error
OR
1. Launch the CaPTk GUI
2. Launch PerfusionPCA from the applications menu
3. Application fails to run or throws an error about missing inputs.

**Expected behavior**
The CLI error should be disabled in this alpha since as I understand it the changes to it have  been made.
The GUI error should not happen so long as users provide the right input.

**CaPTk Version**
1.8.2.Alpha

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
Problem first reported by Jose Garcia.

**Comment by AlexanderGetka-cbica** [comment]
I cannot reproduce this on my Ubuntu installation of 1.8.2.Alpha. While the CLI is finicky (on first run, if the output dir doesn't exist, it will silently exit and not actually run until the next run, and the required input structure is very strict), it does succeed for me. Likewise, the GUI also works for me.

**Comment by sarthakpati** [comment]
> if the output dir doesn't exist, it will silently exit

We can easily fix this, I guess?
