### ISSUE TITLE
BraTSPipeline (and also probably Brain Tumor Segmentation) model version check fails.

### ISSUE THREAD

**Issue by AlexanderGetka-cbica** [CBICA/CaPTk#1468]
**Describe the bug**
When running BraTSPipeline, an error occurs where it says the model version is not compatible with this version of CaPTk.

**To Reproduce**
1. Run the BraTSPipeline with any input.
2. See error: `Starting skull-stripping using DeepMedic.
Command for DeepMedic: /Applications/CaPTk_1.9.0.Alpha.app/Contents/Resources/bin/DeepMedic -md /Applications/CaPTk_1.9.0.Alpha.app/Contents/Resources/bin/../data//deepMedic/saved_models/skullStripping/ -i out_from_nifti/T1_to_SRI.nii.gz,out_from_nifti/T1CE_to_SRI.nii.gz,out_from_nifti/T2_to_SRI.nii.gz,out_from_nifti/FL_to_SRI.nii.gz -o out_from_nifti/dmOut_skull/brainMask_SRI.nii.gz
The version of model is incompatible with this version of CaPTk.
Finished successfully.
Brain Mask was not written, cannot proceed.`

**CaPTk Version**
1.9.0.Alpha

**Additional context**
Originally noted by @chiharusako.

Probably also occurs in Brain Tumor Segmentation and potentially other model-based algorithms.

**Comment by sarthakpati** [comment]
This requires updates to the `VERSION.yaml` files in https://github.com/CBICA/CaPTk/tree/master/data/deepMedic/saved_models
