### ISSUE TITLE
404 error downloading CaPTk 1.9.0 installer for Windows

### ISSUE THREAD

**Issue by waltman** [CBICA/CaPTk#1495]
**Describe the bug**
A 1.9.0 build for Windows is listed at https://www.nitrc.org/frs/?group_id=1059, but clicking on it returns a 404 error

**To Reproduce**
1. Go to https://www.nitrc.org/frs/?group_id=1059
2. Click the Windows x64 link under the 1.9.0 release
3. Click Submit on the next page
4. This goes to https://captk.projects.nitrc.org/CaPTk_1.9.0_Installer.exe, which is returning a 404 error

**Expected behavior**
It downloads the Windows x64 installer for CaPTk 1.9.0

**Screenshots**

**CaPTk Version**
1.9.0

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 10.0.19044 Build 19044

**Additional context**

**Comment by AlexanderGetka-cbica** [comment]
Hi Walt, I had to change the links pre-emptively in the README. Those links will be populated tonight with the 1.9.0 version installers.

**Comment by waltman** [comment]
OK, thanks. I’ll try again over the weekend.

Walt

From: Alexander Getka ***@***.***>
Sent: Friday, May 27, 2022 4:49 PM
To: CBICA/CaPTk ***@***.***>
Cc: Mankowski, Walter ***@***.***>; Author ***@***.***>
Subject: [External] Re: [CBICA/CaPTk] 404 error downloading CaPTk 1.9.0 installer for Windows (Issue #1495)


Hi Walt, I had to change the links pre-emptively in the README. Those links will be populated tonight with the 1.9.0 version installers.
