### ISSUE TITLE
Installers should create install trees for each version

### ISSUE THREAD

**Issue by surrsurus** [CBICA/CaPTk#151]
Installers should create install trees in the format of
```
~/CaPTk
    1.5/
    1.6/
    ...
```

For OSX this is a slight issue as OSX really likes to have only the most up to date version of software and the Applications folder doesn't really accept this (not to mention the typical OSX user might be confused).

On linux this should be fairly simple, however.

**Comment by surrsurus** [comment]
Linux installer now has this feature and it is in the trunk as of revision 4656.

**Comment by sarthakpati** [comment]
Since the standard packaging in OSX does not follow this kind of paradigm, I am closing this issue out.
