### ISSUE TITLE
Different way to package CaPTk installer on Mac

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#152]
Currently, when running the .dmg to install CaPTk, users must drag CaPTk.app into the Applications/ folder in order for CaPTk be properly set up.

However, there is no way to "stop" the user from running the .app in the pop-up window created by the .dmg. Hence, a better packaging method must be implemented, in which the .app inside the pop-up window is replaced by an installer. By running the installer, a .app is generated and copied over to the Applications/ folder automatically.

**Comment by surrsurus** [comment]
I can attest that I've been running the app directly from wherever and haven't had issues with it.  Plus most OSX installers by default don't force you to install to the Applications folder so I don't think this is too big of an issue. As long as the average OSX user can understand how to use the installer there shouldn't be a problem.

Another solution is to use some custom graphics to help direct the user to place the .app in the Applications folder as I've seen on some installers. Something like an arrow from the .app to the folder. While that probably will just add another layer of insanity to the already insane method of OSX packaging, it *is* an option.

**Comment by sarthakpati** [comment]
This is no longer an issue, is it @PhucNgo1711?

**Comment by PhucNgo1711** [comment]
yes
