### ISSUE TITLE
Documentation is not getting picked up properly 

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#154]

**Comment by sarthakpati** [comment]
@surrsurus @PhucNgo1711 could you please check the fix I have pushed just now for the Linux & macOS builds? Check if **1_credits.html** and **0_overview_resize.png** are coming up in `share/doc`. Thanks.

**Comment by surrsurus** [comment]
Having some issues with building on a linux box at home (its been over several years since the software has been updated), however I will check to ensure everything is showing up properly first thing Monday morning when I'm back at my regular desktop.

**Comment by sarthakpati** [comment]
Fixed.
