### ISSUE TITLE
Feature extraction CLI -vc 1 parameter issue

### ISSUE THREAD

**Issue by sbakas** [CBICA/CaPTk#161]
If -vc 1 is used then not all features are extracted.
If -vc 1 is NOT used then additional(?) features are extracted.
Contact Anahita for example subjects

**Comment by sarthakpati** [comment]
Already initiated contact and she has provided the dataset where she is seeing this issue.

**Comment by sarthakpati** [comment]
This was a bug in the code and has been fixed in the last commit on my fork. 

Ref: https://github.com/sarthakpati/CaPTk/commit/e35d9822a6e9ddfeb68679b8b73bd661be76dd6f

**Comment by sarthakpati** [comment]
This has evolved into something different, closing this issue and opening a new one.
