### ISSUE TITLE
Unix CI

### ISSUE THREAD

**Issue by surrsurus** [CBICA/CaPTk#170]
Unix CI revolves around two areas:
- [x] Linux CI
  - [x] Needs to use git LFS to pull in related Qt binary blobs
  - [x] Needs a way to pull in and build dependencies (script?)
  - [x] Possible modifications to existing build script needed to support this change
- [ ] OSX CI
  - [x] Needs to use git LFS to pull in related Qt binary blobs
  - [x] Needs homebrew packages required for build (can be done through CI)
  - [ ] Ideally some sort of script to work with CI to build dependencies and a working version of CaPTk

**Comment by surrsurus** [comment]
Having some issues with Git LFS. We can use lfs to pull in the Qt binaries, however for some reason the refs appear to be broken on my fork. Will be looking into this after the more pressing issue of CWL/Persistent command line for linux is added.

**Comment by surrsurus** [comment]
Today Phuc added a build matrix for both osx and linux so both will build at the same time. Ideally, once the new superbuild changes are in place building should be much simpler on travis.

**Comment by sarthakpati** [comment]
I believe using cache will solve this. Ref: https://docs.travis-ci.com/user/caching/

**Comment by surrsurus** [comment]
Interesting, on my fork my issue was that travis ran out of memory every time. Wonder if this also fixes the issue.

**Comment by surrsurus** [comment]
CCache has been implemented, this removes the issue of the dependency manager taking >50 minutes to run. From start to finished dependency manager build takes about 10 minutes now. Having some issues with cmake being able to find the new ITK-build cmake files, which causes errors. Another concern is that the cache wont carry over when it's merged into master but I don't see a reason why it wouldn't be unless travis hasn't implemented that.

**Comment by surrsurus** [comment]
Linux end-to-end compiles on travis work fully, taking about 1:30 to complete. Caching seems to behave oddly, as VTK constantly needs to recompile.

**Comment by sarthakpati** [comment]
Moving to a new solution. Travis will (hopefully) be deprecated for us soon.
