### ISSUE TITLE
Unable to load dicom 

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#179]
Cannot load Dicom images into Captk via File->Load->Images or drag and drop.
It shows a pop up error message that states: 'Couldn't convert  DICOM with default parameters, please use command line functionality'. Please see the attached screenshot.

![capture-captk-dicom-load-error](https://user-images.githubusercontent.com/43445206/50113951-5da05900-0211-11e9-94aa-4b6cac7ddf45.PNG)

**Comment by activegalaxy** [comment]
Just downloaded Windows version on 2/14/2019 and experienced the same issue.

**Comment by sarthakpati** [comment]
A fix for this is coming.

**Comment by sarthakpati** [comment]
Fix is part of latest series of PRs. Closing this.
