### ISSUE TITLE
Appropriate visualization of longitudinal brain MRI

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#18]
Appropriate visualization of longitudinal brain MRI

**Comment by sarthakpati** [comment]
@sbakas can you provide details/screenshot for this, please?

**Comment by sbakas** [comment]
the default visualization panels in captk when loading a nifti image, show the three different views (axial, coronal, sagittal. The appropriate visualization would be to display a single view (e.g. axial) of each of these longitudinal/three scans, one in each visualization panel. It is not exactly a straight forward change.

**Comment by sarthakpati** [comment]
In progress.

**Comment by ashishsingh18** [comment]
Done as part of #426
