### ISSUE TITLE
DeepMedic output change

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#180]
ROI value of **3** needs change to **4** to conform to the BraTS/GLISTRboost standard.

**Comment by sarthakpati** [comment]
@sbakas is this still the case?

**Comment by sbakas** [comment]
In which version?

**Comment by sarthakpati** [comment]
**1.7.0_nonRelease**

**Comment by sarthakpati** [comment]
@sbakas is this still needed for the **1.7.0.Beta**?

**Comment by sarthakpati** [comment]
Fixed.
