### ISSUE TITLE
Help menu is not a floating window

### ISSUE THREAD

**Issue by sbakas** [CBICA/CaPTk#197]
v.1.6.0: The help menu window itself should be in a floating window, thereby allowing a user to go back and forth between an application within CaPTk and the instructions on how to run an application

**Comment by PhucNgo1711** [comment]
@sarthakpati is this updated?

**Comment by sarthakpati** [comment]
Nope, this is still an "discussion" phase.

**Comment by sarthakpati** [comment]
This is not feasible with the workflow.
