### ISSUE TITLE
Help menu font size is not adaptable 

### ISSUE THREAD

**Issue by sbakas** [CBICA/CaPTk#198]
v.1.6.0: The help menu font size cannot be reduced by any known shortcuts [(CTRL and +) or (CTRL and mouse wheel)], and there is no option similar to various text viewers in the bottom right corner to adjust the zoom level. Current font size is extremely large (viewing this in a 4K monitor). Tried to change the font zoom level from the OS level (in windows) and did not change anything.

**Comment by sarthakpati** [comment]
This actually goes towards making the help menu more intuitive for users. Tagging @ashishsingh18 

I am not sure if we will be able to fix this for 1.6.1 but we should target for the ITCR release.

**Comment by sarthakpati** [comment]
Do this make sense [[ref](https://forum.qt.io/topic/76319/how-to-control-the-font-size-in-qwebengineview/5)]?

`QWebEngineSettings *defaultSettings = QWebEngineSettings::globalSettings();
defaultSettings->setFontSize(QWebEngineSettings::MinimumFontSize,16);`

**Comment by ashishsingh18** [comment]
Done.
