### ISSUE TITLE
Multiple Sample Data Availability

### ISSUE THREAD

**Issue by sbakas** [CBICA/CaPTk#199]
v.1.6.0: It seems that there are 2 sets of sample data installed/available in two different locations. One available upon CaPTk installation (within the installation folder) and another downloadable from the Help -> "sample data" CaPTk menu (saved under the $user$ folder by default without an option to choose)?

**Comment by sarthakpati** [comment]
The **data** folder in the CaPTk installation has files that are needed for CaPTk to work (for instance, the parameter files for Feature Extraction) and a single sub-sampled image with its accompaying mask. Unless we call it **SampleData**, it there any cause for confusion?

**Comment by sarthakpati** [comment]
Was not able to reproduce this. Closing.
