### ISSUE TITLE
Sample Data Versioning

### ISSUE THREAD

**Issue by sbakas** [CBICA/CaPTk#200]
v.1.6.0: Downloaded sample data should mention the CaPTk version somewhere - perhaps in the folder that they are saved? Otherwise these are getting mixed up with previous/next sample data.

**Comment by sarthakpati** [comment]
It is critical that this is fixed. Tagging @saimarathore @ashishsingh18

**Comment by sarthakpati** [comment]
The user now has the option of putting the sample data where they want. The **VERSION.yaml** is distributed along with it.

**Comment by sbakas** [comment]
Sample data filenames still in v.1.6.1.Beta do not include version number. Please add a v.X.Y.Z at the end of the zip files.

**Comment by sarthakpati** [comment]
The sample data have versions when the zip is extracted.
