### ISSUE TITLE
Help menu does not close after application closes

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#209]
Steps to replicate:

- Help > Usage
- Close CaPTk
- Help does not close

**Comment by sarthakpati** [comment]
Related:

- https://bugreports.qt.io/browse/QTBUG-49804?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true
- https://forum.qt.io/topic/255/how-to-delete-properly-a-qwebview-63
- https://stackoverflow.com/a/35097121/1228757

**Comment by ashishsingh18** [comment]
Looks like there is an issue with Qt 5 that is still unresolved for QtWebEngine 
Here's another bug report:
https://bugreports.qt.io/browse/QTBUG-56774

**Comment by ashishsingh18** [comment]
Additionally there are memory leaks in our code.
We have allocated memory for both web engine as well as help dialog but not cleared it.

**Comment by ashishsingh18** [comment]
This issue is now fixed!
Need to test it on all supported platforms.

**Comment by sarthakpati** [comment]
@PhucNgo1711 @surrsurus could you please test the fix proposed by @ashishsingh18 for macOS and Linux machines and report back?

**Comment by PhucNgo1711** [comment]
we just pull from @ashishsingh18 repo right?

**Comment by sarthakpati** [comment]
@PhucNgo1711 yes.

**Comment by sarthakpati** [comment]
Fixed.

**Comment by surrsurus** [comment]
Works on linux.
