### ISSUE TITLE
The standalone exe parser needs update

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#21]
The standalone exe parser needs update

**Comment by sarthakpati** [comment]
Some details, @MarkBergman-cbica?

**Comment by MarkBergman-cbica** [comment]
I dunno. Was that the entire content from the original NITRC ticket, or just the title?

**Comment by sarthakpati** [comment]
Only detail I found:

> The function **fMainWindow::PreparePythonScriptAndConfig** needs to be updated post-MICCAI

This is no longer needed since we have changed the way standalone executables are invoked from within CaPTk. closing the ticket.
