### ISSUE TITLE
About/frontpage figure scaling issue

### ISSUE THREAD

**Issue by sbakas** [CBICA/CaPTk#217]
About/Frontpage figure in v.1.6.1.Beta is not of sufficient resolution, while running CaPTk in a 4K monitor.

Perhaps this can be solved using a scaling factor after detecting the monitor's resolution.

- OS: [Windows 10]
- Version [1.6.1.Beta]

**Comment by PhucNgo1711** [comment]
@ashishsingh18 @sarthakpati

**Comment by sarthakpati** [comment]
This has been fixed, I believe.

**Comment by ashishsingh18** [comment]
This should be fixed after my recent commit.
