### ISSUE TITLE
Pseudo-progression application (results interpretation)

### ISSUE THREAD

**Issue by sbakas** [CBICA/CaPTk#219]
**Describe the bug**
Using the pre-trained model, the application seems to work, i.e. produces a csv with numbers. However, it is unclear what these numbers represent. the documentation (help menu) does not have an indication of how these numbers can be interpreted.

**Possible solution**
A short description in the documentation reporting the obtained results using the sample data we provide, followed by the threshold definitions could solve this issue. e.g. values above 2 indicate pseudo-progression.

**Desktop (please complete the following information):**
OS: [Windows 10]
Version [1.6.1.Beta]

**Comment by saimarathore** [comment]
added details
