### ISSUE TITLE
Pseudo-progression application (train new model functionality issue)

### ISSUE THREAD

**Issue by sbakas** [CBICA/CaPTk#220]
**Describe the bug**
- This functionality is not available at the moment given the sample data (n=5) we provide, or even after the 5 subjects are increased to 23.
- There is a typo on the error/warning message.
- The error/warning message indicates that at least 20 subjects are needed to build a reliable model, when the provided data include just 5 subjects.
- When artificially increasing the sample data by duplicating the existing sample data and reached 23 subjects, the same error message still appears.

**Desktop (please complete the following information):**
OS: [Windows 10]
Version [1.6.1.Beta]

**Comment by sarthakpati** [comment]
@saimarathore this fixed, right?

**Comment by sarthakpati** [comment]
The training is working on 1.8.0.Alpha2; but testing needs debugging.
