### ISSUE TITLE
developer-install target for CMake

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#236]
**Is your feature request related to a problem? Please describe.**

People seeking to extend CaPTk or create new work using the same dependencies -- with the same build configuration -- need an installation of the CaPTk libraries & headers, even if they aren't working with the source tree.

Example use case: CBICA cluster install, providing ITK, VTK, OpenCV, eigen as distinct libraries (ie., not only statically linked into CaPTk) as configured & built for CaPTk.

**Describe the solution you'd like**

cmake -DBuild:STRING=developer -DCMAKE_INSTALL_PREFIX:PATH=/path/to/devtools/CaPTk .... ; make && make install

**Comment by sarthakpati** [comment]
This is now present during Superbuild installation.
