### ISSUE TITLE
PseudoProgression module in CaPTk-1.6.1

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#237]
**Describe the bug**
Pseudoprogression module in CaPTk 1.6.1 does not detect patients in the testing directory as mentioned by the user. Displays the error message: "The specified directory does not have any subject with all the required imaging sequences."

**To Reproduce**
1. Go to 'Applications' menu. 
2. Click 'Glioblastoma PseudoProgression Infiltration Index'. 
3. Specify the test directory, model directory and output directory, and press 'Confirm' button. 

**Expected behavior**
The system should apply the selected model on the selected patients, and write the .csv output file in the specified output directory. 

**Desktop (please complete the following information):**
 - OS: Windows 7 Enterprise, 64 bit operating system

**Screenshots**
![captk_crash](https://user-images.githubusercontent.com/38562504/52089336-51cbe480-257c-11e9-83d1-391175c26740.png)

**Comment by AlexanderGetka-cbica** [comment]
I can't seem to replicate this on Ubuntu 18.04 running CaPTk 1.7.2 or later.

**Comment by ashishsingh18** [comment]
cannot reproduce on 1.8.0Alpha.
