### ISSUE TITLE
Dialog box of survival module disappears as soon as user presses 'Confirm' button (as reported by Hamed)

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#238]
Survival module in CaPTk 1.6.1 does not perform any operation. The dialog box closes as soon as the user presses 'Confirm' button, both for training and testing modules.

To Reproduce

Go to 'Applications' menu.
Click 'Glioblastoma Survival Prediction Index'.
Specify the test directory, model directory and output directory, and press 'Confirm' button.

Expected behavior
The system should apply the selected model on the selected patients, and write the .csv output file in the specified output directory.

Desktop (please complete the following information):
OS: Windows 7 Enterprise, 64 bit operating system

**Comment by AlexanderGetka-cbica** [comment]
I tried to replicate this on Ubuntu 18.04 and did not see the dialog box close in the case of either training a new model or testing. In both cases the program froze for a few minutes, then completed the operation before the dialog box ever closed.
