### ISSUE TITLE
macOSX CaPTk builds with standalone dependency_manager but not with Superbuild

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#239]
**Describe the bug**
The CaPTk _make_ step would fail after the Superbuild has successfully built, and ITK is pointed to **${PROJECT_SOURCE_DIR)/bin/ITK-build**. However, the _make_ step will run successfully if ITK is pointed to **/dependency_manager/bin/ITK-build**, which is built separately.

**To Reproduce**
1. Build dependency manager separately
2. The **CaPTk Cmake** build directory that uses the Superbuild will be put in **bin**, and the **CaPTk Cmake** build directory that uses the standalone dependency manager will be put in **bin2**.
3. Run _cmake ../_ and _make_ in both **bin** and **bin2**
4. **bin** would throw an _openCV/openCL_ error, **bin2** would build successfully

**Expected behavior**
Superbuild should not have an issue because it's the same as the dependency manager

**Screenshots**

**CaPTk Version**
1.6.1 Alpha

**Desktop (please complete the following information):**
 - OS: macOSX
 - Version: 10.13 & 10.14

**Comment by sarthakpati** [comment]
Is there anything in the Apple specific code in CMake that points to this location?

**Comment by PhucNgo1711** [comment]
Testing your new changes to see if this is fixed. I looked around and there wasn't anything that is really mac specific beside the compliers

**Comment by PhucNgo1711** [comment]
I just got the CaPTk build working with the Superbuild, but I had to turn the OpenCL flag off

**Comment by PhucNgo1711** [comment]
The open CL flag is still off for recent builds and fixes just an FYI

**Comment by sarthakpati** [comment]
Closing since this is now redundant. Can reopen if needed.
