### ISSUE TITLE
Feature extraction: include more data in output files

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#24]
Feature extraction: include more data in output files

**Comment by sarthakpati** [comment]
The data that is needed is the images from where the extraction has happened, parameters of the feature families used, etc.

**Comment by sarthakpati** [comment]
This can also be used to check whether the same FeatureMap was used for extraction before and then not to repeat it for a particular case. This can be very useful for batch processing multiple cases.

**Comment by sarthakpati** [comment]
Include DICOM codes from IBSI paper with output.

**Comment by sarthakpati** [comment]
This can be done easily if we use a YAML file for the output.

**Comment by sarthakpati** [comment]
Added; done.
