### ISSUE TITLE
Update the GitHub Wiki for CaPTk

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#240]
**Is your feature request related to a problem? Please describe.**
The GitHub Wiki [[ref](https://github.com/CBICA/CaPTk/wiki)] is a good place to put generic usage and compilation instructions.

**Describe the solution you'd like**
Having some information there would be nice, even if it is just links to the pages in the main source code.

**Comment by surrsurus** [comment]
I will put some documentation about the linux tooling on there, I think its a good place to store that information for collaborators.

**Comment by sarthakpati** [comment]
Excellent idea! Ryan can be our first test case.

**Comment by surrsurus** [comment]
I've added my article about compiling captk on linux, included some blurbs about the app image, ubuntu 16.04, and the superbuild, so it should definitely help him out. In addition, there's also room to expand this to OSX and windows once people get the chance to write them. I also modified the home page to be a bit more informational (based off of the upenn website), and added a footer that links back to the site and the issues page on github in case if someone notices a typo or error. Definitely will be continuing to document more about how the linux side of things work in the future.

**Comment by surrsurus** [comment]
@sbakas

**Comment by sarthakpati** [comment]
Also, could you tag Mark? I think we should not have scientific information on this wiki (I feel that should be there in our med.upenn page). Here, we can keep things relevant to the implementation and sources. 

Thoughts?

**Comment by surrsurus** [comment]
@MarkBergman-cbica

**Comment by MarkBergman-cbica** [comment]
> Also, could you tag Mark? I think we should not have scientific information on this wiki (I feel that should be there in our med.upenn page). Here, we can keep things relevant to the implementation and sources.
> 
> Thoughts?

Absolutely agree.

**Comment by PhucNgo1711** [comment]
What's the status on this ticket?

**Comment by sarthakpati** [comment]
@PhucNgo1711 this is up to date and can be closed.
