### ISSUE TITLE
'features' directory not created in make install step anymore on macOSX

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#245]
**Describe the bug**
After the install step was moved from the root CMakeList.txt to FeatureExtraction/CmakeLists.txt, the 'features' directory along with its .csv files are not populated anymore on macOS.

**To Reproduce**
1. Run make
2. The run would fail at lines 85-99 in fFeaturePanel.h

**Expected behavior**
The 'features' directory should be created in 'data'

**Screenshots**

**CaPTk Version**
1.6.1.Alpha

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.14

**Additional context**

**Comment by sarthakpati** [comment]
Weird. Anyway, thank you for catching this.

**Comment by PhucNgo1711** [comment]
This is now fixed!
