### ISSUE TITLE
Feature extraction (1.6.1) skips some patients in batch mode

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#246]
When i ran CaPTk 1.6.1 feature extraction on a batch of subjects. it skipped some patients (lines) and did not calculate features for those. there was no log file to show the reason; neither in output directory that i mentioned nor in the log folder created in CaPTk under root. 
when i ran CaPTk next time on the same set of patients, it ran successfully. 

**To Reproduce**
Please run feature extraction for the following patient. 
/cbica/projects/brain_tumor/Brain_Tumor_2015/Protocols/Glistr_multiPoints_wTempFiles/ABGJ/ABGJ_2014.12.02/initialization_images/ABGJ_2014.12.02_t1_pp.nii.gz
/cbica/projects/brain_tumor/Brain_Tumor_2015/Protocols/Glistr_multiPoints_wTempFiles/ABGJ/ABGJ_2014.12.02/initialization_images/ABGJ_2014.12.02_t1ce_pp.nii.gz
/cbica/projects/brain_tumor/Brain_Tumor_2015/Protocols/Glistr_multiPoints_wTempFiles/ABGJ/ABGJ_2014.12.02/initialization_images/ABGJ_2014.12.02_t2_pp.nii.gz
/cbica/projects/brain_tumor/Brain_Tumor_2015/Protocols/Glistr_multiPoints_wTempFiles/ABGJ/ABGJ_2014.12.02/initialization_images/ABGJ_2014.12.02_flair_pp.nii.gz

/cbica/projects/brain_tumor/Brain_Tumor_2015/Protocols/Glistr_multiPoints_wTempFiles/ABGJ/ABGJ_2014.12.02/glistrOut/scan_label_map.nii.gz
Labels=175|100|200

**Expected behavior**
i expect CaPTk to generate features for all the patients. if not, at-least i should be notified about the errors. 

**CaPTk Version**
1.6.1

**Desktop (please complete the following information):**
 Windows 7 professional

**Comment by sarthakpati** [comment]
In cases a subject does not work, an error gets generated, now.
