### ISSUE TITLE
CaPTk feature extraction (1.6.1) NGTDM error on some patients. 

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#247]
**Describe the bug**
CaPTk feature extraction (1.6.1) crashes in NGTDM feature extraction for some patients. when i ran the algorithm 3 times for one particular patient, it failed for the first two times, and ran successfully for the third time. 

**To Reproduce**
Please run feature extraction for the following patient. 
/cbica/projects/brain_tumor/Brain_Tumor_2018/Protocols/5_SSFinal/ACMQ/ACMQ_2018.04.01/ACMQ_2018.04.01_t1_LPS_r_SSFinal.nii.gz
/cbica/projects/brain_tumor/Brain_Tumor_2018/Protocols/5_SSFinal/ACMQ/ACMQ_2018.04.01/ACMQ_2018.04.01_t1ce_LPS_r_SSFinal.nii.gz
/cbica/projects/brain_tumor/Brain_Tumor_2018/Protocols/5_SSFinal/ACMQ/ACMQ_2018.04.01/ACMQ_2018.04.01_t2_LPS_r_SSFinal.nii.gz
/cbica/projects/brain_tumor/Brain_Tumor_2018/Protocols/5_SSFinal/ACMQ/ACMQ_2018.04.01/ACMQ_2018.04.01_flair_LPS_r_SSFinal.nii.gz

ROI = /cbica/projects/brain_tumor/Brain_Tumor_2018/Protocols/6_DeepMedic/ACMQ/ACMQ_2018.04.01/segm.nii.gz

Labels = 1|2|3

**Expected behavior**
CapTk should generate features for the patients in all the attempts. 

**CaPTk Version**
1.6.1

**Desktop (please complete the following information):**
 - Windows professional 7

**Comment by sarthakpati** [comment]
Not able to replicate this. Closing; please re-open if this recurs.
