### ISSUE TITLE
feature extraction should keep record of all the ROI numbers mentioned in batch mode

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#248]
**Is your feature request related to a problem? Please describe.**
When i calculated features on a batch of subjects with different number of ROIs like ROI=1|2|3 for first patient and ROI=2|3 for second patient, it copied the features of labels 2 of second patient under label 1 of first patient, and the features of label 3 of second patient under the label 2 of first patient.

**Comment by sarthakpati** [comment]
Is this still an issue after the latest build; especially after putting specific output file locations per subject (which can be specified in the batch file)?

**Comment by sarthakpati** [comment]
Using different output files will fix this.
