### ISSUE TITLE
Project missing top-level ChangeLog, 6_Download.txt contains unexpected content.

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#250]
**Describe the bug**
CaPTk is missing a top-level "ChangeLog" file for the new release.

The file "6_Download.txt" does have this data. A user would never know that, except that the latest commit to 6_Download.txt happens to have the comment that the "changelog" was updated.

The expectation is that "Download.txt" would contain documentation about the download procedure. While that file does contain download instructions, it also contains content that would be easier to find if it was stored in files named things like "Licensing.txt" and "Citations.txt".

**To Reproduce**

1. Go to https://github.com/CBICA/CaPTk/
2. Look for "ChangeLog.txt" :(
3. Read "6_Download.txt"

**Comment by PhucNgo1711** [comment]
This should be fixed by now right? @sarthakpati

**Comment by sarthakpati** [comment]
Still not fixed, unfortunately.

**Comment by sarthakpati** [comment]
This is done.
