### ISSUE TITLE
ChangeLog data missing reference to Github issues

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#251]
**Describe the bug**
The Changelog data should include specific references to all Github issue numbers (bug reports) fixed in the release.

**Comment by PhucNgo1711** [comment]
@sarthakpati

**Comment by sarthakpati** [comment]
This will be a **lot** of information for users (which they can anyway access by looking at the commit history) and is generally not done by projects. We should rather have a more "top level" Changelog (#250). Working on it.
