### ISSUE TITLE
Linux installer (license list, input parsing)

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#252]
**Describe the bug**

1. The Linux CLI installer includes a requirement to accept the license for "WIN32 WGet"

2. The installer doesn't accept likely inputs in response to the license terms. Example:

```
10. Eigen - MPL2 License and can be found at https://www.mozilla.org/en-US/MPL/2.0/
I accept the terms of the licenses above.
1) Yes
2) No
#? ?
#? ?
#? Yes
#? No
#? 
#? y
#? n 
#? help
```

3. The prompt (#?) for the license acceptance is confusing -- it visually implies that "?" is a response.

Suggestions:

1. Change the formatting slightly (blank line after the list of licenses, (Yes/No) choices at the end of the question).

```
10. Eigen - MPL2 License and can be found at https://www.mozilla.org/en-US/MPL/2.0/

I accept the terms of the licenses above (Yes/No):
# 
```
2. Enable any of [Y|Yes|y|yes] to be confirmation, and any of [N|No|n|no|RETURN] to decline.

**Comment by MarkBergman-cbica** [comment]
Item #1 has been resolved.

**Comment by sarthakpati** [comment]
This has been resolved with @PhucNgo1711's latest PR.
