### ISSUE TITLE
Linux CLI: Supplied directory not found

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#253]
**Describe the bug**

Running CaPTk produces the error message:
`
Supplied directory name wasn't found: /_$HOME_/.CaPTk/1.6.1/tmp__$RANDOMNUMBER_`

**To Reproduce**

./captk

**Expected behavior**

No error.

**CaPTk Version**
1.6.1

**Desktop (please complete the following information):**

Linux, Fedora 28

**Comment by sarthakpati** [comment]
Probably related to how the executable is named in Linux. I wonder if the sym-link **captk** is creating a temp folder `$home/.captk/...`

**Comment by surrsurus** [comment]
Not sure what causes this issue to occur, cannot seem to reproduce currently. I know that on Linux a .CaPTk is created in the user's `$HOME`, and that it should create those `tmp` folders automatically. I ran into similar issues pre 1.6.0 but have not encountered them recently, and my guess would be to try to delete those folders and try to run the application again, though I'm not entirely sure what prompts CaPTk to read from or create those directories.

**Comment by sarthakpati** [comment]
Fixed by the builds from Azure.
