### ISSUE TITLE
Linux installer -- improve instructions re. execution

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#254]
**Is your feature request related to a problem? Please describe.**

After running the Linux installer, the instructions are:

`Run the binary by navigating to the ~/CaPTk/1.6.1/ directory and running './captk' in the console`

**Describe the solution you'd like**

An easier instruction might be something like:

`To run CaPTk, enter the command "~/CaPTk/1.6.1/captk"`

**Comment by surrsurus** [comment]
I've implemented this in my fork, will make a PR soon.

**Comment by surrsurus** [comment]
Fixed in #263
