### ISSUE TITLE
Linux installer -- excutable naming

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#256]
**Describe the bug**

The Linux installation of CaPTk 1.6.1 creates the executable as:

`CaPTk_.bin`

In keeping with common methods for naming versioned packages, the executable should be named:

`CaPTk-1.6.1`

(the symlink to "captk" should remain).

**Comment by sarthakpati** [comment]
CMake generates the final executable as **CaPTk** without any versioning information. This probably needs to be handled by AppImage.

**Comment by surrsurus** [comment]
Strange, on my computer the installer is generated as `CaPTk_1.6.1_Installer`, and the AppImage as `CaPTk_1.6.1.bin`.

**Comment by surrsurus** [comment]
Fixed, now packager does this step consistently (Reads directly from CMakeLists)
