### ISSUE TITLE
Linux - graphical environment required for CLI

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#258]
**Describe the bug**

Running CaPTk requires a graphical environment, even if the operation is command-line.

**To Reproduce**

In a text-based environment (console, or ssh without "-X/-Y" to a machine with CaPtk), run CaPTk:

```
[bergman ~]$ captk help
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
[bergman ~]$ 

```

**Comment by sarthakpati** [comment]
Might have something to do with the way the final executable gets linked. Could you post the result of the following command:

```
captk -h
```

**Comment by surrsurus** [comment]
This is not a linking or packaging issue, Qt cannot find the `DISPLAY` since it does not exist without X forwarding in this circumstance (https://stackoverflow.com/questions/48681196/problems-with-running-qt-on-centos-7 not a C++ instance but seems to be a very similar issue). I think maybe something is trying to access the GUI around where the parser is working on the commandline arguments.

**Comment by MarkBergman-cbica** [comment]
Possible solutions:

1. Updating the main "captk" executable, so that there aren't any Qt (graphical) dependencies for running command-line applications. 

2. Writing a wrapper to the gateway "captk" executable so that command-line invocations do not call the current main executable (which requires a graphical environment).

3. Building CaPTk, including the command-line apps, from source. **Need to confirm that all the CLI applications are linked without Qt.**

**Comment by sungminhacbica** [comment]
I am still having failures to run captk 1.6.2Alpha as an sge job.

1. Downloaded 1.6.2Alpha Linux Install: [Linux 1.6.2Alpha Link](https://www.nitrc.org/frs/downloadlink.php/11160)
1. I did install on __`cbica-cluster`__ in my home directory with command `sh /DownloadDirectory/CaPTk_1.6.2.Alpha_Installer.bin`
1. Created a script with `module load xvfb` before calling `~/path/to/1.6.2Alpha/captk`: `/cbica/comp_space/hasun/190228_histogramMatching_Saima/test.sh`
1. Submitted to qsub with `qsub -p 0 -l short -o ~/comp_space/190228_histogramMatching_Saima/\$JOB_NAME_\$JOB_ID_with-1.6.2Alpha-local-install.log  ~/comp_space/190228_histogramMatching_Saima/test.sh`
1. Checked the log file: `cat ~/logFileDirectory/xvfb_captk_1.6.1_test_7355755_with-1.6.2Alpha-local-install.log`

The xclock which I ran prior to calling captk worked, indicating the the xclock could find the dummy graphical forwarding. However, calling captk.bin failed with the following error:

`Error: Can't open display: localhost:1.0
/scratch/hasun/.mount_CaPTk-0ALb6u/usr/bin/CaPTk: /cbica/software/external/gcc/centos7/4.9.2/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /scratch/hasun/.mount_CaPTk-0ALb6u/usr/bin/CaPTk)
/scratch/hasun/.mount_CaPTk-0ALb6u/usr/bin/CaPTk: /usr/lib64/libgpg-error.so.0: no version information available (required by /scratch/hasun/.mount_CaPTk-0ALb6u/usr/lib/libgcrypt.so.20)`

**Comment by sarthakpati** [comment]
This has been fixed.
