### ISSUE TITLE
PseudoProgressionEstimator Fails on Linux 1.6.1

### ISSUE THREAD

**Issue by sungminhacbica** [CBICA/CaPTk#259]
**Describe the bug**

Using the provided pretrained model and sample data for version 1.6.1, The PseudoProgressionEstimator model runs, freezing the the GUI, then outputs errors messages in the CLI and produces 0 byte, empty file named results.csv

**To Reproduce**
1. Call captk executable from CLI with ~/path/to/captk
2. Go to 'Applications -> Pseudo-Progression Estimator'
3. Download Pretrained Model found in the sentence in the "You can find a pretrained model, based on study at PENN, here" to ~/CaPTk/PretrainedModels, then unzip with "7z x *.zip"
4. Download sample data found in 'Help -> Sample Data -> PseudoProgressionEstimator' to ~/CaPTk/SampleData/ then unzip with "7z x *.zip"
5. Populate the model,data, and output directory fields
6. Press confirm.
7. Record the output found in the terminal where ~/path/to/captk was called.

**Expected behavior**
Expected a results.csv at output directory with information.

**Screenshots**
See bottom for the interface.

**CaPTk Version**
1.6.1

**Desktop (please complete the following information):**
 - OS: check the lsb_release -a output below
 - Version (including Build information, if any): check the lsb_release -a output below

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Additional context**
I have run this under the guidance of Hamed.

Here is the full log found on the CLI from calling the captk executable to the generation of empty results.csv.

An OpenGL Core Profile was requested, but it is not supported on the current platform. Falling back to a non-Core profile. Note that this might cause rendering issues.
[0212/174534.283592:WARNING:stack_trace_posix.cc(699)] Failed to open file: /tmp/.gliXKuPn (deleted)
  Error: No such file or directory
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
js: WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.
AAMA
AAMG
AAMJ
AAMP
AAMQ
Loading Perfusion Image: 0
Loading Perfusion Image: 1
Loading Perfusion Image: 2
Loading Perfusion Image: 3
Loading Perfusion Image: 4
Revising Perfusion Image: 0
Revising Perfusion Image: 1
Revising Perfusion Image: 2
Revising Perfusion Image: 3
Revising Perfusion Image: 4
Loading Remianing Features: 0
Shape and neuro features calculated.
Counter Size40
Counter Size75
Counter Size110
Counter Size145
Counter Size180
Counter Size215
Counter Size250
Counter Size285
Counter Size320
Counter Size355
Counter Size390
Counter Size425
Counter Size460
Counter Size495
Counter Size530
Counter Size565
Counter Size600
Counter Size635
Counter Size670
Counter Size705
Counter Size740
Counter Size775
Counter Size810
Basic features copied in the OtherFeatures map.
Loading Remianing Features: 1
Shape and neuro features calculated.
Counter Size40
Counter Size75
Counter Size110
Counter Size145
Counter Size180
Counter Size215
Counter Size250
Counter Size285
Counter Size320
Counter Size355
Counter Size390
Counter Size425
Counter Size460
Counter Size495
Counter Size530
Counter Size565
Counter Size600
Counter Size635
Counter Size670
Counter Size705
Counter Size740
Counter Size775
Counter Size810
Basic features copied in the OtherFeatures map.
Loading Remianing Features: 2
Shape and neuro features calculated.
Counter Size40
Counter Size75
Counter Size110
Counter Size145
Counter Size180
Counter Size215
Counter Size250
Counter Size285
Counter Size320
Counter Size355
Counter Size390
Counter Size425
Counter Size460
Counter Size495
Counter Size530
Counter Size565
Counter Size600
Counter Size635
Counter Size670
Counter Size705
Counter Size740
Counter Size775
Counter Size810
Basic features copied in the OtherFeatures map.
Loading Remianing Features: 3
Shape and neuro features calculated.
Counter Size40
Counter Size75
Counter Size110
Counter Size145
Counter Size180
Counter Size215
Counter Size250
Counter Size285
Counter Size320
Counter Size355
Counter Size390
Counter Size425
Counter Size460
Counter Size495
Counter Size530
Counter Size565
Counter Size600
Counter Size635
Counter Size670
Counter Size705
Counter Size740
Counter Size775
Counter Size810
Basic features copied in the OtherFeatures map.
Loading Remianing Features: 4
Shape and neuro features calculated.
Counter Size40
Counter Size75
Counter Size110
Counter Size145
Counter Size180
Counter Size215
Counter Size250
Counter Size285
Counter Size320
Counter Size355
Counter Size390
Counter Size425
Counter Size460
Counter Size495
Counter Size530
Counter Size565
Counter Size600
Counter Size635
Counter Size670
Counter Size705
Counter Size740
Counter Size775
Counter Size810
Basic features copied in the OtherFeatures map.
PCA features of all the modalities copied in the OtherFeatures map.
patient number0
One patient size130
One patient size230
patient number1
One patient size130
One patient size230
patient number2
One patient size130
One patient size230
patient number3
One patient size130
One patient size230
patient number4
One patient size130
One patient size230
FeaturesOfAllSubjects populated.
parameters read.
scaling done.
double free or corruption (!prev)
Received signal 6
#0 0x7fa66632752f <unknown>
#1 0x7fa664d58b1d <unknown>
#2 0x7fa666327a3e <unknown>
#3 0x7fa66c725890 <unknown>
#4 0x7fa66b572e97 gsignal
#5 0x7fa66b574801 abort
#6 0x7fa66b5bd897 <unknown>
#7 0x7fa66b5c490a <unknown>
#8 0x7fa66b5cbe84 cfree
#9 0x0000007c88f9 <unknown>
#10 0x000000e5fdc6 <unknown>
#11 0x00000113b9f5 <unknown>
#12 0x0000008f22da <unknown>
#13 0x000000e667c0 <unknown>
#14 0x7fa66d792189 QMetaObject::activate()
#15 0x000000f800eb <unknown>
#16 0x000000f77e81 <unknown>
#17 0x000000f80565 <unknown>
#18 0x7fa66d792189 QMetaObject::activate()
#19 0x7fa66e69b3a2 QAbstractButton::clicked()
#20 0x7fa66e69b5a4 QAbstractButtonPrivate::emitClicked()
#21 0x7fa66e69d13e QAbstractButtonPrivate::click()
#22 0x7fa66e69d295 QAbstractButton::mouseReleaseEvent()
#23 0x7fa66e5f3688 QWidget::event()
#24 0x7fa66e5b6e2c QApplicationPrivate::notify_helper()
#25 0x7fa66e5bea13 QApplication::notify()
#26 0x7fa66d7672d8 QCoreApplication::notifyInternal2()
#27 0x7fa66e5bd50f QApplicationPrivate::sendMouseEvent()
#28 0x7fa66e60d1dd QWidgetWindow::handleMouseEvent()
#29 0x7fa66e60fae3 QWidgetWindow::event()
#30 0x7fa66e5b6e2c QApplicationPrivate::notify_helper()
#31 0x7fa66e5bdf60 QApplication::notify()
#32 0x7fa66d7672d8 QCoreApplication::notifyInternal2()
#33 0x7fa66dd93f6f QGuiApplicationPrivate::processMouseEvent()
#34 0x7fa66dd95e65 QGuiApplicationPrivate::processWindowSystemEvent()
#35 0x7fa66dd71bdb QWindowSystemInterface::sendWindowSystemEvents()
#36 0x7fa659e9c0db QPAEventDispatcherGlib::processEvents()
#37 0x7fa66d765c3a QEventLoop::exec()
#38 0x7fa66e793b37 QDialog::exec()
#39 0x0000009141a0 <unknown>
#40 0x000000e68017 <unknown>
#41 0x7fa66d792189 QMetaObject::activate()
#42 0x7fa66e5b0e42 QAction::triggered()
#43 0x7fa66e5b3270 QAction::activate()
#44 0x7fa66e71aa7a QMenuPrivate::activateCausedStack()
#45 0x7fa66e721bb6 QMenuPrivate::activateAction()
#46 0x7fa66e722ad0 QMenu::mouseReleaseEvent()
#47 0x7fa66e5f3688 QWidget::event()
#48 0x7fa66e724feb QMenu::event()
#49 0x7fa66e5b6e2c QApplicationPrivate::notify_helper()
#50 0x7fa66e5bea13 QApplication::notify()
#51 0x7fa66d7672d8 QCoreApplication::notifyInternal2()
#52 0x7fa66e5bd50f QApplicationPrivate::sendMouseEvent()
#53 0x7fa66e60d5e0 QWidgetWindow::handleMouseEvent()
#54 0x7fa66e60fae3 QWidgetWindow::event()
#55 0x7fa66e5b6e2c QApplicationPrivate::notify_helper()
#56 0x7fa66e5bdf60 QApplication::notify()
#57 0x7fa66d7672d8 QCoreApplication::notifyInternal2()
#58 0x7fa66dd93f6f QGuiApplicationPrivate::processMouseEvent()
#59 0x7fa66dd95e65 QGuiApplicationPrivate::processWindowSystemEvent()
#60 0x7fa66dd71bdb QWindowSystemInterface::sendWindowSystemEvents()
#61 0x7fa659e9c0db QPAEventDispatcherGlib::processEvents()
  r8: 0000000000000000  r9: 00007fffa30bfd70 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007fffa30bffe0 r13: 0000000000001000 r14: 0000000000000000 r15: 0000000000000030
  di: 0000000000000002  si: 00007fffa30bfd70  bp: 00007fffa30c00e0  bx: 00007fffa30bffe0
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007fa66b572e97  sp: 00007fffa30bfd70
  ip: 00007fa66b572e97 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

Screenshot of the interface with the paths.
![screenshot from 2019-02-12 18-07-51](https://user-images.githubusercontent.com/45636290/52674314-3accb100-2ef1-11e9-8f8d-574034425700.png)

**Comment by sarthakpati** [comment]
@saimarathore this was related to the memory requirement, right?

**Comment by sarthakpati** [comment]
This was a memory requirement issues. Fixed in documentation.
