### ISSUE TITLE
build failing on cluster

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#261]
**Describe the bug**
Captk build failing on cluster from my fork. It works on Windows.

**To Reproduce**
1. Fresh clone from my fork
2. Run CMake
3. Run make -> error

Please see the screenshot.
![image](https://user-images.githubusercontent.com/43445206/52730588-c003a480-2f89-11e9-9282-5cd8c67cce8b.png)

**Comment by ashishsingh18** [comment]
@surrsurus @MarkBergman-cbica

**Comment by MarkBergman-cbica** [comment]
Maybe see: https://github.com/rubengooj/pl-slam/issues/3

Any pointer to what YAML files within the CaPTk source are involved?

**Comment by surrsurus** [comment]
None of my Travis CI builds seem to pick up this error, and it appears as if the master Travis CI also doesn't have this issue. I will try to reproduce it on my own. A potential fix is to delete the *.cwl files and then try another `make`. This should rebuild all of the cwl from scratch.

**Comment by surrsurus** [comment]
For clarity, the use of YAML at compilation time mostly comes down to writing the cwl files. This means that the YAML syntax is valid (as we use the YAML library to build an object and then write that to the file), which means in this case the `BadFile` refers to not being able to write said YAML to it's given destination. cwl files are created for all applications that use the cbica command parser automatically, all that needs to be done is to create an instance of the parser with the name of the application passed in as a string.

**Comment by sarthakpati** [comment]
Fixed.
