### ISSUE TITLE
Whitestripe and HistogramMatching crashing in CaPTk_1.6.1.Alpha

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#262]
**Describe the bug**
Whitestripe and HistogramMatching is crashing on Windows, Linux, and MacOS. I'm not sure how long this has been out there, but it seems like the previous release did not have this bug. 

**To Reproduce**
To be described later once I have gathered information on how to reproduce the bug from the user.

**Expected behavior**
Whitestripe and HistogramMatching should work. Or if they fail, they should not crash the whole CaPTk application.

**Screenshots**
To be provided

**CaPTk Version**
1.6.1 Alpha

**Desktop (please complete the following information):**
 - OS: Windows, Linux, macOS
 - Version (including Build information, if any): Windows 7, macOS 10.14

**Comment by sarthakpati** [comment]
Histogram Matching fixed.

**Comment by PhucNgo1711** [comment]
Awesome! Thanks

**Comment by sarthakpati** [comment]
I added a fix to WS but I still don't know how it was causing the application to crash (it was assuming the output parameter was always a directory). Anyway, closing this out, for now.

**Comment by PhucNgo1711** [comment]
is this still in your fork or it's part of your pull request going into master now?
