### ISSUE TITLE
multi-Image registration - doesn't increment assignment of autocreated matrix names

### ISSUE THREAD

**Issue by pefs44** [CBICA/CaPTk#265]
**Describe the bug**
On adding the first floating image to registration, the output and matrix names are auto-created. 
Adding subsequent floating images - the output name gets added but not the matrix name

**To Reproduce**
1. start  'Preprocessing' -> 'Registration'
2. Set 'Fixed Image'
3. Set Moving Image 1
4. Click on Input '+'
5. Set Moving Image 2
- Transformation Matrix 2 remains empty, but expected name overwrites that of Tranformation Matrix 1

**Expected behavior**
same name as generated for output  N should be generated for transformation matrix N for N >= 1 , and not successively assigned to Transformation Matrix 1.

**Screenshots**
Screenshots showing fourth transformation name replacing 1st.. 
![multireg_masknames](https://user-images.githubusercontent.com/19158519/52920514-672b6780-330d-11e9-80e1-c3a4e13c4a0c.jpg)

**CaPTk Version**
1.6.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version (including Build information, if any): Pro 1803

**Additional context**

**Comment by sarthakpati** [comment]
Fixed by commit https://github.com/sarthakpati/CaPTk/commit/80ebcea4370f7d6bd795345447ea623c785fbb9e
