### ISSUE TITLE
DicomLoad+SaveNifti not equal DICOMtoNIFTI

### ISSUE THREAD

**Issue by pefs44** [CBICA/CaPTk#266]
**Describe the bug**
FIle->Load -> Image(s) followed by File->Save -> Image(NIFTI) produces a (mirrored?) version of what is produced by Preprocessing->DICOM to NIFTI

**To Reproduce**
1. FIle->Load -> Image(s)  - choose a DICOM image
2. File->Save -> Image(NIFTI)  
3. Close image loaded above
4. Preprocessing >DICOM to NIFTI  - choose the same DICOM image as above, and set a  different nifti name
5. FIle->Load -> Image(s)  - choose the first of the above created nifti images
6.  FIle->Load -> Image(s)  - choose the second of the above created nifti images
7. See error: Spacing not matching. Please register the images. 
8. Note some image values
9. Close the loaded image 
10.  FIle->Load -> Image(s)  - choose the second of the above created nifti images
11. Note some image values- they are different from those in 8. above.

**Expected behavior**
Would expect the saved images to have the same properties as the converted images unless the images being saved are somehow transformed.

**Screenshots**
comparing the images loaded at steps 6 and 10 above: the orientation and value information is different.
![dcm2niinedicomsavenifti](https://user-images.githubusercontent.com/19158519/52920993-c5a71480-3312-11e9-99d9-72f95b4a6dd9.jpg)

**CaPTk Version**
1.6.1

**Desktop (please complete the following information):**
 - OS: Windows
 - Version (including Build information, if any): 10.1803]

**Additional context**

**Comment by sarthakpati** [comment]
Fixed in my fork: https://github.com/sarthakpati/CaPTk/commit/8f9e200a1718ca15c35b6acc4294922f88afae7d
