### ISSUE TITLE
Can't set output path or filename for DICOM to NIFTI conversion from gui

### ISSUE THREAD

**Issue by pefs44** [CBICA/CaPTk#267]
**Describe the bug**
The names of the output directory and file name set in the pop-up for DICOM to NIFTI are ignored.

**To Reproduce**
1. Preprocessing -> DICOM to NIFTI
2. Browse and choose an input DICOM file
3. Browse and choose a different directory, and set a name for the output nifti image
4. a popup emerges saying image saved in chosen output folder
5. I find no image in the output directory that was chosen, and a file named according to the scan date, sequence and serie numbers (or similar) in the original DICOM directory. 

**Expected behavior**
the nifti file should end up in the user specified output folder with the specified output name.

**Screenshots**

**CaPTk Version**
1.6.1

**Desktop (please complete the following information):**
 - OS: Windows
 - Version (including Build information, if any): 10.1803]

**Comment by ashishsingh18** [comment]
We are able to reproduce this issue.

**Comment by ashishsingh18** [comment]
Also, there is no way we can select .ima(dicom) files.

**Comment by ashishsingh18** [comment]
This is now fixed in my fork, waiting to get merged into master.

**Comment by sarthakpati** [comment]
Fixed; closing.
