### ISSUE TITLE
CLI examples for preprocesing procedures

### ISSUE THREAD

**Issue by pefs44** [CBICA/CaPTk#268]
**Is your feature request related to a problem? Please describe.**
Yes
When I try to convert 4D DICOM to NIFTI I get a popup  error message to try using the command-line version of the routine - but what is the command to use on the command-line?
equally, I would like to script all the preparative steps, but most of the command-line versions of the preprocessing are not documented.

**Describe the solution you'd like**
The CLI commands documented (at least indicated) in the manual.
If possible an indication or log showing what the CLI version of a command run from the gui visible someplace so that once I find what I want to do via the gui I can replicate it via the CLI.

**Comment by sarthakpati** [comment]
The **Preprocessing** executable now holds this.
