### ISSUE TITLE
-rt flags are unpopulated

### ISSUE THREAD

**Issue by surrsurus** [CBICA/CaPTk#269]
**Describe the bug**
All commandline applications have been given a `-rt` target through the cbica parser, however none of them actually do anything and are not populated with tests.

**To Reproduce**
1. Go to the same directory as any commandline application
2. Run the application with flag `-rt`
3. -rt is unpopulated

**Expected behavior**
All applications should have a commandline target `-rt` that runs tests for that application.

**CaPTk Version**
1.6.1

**Additional context**
By default, test data is stored in /bin (or folder used to build captk in)/testing/TestData

**Comment by sarthakpati** [comment]
We will remove this in favor of fully populated unit tests.
