### ISSUE TITLE
captk help (from CLI) insufficient

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#273]
**Describe the bug**
Running
`captk help`
should display more help, at a minimum the names of the child applications.

Running `captk help _application_`

should display help for the named _application_

**Expected behavior**

```
captk help
Executable Name: CaPTk v1.6.1

Usage:
captk                          begin GUI session
captk help
captk help _application_     display details of _application_
captk feature                       Feature Extraction
captk _app2_                      Application2
captk _app3_                      Application3
```

**CaPTk Version**

Linux, 1.6.1

**Comment by sarthakpati** [comment]
Running the following works:

```bash
captk $Application --help
```

Closing this ticket, unless a different mechanism can be proposed.
