### ISSUE TITLE
1.6.1 Linux WhiteStripe CLI Fails to run on Ubuntu 18.04

### ISSUE THREAD

**Issue by sungminhacbica** [CBICA/CaPTk#277]
## Expected Behavior
Give me a help documentation about whitestripe on command line

## Actual Behavior

Error Message:
/tmp/.mount_captkeuRlZU/usr/bin/WhiteStripe: relocation error: /tmp/.mount_captkeuRlZU/usr/bin/WhiteStripe: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev version Qt_5 not defined in file libQt5Positioning.so.5 with link time reference

## Steps to Reproduce the Problem

  1. Install CaPTk/1.6.1 on Ubuntu 18.04 64bit
  2. Run `~/CaPTk/1.6.1/captk whitestripe`

## Specifications

  - Version: 1.6.1
  - Platform: Linux Install
  - Subsystem:

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Comment by sungminhacbica** [comment]
I also tried to run on GUI, it is crashing immediately after generating an output and quitting the GUI executable.

`An OpenGL Core Profile was requested, but it is not supported on the current platform. Falling back to a non-Core profile. Note that this might cause rendering issues.
[0222/164750.003126:WARNING:stack_trace_posix.cc(699)] Failed to open file: /tmp/.glfETp5S (deleted)
  Error: No such file or directory
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
js: WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.
Received signal 11 SEGV_MAPERR 000000000000
#0 0x7fd47581552f <unknown>
#1 0x7fd474246b1d <unknown>
#2 0x7fd475815a3e <unknown>
#3 0x7fd47bc13890 <unknown>
#4 0x00000068405b <unknown>
#5 0x00000092cac0 <unknown>
#6 0x000000e66f98 <unknown>
#7 0x7fd47cc80189 QMetaObject::activate()
#8 0x000000fc06d5 <unknown>
#9 0x000000fbd3de <unknown>
#10 0x000000fc0855 <unknown>
#11 0x7fd47cc80189 QMetaObject::activate()
#12 0x7fd47db893a2 QAbstractButton::clicked()
#13 0x7fd47db895a4 QAbstractButtonPrivate::emitClicked()
#14 0x7fd47db8b13e QAbstractButtonPrivate::click()
#15 0x7fd47db8b295 QAbstractButton::mouseReleaseEvent()
#16 0x7fd47dae1688 QWidget::event()
#17 0x7fd47daa4e2c QApplicationPrivate::notify_helper()
#18 0x7fd47daaca13 QApplication::notify()
#19 0x7fd47cc552d8 QCoreApplication::notifyInternal2()
#20 0x7fd47daab50f QApplicationPrivate::sendMouseEvent()
#21 0x7fd47dafb1dd QWidgetWindow::handleMouseEvent()
#22 0x7fd47dafdae3 QWidgetWindow::event()
#23 0x7fd47daa4e2c QApplicationPrivate::notify_helper()
#24 0x7fd47daabf60 QApplication::notify()
#25 0x7fd47cc552d8 QCoreApplication::notifyInternal2()
#26 0x7fd47d281f6f QGuiApplicationPrivate::processMouseEvent()
#27 0x7fd47d283e65 QGuiApplicationPrivate::processWindowSystemEvent()
#28 0x7fd47d25fbdb QWindowSystemInterface::sendWindowSystemEvents()
#29 0x7fd46938a0db QPAEventDispatcherGlib::processEvents()
#30 0x7fd47cc53c3a QEventLoop::exec()
#31 0x7fd47dc81b37 QDialog::exec()
#32 0x0000009144d2 <unknown>
#33 0x000000e68067 <unknown>
#34 0x7fd47cc80189 QMetaObject::activate()
#35 0x7fd47da9ee42 QAction::triggered()
#36 0x7fd47daa1270 QAction::activate()
#37 0x7fd47dc08a7a QMenuPrivate::activateCausedStack()
#38 0x7fd47dc0fbb6 QMenuPrivate::activateAction()
#39 0x7fd47dc10ad0 QMenu::mouseReleaseEvent()
#40 0x7fd47dae1688 QWidget::event()
#41 0x7fd47dc12feb QMenu::event()
#42 0x7fd47daa4e2c QApplicationPrivate::notify_helper()
#43 0x7fd47daaca13 QApplication::notify()
#44 0x7fd47cc552d8 QCoreApplication::notifyInternal2()
#45 0x7fd47daab50f QApplicationPrivate::sendMouseEvent()
#46 0x7fd47dafb5e0 QWidgetWindow::handleMouseEvent()
#47 0x7fd47dafdae3 QWidgetWindow::event()
#48 0x7fd47daa4e2c QApplicationPrivate::notify_helper()
#49 0x7fd47daabf60 QApplication::notify()
#50 0x7fd47cc552d8 QCoreApplication::notifyInternal2()
#51 0x7fd47d281f6f QGuiApplicationPrivate::processMouseEvent()
#52 0x7fd47d283e65 QGuiApplicationPrivate::processWindowSystemEvent()
#53 0x7fd47d25fbdb QWindowSystemInterface::sendWindowSystemEvents()
#54 0x7fd46938a0db QPAEventDispatcherGlib::processEvents()
#55 0x7fd47cc53c3a QEventLoop::exec()
#56 0x7fd47cc5c640 QCoreApplication::exec()
#57 0x00000043ee21 <unknown>
#58 0x7fd47aa43b97 __libc_start_main
#59 0x000000472b89 <unknown>
  r8: 0000000000000000  r9: 0000000000000001 r10: 000000000567f010 r11: 0000000000000000
 r12: 00007ffe5677de80 r13: 00000000019dcb50 r14: 000000000f729130 r15: 000000000f729140
  di: 000000000f71d480  si: 0000000000000000  bp: 000000000f723810  bx: 000000000f7290f0
  dx: 0000000000683e10  ax: 0000000000000000  cx: 0000000000000000  sp: 00007ffe5677de30
  ip: 000000000068405b efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.`

**Comment by sungminhacbica** [comment]
I ran with 1.6.0 and it runs without shutting down and it generates results too.

**Comment by sungminhacbica** [comment]
I tried to install CaPTk 1.5.1 on my same Linux machine.

Trying to call GUI I got the following error:
~/Applications/CaPTk/captk

/home/hasm/Applications/CaPTk/captk: error while loading shared libraries: libQtCore.so.4: cannot open shared object file: No such file or directory

Trying to call the CL for White Stripe:

~/Applications/CaPTk/bin/WhiteStripe 
/home/hasm/Applications/CaPTk/bin/WhiteStripe: error while loading shared libraries: libQtCore.so.4: cannot open shared object file: No such file or directory

**Comment by sarthakpati** [comment]
I think this has been fixed in the latest build. I will keep the issue open for now until testing finishes.

**Comment by PhucNgo1711** [comment]
Looks like this still exists on Linux as well

**Comment by sarthakpati** [comment]
I wonder if the fixes done by me, @PhucNgo1711 and @ashishsingh18 today for #298 fixes these?

**Comment by PhucNgo1711** [comment]
Hopefully

**Comment by surrsurus** [comment]
Got a fix in my fork for this, should be in master soon.
