### ISSUE TITLE
DICOM File names are not shown

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#281]
**Describe the bug**
When CaPTk loads up a DICOM image, the file (or folder or series) name of that image does not come up.

**To Reproduce**
Load any DICOM image

**Expected behavior**
One of the following should come in the image panel:
1. Filename of the first file
2. Base Folder name
3. Series name
4. Something more descriptive, perhaps?

**Screenshots**
![image](https://user-images.githubusercontent.com/11719673/53424694-a9117900-39b1-11e9-91b8-776e1a75d506.png)

**CaPTk Version**
1.6.2.PreAlpha

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 7

**Additional context**
The images panel gets updated in the function `LoadSlicerImages`. Updating the function `cbica::ReadImage` should fix this issue.

**Comment by sarthakpati** [comment]
Related to #66

**Comment by ashishsingh18** [comment]
We are now displaying base folder name. Needs further discussion on the side-effects of it.

**Comment by sarthakpati** [comment]
Hopefully that alone should be fine. The applications that need the file name have been changed to take a temporary file written out into `m_tempFolderLocation` from the appropriate Slicer Manager.

**Comment by ashishsingh18** [comment]
Fixed.
