### ISSUE TITLE
Feature extraction should be tested on multiple different datasets. 

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#294]
**Describe the bug**
Feature extraction should be tested on multiple different datasets. 
Feature extraction should have handling of different number of ROIs in batch mode.

**Comment by sarthakpati** [comment]
Hopefully, the work mentioned by @sbakas will suffice for this?

**Comment by sbakas** [comment]
The "work" mentioned by me under confidential circumstances is not expected to be done before April due to other commitments. Unless it is assigned to someone else. This needs clarification in person.

**Comment by sarthakpati** [comment]
Understood.

**Comment by sarthakpati** [comment]
Done.
