### ISSUE TITLE
Qt needs to be copied to /usr/local/Cellar/qt as if it was installed using Homebrew

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#297]
**Describe the bug**
When building CaPTk, CaPTk itself will pick up Qt in `CaPTk/bin/qt`, but some applications like `WhiteStripe` looks into `usr/local`(where Qt is installed using brew) to find Qt. This happens when `CaPTk/bin/qt` already exists in `CMAKE_PREFIX_PATH`

**To Reproduce**
1. Run make to build CaPTk

**Expected behavior**
There should be no complains about Qt5 not found

**CaPTk Version**
1.6.*

**Desktop (please complete the following information):**
 - OS:  macOS
 - Version (including Build information, if any): 10.13+

**Comment by PhucNgo1711** [comment]
@sarthakpati I couldn't find $SUPERBUILD_BUILD_DIR or anything like that. Can you help me find the exact variable name?

**Comment by sarthakpati** [comment]
I am assuming you are asking about forcing the Superbuild? It is `CAPTK_SUPERBUILD_FORCE`: https://github.com/sarthakpati/CaPTk/blob/master/CMakeLists.txt#L40

**Comment by PhucNgo1711** [comment]
Oh I meant what you said earlier about pointing the extracted qt directory to /usr/local instead of superbuild build dir

**Comment by sarthakpati** [comment]
I was talking about creating a symlink.

**Comment by sarthakpati** [comment]
Abdhi is facing issues with the 1.6.2.Alpha package because of this.

**Comment by abdhigithub** [comment]
On macOS, this is how it can be replicated:

```
modv-ve502-0139:~ abdhi$ /Applications/CaPTk_1.6.2.Alpha.app/Contents/MacOS/CaPTk_1.6.2.Alpha FeatureExtraction -u
dyld: Library not loaded: /usr/local/opt/qt/lib/QtSvg.framework/Versions/5/QtSvg
  Referenced from: /Applications/CaPTk_1.6.2.Alpha.app/Contents/Resources/bin/FeatureExtraction
  Reason: image not found
```

**Comment by PhucNgo1711** [comment]
So the real issue here is how Qt5 frameworks and macdeployqt do things by default.
The pattern `/usr/local/opt/qt5` is matched by all Qt5 frameworks and macdeployqt. 

The CaPTk executable points to the correct Qt libraries (not in `/usr/local/opt`), but the libraries themselves point to `/usr/local/opt`

A detailed explanation can be found here 
https://github.com/Homebrew/homebrew-core/issues/6161#issue-184618691

**Comment by PhucNgo1711** [comment]
this is resolved
