### ISSUE TITLE
Build failing on windows

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#300]
**Describe the bug**
Build failing on Windows after updating to upstream master ( Merge pull request #282 )

**To Reproduce**
Update from Upstream-master and build.

Please see the below screenshot.
![image](https://user-images.githubusercontent.com/43445206/53522194-e2c4ab80-3aa7-11e9-9092-7fea32aafd0f.png)

**Comment by ashishsingh18** [comment]
Tried going back in time. Issue isn't there with commit titled "minor correction to the save dialog".

**Comment by sarthakpati** [comment]
Unable to replicate on 3 Windows machines with varying build paths, everything from `C:/CaPTkMasterBuild` to `E:/Projects/CaPTk_master/bin`. So, the initial hypothesis about this being an issue with the build path is probably incorrect.

**Comment by ashishsingh18** [comment]
Something that was working before with the same build path and doesn't work after update doesn't seem like a build path issue. Could be some changes that affected a specific platform. Needs more investigation.

**Comment by sarthakpati** [comment]
Fresh build (includes Superbuild) finished on pc-132. Pull from my fork to get the "force Superbuild") option.

**Comment by ashishsingh18** [comment]
Still getting the error with fresh build( Superbuild) in a new location.

**Comment by sarthakpati** [comment]
A full build on an Azure VM with same hardware specs as @ashishsingh18 's machine finished successfully.

**Comment by ashishsingh18** [comment]
It works now. For documentation purposes, the solution is to do the superbuild in a location with short path such as C:\Libs.
