### ISSUE TITLE
Cloning CaPTk on a Linux system takes very long

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#303]
**Describe the bug**
Fresh cloning of Captk on a Linux system takes a very long time (several hours)

**To Reproduce**
Fresh clone of Captk on a clean system

 - OS: Ubuntu 18.04.1 x64

**Comment by sarthakpati** [comment]
I wonder if this is a factor of the initial repo depth? I am seeing the `git clone` command on Travis (all platforms) is taking ~250 seconds for a depth of 50.

**Comment by MarkBergman-cbica** [comment]
Was that a simple clone, or with any options (ie., depth)?

This is likely due to network bandwidth and any issues with Github, not with the content of our repo.

```
time git clone https://github.com/CBICA/CaPTk.git
Cloning into 'CaPTk'...
remote: Enumerating objects: 7628, done.
remote: Total 7628 (delta 0), reused 0 (delta 0), pack-reused 7628
Receiving objects: 100% (7628/7628), 139.23 MiB | 28.86 MiB/s, done.
Resolving deltas: 100% (4458/4458), done.

real    0m6.447s
user    0m3.970s
sys     0m1.216s
```

**Comment by sarthakpati** [comment]
Please see the usage of the environment variable ```GIT_LFS_SKIP_SMUDGE``` in https://github.com/CBICA/CaPTk/blob/master/azure-pipelines.yml
