### ISSUE TITLE
Travis builds for Xenial are failing

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#304]
**Describe the bug**
Builds for Ubuntu Xenial are failing: due to different reasons each time.

**To Reproduce**
1. Go to travis-ci webpage after a build finishes
2. See log of xenial

**Expected behavior**
Builds should pass.

**Screenshots**
A few examples of such builds:
1. https://travis-ci.com/sarthakpati/CaPTk/builds/102915609
2. https://travis-ci.org/CBICA/CaPTk/builds/500819057?utm_source=github_status&utm_medium=notification

**CaPTk Version**
Current master.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: Xenial

**Comment by sarthakpati** [comment]
On the postive side, caching is now getting picked up; so full builds are taking ~1 hour on Xenial (the failures are always at the ~99% stage).

**Comment by surrsurus** [comment]
Linux builds are now on Azure, working as intended there. Can we close this issue?

**Comment by sarthakpati** [comment]
Absolutely
