### ISSUE TITLE
Feature Extraction Image Resampling should have option to have nearest neighbor interpolation specifically for masks and ROIs

### ISSUE THREAD

**Issue by sungminhacbica** [CBICA/CaPTk#305]
**Describe the bug**
Currently the feature extraction's resampling takes in the image, interpolates, then does rounding on the interpolated values. However, if multi label ROI with for example adjacent values of 2 and 4, the interpolated image may be values 3 where a 2 or 4 should be.

**To Reproduce**

**Expected behavior**

For the example, the value at the edge between label 2 and label 4 should get interpolated to either 2 or 4, not 3.

**Screenshots**

**CaPTk Version**
Version information is found on Help > About
1.6.1

**Comment by sarthakpati** [comment]
Done.
