### ISSUE TITLE
GeodesicTraining Command Line does not compile

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#306]
**Describe the bug**
When building CaPTk from source, the GeodesicTraining command line does not compile and generates errors.

**To Reproduce**
1. Build CaPTk from source on Linux

**Expected behavior**
It should compile.

**Comment by dboun** [comment]
Does the normal CaPTk compile? (Apart from the GeodesicTraining standalone exe)

**Comment by sarthakpati** [comment]
Yes.

**Comment by dboun** [comment]
The issue is fixed and the code for the fix is in a PR in Sarthak's branch.
