### ISSUE TITLE
macOS build/installer/packaging script

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#308]
**Is your feature request related to a problem? Please describe.**
A single build script that handles compilation (Superbuild + CaPTk) and packaging for macOS and Linux (I will integrate Windows into it).

**Describe the solution you'd like**
Referring to `scripts/captk-pkg`, I'd like to see it being able to handle macOS. I saw that there is a `.travis/mac-generic.sh` but it is by no means complete. It would be great to have a point-of-entry to handle the whole process; even if they call on different scripts.

**Describe alternatives you've considered**
A full manual build is what we are doing right now.

**Additional context**
Related to #126 #152

**Comment by PhucNgo1711** [comment]
This is resolved

**Comment by sarthakpati** [comment]
Is there such a "build script"?

**Comment by PhucNgo1711** [comment]
Yes the mac-generic.sh script handles this from end-to-end now. 
I just need to add the "post-install" part for the .pkg 

We can reopen this if you feel needed

**Comment by sarthakpati** [comment]
Nope, just wanted to ensure that we have something for macOS. Perhaps we can have the `captk-pkg` script call out to `*-generic.sh` (depending on platform) and then handle specific build routines.
