### ISSUE TITLE
WebProcess is broken for some machines

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#309]
**Describe the bug**
About Captk popup on application launch is blank

**To Reproduce**
1. launch Captk

**Expected behavior**
The popup should show information.

**Screenshots**
![image](https://user-images.githubusercontent.com/43445206/53819567-2a2fb980-3f38-11e9-926c-0990270ad457.png)

CaPTk Version: 1.6.2

 - OS: Windows 7 Enterprise SP1

**Comment by ashishsingh18** [comment]
Same issue if one tries Help->About

**Comment by sarthakpati** [comment]
WebProcess is broken. Even Abdhi is seeing this.

**Comment by surrsurus** [comment]
WebEngine was working for me on Linux, did not have any issues when my fork was merged into master. I don't remember changing any of the web engine stuff either.

**Comment by sarthakpati** [comment]
This issue is local to that single Windows machine, I believe. Abdhi had a different issue with qt

**Comment by sarthakpati** [comment]
Not blocking since it does not impede functionality of package.

**Comment by PhucNgo1711** [comment]
This should be fixed already right? @sarthakpati

**Comment by sarthakpati** [comment]
I think so. I was not able to replicate this problem on the machine @ashishsingh18 reported on in the new builds.
