### ISSUE TITLE
Histogram Matching without any inputs crashes the application

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#311]
**Describe the bug**
Histogram Matching without any inputs crashes the application

**To Reproduce**
1. Launch application. '
2. Do not load any data.
3. click on Preprocessing->Histogram Matching.
4. Do not provide any data to Histogram matching popup window
5. Click confirm -> Application crashes

**Expected behavior**
Application should tell the user to load data first

**CaPTk Version: 1.6.2

- OS: Windows 7 Enterprise SP1

**Comment by ashishsingh18** [comment]
Same behavior observed for Preprocessing->DeepMedic Normalizer

**Comment by sarthakpati** [comment]
Same behavior for `Applications -> Geodesic Training Segmentation`

**Comment by surrsurus** [comment]
Tested this on OSX 1.6.0 and can confirm this crashes.

**Comment by sarthakpati** [comment]
Fixed for histogram matchin and deep medic normalizer; testing for Geodesic Training

**Comment by surrsurus** [comment]
Tested on 1.6.2 Beta on OSX and this issue still exists

**Comment by surrsurus** [comment]
I simply opened histogram matching right up, clicked confirm and it crashed.

**Comment by sarthakpati** [comment]
Fix added in my fork. Waiting for my current PR #383 to be accepted and merged before pushing anything new in.

**Comment by sarthakpati** [comment]
Fixed.
