### ISSUE TITLE
Libra images loaded via drag and drop do not show up correctly

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#316]
**Describe the bug**
Libra images loaded via drag and drop show up as fully black

**To Reproduce**
1. Drag and drop Libra sample data images for example: case2.dcm
2. Images table gets updated and image shows up as black.
Please see attached screenshot

**Expected behavior**
Image should show up correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/43445206/53823970-dc6b7f00-3f40-11e9-86ae-d9778124fce6.png)

**CaPTk Version: 1.6.2

**Desktop (please complete the following information):**
 - OS: Windows 7 Enterprise SP 1

**Comment by sarthakpati** [comment]
This might be related to something going on with that particular machine. Needs further localized investigation.

**Comment by sarthakpati** [comment]
@ashishsingh18 which machine was this, again? It might be related to #400

**Comment by sarthakpati** [comment]
Closing the same issues out because we should keep conversation about a particular issue isolated in its own thread.
