### ISSUE TITLE
Application crashing on loading Libra images from file->Load->Images

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#318]
**Describe the bug**
Application crashing on loading Libra images from file->Load->Images

**To Reproduce**
1. Launch application
2. Load Libra sample data image from File->Load->Images
This leads to application crash. Please see attached screenshot

**Expected behavior**
Image should be loaded and application should not crash

**Screenshots**
![image](https://user-images.githubusercontent.com/43445206/53824148-4d129b80-3f41-11e9-94b8-6a4a1f2c1b9b.png)

**CaPTk Version: 1.6.2

**Desktop (please complete the following information):**
 - OS: Windows 7 Enterprise SP 1

**Comment by sarthakpati** [comment]
@ashishsingh18 which machine was this, again? It might be related to #400

**Comment by sarthakpati** [comment]
Closing the same issues out because we should keep conversation about a particular issue isolated in its own thread.
