### ISSUE TITLE
CLI (help) documentation

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#320]
**Describe the bug**

The documentation in response to the 'help' argument needs to be improved.

The output of "captk help" should be revised to be more user-friendly:

1. begin with a short overview (ie., captk can be called with the name of an operation as the argument)
2. provide examples of the most common usage (ie., "captk FeatureExtraction")
3. remove the ".cwl" extension from the list of applications
4. enhancement: have "captk help $application" actually run: "captk $application --help"

Within each application, the `--help` output should **not** be the same as the "usage" output that is produced in the event of an error in the user-supplied arguments. The `--help` output should be more user-friendly, should begin with a very brief description of the intent and use of the application, should have more usage examples, and does not necessarily need a full list of all options and arguments.

**Comment by sarthakpati** [comment]
First 3 added. 4 is a cosmetic change but not essential. Closing issue.
