### ISSUE TITLE
EGFRVIIISurrogateIndex images loaded via drag and drop are showing incorrectly

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#321]
**Describe the bug**
EGFRVIIISurrogateIndex images loaded via drag and drop are showing incorrectly

**To Reproduce**
1. Load one of the nifiti images from EGFRVIIISurrogateIndex sample data via drag and drop.
Images do not show up correctly. Only one view shows up as black. Please see attached screenshot.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/43445206/53825119-919f3680-3f43-11e9-99cb-686878ad9640.png)

**CaPTk Version: 1.6.2
**Desktop (please complete the following information):**
 - OS: windows 7 Enterprise SP1

**Comment by ashishsingh18** [comment]
related to #316

**Comment by ashishsingh18** [comment]
Behavior is the same for all Nifti images.

**Comment by sarthakpati** [comment]
@ashishsingh18 which machine was this, again? It might be related to #400

**Comment by sarthakpati** [comment]
Closing the same issues out because we should keep conversation about a particular issue isolated in its own thread.
