### ISSUE TITLE
drawing opacity does seem to work when we load images in series

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#322]
**Describe the bug**
i loaded one image, did some drawing, changed the opacity of 0.4. closed the images.
i loaded another image, did some drawing. the opacity box was still showing 0.4 but the actual opacity of the drawing was 1.

**Comment by surrsurus** [comment]
Actually I encountered this too on 1.6.0 OSX, which means that the issue still exists in 1.6.1.

**Comment by sarthakpati** [comment]
The opacity level should be stored in a variable and get only get initialized once per CaPTk instance.

**Comment by AlexanderGetka-cbica** [comment]
This issue has been fixed in my fork. The fix will be in my next pull request.
