### ISSUE TITLE
Clicking on 3D visualizer after loading a dataset leads to application crash

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#324]
**Describe the bug**
Clicking on 3D visualizer after loading a dataset leads to application crash

**To Reproduce**
1. Load a Nifti dataset.
2. Click on 3D visualizer.
Application crashes.

**Expected behavior**
Application should not crash and show the 3D view.

**CaPTk Version: 1.6.2

**Desktop (please complete the following information):**
 - OS: Windows 7 Enterprise SP 1

**Comment by sarthakpati** [comment]
I believe this can be mitigated by checking is the mask is valid or not.

**Comment by ashishsingh18** [comment]
This has been already fixed. Closing.
