### ISSUE TITLE
Feature Extraction not computed

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#325]
**Describe the bug**
When clicking 'Compute + Save' in Feature Extraction, it throws an itk error where it links to my computer (phucngo)

**To Reproduce**
1. In the Output box in Feature Extraction, create an output file
2. Click on 'Compute + Save'
3. Even though the progress bar says 100% Feature export complete, no output file is generated
4. An error box pops up with an itkLabelMap error

**Expected behavior**
No error should pop up, and the report .csv file should be generated

**Screenshots**
See below

**CaPTk Version**
Version information is found on Help > About

**Desktop (please complete the following information):**
 - OS: macOS, Windows
 - Version (including Build information, if any): 10.13+, 10.1803

**Comment by abdhigithub** [comment]
<img width="451" alt="screen shot 2019-03-05 at 12 32 42 pm" src="https://user-images.githubusercontent.com/39806556/53825764-12126700-3f45-11e9-8218-805f0e589b71.png">

**Comment by sarthakpati** [comment]
Same as #327, merging.

**Comment by sarthakpati** [comment]
If `Morphologic Features` are disabled, it works.

**Comment by sarthakpati** [comment]
Issue is stemming from the Resampling

**Comment by sarthakpati** [comment]
Fixed in CLI. Default sampling rate has been set to `3` for computational efficiency. Testing a warning on the UI.

**Comment by sarthakpati** [comment]
Fixed in UI. Now gives a warning when the default resampling rate (3.0) has been used so that the user knows to change this when doing extraction.
