### ISSUE TITLE
CaPTK 1.6.2Alpha Install has path ~/CaPTk/CaPTk-.bin not ~/CaPTk/1.6.2.Alpha/captk

### ISSUE THREAD

**Issue by sungminhacbica** [CBICA/CaPTk#326]
**Describe the bug**
The expected install path from previous installs is: ~/CaPTk/1.6.2Alpha/captk
Actual install path on the cbica-cluster's personal home directory is: ~/CaPTk/CaPTk-.bin without the subdirectory named the version number

**To Reproduce**
1. Download: [Do a wget of this link](https://www.nitrc.org/frs/downloadlink.php/11160 "Linux 1.6.2Alpha Download Link")
1. do `sh /DownloadDirectory/CaPTk_1.6.2.Alpha_Installer.bin`
1. Confirm
1. Check the install path at ~/CaPTk

**Expected behavior**
I expected the install path to be:
~/CaPTk/1.6.2Alpha/captk
similar to previous releases 1.6.0 and 1.6.1

**Screenshots**

**CaPTk Version**
Version information is found on Help > About
1.6.2Alpha

**Desktop (please complete the following information):**
 - OS: Linux (cbica-cluster)
 - Version (including Build information, if any): CentOS7

LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core)
Release:        7.6.1810
Codename:       Core

**Additional context**

**Comment by sarthakpati** [comment]
The AppImage should contain the version information which gets pulled in from `PROJECT_VERSION`

**Comment by PhucNgo1711** [comment]
Has this been fixed yet?

**Comment by surrsurus** [comment]
Yep, this one should be fixed, versioning is picked up directly from CaPTk, have not been seeing the issue since with generated CaPTk packages.
