### ISSUE TITLE
Unable to select proper files(from sample data) for Population Atlas via GUI

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#328]
**Describe the bug**
Unable to select proper files for Population Atlas via GUI. The terminology on GUI and files in sample data are confusing. 

**To Reproduce**
1. Launch Application->Population Atlas
2. Confusion in selecting appropriate files from sample data for each of items.
3. Selecting Atlas file via 'Browse' always updates the 'Label' file.

**Expected behavior**
a) File selected via 'Browse' should show up in the appropriate line edit box. 
b) Sample data should clearly mention which one is label and atlas, perhaps in the filename itself.

**Screenshots**
![image](https://user-images.githubusercontent.com/43445206/53826518-c2349f80-3f46-11e9-8a57-13f28483bf85.png)

**CaPTk Version: 1.6.2

**Desktop (please complete the following information):**
 - OS: Windows 7 Enterprise SP 1

**Comment by saimarathore** [comment]
bug fixed. data revised.
