### ISSUE TITLE
[OSX] CaPTk crashes when undoing free hand drawings to an image

### ISSUE THREAD

**Issue by surrsurus** [CBICA/CaPTk#331]
**Describe the bug**
CaPTk will crash after drawing on an image in freehand mode on OSX.

**To Reproduce**
1. Load the test tumor image
2. Load the test tumor ROI
3. Draw some freehand labels (I did mine on the center image, pretty sure that doesn't affect anything though)
4. Click undo many times/very fast
5. CaPTk crashes

**Expected behavior**
CaPTk does not crash.

**CaPTk Version**
1.6.0, pretty sure that this issue is new however and may still be present on 1.6.1

**Desktop (please complete the following information):**
 - OS: OSX Sierra

**Comment by PhucNgo1711** [comment]
this seems to be fixed
