### ISSUE TITLE
Directionality, documentation, insufficient help

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#332]
Directionality, documentation, insufficient help

	Missing explanation of purpose (1 paragraph overview, basic info re. required input data types, results that are produced, etc)

	Missing usage examples

**Comment by sarthakpati** [comment]
Related to #363

**Comment by sarthakpati** [comment]
Please see `Utilities.cxx` for an example on how to do this. The API reference is `cbica::CmdParser::addExampleUsage`.

**Comment by sarthakpati** [comment]
Fixed.
