### ISSUE TITLE
EGFRvIIISurrogate, documentation, insufficient help

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#334]
The '--help' output is missing an explanation of purpose (1 paragraph overview, basic info re. required input data types, results that are produced, etc)

	Typo in example (application name repeated)

**Comment by sarthakpati** [comment]
Related to #363

**Comment by sarthakpati** [comment]
Please see `Utilities.cxx` for an example on how to do this. The API reference is `cbica::CmdParser::addExampleUsage`.
