### ISSUE TITLE
[OSX] Quitting application (cmd+q) won't close documentation that's open

### ISSUE THREAD

**Issue by surrsurus** [CBICA/CaPTk#335]
**Describe the bug**
Quitting CaPTk does not kill the web engine process on OSX.

**To Reproduce**
1. Open CaPTk
2. Open some help guide
3. Cmd + q
4. Docs still open

**Expected behavior**
OSX users expect that cmd+q will fully quit a program, however this is not the case.

**CaPTk Version**
1.6.0, will test on 1.6.1

**Desktop (please complete the following information):**
 - OS: OSX Sierra

**Additional context**
I believe this is because the webengineprocess isn't under the 'captk' process, after all, the web engine is literally just a chromium instance so it's probably forked() somewhere in the qt libraries. This may also not be a serious enough issue to warrant fixing, so feel free to close if that's the case.

**Comment by sarthakpati** [comment]
We had seen this issue on Windows before but it was fixed courtesy @ashishsingh18 . I wonder why the same mechanism is not working for macOS?

**Comment by surrsurus** [comment]
Actually, I checked it again with a new compile and the issue was fixed, haven't seen anything like it recently. Closing issue.
