### ISSUE TITLE
Greedy Registration, `--help` documentation, insufficient help

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#341]
**Describe the Bug**
Greedy Registration, `--help` documentation, insufficient help

	The `--help` output is missing explanation of purpose (1 paragraph overview, basic info re. required input data types, results that are produced, etc)

**Comment by sarthakpati** [comment]
Please see `Utilities.cxx` for an example on how to do this. The API reference is `cbica::CmdParser::addExampleUsage`.
