### ISSUE TITLE
Cannot open CaPTk 1.6.2Alpha on cbica-cluster

### ISSUE THREAD

**Issue by sungminhacbica** [CBICA/CaPTk#343]
**Describe the bug**
I cannot open an install of CaPTk 1.6.2Alpha on my home directory in cbica-cluster, even if I am logged in with ssh -XY flag and have verified with xclock that I have graphical X11 forwarding.

**To Reproduce**
1. Log in to the __`cbica-cluster`__ with with ssh -XY flag.
1. Verify that I have X11 forwarding with `xclock`.
1. Downloaded 1.6.2Alpha Linux Install with wget on the cluster: [Linux 1.6.2Alpha Link](https://www.nitrc.org/frs/downloadlink.php/11160)
1. I did install on __`cbica-cluster`__ in my home directory with command `sh /DownloadDirectory/CaPTk_1.6.2.Alpha_Installer.bin`
1. Called the executable captk by navigating to  `~/CaPTk` then `./captk`

**Expected behavior**
The xclock which I ran prior to calling captk worked, indicating I have X11 forwarding; I had a new window appear with the xclock. I expected the CaPTk GUI window to open when I called `./captk`

I got the following error on the command line, and no GUI appeared:

Error: Can't open display: localhost:1.0
/scratch/hasun/.mount_CaPTk-0ALb6u/usr/bin/CaPTk: /cbica/software/external/gcc/centos7/4.9.2/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /scratch/hasun/.mount_CaPTk-0ALb6u/usr/bin/CaPTk)
/scratch/hasun/.mount_CaPTk-0ALb6u/usr/bin/CaPTk: /usr/lib64/libgpg-error.so.0: no version information available (required by /scratch/hasun/.mount_CaPTk-0ALb6u/usr/lib/libgcrypt.so.20)

**CaPTk Version**
1.6.2Alpha

**Desktop (please complete the following information):**
 - OS: Linux
 - Version (including Build information, if any):

LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core)
Release:        7.6.1810
Codename:       Core

**Additional context**

**Comment by surrsurus** [comment]
Will be looking into this issue. So, my take is that this bug is incredibly strange because it's this exact issue that the AppImage should remove, as the AppImage should simply package my glibc and therefore should be available now that we have set the LD_LIBRARY_PATH. Actually, now that I think about it, maybe that's the issue? Is the cluster running the most recent rev of master with my LD_LIBRARY_PATH fix?

**Comment by sarthakpati** [comment]
@surrsurus the cluster is not running the latest master. could you test a package you compile on your machine to see if it works?

**Comment by surrsurus** [comment]
I think this issue is fixed, LD_LIBRARY_PATH is set properly now and missing/improper GLIBC is a known issue with AppImages, closing issue but feel free to reopen if the problem comes back up in any capacity.
