### ISSUE TITLE
Dicom to nifti conversion

### ISSUE THREAD

**Issue by abdhigithub** [CBICA/CaPTk#344]
Loading the Dicom on CaPTk is smooth. However while saving out to a NifTi image, the application quits.
<img width="517" alt="screen shot 2019-03-05 at 1 15 16 pm" src="https://user-images.githubusercontent.com/39806556/53827318-c497f900-3f48-11e9-89ad-c9c5c72b6191.png">

**Comment by sarthakpati** [comment]
Not specific to macOS. Hopefully with the contributions from @ashishsingh18 (where `cbica::ReadImage` contains the DICOM parsing, this will be fixed).

**Comment by ashishsingh18** [comment]
The issue still exists. The crash happens in save function in mainwindow.

**Comment by ashishsingh18** [comment]
Issue fixed. Needs testing.

**Comment by ashishsingh18** [comment]
This is now fixed in my fork, waiting to get merged into master.

**Comment by sarthakpati** [comment]
Related to #4. Fixed, closing.
