### ISSUE TITLE
[OSX] Strange selection artifacts on draw screen

### ISSUE THREAD

**Issue by surrsurus** [CBICA/CaPTk#346]
**Describe the bug**
Selecting multiple drawing tools creates strange artifacts

**To Reproduce**
1. Go to Drawing panel
2. Select a bunch of different drawing tools (free hand, circle, etc)

**Expected behavior**
UI displays normally

**Screenshots**
![slection artifact 1](https://user-images.githubusercontent.com/9388076/53827300-bba72780-3f48-11e9-8bcb-5cd265c9f616.png)
![selection artifact 2](https://user-images.githubusercontent.com/9388076/53827301-bba72780-3f48-11e9-9e3f-91f7744c751d.png)

**CaPTk Version**
1.6.0 CaPTk, might be present in 1.6.1, will check.

**Desktop (please complete the following information):**
 - OS: OSX Sierra

**Additional context**
This is cosmetic, and might not be worth working on, if so, feel free to close. It is also entirely possible that this just happens for me, and is not reproducible.

**Comment by PhucNgo1711** [comment]
This seems to be fixed now
