### ISSUE TITLE
PerfusionPCA: `--help` output needs improvement

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#347]
**Describe the Bug**
PerfusionPCA: `--help` output needs improvement

	The `--help` output is missing explanation of purpose (1 paragraph overview, basic info re. required input data types, results that are produced, etc)

	The `--help` output is missing usage examples

**Comment by sarthakpati** [comment]
Please see `Utilities.cxx` for an example on how to do this. The API reference is `cbica::CmdParser::addExampleUsage`.
