### ISSUE TITLE
Utilities `--help` documentation

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#357]
**Describe the Bug**
Utilities `--help` documentation
	The `--help` output is missing explanation of purpose (1 paragraph overview, basic info re. required input data types, results that are produced, etc),
	
	The `--help` output is missing examples

**Comment by sarthakpati** [comment]
Done.

**Comment by sarthakpati** [comment]
The command `Utilities.exe -h` generates the following output in addition to the usual stuff:

```
Examples of Usage:

 Command: Utilities.exe -i C:/test.nii.gz -o C:/test_int.nii.gz -c int
 Result : Cast an image pixel-by-pixel to a signed integer

 Command: Utilities.exe -i C:/test.nii.gz -o C:/test_75.nii.gz -r 75 -ri linear
 Result : Resize an image by 75% using linear interpolation

 Command: Utilities.exe -i C:/test.nii.gz -inf
 Result : Prints out image information to console (for DICOMs, this does a full dump of the tags)
```
