### ISSUE TITLE
Superbuild failing on Windows 

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#359]
**Describe the bug**
Superbuild fails on Windows. It is trying to do the installation and fails due to lack of admin rights.

**To Reproduce**
1. Update from master
2. create a new build directory and do a force superbuild

**Expected behavior**
Superbuild should succeed.

OS: Windows 7 Enterprise SP 1

**Comment by sarthakpati** [comment]
Updated the Superbuild recipe to ensure that the installation happens in the build location; this way the user does not need admin rights and the build will pass.
