### ISSUE TITLE
PseudoProgressionEstimator Fails on Linux 1.6.2

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#362]
## Expected Behavior

Pseudoprogression training outputs model

## Actual Behavior

Killed/Terminated during revising perfusion image.
Produced Mean_PERF.csv and PCA_PERF.csv only in model directory

## Steps to Reproduce the Problem

 Used command line 
 > captk PseudoProgressionEstimator -t 0 -i $inputdir -o $outputdir

## Specifications

  - Version: v1.6.2Alpha
  - Platform: Ubuntu 18.10 and Centos

## Logs 
Both from Centos and Ubuntu copied below

Centos

AAOQ
AAQZ
.... (skip)
ABLW
Number of subjects with required input: 40
Loading Perfusion Image: 0
Loading Perfusion Image: 1
Loading Perfusion Image: 2
Loading Perfusion Image: 3
Loading Perfusion Image: 4
Loading Perfusion Image: 5
Loading Perfusion Image: 6
Loading Perfusion Image: 7
Loading Perfusion Image: 8
Loading Perfusion Image: 9
Loading Perfusion Image: 10
Loading Perfusion Image: 11
Loading Perfusion Image: 12
Loading Perfusion Image: 13
Loading Perfusion Image: 14
Loading Perfusion Image: 15
Loading Perfusion Image: 16
Loading Perfusion Image: 17
Loading Perfusion Image: 18
Loading Perfusion Image: 19
Loading Perfusion Image: 20
Loading Perfusion Image: 21
Loading Perfusion Image: 22
Loading Perfusion Image: 23
Loading Perfusion Image: 24
Loading Perfusion Image: 25
Loading Perfusion Image: 26
Loading Perfusion Image: 27
Loading Perfusion Image: 28
Loading Perfusion Image: 29
Loading Perfusion Image: 30
Loading Perfusion Image: 31
Loading Perfusion Image: 32
Loading Perfusion Image: 33
Loading Perfusion Image: 34
Loading Perfusion Image: 35
Loading Perfusion Image: 36
Loading Perfusion Image: 37
Loading Perfusion Image: 38
Loading Perfusion Image: 39
Revising Perfusion Image: 0
Revising Perfusion Image: 1
Revising Perfusion Image: 2
Revising Perfusion Image: 3
Revising Perfusion Image: 4
Revising Perfusion Image: 5
Revising Perfusion Image: 6
Revising Perfusion Image: 7
Revising Perfusion Image: 8
Revising Perfusion Image: 9
Revising Perfusion Image: 10
Revising Perfusion Image: 11
Revising Perfusion Image: 12
Revising Perfusion Image: 13
Revising Perfusion Image: 14
Revising Perfusion Image: 15
Revising Perfusion Image: 16
Revising Perfusion Image: 17
Revising Perfusion Image: 18
Revising Perfusion Image: 19
Revising Perfusion Image: 20
Revising Perfusion Image: 21
Revising Perfusion Image: 22
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Ubuntu:
...(skip - same as above)
Revising Perfusion Image: 18
Revising Perfusion Image: 19
Revising Perfusion Image: 20
Revising Perfusion Image: 21
Revising Perfusion Image: 22
Revising Perfusion Image: 23
Revising Perfusion Image: 24
Revising Perfusion Image: 25
Revising Perfusion Image: 26
Revising Perfusion Image: 27
Revising Perfusion Image: 28
Revising Perfusion Image: 29
Revising Perfusion Image: 30
Revising Perfusion Image: 31
Revising Perfusion Image: 32
Revising Perfusion Image: 33
Killed

**Comment by sarthakpati** [comment]
Hey @chiharusako, did you manage to speak to @saimarathore about this?

**Comment by sarthakpati** [comment]
According to @saimarathore, this might be related to memory issues.

**Comment by sarthakpati** [comment]
Documentation updated.
