### ISSUE TITLE
CmdParser updates needed in ALL CLI applications

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#363]
**Is your feature request related to a problem? Please describe.**
The `--help` option is an extended version of `--usage`, which should not be the case.

**Describe the solution you'd like**
The `--help` command line parameter should give a single line/paragraph description of the application and exemplary usage scenarios (with explanation of what the respective command does.

**Additional context**
`Application.exe --help` should give the following information:

```
Description:
  # here is where a single line/paragraph description of the application should go

## Usage as it shows up currently

Examples:
  # first usage
  # description of first usage
  
  # second usage
  # description of second usage
```

**Comment by sarthakpati** [comment]
Related to all the `--help` issues opened by @MarkBergman-cbica

**Comment by MarkBergman-cbica** [comment]
> Is your feature request related to a problem? Please describe.
> The --help option is an extended version of --usage, which should not be the case.

I would say that --help should be an extended version of --usage, from the end-user's point of view. Within the code, they may have significant differences.

The extensions to "--usage" should include a brief description of the purpose of the application, very brief guidelines about the required inputs (ie., file types, required pre-processing, etc) the outputs, and usage examples with explanations.

That can be in addition to the terse syntax summary that is present in "--usage"

**Comment by sarthakpati** [comment]
Added an `assert` statement to check if the variable `m_exampleUsage` is empty or not for `cbica::CmdParser`. Tested that this works but will keep it commented out till all developers have been notified in the weekly meeting.

This can be used as a base to extend `m_exampleUsage` in a `map< string, string >` interface which records the CLI example and its description. The same thing can also be done for the description.

**Comment by sarthakpati** [comment]
This is ready to be tested (after the 1.6.2 release). All developers need to be notified of the new changes:

1. `CmdParser::exampleUsage` is now deprecated (this warning will come up at compile time)
2. `CmdParser::addExampleUsage` is required (there will be compile time error if the underlying variable is empty). It takes takes 2 strings, one for the actual command (without the executable name) and one for the command's description. Multiple such examples can be added.
3. `CmdParser::addApplicationDescription` is required (there will be compile time error if the underlying variable is empty). 

Tagging @ashishsingh18 @saimarathore @MarkBergman-cbica

**Comment by sarthakpati** [comment]
Fixed.
