### ISSUE TITLE
Addition of MITK as a dependency 

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#366]
**Is your feature request related to a problem? Please describe.**
Reinventing wheels (DICOM parsing, specifically) is a painful process.

**Describe the solution you'd like**
[MITK](http://www.mitk.org/wiki/The_Medical_Imaging_Interaction_Toolkit_(MITK)) has an excellent repository of functions, specifically related to DICOM parsing and XNAT communications, which will be very useful for the cohort UI. Addition of this library as a dependency would make life much easier for developers.

**Describe alternatives you've considered**
Replicating what MITK has done ourselves would be time-consuming.

**Additional context**
MITK compiles need to be tested with the current Superbuild mechanism. A separate branch needs to be created to track this.

**Comment by sarthakpati** [comment]
MITK compile takes a **long** time (approaching ~1 hour on a 2 core Windows x64 machine). This will essentially ensure that we can never use Travis again. Suddenly, #360 has become very important.

**Comment by ashishsingh18** [comment]
We need to try things with MITK in a separate branch and do the due diligence before we put it in.

**Comment by sarthakpati** [comment]
Absolutely, that is what I intend to do. Separate branches for this and #367

**Comment by sarthakpati** [comment]
Nope.
