### ISSUE TITLE
getFilenameExtension returns incorrect extension for .nii files

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#371]
**Describe the bug**
getFilenameExtension returns incorrect extension( empty string) for .nii files

**To Reproduce**
Load file with .nii extension and check the extension return by getFilenameExtension . It returns empty string. Don't know if there is a way to test this. Came across this while trying out dicom loading and putting breakpoints.

**Expected behavior**
It should return .nii and not empty string

**Additional context**
We should write tests for such functions so we know our code is working correctly.

**Comment by sarthakpati** [comment]
Thanks for picking this up! Travis did not even reach the tests before timing out, unfortunately. Again, highlights how important #360 is.

**Comment by sarthakpati** [comment]
Fixed in PR.
