### ISSUE TITLE
!!! CmdParser::exampleUsage() IS DEPRECATED; use CmdParser::AddExampleUsage instead !!!

### ISSUE THREAD

**Issue by surrsurus** [CBICA/CaPTk#375]
**Describe the bug**
Applications sometimes output a deprecation warning: `!!! CmdParser::exampleUsage() IS DEPRECATED; use CmdParser::AddExampleUsage instead !!!` We should migrate all of these over to the new method.

**To Reproduce**
1. Run `./CaPTk FeatureExtraction -u`
2. Warning is output

**Expected behavior**
No warning displayed

**CaPTk Version**
Latest master revision

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux Xenial (16.04)

**Comment by sarthakpati** [comment]
Related to #363
