### ISSUE TITLE
CWL should be picked up even when extension is passsed in

### ISSUE THREAD

**Issue by surrsurus** [CBICA/CaPTk#376]
**Describe the bug**
`./captk FeatureExtraction.cwl -u` Should still direct to FeatureExtraction even though the extension is present, though it occurs in every application

**To Reproduce**
1. ./captk FeatureExtraction.cwl -u

**Expected behavior**
Feature extraction usage is printed, or whatever arguments should be passed to the application.

**CaPTk Version**
Latest master revision

**Desktop (please complete the following information):**
 - OS: Ubuntu Xenial

**Comment by sarthakpati** [comment]
Fixed.
