### ISSUE TITLE
Desktop shortcut is not created upon installation despite selection

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#38]
Desktop shortcut is not created upon installation despite selection

**Comment by sarthakpati** [comment]
This option has now been deprecated. Shortcuts are limited to the start menu.

**Comment by MarkBergman-cbica** [comment]
> This option has now been deprecated. Shortcuts are limited to the start menu.

Reference?

I don't see that in the spec:

https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#deprecated-items

**Comment by sarthakpati** [comment]
This is for Windows.

https://github.com/CBICA/CaPTk/blob/master/CMakeLists.txt#L1027
