### ISSUE TITLE
Build problem on Windows

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#380]
**Describe the bug**
CaPTk _sometimes_ doesn't build on Windows. Other times it is the superbuild other times it is some subprojects. It is kind of random when it happens. Some times rebuilding helps, sometimes not. Running VS as administrator seems to help, believe it or not, but I'm not sure.

**To Reproduce**
It is hard to reproduce since it is not consistently doing it. 

**Desktop (please complete the following information):**
 - OS: Windows 7/10

**Additional context**
```cmd
The relevant part of the output:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: The command "setlocal [C:\Ca\sup\ITK-build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake [C:\Ca\sup\ITK-build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\Ca\sup\ITK-build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmEnd [C:\Ca\sup\ITK-build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [C:\Ca\sup\ITK-build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmErrorLevel [C:\Ca\sup\ITK-build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: exit /b %1 [C:\Ca\sup\ITK-build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmDone [C:\Ca\sup\ITK-build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [C:\Ca\sup\ITK-build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :VCEnd" exited with code 1. [C:\Ca\sup\ITK-build\install.vcxproj]
```

There is usually 5-6 different places where "the command setlocal exits with code 1". The full output attached is from trying to build the superbuild.

[build_output.txt](https://github.com/CBICA/CaPTk/files/2949082/build_output.txt)

**Comment by sarthakpati** [comment]
The most common source of build issues on Windows is the ITK build directory build fairly long (there is check for this but I guess it should be made more stringent). I always do the Superbuild separately from CaPTk since I want to use the same libraries for other projects in a location to the tune of **C:/LibsCaPTk** or something similar with a very short path. We had similar issues on the machine that @ashishsingh18 uses and this seemed to help.

**Comment by dboun** [comment]
Unfortunately, I knew that and I always do the same. In the lab my build directory was 'C:\CaPTk_d' and now it was 'C:\Ca\sup'. So it's not that.

Running VS as admin helped again and it built. I'm mostly reporting it in case it happens again to someone else

**Comment by sarthakpati** [comment]
I think I know what the issue is. Please pull my [latest commit](https://github.com/sarthakpati/CaPTk/commit/b5e164ee78e2793a2111b913b703cb806bbe7b22); this will solve the issue for you. Also, there will be some libraries installed in your **Program Files** folder, which you should delete.
