### ISSUE TITLE
1.6.2 Beta, Linux version download link not working

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#384]
**Describe the bug**
Cannot download the 1.6.2 Beta Linux version

**To Reproduce**
1. Go to https://www.nitrc.org/frs/downloadlink.php/11160
2. Receive an Alert saying 
   ! 550 Failed to change directory

**CaPTk Version**
1.6.2 Beta

**Desktop (please complete the following information):**
Ubuntu 18.10

**Comment by sarthakpati** [comment]
Try now?

**Comment by chiharusako** [comment]
It worked :)
Now downloading. Thank you!

**Comment by sarthakpati** [comment]
Excellent. Closing the issue
