### ISSUE TITLE
OSX CaPTk is not able to be ran normally in High Sierra

### ISSUE THREAD

**Issue by surrsurus** [CBICA/CaPTk#385]
**Describe the bug**
The CaPTk application is displayed with a no sign overplayed and upon opening displays the message: You have macOS 10.13.2, The application requires macOS 10.14 or later.

**To Reproduce**
1. Install CaPTk on 10.13.2
2. Run application

**Expected behavior**
Application should run normally

**Screenshots**
![Screen Shot 2019-03-13 at 12 13 35 PM](https://user-images.githubusercontent.com/9388076/54295542-9e4a0d00-4589-11e9-9f26-7f00419d9509.png)

**CaPTk Version**
1.6.2 Beta

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.2

**Comment by surrsurus** [comment]
For reference, I was able to go into the .app and directly run the CaPTk executable and it worked fine, and I think it's a packaging issue.

**Comment by PhucNgo1711** [comment]
@surrsurus let me know when you have verified the .pkg I sent you works

**Comment by surrsurus** [comment]
It will let me install, but not run CaPTk, same as before.

**Comment by sarthakpati** [comment]
@PhucNgo1711 are you creating the installer on macOS 10.14?

**Comment by PhucNgo1711** [comment]
Yeah. But I'm not sure if it's the reason

**Comment by sarthakpati** [comment]
@PhucNgo1711 any updates?

**Comment by PhucNgo1711** [comment]
I need a machine with macOS 10.13 to test. Azure has macOS 10.13 and that installer has been working for 10.14, but I haven't had the chance to test it on a 10.13 machine

**Comment by sarthakpati** [comment]
Then let's reopen if we run into it again.
