### ISSUE TITLE
1366 x 768 Displays visualization panel smaller than normal

### ISSUE THREAD

**Issue by surrsurus** [CBICA/CaPTk#390]
On 1366x768 displays (A strange display type laptops like to use) the visualization panel is very small.

![Screen Shot 2019-03-13 at 12 37 18 PM](https://user-images.githubusercontent.com/9388076/54297203-c5eea480-458c-11e9-8e17-baa50d778165.png)

CaPTk is still usable, but it might be easier for users with this display if the panel was slightly bigger.

**Comment by sarthakpati** [comment]
Identical to #405

**Comment by sarthakpati** [comment]
@ashishsingh18 based on our last discussion during the devs meeting, the minimum vertical height we will look to support is 1024, correct? Hopefully, after the UI-based changes have taken effect (RSNA 2019), targetting lower resolutions might become easier. I am closing this (and related issue).
