### ISSUE TITLE
CaPTk throws a segfault when loading ROI masks

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#391]
**Describe the bug**
If you open an image and try to load an ROI mask, which was created on top of a different image, it would crash CaPTk with a segfault error. 

**To Reproduce**
1. Open an image, draw a new mask on it
2. Save the mask
3. Open a different image
4. Load the mask that was just saved
5. CaPTk crashes with a segfault

**Expected behavior**
It should not give an error, especially when loading on the same image space

**CaPTk Version**
1.6.2.Beta

**Desktop (please complete the following information):**
 - OS: macOS
 - Version (including Build information, if any): 10.13+

**Comment by surrsurus** [comment]
+1. Confirmed this on my machine (osx 10.13.2 1.6.2 Beta). I loaded the basic ACCC0 image and then tried to add "atlas mask" from the sri24 folder and CaPTk hard crashed with a very unhelpful stack trace of just pointers.

**Comment by sarthakpati** [comment]
Fixe added in my fork. Waiting for my current PR #383 to be accepted and merged before pushing anything new in.
