### ISSUE TITLE
Feature extraction does not work for either a single or multiple label ROI

### ISSUE THREAD

**Issue by sbakas** [CBICA/CaPTk#392]
<img width="1620" alt="captk error" src="https://user-images.githubusercontent.com/5031169/54297778-deab8a00-458d-11e9-924b-234a43ab06d0.png">
**Describe the bug**
The error I receive implies that features cannot be extracted for a single label ROI

**To Reproduce**
1. Load the image coming with CaPTk (AAAC0_flair_pp_shrunk.nii.gz)
2. Create a rough mask using the tools in the drawing tab.
3. Go to feature extraction tab
4. Click compute+save
5. See error

**Expected behavior**
Features should have been extracted.

**Screenshots**
<img width="1620" alt="captk error" src="https://user-images.githubusercontent.com/5031169/54297751-d2bfc800-458d-11e9-92f7-6180e82f4767.png">

**CaPTk Version**
v.1.6.2.Beta (downloaded from nitrc on 2019.03.13)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by sbakas** [comment]
The previous error is appears only when the "morphologic" features are selected (as shown in the previous screenshot. If the morphologic features are not selected then CaPTk crashes completely (without any error).

**Comment by sarthakpati** [comment]
@sungminhacbica: Issue is coming from `GLSZMFeatures.h` in the `CalculateFeatures` function.

**Comment by sarthakpati** [comment]
Fixes have been added to my fork. @sungminhacbica please check them ASAP.

**Comment by sarthakpati** [comment]
Fixed.
