### ISSUE TITLE
C++11 Error on macOS

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#396]
**Describe the bug**
A new bug appears after the latest fixes are built on macOS. 
```
clang-7: error: no input files
/bin/sh: -std=c++11: command not found
```

**To Reproduce**
1. Build `Superbuild`
2. Run `cmake `then `make `to build `CaPtk`
3. The error is thrown on the very first step of the build process

**Expected behavior**
`CaPTk` should be built without any error like before

**Screenshots**
<img width="947" alt="Screen Shot 2019-03-15 at 12 30 51 PM" src="https://user-images.githubusercontent.com/14838084/54446885-688a5d00-471e-11e9-8895-5c7fd48e7300.png">

**CaPTk Version**
1.6.2.Beta

**Desktop (please complete the following information):**
 - OS: macOS
 - Version (including Build information, if any): 10.13+

**Comment by PhucNgo1711** [comment]
This is caused because the DicomImageReader file is not in this location `src/cbica_toolkit/CMakeFiles/CaPTk_CBICATK.dir/src/IO/src/DicomImageReader.cpp.o`
@sarthakpati

**Comment by sarthakpati** [comment]
The latest fix on Phuc's fork should have fixed this.

**Comment by PhucNgo1711** [comment]
Fix being tested
