### ISSUE TITLE
CaPTk version is not picked up properly on macOS

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#397]
**Describe the bug**
The `.Beta` portion is being treated as the file extension instead of `.app`, hence cut off. The error is:
`Supplied directory name wasn't found: /Users/phucngo/Desktop/CaPTk/bin/CaPTk_1.6.2.app/Contents/MacOS/../Resources/bin`

**To Reproduce**
1. Build `CaPTk`
2. Try running `CaPTk_1.6.2.Beta.app` (The `.Beta` shows here in the app bundle)
3. An error is thrown because it's trying to access this path `CaPTk_.1.6.2.app/Contents/Resources/...`

**Expected behavior**
The `.Beta` should be picked up. This was not an error in `1.6.2.Alpha`

**CaPTk Version**
1.6.2.Beta

**Desktop (please complete the following information):**
 - OS: macOS
 - Version (including Build information, if any): 10.13+

**Comment by surrsurus** [comment]
Did the changes to the cbicaUtilities not fix this?

**Comment by PhucNgo1711** [comment]
no I still have it

**Comment by sarthakpati** [comment]
Fix added and is now being tested.

**Comment by PhucNgo1711** [comment]
This is now fixed and tested

**Comment by PhucNgo1711** [comment]
Quick note: The string matching mechanism would fix Linux but break macOS. The macOS path was actually properly populated in the first place, so the splitting and rematching ended up removing the Version Patch @surrsurus
