### ISSUE TITLE
FUSE mounts not umounted

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#398]
**Describe the bug**

When CaPTk exits, the FUSE mount is not umounted.

**To Reproduce**
Login to cbica-cluster

Run captk
Check $TMPDIR for ".mount_captk*" FUSE mounts via "`mount`" or "`ls`"

Also see RT ticket #245

**Comment by surrsurus** [comment]
So, FUSE *should* automatically unmount the partition after the process and subprocess (AppRun) both finish, I think it's very strange that this doesn't seem to be happening. I've started looking around at relevant documentation/issues and found that there might be potential issues with force-closing (https://github.com/AppImage/AppImageKit/issues/146).

**Comment by MarkBergman-cbica** [comment]
You can close this. The processes are still running, so the FUSE mounts should still exist.

Whether the processes should be taking this long might be the subject of another bug report...
