### ISSUE TITLE
Image viewer too small. Linux - 1366x768 screen

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#405]
**Describe the bug**
Image viewer is too small on 1366x768 screen on Linux.

**Screenshots**
![CaPTkLinuxMint](https://user-images.githubusercontent.com/39439832/54647794-a257bc80-4aac-11e9-943b-75a696ccffc1.png)

**CaPTk Version**
1.6.2_RC

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version (including Build information, if any): 19
 - Intel Core i7 2670QM
 - AMD Radeon HD 6490M (2012 midrange discrete laptop gpu)
 - Intel HD Graphics 3000 (integrated gpu)
 - 4GB RAM
 - 1366x768 resolution

**Additional context**
CaPTk 1.6.1 on Windows had a normal sized image viewer on the same screen.

**Comment by sarthakpati** [comment]
@ashishsingh18 based on our last discussion during the devs meeting, the minimum vertical height we will look to support is 1024, correct? Hopefully, after the UI-based changes have taken effect (RSNA 2019), targetting lower resolutions might become easier. I am closing this (and related issue).
