### ISSUE TITLE
[Utilities] Image Information update

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#411]
**Is your feature request related to a problem? Please describe.**
Currently, the **Image Information** part of `Utilities` only gives basic information, we need something more detailed.

**Describe the solution you'd like**
Image information from all DICOM image(s) [not just structural but also DTI, DWI, Perfusion, fMRI] headers should be coming out as console output.

**Describe alternatives you've considered**
Something similar to `fslhd` is what we are looking for.

Additionally, this information should also be saved when doing a DICOM to NIfTI conversion (either through `Utilities` or via `dcm2nii`) in the output directory.

**Comment by ashishsingh18** [comment]
This is done. Waiting to get merged into master.

**Comment by sarthakpati** [comment]
Closing.
