### ISSUE TITLE
cannot run Captk on Linux

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#413]
**Describe the bug**
Cannot run Captk in Debug mode on linux. It gives the following error:
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**To Reproduce**
1. Fresh checkout of nightly
2. Super-build + build Captk
4. Run

**Expected behavior**
Captk UI should show up.

**CaPTk Version**
1.6.2

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.02

**Comment by sarthakpati** [comment]
This is probably because the `platforms` directory is not getting picked up properly (courtesy [ref](https://stackoverflow.com/questions/17106315/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without)). Performing `linuxdeployqt` on the CaPTk executable should fix this.
