### ISSUE TITLE
Unable to draw seed points on macOS

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#417]
**Describe the bug**
The yellow crosshairs are not showing on CaPTk running on macOS. Double clicking, command + space, and control + space don't show anything.

**To Reproduce**
1. Try to draw seed points on images by double clicking or control + space or command + space
2. No yellow crosshairs visible

**Expected behavior**
Yellow crosshairs should be visible on the image

**CaPTk Version**
1.6.0+

**Desktop (please complete the following information):**
 - OS: macOS
 - Version (including Build information, if any): 10.13+

**Comment by sarthakpati** [comment]
This is now working in the current build, right @PhucNgo1711?

**Comment by PhucNgo1711** [comment]
Yes 
I would like to have it properly tested out on Monday before closing this

**Comment by sarthakpati** [comment]
Can we check this on the lab machine?

**Comment by sarthakpati** [comment]
As an update, the keyboard shortcut is **Fn + Command + Space**.

**Comment by PhucNgo1711** [comment]
I'll test this on the lab machine later today. Building the latest fixes now

**Comment by sarthakpati** [comment]
This is done.
