### ISSUE TITLE
2D Images

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#427]
**Describe the bug**
CaPTk crashes when trying to load a 2D image. It says (on the terminal):

```
'Image Dimension mismatch. Return image is expected to be '3'D and doesn't match the image dimension read from the input file, which is '2'.
```

I think I can not share the images publicly due to HIPAA rules, but @ashishsingh18 has them. It's the "Breast_MRI images with seg" dataset.

**CaPTk Version**
1.6.2.Beta

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - 19

**Additional context**
CaPTk generally works only with 3D images. Some other images that are 2D can be loaded, such as one image @sarthakpati supplied to me in the past (called Case3.nii.gz). I'm assuming this happens because these images are actually 3D images with one dimension set to one.

_Related to this:_ I also tried to run GeodesicTraining on that working image. After the algorithm runs the ROI can't be loaded. That is because the default ROI is 3D, but the ROI GeodesicTraining is trying to load is 2D. 

What it says on the gui for the GeodesicTraining thing:

![mismatch2](https://user-images.githubusercontent.com/39439832/55622540-2e562d80-57a9-11e9-8a4e-a460cee1ff17.png)

What it says on the terminal for the GeodesicTraining thing:

```
The dimensions of the image_1 (/home/dimitris/.CaPTk/1.6.2.RC/tmp_7428777540027752032/GeodesicTrainingOutput/labels_res.nii.gz) and image_2 (/home/dimitris/.CaPTk/1.6.2.RC/tmp_7428777540027752032/temp_prev.nii.gz) doesn't match.
```

A potential fix could be that CaPTk checks the dimensions of the images and ROI(s) before loading them as itk::Image<\_,3>  (maybe try/catching if itk doesn't support this?). If they are 2D load them as itk::Image<\_,2> and convert them to itk::Image<_,3>.

**Comment by sarthakpati** [comment]
> CaPTk generally works only with 3D images

That is correct; the way we circumvent this is by changing a 2D image to a single slice 3D image (I have already given you the reference to this earlier). Check **fFeaturePanel.cpp** for an example how this happens. We should be able to replicate this easily in the code that is reading the mask.

**Comment by sarthakpati** [comment]
Check above reference commit out. I have added a "naive" check for this in the FE CLI part.

**Comment by dboun** [comment]
Just so we are at the same page, this isn't an issue with GeodesicTraining at all, GeodesicTraining works as intended. It knows that it's input will always be 3D and checks itself if it should convert it to 2D.

The problem is that CaPTk crashes when loading 2D images/ROIs. I am surprised this hasn't come up before.

I tried to compile your fork, but it failed to build FeatureExtraction (terminate called after throwing an instance of 'YAML::BadFile').

**Comment by sarthakpati** [comment]
> The problem is that CaPTk crashes when loading 2D images/ROIs.

I understand; this has already been committed to my fork. I will push later today.

> I tried to compile your fork, but it failed to build FeatureExtraction (terminate called after throwing an instance of 'YAML::BadFile').

That is weird; I didn't see any issue on Pipelines related to this.

**Comment by sarthakpati** [comment]
Fixed.
