### ISSUE TITLE
Linux Installer Artifact Bugs

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#441]
**Describe the bug**
Minor bugs found by running the installer generated by Azure Pipeline Artifact
1. The license agreement doesn't read Yes/No for some reasons. Trying 1/0 works.
2. Not all html documentations were packaged. (This is similar to the bug on macos)

**To Reproduce**
1. Download the installer artifact on Azure DevOps
2. Unzip and run the installer

**Expected behavior**
The installer should not have those bugs

**CaPTk Version**
1.7.0

**Desktop (please complete the following information):**
 - OS: Linux 
 - Version (including Build information, if any): Ubuntu 16.04

**Comment by PhucNgo1711** [comment]
Trying out a tweak. I think I found out why it was not packaged properly

**Comment by sarthakpati** [comment]
Fixed.
