### ISSUE TITLE
Unable to load second image - Win10 - CaPTk 1.6.2

### ISSUE THREAD

**Issue by pefs44** [CBICA/CaPTk#446]
After loading a first image, trying to load a second image that has been registered to the first, or is a renamed copy of the first image fails and gives the error message: 

"The physical dimensions of the previously loaded image and the current images are inconsistent; cannot load"

Log file when trying to load two copies of the same flair.nii.gz (flair and flairb) in the same folder shows: 
The origin in dimension[0] of the image_1 (D:/data/flair.nii.gz) and image_2 (C:/users/me/.CapTk/1.6.2/tmp_155588145617326387475847/temp_prev.nii.gz) doesn't match.

**To Reproduce**
1. Load - Images - choose fixed image from prior registration
2. Load - Images - choose output image from prior registration

**Expected behavior**
Load multiple registered images...

**CaPTk Version**
1.6.2

**Desktop (please complete the following information):
 - Win 10 Pro 64bit Build 17134

**Additional context**
does not happen with the rather small demo images in the CapTk demo folder (the smallest of my images is about 2.5MB, and most are about 40MB). 
does happen if I copy a pair of my images into the demo folder.

**Comment by sarthakpati** [comment]
Hi @pefs44, will it be possible for you to share the (anonymized) image(s) in question? Our sample data has pretty big images as well and they load up correctly if registered.

**Comment by pefs44** [comment]
This was prepared from a Philips 3T scanner as a reformat from a set of coronal images (I get the error with axial acquired images as well. I don't really believe it is a problem of image size, If I copy the image and save in a new name so they have the same coordinate matrices, the second I try to load gives the above.

The image should be clean, but if you spot anything let me know. 
Actually it is a reformat from a set of coronal images, but the same problem happens with the conventional axial images.

Uninstalled the dataset, installed 1.7.0nonrelease, - same problem.on Windows.

 [flax.nii.gz](https://github.com/CBICA/CaPTk/files/3119124/flax.nii.gz)

**Comment by pefs44** [comment]
sorry for closing - wrong button...

**Comment by sarthakpati** [comment]
To be clear: the second image is not closing for you?

**Comment by pefs44** [comment]
I can only load one image. the second gives the error message. 
the comment about "closing was because I accidentally closed the issue.

**Comment by sarthakpati** [comment]
Ah okay. I think this issue is no longer there in 1.7.0. But just to be safe, can you post the 2 (no PHI) images here?

**Comment by pefs44** [comment]
making a copy of the flax.nii image (flax2.nii) sent a few days ago replicates the problem for me.

**Comment by pefs44** [comment]
[flair.nii.gz](https://github.com/CBICA/CaPTk/files/3136214/flair.nii.gz)
[3dt1_2_flair.nii.gz](https://github.com/CBICA/CaPTk/files/3136215/3dt1_2_flair.nii.gz

just tried with the 1.7.0 beta on windows 10 and still can't load a second once a first has been loaded.

**Comment by sarthakpati** [comment]
This has been fixed on my fork. It will be reflected on the Beta build (due later this week). Thank you!

**Comment by pefs44** [comment]
Working for 1.7.0 beta on Win 10 from 10/05/19 build.
closing

**Comment by sarthakpati** [comment]
Thanks for the update.
