### ISSUE TITLE
dcm2nii places output in source folder not destination folder if destination isn't on home partition

### ISSUE THREAD

**Issue by pefs44** [CBICA/CaPTk#450]
**Describe the bug**
dcm2nii places output in source folder not destination folder

**To Reproduce**
run dcm2nii  with -o d:\test  where d is a partition separate from the partition where dcm2nii is located.

4. On completion, the popup says the images have been put in the destination folder
log shows:
C:/prog/CaPTk_Full/1.6.2/bin/dcm2nii.exe -a Y -r N -o D:/data/pclin_glio/nii/test D:/data/pclin_glio/dicom/depers/glio01_1a_20131205/3dt1 

**Expected behavior**
output nifti images end in destiantion folder

**CaPTk Version**
1.6.2

**Desktop (please complete the following information):**
Win 10 Pro build 17134

**Additional context**
trying from the commandline, I get the same error 
if I use a destination on c: partiiton, e.g. -o c:\user\me\Desktop the output isn't left in the source folder.
So, seems a dcm2nii problem rather than a capTk issue.
with dcm2niix (later version of dcm2nii) I don't get this issue.

**Comment by sarthakpati** [comment]
This has been fixed in 1.7.0. Once the testing finishes, we will make the new package available for download publicly. Reopen this issue if you continue to see issue.
