### ISSUE TITLE
Unable to start CaPTk after fresh install

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#459]
**Describe the bug**
Unable to start CaPTk after fresh install. Checking 'Run' checkbox and clicking on proceed doesn't start CaPTk. It complains about missing dll and shows the attached error message.

**To Reproduce**
1. Fresh install of CaPTk
2. Check 'Run' checkbox
3. Proceed

**Expected behavior**
CaPTk should start

**Screenshots**
![image](https://user-images.githubusercontent.com/43445206/57025279-b7278400-6c04-11e9-85a0-8ee70ed950fc.png)

**CaPTk Version**
1.7.0 Alpha

**Desktop (please complete the following information):**
 - OS: Windows 7 Enterprise SP1

**Comment by sarthakpati** [comment]
Good catch. Fix has been added in the CPack step [[ref](https://cmake.org/cmake/help/latest/module/InstallRequiredSystemLibraries.html)]
