### ISSUE TITLE
CaPTk disappeared while loading images

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#461]
**Describe the bug**
i selected 4 images from sample data altogether to load in captk:
RecurrenceEstimator\RecurrenceEstimator_1.6.1\one_subject_based\images\AABT_PreOp_t1_pp.nii
RecurrenceEstimator\RecurrenceEstimator_1.6.1\one_subject_based\images\AABT_PreOp_t1ce_pp.nii
RecurrenceEstimator\RecurrenceEstimator_1.6.1\one_subject_based\images\AABT_PreOp_t2_pp.nii
RecurrenceEstimator\RecurrenceEstimator_1.6.1\one_subject_based\images\AABT_PreOp_flair_pp.nii

CaPTk disappeared after i selected the images. 

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by sarthakpati** [comment]
Possibly related #477; after the new fixes, I am able to do this without issue.

**Comment by sarthakpati** [comment]
Fixed.
