### ISSUE TITLE
Deep learning segmentation is not working

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#462]
**Describe the bug**
When i loaded 4 images in CaPTk and ran deep learning segmentation with default parameters, the following pop-up appeared. 
![image](https://user-images.githubusercontent.com/38562504/57025745-0b7f3380-6c06-11e9-9fc8-ddc8773729ae.png)

**CaPTk Version**
1.7.0

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by sarthakpati** [comment]
Was this for skull stripping on tumor segmentation?

**Comment by PhucNgo1711** [comment]
@sarthakpati both tumor segmentation and skull stripping doesn't seem to be working properly. 

Siddhesh ran into the same issue, plus on the GUI, the browse button for selecting existing models doesn't work

![browse_doesnt_work](https://user-images.githubusercontent.com/14838084/57537011-67873d80-7313-11e9-8b6d-c9493e96954e.png)
![modelweightnotfound](https://user-images.githubusercontent.com/14838084/57537016-69510100-7313-11e9-85e4-ae99eeb7927b.png)

**Comment by sarthakpati** [comment]
Fixed in https://github.com/CBICA/CaPTk/pull/494
