### ISSUE TITLE
model is missing for deep learning skull stripping

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#463]
Describe the bug
When i loaded 4 images in CaPTk and ran deep learning skull stripping with default parameters, the following pop-up appeared.
image

CaPTk Version
1.7.0

![image](https://user-images.githubusercontent.com/38562504/57025911-7a5c8c80-6c06-11e9-8f68-28b004c56836.png)

Desktop (please complete the following information):

    OS: Windows

**Comment by sarthakpati** [comment]
@Geeks-Sid: FYI

**Comment by PhucNgo1711** [comment]
@sarthakpati duplicate of @462 ?

**Comment by sarthakpati** [comment]
Fixed in https://github.com/CBICA/CaPTk/pull/494
