### ISSUE TITLE
breastDensityEstimation(Single Image) is not running the way it si expected to do

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#464]
loaded on mammogram image from sample data
(case1.dcm)
Selected breastDensityEstimation(Single Image)  from the applications menu. Got the following error message. 

![image](https://user-images.githubusercontent.com/38562504/57026495-fdcaad80-6c07-11e9-9b69-11e33413e1ea.png)

Windows 7

**Comment by ashishsingh18** [comment]
Duplicate of #474
