### ISSUE TITLE
BreastSegmentation does not work when i load mammogram image

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#466]
loaded one mammogram image from sample data
(case1.dcm)
Selected BreastSegmentation from the applications menu. Got the following error message.

![image](https://user-images.githubusercontent.com/38562504/57026899-e04a1380-6c08-11e9-9fc1-bbf61a433419.png)

**Comment by sarthakpati** [comment]
Related to #467 and #468

**Comment by sarthakpati** [comment]
Duplicate of #467 and #468

**Comment by sarthakpati** [comment]
Tracking this issue on #464 and closing this
