### ISSUE TITLE
TextureFeaturesPipeline is not working with sample data

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#467]
loaded one mammogram and selected 'TextureFeaturesPipeline' from applications menu.
Got the following message.

![image](https://user-images.githubusercontent.com/38562504/57026925-ef30c600-6c08-11e9-9b84-7d120acd3e94.png)

Windows 7
CaPTk 1.7.0

**Comment by sarthakpati** [comment]
Tracking this on #464 and closing this.
