### ISSUE TITLE
Incorrect modality error message

### ISSUE THREAD

**Issue by jminock** [CBICA/CaPTk#469]
**Is your feature request related to a problem? Please describe.**
When testing for WhiteStripe Normalization, an error message comes up if an incorrect modality is used, but the error message does not specify the source of the error.
![WhiteStripeNorm_error](https://user-images.githubusercontent.com/20047333/57027104-79792a00-6c09-11e9-8448-1e4032442239.PNG)

**Describe the solution you'd like**
An error message that points out where the application goes wrong, instead of a general help message.  In this case, a message highlighting the modality error would be much more helpful.

**Describe alternatives you've considered**
The current feature is that once the error message is closed, the documentation is pulled up for that specific application.  It was helpful.  An alternative could be for the error message to say to check over the manual.

**Additional context**

**Comment by sarthakpati** [comment]
I am curious how we can detect the original modality if the user changes it to T1 or T2 (for WhiteStripe).

**Comment by sarthakpati** [comment]
If **Flair** image is loaded, the "input" modality for WhiteStripe needs to be **T2**. This is confusing and needs to be clarified in the documentation.

**Comment by sarthakpati** [comment]
This is already there: https://github.com/CBICA/CaPTk/blob/master/3_HowToGuides.txt#L486

Closing.
