### ISSUE TITLE
ComparisonMode did not work with 4 images

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#470]
i loaded 4 images in CaPTk and selected 'ComparisonMode' from the top right corner, CaPTk crashed.

**Comment by ashishsingh18** [comment]
I am not able to reproduce this. It works on 2 different machines that we tried on.

**Comment by ashishsingh18** [comment]
Tried it on Mac OS and still can't reproduce the issue.

**Comment by ashishsingh18** [comment]
Closing the issue. If we see it again, we will reopen it.
