### ISSUE TITLE
ROI can not be loaded on image

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#471]
Loaded a co-registered image and ROI, and got the following error message. 

image = RecurrenceEstimator\RecurrenceEstimator_1.6.1\training_samples\AAAB\CONVENTIONAL\AAAB_PreOp_flair_pp.nii
segmentation= RecurrenceEstimator\RecurrenceEstimator_1.6.1\training_samples\AAAB\SEGMENTATION\AAAB_label_map.nii

![image](https://user-images.githubusercontent.com/38562504/57027878-96aef800-6c0b-11e9-903c-b7011a3a530e.png)

Windows 7
CaPTk 1.7.0 Alpha

**Comment by sarthakpati** [comment]
Fixed.
