### ISSUE TITLE
Feature Extraction Resampling

### ISSUE THREAD

**Issue by jminock** [CBICA/CaPTk#472]
When running Feature Extraction, a warning message appears to reduce resampling rate for accuracy.  There is no documentation for where the resampling rate is.

I found it through the "Advanced ..." button in the Customization area for Feature Extraction. Then, I clicked the drop-down for "Generic" which has the resampling rate.

The warning message can include "Customization -> Advanced ... -> Generic -> Resampling Rate"

**Comment by sarthakpati** [comment]
Addressed.
