### ISSUE TITLE
cannot download sample data for LIBRA

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#473]
**Describe the bug**
Cannot download sample data for LIBRA. It shows a popup message asking to login to ftp server. Please see the attached screenshot.

**To Reproduce**
1. Click on Help->Sample Data->Libra

**Expected behavior**
Data download should start

**Screenshots**
![image](https://user-images.githubusercontent.com/43445206/57028946-6fa5f580-6c0e-11e9-95f2-35663355c32e.png)

**CaPTk Version** - 1.7.0 Alpha

**Desktop (please complete the following information):**
 - OS:Windows 7 SP 1

**Comment by sarthakpati** [comment]
This might be a momentary issue on NITRC servers. Seems to have been fixed now. Let's reopen if it persists and we can contact the NITRC admins.
