### ISSUE TITLE
Libra Application Breast Density Estimator(batchmode) doesnt work

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#475]
**Describe the bug**
Libra Application Breast Density Estimator(batchmode) doesnt work. It shows a popup message stating "cannot find binlibra.bat". Please see attached screenshot.

**To Reproduce**
1. Load single dicom image from Libra sample data.
2. Click on Application->Breast Density Estimator(batchmode) 

**Expected behavior**
Appliation should run.

**Screenshots**
![image](https://user-images.githubusercontent.com/43445206/57029699-7e8da780-6c10-11e9-9e40-b280fd47ab76.png)

**CaPTk Version**
1.7.0. Alpha

**Desktop (please complete the following information):**
 - OS: Windows 7 SP1

**Comment by sarthakpati** [comment]
Fixed.
