### ISSUE TITLE
Comparison mode doesnt work for Libra Images 

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#476]
Comparison mode doesnt work for Libra Images. The view doesn't change and stays the same and there is no message informing the user.

**To Reproduce**
1. Load 3 Libra images.
2. Click on comparison mode.

**Expected behavior**
A message should be shown telling the user that MG images won't work with comparison mode.

**CaPTk Version**
1.7.0 Alpha

**Desktop (please complete the following information):**
 - OS: Windows 7 SP1

**Comment by sarthakpati** [comment]
Fixed in latest PR: https://github.com/CBICA/CaPTk/pull/491
