### ISSUE TITLE
cannot load all SBRT sample datasets

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#477]
**Describe the bug**
Cannot load all SBRT sample datasets. For the 2nd dataset it shows a message stating "physical dimensions are inconsistent". Please see attached screenshot.

**To Reproduce**
1. Load one SBRT data.
2. Load second SBRT data->it shows a popup message here

**Expected behavior**
The application should load the datasets.

**Screenshots**
![image](https://user-images.githubusercontent.com/43445206/57030243-18a21f80-6c12-11e9-833a-79a44ceb9928.png)

**CaPTk Version**
1.7.0 Alpha

**Desktop (please complete the following information):**
 - OS: windows 7 SP1

**Comment by ashishsingh18** [comment]
Related to #471

**Comment by sarthakpati** [comment]
Fixed.
