### ISSUE TITLE
Error with cwl generation for Preprocessing

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#478]
**Describe the bug**
All cwl files are generated except Preprocessing. This happens in the cluster

**To Reproduce**
1. Build CaPTk normally

**Expected behavior**
It should generate Preprocessing.cwl

**Screenshots**
![Capture](https://user-images.githubusercontent.com/14838084/57030481-cad9e700-6c12-11e9-83ce-f1f5da56307c.PNG)

**CaPTk Version**
1.7.0

**Desktop (please complete the following information):**
 - OS: Linux
 - Version (including Build information, if any): Cluster

**Comment by PhucNgo1711** [comment]
adding the `cluster` label to this
the error is still present when building captk on the cluster

**Comment by sarthakpati** [comment]
Is this happening only for Preprocessing or for other executables as well?

**Comment by sarthakpati** [comment]
Hey @jminock, can you see if you are seeing this on your VM? We might have to use that to build our Linux package since the Ubuntu on Azure is very new and older systems aren't able to run the installer generated by it.

**Comment by PhucNgo1711** [comment]
Just for Preprocessing
The builds on Azure and my Linux VM are fine

**Comment by jminock** [comment]
The Preprocessing executable and cwl are not in CaPTk/bin/, but are in CaPTk/bin/install/appdir/usr/bin/
This is on my Ubuntu 18.10 VM

**Comment by sarthakpati** [comment]
I have been building the installer on the cluster to ensure we are able to use the package on older Linux distros. I am not able to replicate this. Closing till we are able to find a way to replicate this in a meaningful way.
