### ISSUE TITLE
Superbuild does not build with CMake 3.14

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#483]
**Describe the bug**
Currently the minimum `CMake `version is `3.7`. However, everything works up until `3.13`, because the superbuild throws an error while downloading `VTK`, `Eigen`, `OpenMP`, and `ITK `if `Cmake 3.14` is used

**To Reproduce**
1. Make sure the dependencies are not picked up so the superbuild is triggered
2. `CMake `version is >= `3.14`
3. Build the superbuild
4. It times out when trying to download and extract `VTK`, `Eigen`, `OpenMP`, and `ITK `

**Expected behavior**
The build works.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/14838084/57247348-8d5bcc00-700d-11e9-968e-73af644a3f90.PNG)

**CaPTk Version**
1.7.0.Beta

**Desktop (please complete the following information):**
 - OS: Linux
 - Version (including Build information, if any): Ubuntu 16.04

**Comment by sarthakpati** [comment]
Check this response: https://stackoverflow.com/a/33512778

**Comment by MarkBergman-cbica** [comment]
The stackoverflow response is from 2015.

Yes, more servers are requiring https, which is why CMake that uses CURL without SSL will fail.

Which doesn't explain why 3.7 -- 3.13 worked.

@PhucNgo1711 -- did you self-compile CMake 3.7 -- 3.13? Did you install 3.14 via the same mechanism (compiled or from brew) as the older versions?

Personally, I'd blame Archimedes for the failure of version 3.14.159.27

**Comment by PhucNgo1711** [comment]
I haven't tried following the solution on stackoverflow yet. I was trying to get my PR to build so I didn't want to mess with it.

But the reason I caught this was because doing `sudo apt-get install cmake` on my `Ubuntu 16.04 VM` only installs `cmake 3.5` (reasons can be found [here](https://askubuntu.com/a/865294)), so I went and downloaded the latest Cmake version `3.14.3` on https://cmake.org/download/ 

In terms of what version of cmake I have tried so far, I've tested 3.11, 3.13, and 3.13. 
3.11 is installed by doing sudo apt-get install cmake on Azure, which also has a Ubuntu 16.04 VM but apparently it as a newer version of cmake
3.12 is on mac
3.13 is installed via `pip3` on my Ubuntu VM

**Comment by sarthakpati** [comment]
If you notice the superbuild command, the GIT protocol-related things are commented out. I am guessing switching to that instead of the zip URL might work. But that creates an issue for firewalls where the git protocol is blocked.

**Comment by ashishsingh18** [comment]
cmake 3.14 has been giving me issues as well on windows. Reverting to 3.12 works

**Comment by sarthakpati** [comment]
> cmake 3.14 has been giving me issues as well on windows. Reverting to 3.12 works

This is regards to the generator not working as expected.

**Comment by PhucNgo1711** [comment]
CMake 3.15 works fine so I guess as long as we don't use 3.14 then there shouldn't be an issue.
