### ISSUE TITLE
Deep Learning based Tumor Segmentation does not work

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#497]
**Describe the bug**
The brain tumor segmentation application using deep learning does not work.

**To Reproduce**
1. Load co-registered brain tumor subject (multi-modal with 4 modalities)
2. Click on **Applications > Brain Tumor Segmentation**
3. The python prompt starts up but exits with an error

**Expected behavior**
The segmentation should work.

**CaPTk Version**
1.7.0.Beta

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version: 7 & 10

**Comment by sarthakpati** [comment]
After conferring with Kostas (the algorithm developer behind DeepMedic), it was determined that the model getting shipped was an older version. This needed an update (will be present by default for the RC release). For users who have come across this thread, please use the file attached in this message and replace the contents in 
- Linux & Windows: **${CaPTk_Install_Dir}/data/saved_models/brainTumorSegmentation**
- macOS: **${CaPTk_Install_Dir}.app/Contents/Resources/data/saved_models/brainTumorSegmentation**.

[brainTumorSegmentation.zip](https://github.com/CBICA/CaPTk/files/3174253/brainTumorSegmentation.zip)

**Comment by MarkBergman-cbica** [comment]
> After conferring with Kostas (the algorithm developer behind DeepMedic), it was determined that the model getting shipped was an older version. This needed an update (will be present by default for the RC release). For users who have come across this thread, please use the file attached in this message and replace the contents in
> 

Independent of DeepMedic, this is an example of the need for metadata (version number, date, etc) in every data file (model, CSV with pre-set features, etc) we distribute **and** a mechanism for each application to read and verify that meta-data (ie., model version 1.7 works with CaPTk 1.7--1.9). Bonus points for making the metadata human readable, from a literal sense (ie., a text-based comment, even in a binary file) and conceptual (ie., verbose metadata like "Model file foobar generated on 13 May 2019 has version 1.7a").

In the case of binary files, CaPTk should provide a "--about" flag (and GUI equivalent) to display metadata in models, binary masks, etc.
