### ISSUE TITLE
SBRT Analysis error

### ISSUE THREAD

**Issue by jminock** [CBICA/CaPTk#509]
**Describe the bug**
No error message is given in terminal. Only a pop-up that says vector is out of range.  See screenshot for more info

**To Reproduce**
Open PowerShell
```
C:\CaPTkBuild\Debug\SBRT_Analysis.exe -i C:\CaPTkBuild\testing\TestData\sbrt\AAAC0_flair_pp_shrunk.nii.gz -m C:\CaPTkBuild\testing\TestData\sbrt\AAAC0_flair_pp_shrunk_testTumor.nii.gz -l 1
```
same error even if output directory is declared

**Expected behavior**
SBRT_Analysis is to generate a message saying it finished successfully

**Screenshots**
![SBRT_Analysis_bug](https://user-images.githubusercontent.com/20047333/57792537-38a30a00-770d-11e9-8b63-c13f6d3217d9.PNG)

**CaPTk Version**
1.7.0.Beta

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by jminock** [comment]
The same error arises if an output directory is declared too

**Comment by ashishsingh18** [comment]
In this case the test was being done with MR data while SBRT handles only CT and PET datasets. I have added a check for modality type. 
@jminock : Can you please test again after taking the updates?

**Comment by sarthakpati** [comment]
These checks work. Unfortunately, we cannot do this for CLI for NIfTI files, so closing the ticket.
