### ISSUE TITLE
MolecularSubtypePredictor Command Line

### ISSUE THREAD

**Issue by jminock** [CBICA/CaPTk#510]
**Describe the bug**
MolecularSubtypePredictor is unable to read in input data via the command line. As shown in screenshots, 0 subjects were read in in either paths given for the executable. Other screenshot shows data exists and is in format aligned with HowTo guide.

**To Reproduce**
Open Powershell
```
C:\CaPTkBuild\Debug\MolecularSubtypePredictor.exe -t 0 -i C:\CaPTkBuild\testing\TestData\molsub\test_samples\AAUA -o C:\CaPTkBuild\testing\TestData\outputs\molsub\
```
**edit** fixed typo
**Expected behavior**
Output is generated and 1 subject is listed with required input instead of 0

**Screenshots**
![Molec_CL](https://user-images.githubusercontent.com/20047333/57794231-2c20b080-7711-11e9-9b66-5e8266cfee3c.PNG)
![MSP_data](https://user-images.githubusercontent.com/20047333/57794236-2fb43780-7711-11e9-941a-78aa82eb0276.PNG)

**CaPTk Version**
1.7.0.Beta

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by sarthakpati** [comment]
One potential issue:

> C:\CaPTkBuild\testing\TestData\molsub\test_samples/AAUA

Should probably be

> C:\CaPTkBuild\testing\TestData\molsub\test_samples\AAUA

Or (preferably),

> C:/CaPTkBuild/testing/TestData/molsub/test_samples/AAUA

**Comment by jminock** [comment]
I double checked in PowerShell, same issue with consistent "\" and consistent "/"
![Molec_CL_doublecheck](https://user-images.githubusercontent.com/20047333/57802734-a1e24780-7724-11e9-96f2-ffa0425c0fcf.PNG)
That inconsistency is just a typo in this report, not what I tested, will fix

**Comment by saimarathore** [comment]
we need to specify the path of the training directory instead of training subjects. the command should be:

C:\CaPTkBuild\Debug\MolecularSubtypePredictor.exe -t 0 -i C:\CaPTkBuild\testing\TestData\molsub\test_samples -o C:\CaPTkBuild\testing\TestData\outputs\molsub\
