### ISSUE TITLE
SBRT Lung Assertion Failed

### ISSUE THREAD

**Issue by jminock** [CBICA/CaPTk#513]
**Describe the bug**
A pop-up error saying abort() was called as shown in screenshot. Other screenshot shows terminal output
'''
Assertion failed: i<size(), file C:\LibsCaPTk\ITKsource\Modules\ThirdParty\VNL\src\vxl\core\vnl/vnl_vector.h, line 178
'''
**To Reproduce**
Open Powershell
```
C:\CaPTkBuild\Debug\SBRT_LungField.exe -p C:\CaPTkBuild\testing\TestData\sbrt\AAAC0_flair_pp_shrunk.nii.gz -c C:\CaPTkBuild\testing\TestData\sbrt\AAAC0_flair_pp_shrunk.nii.gz -o C:\CaPTkBuild\testing\TestData\outputs\sbrt\lung
```

**Expected behavior**
Program completes without aborting and without generating any errors

**Screenshots**
![SBRT_Lung_bug](https://user-images.githubusercontent.com/20047333/57806168-97c44700-772c-11e9-88ff-efe48b5171bd.PNG)
![SBRT_Lung_output](https://user-images.githubusercontent.com/20047333/57806173-998e0a80-772c-11e9-91d5-37d7a00d9c4b.PNG)

**CaPTk Version**
1.7.0.Beta

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by ashishsingh18** [comment]
In this case the test was being done with MR data while SBRT handles only CT and PET datasets. I have added a check for modality type. 
@jminock : Can you please test again after taking an update?

**Comment by sarthakpati** [comment]
These checks work. Unfortunately, we cannot do this for CLI for NIfTI files, so closing the ticket.
