### ISSUE TITLE
QT GLX issue on Linux

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#518]
**Describe the bug**
Running CaPTk on Linux throws a bunch of qt.glx errors, but doesn't crash the application.
`qt.glx: qglx_findConfig: Failed to finding matching FBConfig
`

**To Reproduce**
1. Run CaPTk through the command line `./{path_to_captk}/captk`
2. See error

**Expected behavior**
There should be no error 

**Screenshots**
<img width="1376" alt="Screen Shot 2019-05-20 at 9 20 26 AM" src="https://user-images.githubusercontent.com/14838084/58024593-88ece400-7ae0-11e9-893b-5a19d7ea7824.png">

**CaPTk Version**
1.7.0*

**Desktop (please complete the following information):**
 - OS: Linux
 - Version (including Build information, if any): Ubuntu 16.04 and 18.04

**Comment by sarthakpati** [comment]
I think this is worth a try: https://stackoverflow.com/a/55235823/1228757

**Comment by PhucNgo1711** [comment]
@sarthakpati actually this has been there ever since 1.6.2 Alpha #365

**Comment by sarthakpati** [comment]
> @sarthakpati actually this has been there ever since 1.6.2 Alpha #365

Got it. I wonder if this is related to #519 in a way.

**Comment by sarthakpati** [comment]
Closing this to continue conversation in #365
