### ISSUE TITLE
Cannot load image on Linux

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#519]
**Describe the bug**
Loading any images to CaPTk crashes the application with unclear error messages.
```
Received signal 11 SEGV_MAPERR 000000000000
#0 0x7fa3d4c67a4f <unknown>
#1 0x7fa3d4c67e4b <unknown>
#2 0x7fa3d4c684ce <unknown>
#3 0x7fa3d0a88390 <unknown>
  r8: 0000000000000003  r9: 4357786574726576 r10: 0000000006219700 r11: 00007fa3cf146f90
 r12: 0000000000001184 r13: 000000000b0411b0 r14: 000000000b195e00 r15: 00000000061fc1a0
  di: 0000000000000001  si: 000000000b19f974  bp: 00007fff887f7ea0  bx: 0000000000000018
  dx: 000000000b19f974  ax: 0000000000000000  cx: 0000000000000000  sp: 00007fff887f7e78
  ip: 0000000000000000 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000014
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

**To Reproduce**
1. Open CaPTk
2. Load an image (anything)
3. See error

**Expected behavior**
Loading images should not crash CaPTk

**CaPTk Version**
1.7.0_RC

**Desktop (please complete the following information):**
 - OS: Linux
 - Version (including Build information, if any): Ubuntu 16.04

**Comment by sarthakpati** [comment]
Cannot replicate on Windows 7 or 10. @PhucNgo1711 what is the status for macOS?

**Comment by PhucNgo1711** [comment]
macOS is good @sarthakpati

**Comment by sarthakpati** [comment]
Reproducible on all 1.7.0 builds.

**Comment by sarthakpati** [comment]
To give more context, here is the workflow:

- CaPTk UI is coming up and WebEngine is working (the about page and Usage is coming up fine)
- When a image is loaded, the UI crashes

**Comment by sarthakpati** [comment]
Running CLI applications is fine, which means the IO portion is working fine on Linux.

**Comment by sarthakpati** [comment]
This is not reproducible on Ubuntu 18.04 (however, the icon is not present #520).

**Comment by sarthakpati** [comment]
Update: @sungminhacbica was able to load images after removing his graphics card.

**Comment by sarthakpati** [comment]
In the debugging file `${user_home_directory}/.CaPTk/vtk_errors.txt`:

```
ERROR: In /home/vsts/work/1/s/bin/VTK-source/Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx, line 785
vtkGenericOpenGLRenderWindow (0x760ca70): GLEW could not be initialized.

ERROR: In /home/vsts/work/1/s/bin/VTK-source/Rendering/OpenGL2/vtkTextureObject.cxx, line 1537
vtkTextureObject (0x9251400): Failed to determine texture parameters. IF=0 F=6408 T=5121

ERROR: In /home/vsts/work/1/s/bin/VTK-source/Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx, line 1875
vtkGenericOpenGLRenderWindow (0x760ca70): Hardware does not support the number of textures defined.
```

**Comment by ashishsingh18** [comment]
We need to debug this. People have encountered similar issues. Please see the url:
http://vtk.1045678.n5.nabble.com/AppImage-packaging-GLEW-could-not-be-initialized-td5739194.html

**Comment by sarthakpati** [comment]
Another report from a machine where this failed:

```
ERROR: In /home/vsts/work/1/s/bin/VTK-source/Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx, line 797
vtkGenericOpenGLRenderWindow (0x701ad10): GL version 2.1 with the gpu_shader4 extension is not supported by your graphics driver but is required for the new OpenGL rendering backend. Please update your OpenGL driver. If you are using Mesa please make sure you have version 10.6.5 or later and make sure your driver in Mesa supports OpenGL 3.2.

ERROR: In /home/vsts/work/1/s/bin/VTK-source/Rendering/OpenGL2/vtkTextureObject.cxx, line 1537
vtkTextureObject (0x9335880): Failed to determine texture parameters. IF=0 F=6408 T=5121
```

**Comment by ashishsingh18** [comment]
This points to unsupported OpenGL version. We need to update our OpenGL version check for Linux.

**Comment by sarthakpati** [comment]
Advanced checking has been added. Windows check needs to be separate because the new code isn't able to check dedicated GPU. Currently, @ashishsingh18 is testing a possible usage of [vtkGenericOpenGLRenderWindow::SupportsOpenGL()](https://vtk.org/doc/nightly/html/classvtkGenericOpenGLRenderWindow.html#a799a39d8df3d022de88f8ad226146c9c) to do this check in a cleaner manner.

**Comment by sarthakpati** [comment]
Code is working as expected (results from my WSL which has OpenGL 3.0):

```
Checking for compatible OpenGL - this will happen only once.
WARNING: Application calling GLX 1.3 function "glXCreatePbuffer" when GLX 1.3 is not supported!  This is an application bug!
A working 3.2 version of OpenGL was not found in your hardware/software combination; consequently, CaPTk's GUI will not work; all CLIs will work as expected.

        OpenGL Version : 3.0 Mesa 18.0.5
        OpenGL Renderer: llvmpipe (LLVM 6.0, 256 bits)
        OpenGL Vendor  : VMware, Inc.
```

**Comment by ashishsingh18** [comment]
vtkrenderwindow isn't reporting the right values of opengl version. We need to test it further to see if there are certain pipeline calls that need to be made for it to work.
