### ISSUE TITLE
CaPTk icon not loaded on Linux

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#520]
**Describe the bug**
The application does not have a working icon

**To Reproduce**
1. Run CaPTk
2. The icon is a question mark

**Expected behavior**
There should be a "brain" icon

**Screenshots**
<img width="1440" alt="Screen Shot 2019-05-20 at 9 44 09 AM" src="https://user-images.githubusercontent.com/14838084/58026232-fe0de880-7ae3-11e9-9e2b-137163792191.png">

**CaPTk Version**
1.7.0*

**Desktop (please complete the following information):**
 - OS: Linux
 - Version (including Build information, if any): Ubuntu 16.04 and 18.04

**Comment by sarthakpati** [comment]
Possible solution is how AppImage uses the desktop file itself [[ref](https://github.com/AppImage/AppImageKit/search?q=appimagetool.desktop&unscoped_q=appimagetool.desktop)].

**Comment by sarthakpati** [comment]
This is working fine for native Linux Installation (tried on 2 machines running on 16.04+).
