### ISSUE TITLE
CaPTk Docker Build failure

### ISSUE THREAD

**Issue by jminock** [CBICA/CaPTk#521]
**Describe the bug**
Docker build fails with warnings of lib*.so files are needed by qt/5.12.1/lib/libQt5WebEngineCore.so.5.12.1 but these files are not found.  Recipes for target 'CMakeFiles/CaPTk.dir/all' fail.  (as shown in screenshots)

**To Reproduce**
Use azure-pipeline.yml and Dockerfile from jminock/CaPTk
Have Azure Pipeline set up
Include DockerBuild job from azure-pipeline.yml from jminock/CaPTk (as seen in screenshot)
Run build
See error under End-to-end Docker build & package 'CmdLine' after ~ 2 hours of running

**Notes:**
End-to-end Linux (Xenial) Build succeeds on Azure
Dockerfile clones from CBICA/CaPTk
when checking against VM with successful CaPTk installation, lib*.so files exist in CaPTk/bin/install/appdir/usr/lib/

**Expected behavior**
Docker build succeeds

**Screenshots**
![azure_docker_job](https://user-images.githubusercontent.com/20047333/58132469-61d10800-7bef-11e9-8d05-e67c857fd7ec.PNG)
![Dockerfile_error1](https://user-images.githubusercontent.com/20047333/58132475-6695bc00-7bef-11e9-8bdf-c826a34629e3.PNG)
![Dockerfile_error2](https://user-images.githubusercontent.com/20047333/58132477-685f7f80-7bef-11e9-833c-1b8b4d1ece71.PNG)

**CaPTk Version**
1.7.0

**Desktop (please complete the following information):**
 - OS: Windows 7

Can a path be added after CaPTk Superbuild but before CaPTk build?

**Comment by sarthakpati** [comment]
Make sure the docker is built on Ubuntu 16.04 and it will work. This is a well documented issue when using pre built Qt binaries on 14.04.
