### ISSUE TITLE
Brain Tumor Segmentation

### ISSUE THREAD

**Issue by jacobantonyalappatt** [CBICA/CaPTk#529]
**Describe the bug**
After providing the necessary image contrasts (T1, T1ce, FLAIR, T2), it throws this error message "DeepMedic returned with exit code !=0".
Previously, I have used the DeepMedic executable to segment the tumor in this particular patient, using these 4 co-registered images. As these images had worked before, and I have the segmented tumor image from DeepMedic, I wanted to compare CaPTk's output, to see if there are differences being introduced.  

**To Reproduce**
1. I provided 4 co-registered images. 
2. They succesfully overlaid in the viewer, and I selected the appropriate modality for each of them.
3. I selected Deep Learning > Brain Tumor Segmentation
4. Allowed the machine to select the existing model directory, and I specified a new output directory.

**Behavior**
It is surprising that an error was thrown by CaPTk after I provided the same 4 images. Error report also fails to point the user in a direction that would help them solve the issue, if it is with respect to the images. 

**CaPTk Version**
The installed version is 1.7.0,  but in the Help>About section, all I can see is a blank black background. There is no visible content in the 'About CaPTk' popup box.

**Desktop:**
 - OS: Windows 7 Enterprise

**Comment by sarthakpati** [comment]
I believe this issue has been resolved in the builds that originated in the previous week. You can try the latest here (accessible only via the UPHS network): 
`S:/CBICA/CaPTk/installers/CaPTk_1.7.0_nonRelease_Installer.exe`

Closing the issue for now. Please reopen if it persists.

**Comment by dboun** [comment]
Are we sure this is resolved? Because last time I tried the Deep Learning Brain Tumor Segmentation it didn't work, and also someone at RSNA mentioned the same thing

**Comment by sarthakpati** [comment]
I am not able to replicate this on 1.7.2 or any of the development builds. I feel that the person who mentioned this at RSNA has probably something funky going on with the data. Will need more context regarding the data being used. Once I get that, I'll open up a new issue.
