### ISSUE TITLE
All applications should be made available as a "download" and not bundled in by default

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#530]
**Is your feature request related to a problem? Please describe.**
The current CaPTk installers (for all platforms) is huge (ranging from **~400MB** for macOS to **~1GB** for Linux). This needs to be addressed.

**Describe the solution you'd like**
Since it isn't necessary that _every_ users requires access to _every_ application, make all of them available in the menu but have them download the platform-specific executable.

**Describe alternatives you've considered**
Separate builds for Brain, Breast and Lung: although this would improve the situation for Lung, it would still leave a **lot** of applications on the plate for Brain.

**Comment by ashishsingh18** [comment]
Duplicate of #883
