### ISSUE TITLE
ITK-SNAP not working on windows and linux

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#535]
**Describe the bug**
ITK-SNAP does not run from CaPTK. There is no error message, and CaPTk doesn't crash.
ITK-SNAP is launched by running the executable with the `-w` flag in [fMainWindow.cpp](https://github.com/CBICA/CaPTk/blob/9a9cb89fc3e635f0da1618b8a285953205aa52d5/src/view/gui/fMainWindow.cpp#L6495)

**To Reproduce**
1. Open CaPTk
2. Load an image
3. Draw something
4. Go to Applications -> ITK-SNAP
5. At the bottom it says 

> Mask saved from ITK-SNAP loaded
6. ITK-SNAP is not launched, but there's no error message.

**Expected behavior**
ITK-SNAP should launch, or there should at least be an error message.

**CaPTk Version**
>1.6.2

**Desktop (please complete the following information):**
 - OS: Windows + Linux
 - Version (including Build information, if any): Windows 7 and Ubuntu 16.04

**Comment by sarthakpati** [comment]
This is working. But, we have a new, unrelated issue #549
