### ISSUE TITLE
Cannot find file Survival_HMFeatures_Configuration.csv

### ISSUE THREAD

**Issue by jminock** [CBICA/CaPTk#536]
**Describe the bug**
Survival Predictor is unable to run due to a missing file and directory in Windows installation of CaPTk 1.7.0

File and directory exists in local superbuild of CaPTk

2019:05:30,14:37:57;CaPTk;MinockJ;Cannot find the file 'Survival_HMFeatures_Configuration.csv' in the ../data/survival directory. Error code : e:\libscaptk\itk-source\modules\io\csv\include\itkcsvarray2dfilereader.hxx:66:
itk::ERROR: CSVArray2DFileReader(000000000DA222C0): The file C:/CaPTk_Full/1.7.0/bin/../data//survival/Survival_HMFeatures_Configuration.csv cannot be opened for reading!
Reason: No such file or directory

**To Reproduce**
1. Open CaPTk on Windows 7
2. Open Glioblastoma Survival Predictor Index under Applications tab
3. Select "Train a new survival prediction model" and select samples from survival sample data
4. Select an output directory
5. Confirm
6. See error in .CaPTk/1.7.0/'current date'.txt

**Expected behavior**
Survival predictor runs without issue

**Screenshots**
![Survival_HMFeatures](https://user-images.githubusercontent.com/20047333/58656953-3cc54f00-82eb-11e9-8200-0c14bab456a6.PNG)
![survival_data_directory](https://user-images.githubusercontent.com/20047333/58657356-18b63d80-82ec-11e9-8b59-c5c5f7e0bf1b.PNG)

**CaPTk Version**
1.7.0 RC Release

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by sarthakpati** [comment]
This was an issue with the installer. Fixed.
