### ISSUE TITLE
cannot load sample data for EGFRvIII Surrogate Index(PHI Estimator)

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#539]
**Describe the bug**
CaPTk is unable to load sample data for EGFRvIII Surrogate Index(PHI Estimator)

**To Reproduce**
1. Download Sample data for EGFRvIIISurrogateIndex
2. Drag and drop the data onto CaPTk.
3. It comes up with a pop-up message stating extensions for following files are not supported but doesn't state which files. Please see the attached screenshot.

**Expected behavior**
Data should be loaded and unsupported files should also be specified.

**Screenshots**
![image](https://user-images.githubusercontent.com/43445206/58962558-80034000-8779-11e9-8627-660319e30d88.png)

CaPTk Version: 1.7.0

**Desktop (please complete the following information):**
 - OS: Win 7 x64

**Comment by jminock** [comment]
When replicating the error but loading the files one at a time, this is the error
"The physical dimensions of the previously loaded image and the current image are inconsistent; cannot load"
![EGFR_sample_sata](https://user-images.githubusercontent.com/20047333/58971248-083d1180-8789-11e9-984c-7c49cab523bb.PNG)

Same version of CaPTk
Same OS

**Comment by sarthakpati** [comment]
This is related to how the image check is happening for 4D images.

**Comment by sarthakpati** [comment]
Fixed.
