### ISSUE TITLE
Command line load sample data Unit Test

### ISSUE THREAD

**Issue by jminock** [CBICA/CaPTk#540]
**Is your feature request related to a problem? Please describe.**
See issue #539 
Some sample data files failed to load when other files were present

**Describe the solution you'd like**
Have a unit test that tests loading images from sample data sets

**Additional context**
![EGFR_sample_sata](https://user-images.githubusercontent.com/20047333/58971158-d166fb80-8788-11e9-9ba6-8799079427ea.PNG)

**Comment by sarthakpati** [comment]
Duplicate of #539; closing this and continuing discussion there.
