### ISSUE TITLE
Better support for High DPI screens

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#542]
**Is your feature request related to a problem? Please describe.**
When trying to open a file (we are using Qt's native file browser for all), the icons appear very blurry (see attached screenshot).

**Describe the solution you'd like**
Better high DPI icons for the file browser.

**Describe alternatives you've considered**
N.A.

**Additional context**
Blurred icons:

![image](https://user-images.githubusercontent.com/11719673/59108529-15810a00-8909-11e9-82da-a64036e95aae.png)

Display settings (all default):

![image](https://user-images.githubusercontent.com/11719673/59108549-2762ad00-8909-11e9-975c-0c44207e80b7.png)

**Comment by ashishsingh18** [comment]
Tried this as an isolated test. Test result indicated that the order in which Qt's high DPI flags were set and the instantiation of qapp, matters. We will need to test this further with CaPTk on all platforms.

**Comment by sarthakpati** [comment]
The commit https://github.com/sarthakpati/CaPTk/commit/624a81cbbc70e6523bc383397585483acaa031d6 seems to have fixed this, at least on Windows.

**Comment by sarthakpati** [comment]
> The commit [sarthakpati@624a81c](https://github.com/sarthakpati/CaPTk/commit/624a81cbbc70e6523bc383397585483acaa031d6) seems to have fixed this, at least on Windows.

This has made Windows and Linux icons much better. Not so much for macOS, though.

**Comment by sarthakpati** [comment]
@PhucNgo1711, what was the setting that was used for the macOS packaging that enabled us to view the application properly but at the cost of resolution? I seem to remember running into this issue before.

**Comment by PhucNgo1711** [comment]
@sarthakpati do you mean the low resolution setting on mac?

**Comment by sarthakpati** [comment]
Yes, exactly. Do you remember where this was added and what its exact purpose was?

**Comment by PhucNgo1711** [comment]
So it was more like a built-in thing on mac that let you manually check/uncheck a box to enable/disable this. Before the ISNR release last year, CaPTk running in high resolution would mess up the rendering of the GUI (large buttons, etc.) However, a fix was released back in January I believe and CaPTk on macOS has always been running in low-resolution mode ever since. You can't even make it run in high resolution anymore.

**Comment by sarthakpati** [comment]
What was the piece of code that enabled the low-resolution mode on macOS?

**Comment by PhucNgo1711** [comment]
I'm actually not sure. @ashishsingh18's fix to the chopped off screen a few months ago enables this. Before that, there was no code that really lets you select between high and low resolution. It was something automatically picked up by macOS

**Comment by sarthakpati** [comment]
So basically #137 and #122?

**Comment by sarthakpati** [comment]
There is a very nice (and brief) tutorial about it [here](https://vicrucann.github.io/tutorials/osg-qt-high-dpi/). Hopefully, this can help us provide some remedy to this DPI issue on macOS.

**Comment by PhucNgo1711** [comment]
Resolved on macOS. Apparently the plist file was not picked up during the move to GitHub, and adding it back plus [this approach ](https://doc.qt.io/qt-5/highdpi.html) fixed the DPI issue.

**Comment by sarthakpati** [comment]
Closing this; let's reopen if issue comes up again.

**Comment by PhucNgo1711** [comment]
NOTE: the highDPI attributes in the c++ code actually does **not** affect the resolution. I tried commenting them out and the result is still the same

**Comment by PhucNgo1711** [comment]
We ran into an issue with older Mac machines (before 2015) where the default screen resolution is 1280 x 900, resulting in CaPTk getting chopped off a portion on the right.

**Comment by sarthakpati** [comment]
This loops better in the new releases. Closing this until anyone else reports as an issue.
