### ISSUE TITLE
1.7.0-1.3.0 Windows Installer Link broken

### ISSUE THREAD

**Issue by johannauthoff** [CBICA/CaPTk#546]
**Describe the bug**
Cannot download the 1.7.0 Windows installer version

**To Reproduce**

1) Go to https://www.nitrc.org/frs/?group_id=1059
2) Click any of the Windows x64 installer links
Receive an Alert saying
"The webpage at ftp://www.nitrc.org/home/groups/captk/downloads/CaPTk_1.7.0_Installer.exe might be temporarily down or it may have moved permanently to a new web address."
3) Problem persists in Chrome, Firefox, and Edge browsers (with slight variations in alert wording)

**Desktop (please complete the following information):**
Windows 7

Thanks!
Jo

**Comment by sarthakpati** [comment]
Hi @johannauthoff, we are currently speaking with the NITRC webmaster to check what the issue is. Thanks for reporting!

**Comment by sarthakpati** [comment]
UPDATE: The NITRC webmaster has responded that there indeed seems to be some issue on their side and they are looking into it.

**Comment by johannauthoff** [comment]
Thank you for the update @sarthakpati!

**Comment by sarthakpati** [comment]
This should be working, now. Could you please confirm and then close the issue, @johannauthoff? Cheers!

**Comment by johannauthoff** [comment]
@sarthakpati, yes link is now working. Thank you!

**Comment by sarthakpati** [comment]
You are welcome. Also, as an FYI, we will be releasing 1.7.1 later this month.
