### ISSUE TITLE
About Screen UI is off

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#548]
**Describe the bug**
The bottom section of the about screen, which has the control for scaling, appears too big (see attached screenshot).

**Expected**
There should not be that much unused UI estate, perhaps?

**Screenshots**
![image](https://user-images.githubusercontent.com/11719673/59964031-07b2b380-94c9-11e9-8c0b-7150be735876.png)

**Comment by sarthakpati** [comment]
Interestingly, this doesn't happen after I have done a full install on my laptop.

**Comment by sarthakpati** [comment]
This is localized to my desktop, which has a display driver issue. Closing.

**Comment by ashishsingh18** [comment]
I could replicate this in Debug mode on my machine. Re-opening.

**Comment by ashishsingh18** [comment]
This should be fixed by the recent check-in.
