### ISSUE TITLE
Missing symlink from $CAPTKDIR/bin/CaPTk to $CAPTKDIR/bin/captk

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#558]
[> 3. A captk symlink is generated as a part of the make install step, and a PostInstall.cmake file has been added alongside this functionality to make further post install operations have a defined place.](https://github.com/CBICA/CaPTk/pull/192#issue-243800137)

There is no "captk" symlink created in $CAPTKDIR/bin/ after running "make install/strip"

**Comment by sarthakpati** [comment]
This is fixed.
