### ISSUE TITLE
Linux packaging -- $CAPTKDIR/bin has visualizer subdirectory

### ISSUE THREAD

**Issue by MarkBergman-cbica** [CBICA/CaPTk#559]
After installation, the Linux version of CaPTk has the subdirectory: $CAPTKDIR/bin/visualizer.

The directory contains ".py" files which are not executable.

That subdirectory should not exist.

Executables that may be called by a user should be in $CAPTKDIR/bin.

Executables that will only be called by other executables should be in $CAPTKDIR/libxec.

Neither of those should have subdirectories.

**Comment by sarthakpati** [comment]
This was stemming from Theia and has been fixed.
