### ISSUE TITLE
EGFRvIII SVM Index SegmentationFault

### ISSUE THREAD

**Issue by jminock** [CBICA/CaPTk#566]
**Describe the bug**
When running EGFRvIIIIndexPredictor.exe, a pop up comes up that the program has stopped working
![EGFRvIIIIndex_error](https://user-images.githubusercontent.com/20047333/60596732-964fec00-9d77-11e9-83ce-cbd4497de8c6.PNG)

**To Reproduce**
1. Open a terminal (in this case Windows Powershell)
2. Run the following:
```${CAPTK_BUILD_DIR}/Debug/EGFRvIIIIndexPredictor.exe -i S:/SampleData_UnitTesting/EGFRvIIISVMIndex_1.6.1/samples -t 0 -o ${TEST_OUTPUT_DIR}/EGFRvIIIIndexPredictorModel```
My command in powershell:
```C:\CaPTkBuild\Debug\EGFRvIIIIndexPredictor.exe -i S:\SampleData_UnitTesting\EGFRvIIISVMIndex_1.6.1\samples -t 0 -o C:\CaPTkBuild\testing\TestData\outputs\EGFRvIIIIndexPredictorModel```

**Expected behavior**
The program will complete without error with a model file located in the EGFRvIIIIndexPredictorModel directory

**CaPTk Version**
1.7.1

**Desktop (please complete the following information):**
 - OS: Windows 7

**Additional context**
Updated to CBICA master as of 7/3 9:59 am

**Comment by saimarathore** [comment]
I could not replicate it. EGFRvIIIIndexPredictor works fine and generates desired output when i ran it from 1.7.1.

**Comment by sarthakpati** [comment]
@jminock could you send me the test data so that @saimarathore can try it with the same dataset? Thanks,

**Comment by jminock** [comment]
[AASF.zip](https://github.com/CBICA/CaPTk/files/3362692/AASF.zip)
I attached a .zip folder of one of the subjects.  Just unzip it and point the input directory to the directory AASF is in, not AASF itself.
I also have the data on the S: drive at S:/SampleData_UnitTesting/EGFRvIIISVMIndex_1.6.1
Even though this is the exact same data set that I am using locally, sometimes the executable recognizes it, sometimes it does not

**Comment by jminock** [comment]
Issue no longer exists on my machine. Cannot replicate.
