### ISSUE TITLE
Training Module Test Only Error

### ISSUE THREAD

**Issue by jminock** [CBICA/CaPTk#568]
**Describe the bug**
The training module "test only" option fails in command line

**To Reproduce**
Open terminal (in this case windows powershell)

Run the following command:
```
${CAPTK_BUILD_DIR}/Debug/TrainingModule.exe -f ${TEST_INPUT_DATA}/training/features2.csv -l ${TEST_INPUT_DATA}/training/labels2.csv -c 1 -o ${TEST_OUTPUT_DIR}/training/ -k 5 -n 4
```
My command:
```
C:\CaPTkBuild\Debug\TrainingModule.exe -f S:\SampleData_UnitTesting\training\features2.csv -l S:\SampleData_UnitTesting\training\labels2.csv -c 1 -o C:\CaPTkBuild\testing\TestData\outputs\training -k 5 -n 4
```

**Expected behavior**
The program completes without error and all output is generated to the specified output folder

**Screenshots**
![training_module_error](https://user-images.githubusercontent.com/20047333/60601489-36aa0e80-9d80-11e9-9933-0860a3124256.PNG)
![training_module_error_output](https://user-images.githubusercontent.com/20047333/60601503-3b6ec280-9d80-11e9-9384-4238aef52213.PNG)

**CaPTk Version**
CaPTk 1.7.1

**Desktop (please complete the following information):**
 - OS: Windows 7

**Additional context**

**Comment by saimarathore** [comment]
An additional parameter of (-m ModelDirectory) is required for "test only" option. This was not mentioned in the document earlier. i have updated the documentation now.
