### ISSUE TITLE
Start caching test in Azure

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#575]
**Is your feature request related to a problem? Please describe.**
The build takes a long time since the Superbuild needs to finish every single time.

**Describe the solution you'd like**
Use [caching](https://github.com/microsoft/azure-pipelines-yaml/pull/113) to speed things up (our build agents are at the required `2.154.1` version already). More details about implementation in [this comment](https://github.com/microsoft/azure-pipelines-yaml/pull/113#issuecomment-508077422).

**Comment by sarthakpati** [comment]
Hey @PhucNgo1711, I think the Cache is now available for the CBICA org.

**Comment by PhucNgo1711** [comment]
@sarthakpati testing on macOS on Azure right now
The task is renamed to CacheBeta@ instead of Cache@ (for now I guess)

**Comment by PhucNgo1711** [comment]
@sarthakpati looks like caching (single file / multiple files) is working but we have to figure out a way to cache the whole ITK-build directory (or wait for a fix to be out)

**Comment by sarthakpati** [comment]
Ah okay. As a first measure, let's get the precompiled binaries (applications and qt) cached. This would tremendously reduce the bandwidth requirement from GitHub.

**Comment by sarthakpati** [comment]
This is currently active for GCC and CLang but not for MSVC [[ref](https://github.com/microsoft/azure-pipelines-yaml/pull/113#issuecomment-513223426)].

For MSVC, there is one implementation we could try: https://github.com/frerich/clcache

The usage for this is pretty simple via CMake and so is the installation (apparently). Once the cache gets updated to handle all files, we could explore putting this in for MSVC.

**Comment by sarthakpati** [comment]
This is currently active for GCC and CLang but not for MSVC [[ref](https://github.com/microsoft/azure-pipelines-yaml/pull/113#issuecomment-513223426)].

For MSVC, there is one implementation we could try: https://github.com/frerich/clcache

The usage for this is pretty simple via CMake and so is the installation (apparently). Once the cache gets updated to handle all files, we could explore putting this in for MSVC.

**Comment by PhucNgo1711** [comment]
I see.
I got the precomplied binaries and qt to properly cache.
For the superbuild, either we wait for the file glob fix to be out, or we can try some workarounds that. 
Something like store the output of` ls -R ITK-build` to a variable then use that variable as a file pattern for caching

**Comment by sarthakpati** [comment]
> I got the precomplied binaries and qt to properly cache.

That is awesome! Can you initiate a PR for this?

**Comment by sarthakpati** [comment]
> For the superbuild, either we wait for the file glob fix to be out, or we can try some workarounds that.

Agreed.

**Comment by PhucNgo1711** [comment]
> > I got the precomplied binaries and qt to properly cache.
> 
> That is awesome! Can you initiate a PR for this?

Okay. I just test to test one more thing and I'll create a PR
