### ISSUE TITLE
DeepMedic can't run on macOS without LLVM installed

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#576]
**Describe the bug**
The DeepMedic executable on macOS uses OpenMP provided by LLVM. It will throw an error if LLVM is not presented in the machine. 

**To Reproduce**
1. Load samples in CaPTk (T1, T1CE, T2, Flair)
2. Run Deep Medic
3. DeepMedic fails to run immediately

**Expected behavior**
DeepMedic should work

**Screenshots**
![66294362_461358778039688_934469851500511232_n](https://user-images.githubusercontent.com/14838084/61057372-2f5bb400-a3c3-11e9-84ae-826ce4f9dda1.png)

**CaPTk Version**
1.7.1

**Desktop (please complete the following information):**
 - OS: macOS
 - Version (including Build information, if any): 10.13, 10.14

**Comment by sarthakpati** [comment]
Interesting. This might be what that other person was seeing.

**Comment by sarthakpati** [comment]
There would be 2 possible routes to fix this:

1. Recompile DeepMedic on the fresh machine with no LLVM installed
2. Try https://github.com/indygreg/PyOxidizer to see if that fixes it

**Comment by PhucNgo1711** [comment]
@sarthakpati can you post the instructions on how to compile DeepMedic here? I'm going to try to compile it without llvm.

**Comment by sarthakpati** [comment]
Will email since it is part of a private repo.

**Comment by sarthakpati** [comment]
New executable has been made ready courtesy @PhucNgo1711. Once the testing on 10.13 is completed, it will be incorporated into the new package.

**Comment by sarthakpati** [comment]
> New executable has been made ready courtesy @PhucNgo1711. Once the testing on 10.13 is completed, it will be incorporated into the new package.

This has now been tested and incorporated into #577.
