### ISSUE TITLE
Cannot run WhiteStripe in MacOS

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#580]
**Describe the bug**
Cannot run White Stripe in MacOS

**To Reproduce**
> /Applications/CaPTk_1.7.1.app/Contents/Resources/bin/WhiteStripe -h
dyld: Library not loaded: /usr/local/opt/llvm/lib/libomp.dylib
  Referenced from: /Applications/CaPTk_1.7.1.app/Contents/Resources/bin/WhiteStripe
  Reason: image not found
Abort trap: 6

> /Applications/CaPTk_1.7.1.app/Contents/MacOS/CaPTk_1.7.1 WhiteStripe.cwl -h
dyld: Library not loaded: /usr/local/opt/llvm/lib/libomp.dylib
  Referenced from: /Applications/CaPTk_1.7.1.app/Contents/Resources/bin/WhiteStripe
  Reason: image not found

**CaPTk Version**
MacOS 1.7.1, downloaded from https://www.nitrc.org/frs/?group_id=1059 on 7/16/2019

**Desktop (please complete the following information):**
 - OS: macOS
 - Version (including Build information, if any): Mojave 10.14.4

**Additional context**
I see a similar closed issue #576 so I'm hoping there is a similar fix

**Comment by sarthakpati** [comment]
@PhucNgo1711 this is an OpenMP issue.

**Comment by PhucNgo1711** [comment]
@sarthakpati It looks like it needs LLVM OpenMP  
Can we fix this the same way we did for DeepMedic?

**Comment by sarthakpati** [comment]
Well, WhiteStripe is built along with CaPTk in the same compilation unit. If CaPTk does not need OMP, why does any specific CLI?

I would assume by doing the same thing we could solve this. Bigger question is why is this coming up at all?

**Comment by sarthakpati** [comment]
@chiharusako, can you try to install **llvm** using the following command and retrying:
```
brew install llvm
```

**Comment by sarthakpati** [comment]
@PhucNgo1711 on a related note, do we absolutely **need** LLVM? Reference: https://iscinumpy.gitlab.io/post/omp-on-high-sierra/

**Comment by PhucNgo1711** [comment]
interesting
let me try this out

**Comment by sarthakpati** [comment]
If OpenMP gets statically bundled by clang, we might not. Will need to check the package after it gets built. Could you look into it, please? We obviously cannot target this fix for 1.7.2 but we can for the next one.

**Comment by PhucNgo1711** [comment]
Testing a new workaround with libomp

**Comment by sarthakpati** [comment]
Could you link to the commit with this attempt? This is so that we know what things we have tried.

**Comment by PhucNgo1711** [comment]
Update SET_TARGET_PROPERTIES https://github.com/PhucNgo1711/CaPTk/commit/bc45022bfcb81c1648ce175079045da40609aa16

**Comment by sarthakpati** [comment]
> Update SET_TARGET_PROPERTIES [PhucNgo1711@bc45022](https://github.com/PhucNgo1711/CaPTk/commit/bc45022bfcb81c1648ce175079045da40609aa16)

Any update on this? 

What we basically saw was that the libomp.dylib was getting packaged inside the "Frameworks" folder and we are trying to link the CLI executables to it.

**Comment by PhucNgo1711** [comment]
that didn't work. I'm trying something else

**Comment by PhucNgo1711** [comment]
The current solution is to run `install_name_tool` command as part of the script after` make package`

**Comment by PhucNgo1711** [comment]
This should be fixed now as we don't depend on llvm anymore
