### ISSUE TITLE
CaPTk command-line: preprocessing histogram matching doesn't output

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#587]
**Describe the bug**
Preprocessing -hi doesn't output file

**To Reproduce**
in command-line:
> Module Load captk/1.7.0
> CaPTk Preprocessing -hi $refimage -i $input -o $output

This does not give an error but doesn't output either. 
This worked in 1.6.2.Beta on the cluster (local install), using the same arguments.

**Expected behavior**
It should output a file

**CaPTk Version**
1.7.0 on cbica cluster

**Desktop (please complete the following information):**
 - OS: Linux centos, on cbica-cluster cubic-login2

**Comment by sarthakpati** [comment]
Thanks for reporting! Fixed.
