### ISSUE TITLE
Persistent GLIBCXX or GLIBC Issues on Centos 7 CaPTk 1.7.2

### ISSUE THREAD

**Issue by giemmecci** [CBICA/CaPTk#602]
Hi,
I had issues with GLIBCXX after installing the software, and the solution provided in the Documentation did not solve the problem.

I ran:
`sudo yum install centos-release-scl`
`sudo yum install devtoolset-6`

but nothing changed, I am still getting the following error messages:

/tmp/.mount_captkIhcQRC/usr/bin/CaPTk: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.mount_captkIhcQRC/usr/bin/CaPTk)

/tmp/.mount_captkIhcQRC/usr/bin/CaPTk: /usr/lib64/libgpg-error.so.0: no version information available (required by /tmp/.mount_captkIhcQRC/usr/lib/libgcrypt.so.20)

**CaPTk Version**
1.7.2

**Desktop (please complete the following information):**
 - OS: Centos 7

Thanks

**Comment by sarthakpati** [comment]
Hi @giemmecci, thank you for taking time to post about this issue. 

Could you tell me which version of GCC is running on your machine?

**Comment by giemmecci** [comment]
Hi, @sarthakpati , thank you for the fast reply.
I have version 4.8.5
`gcc --version`
`gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)`

Thanks

**Comment by sarthakpati** [comment]
No worries, @giemmecci, I am glad to help out. 

Can you try installing a newer version of GCC? 4.9 or newer.

**Comment by giemmecci** [comment]
Hi,
after installing the devtoolset-6 as from the FAQ, I activated it by running
`scl enable devtoolset-6 bash`

Now when I check the gcc version I get the following:
`gcc --version`
`gcc (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3)`

However, when I try to open the software by running
`~/CaPTk/1.7.2/captk`

I still get the error message I've posted in the first message.

Am I doing something wrong? Thanks

**Comment by sarthakpati** [comment]
Interesting, that is definitely higher than the version we use to build CaPTk. Could you give me the result of the following command (after you have activated the ```devtoolset-6```)?
```bash
/sbin/ldconfig -p | grep stdc++
# you will see the path to libstdc++
strings $path_to_libstdc++.so.6 | grep LIBCXX 
```

For example, on my WSL:

```bash
root@sbia-pc137:~# /sbin/ldconfig -p | grep stdc++
        libstdc++.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
        libstdc++.so.6 (libc6) => /usr/lib32/libstdc++.so.6
root@sbia-pc137:~# strings /usr/lib32/libstdc++.so.6 | grep LIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21 # <=== this is what we need to see
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by giemmecci** [comment]
It seems like it is missing, here are the commands and the outputs

```
[user]$ scl enable devtoolset-6 bash
[user]$ /sbin/ldconfig -p | grep stdc++
	libstdc++.so.6 (libc6,x86-64) => /lib64/libstdc++.so.6
[user]$ strings /lib64/libstdc++.so.6 | grep LIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by sarthakpati** [comment]
Oh wow, if the ```devtoolset-6``` did not change the ```GLIBCXX``` version, I am at a loss. Calling out the big guns, here; @MarkBergman-cbica, we need your expertise in this matter.

**Comment by MarkBergman-cbica** [comment]
@sarthakpati :+1: 
> root@sbia-pc137:~# /sbin/ldconfig -p | grep stdc++
>         libstdc++.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
>         libstdc++.so.6 (libc6) => /usr/lib32/libstdc++.so.6
> root@sbia-pc137:~# strings /usr/lib32/libstdc++.so.6 | grep LIBCXX

Are you really using the 32-bit version of libstdc++?! (And why does Git format the quoted text with a strikethrough after the hash sign, instead of keeping it as-is?)

@giemmecci 
1. What is the result of:
`echo $LD_LIBRARY_PATH`
2. What's the result of:
`ldd ~/CaPTk/1.7.2/captk`
3. Enabling a devtoolset environment will not change `/lib64/libstdc++.so`, so the result below is as expected:
> [user]$ scl enable devtoolset-6 bash
> [user]$ /sbin/ldconfig -p | grep stdc++
> 	libstdc++.so.6 (libc6,x86-64) => /lib64/libstdc++.so.6
> [user]$ strings /lib64/libstdc++.so.6 | grep LIBCXX

Note that `/opt/rh/devtoolset-6/root/usr/lib/gcc/x86_64-redhat-linux/6.3.1/libstdc++.so` is just a stub (ASCII text, telling the linker to use the system library), where `/opt/rh/devtoolset-6/root/usr/lib/gcc/x86_64-redhat-linux/6.3.1/libstdc++.a` is a static library (which will **not** be picked up at runtime) and which is used for development of software that requires a higher version of GLIBCXX than the RHEL7 package. Think of `devtoolset` for **development**, not to provide dynamic libraries for other packages to use at runtime.

[See this discussion](https://access.redhat.com/discussions/3405861)

@sarthakpati -- doesn't the appimage executable (~/CaPTk/1.7.2/captk) supersede $LD_LIBRARY_PATH, whereas the individual CLI executables will use the same library search order as provided system-wide?

Possible solutions: 

1. Compile CaPTk under default CentOS7 tools (should be compatible with newer systems as well).
2. Compile CaPTk under CentOS7 with devtoolset-{6,7} -- that will generate a binary with mixed static/dynamic linking, and should be compatible with CentOS7 & newer distros.
3. Provide libstdc++.so.6 with GLIBCXX >= 3.4.20 with CaPTk, setting LD_LIBRARY_PATH to find our library first.

**Comment by MarkBergman-cbica** [comment]
Same as [issue 505](https://github.com/CBICA/CaPTk/issues/505)

**Comment by sarthakpati** [comment]
> Are you really using the 32-bit version of libstdc++?!

This was an example from one of my WSL machines; compiles are happening on Azure, which is 64-bit.

**Comment by giemmecci** [comment]
> @sarthakpati 
> 
> > root@sbia-pc137:~# /sbin/ldconfig -p | grep stdc++
> > libstdc++.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> > libstdc++.so.6 (libc6) => /usr/lib32/libstdc++.so.6
> > root@sbia-pc137:~# strings /usr/lib32/libstdc++.so.6 | grep LIBCXX
> 
> Are you really using the 32-bit version of libstdc++?! (And why does Git format the quoted text with a strikethrough after the hash sign, instead of keeping it as-is?)
> 
> @giemmecci
> 
> 1. What is the result of:
>    `echo $LD_LIBRARY_PATH`
> 2. What's the result of:
>    `ldd ~/CaPTk/1.7.2/captk`
> 3. Enabling a devtoolset environment will not change `/lib64/libstdc++.so`, so the result below is as expected:
> 
> > [user]$ scl enable devtoolset-6 bash
> > [user]$ /sbin/ldconfig -p | grep stdc++
> > libstdc++.so.6 (libc6,x86-64) => /lib64/libstdc++.so.6
> > [user]$ strings /lib64/libstdc++.so.6 | grep LIBCXX
> 
> Note that `/opt/rh/devtoolset-6/root/usr/lib/gcc/x86_64-redhat-linux/6.3.1/libstdc++.so` is just a stub (ASCII text, telling the linker to use the system library), where `/opt/rh/devtoolset-6/root/usr/lib/gcc/x86_64-redhat-linux/6.3.1/libstdc++.a` is a static library (which will **not** be picked up at runtime) and which is used for development of software that requires a higher version of GLIBCXX than the RHEL7 package. Think of `devtoolset` for **development**, not to provide dynamic libraries for other packages to use at runtime.
> 
> [See this discussion](https://access.redhat.com/discussions/3405861)
> 
> @sarthakpati -- doesn't the appimage executable (~/CaPTk/1.7.2/captk) supersede $LD_LIBRARY_PATH, whereas the individual CLI executables will use the same library search order as provided system-wide?
> 
> Possible solutions:
> 
> 1. Compile CaPTk under default CentOS7 tools (should be compatible with newer systems as well).
> 2. Compile CaPTk under CentOS7 with devtoolset-{6,7} -- that will generate a binary with mixed static/dynamic linking, and should be compatible with CentOS7 & newer distros.
> 3. Provide libstdc++.so.6 with GLIBCXX >= 3.4.20 with CaPTk, setting LD_LIBRARY_PATH to find our library first.


@MarkBergman-cbica 
Here are the outputs:
```
echo $LD_LIBRARY_PATH
/home/user/CUDA/include:/home/user/CUDA/lib64:/home/user/CUDA/lib:/home/user/CUDA/include:/home/user/CUDA/lib64:/home/user/CUDA/lib:
```
```
[user ~]$ ldd ~/CaPTk/1.7.2/captk
	not a dynamic executable
```
Thank you for your help, I'll try the solutions you suggested.

**Comment by sarthakpati** [comment]
@giemmecci Thank you for your patience. As an alternative, I am currently trying to build a package on CentOS7.

**Comment by sarthakpati** [comment]
Testing the new package (ref to commit: https://github.com/sarthakpati/CaPTk/commit/80a2427f5b56bd78c4504cdef3a2fa0f01da6341)

**Comment by sarthakpati** [comment]
Slight hiccup: apparently, Qt 5.12.1 does not support CentOS 7 from their binary distribution. Need to figure another way around this.

**Comment by giemmecci** [comment]
Thank you for your efforts, I'll keep following the thread for the new package

**Comment by sarthakpati** [comment]
Hey @giemmecci, could you try the following package (created as a one off form the current master) and let me know if it works for you? 

https://www.nitrc.org/frs/downloadlink.php/11517

**Comment by giemmecci** [comment]
Thanks @sarthakpati , I'll test it today

**Comment by sarthakpati** [comment]
Build from latest master is up: https://www.nitrc.org/frs/downloadlink.php/11522

**Comment by giemmecci** [comment]
I was able to install the software but I am running into an OpenGL issue:
```
(base) [user ~]$ ~/CaPTk/1.7.3.nonRelease.20190821/captk
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
Checking for compatible OpenGL - this will happen only once.
QXcbIntegration: Cannot create platform offscreen surface, neither GLX nor EGL are enabled
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
QOpenGLFunctions created with non-current context
Segmentation fault (core dumped)

```
And this is my OpenGL version:

```
(base) [user ~]$ glxinfo | grep 'version'
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL version string: 2.1 Mesa 18.0.5
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 18.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16

```
I saw on the FAQ that there's a solution for this issue, so I'll ask  my admin to update the OpenGL version (I can't sudo).

Thanks

**Comment by sarthakpati** [comment]
> I was able to install the software

Great! 

> but I am running into an OpenGL issue

Not uncommon in clustered environments. We have had a similar issue (#569) and we can follow up there. Closing this issue; please reopen if problems persist.
