### ISSUE TITLE
Add different quantization approaches (e.g. uniform, equal) for feature extraction

### ISSUE THREAD

**Issue by sbakas** [CBICA/CaPTk#605]
**Describe the solution you'd like**
Various options should be offered, as the parameterization of the quantization step. Example of such include:
Equal: Equal-probability quantization on the ROI considered.
Uniform: Uniform quantization on the ROI considered. (preserving intrinsic texture)
Lloyd: Lloyd-Max quantization on the ROI considered.

**Alternative packages**
https://github.com/mvallieres/radiomics

**Comment by sarthakpati** [comment]
The first 2 are already there in [ITK's histogram calculation class](https://itk.org/Doxygen/html/classitk_1_1Statistics_1_1ImageToHistogramFilter.html), I believe. 

Uniform:
```cpp
auto imageToHistogramFilter = ImageToHistogramFilterType::New();
imageToHistogramFilter->SetInput( inputImage );
imageToHistogramFilter->SetHistogramBinMinimum( lowerBound );
imageToHistogramFilter->SetHistogramBinMaximum( upperBound );
imageToHistogramFilter->SetHistogramSize( size );
```

Equal:
```cpp
auto imageToHistogramFilter = ImageToHistogramFilterType::New();
imageToHistogramFilter->SetInput( inputImage );
// imageToHistogramFilter->SetHistogramBinMinimum( lowerBound );
// imageToHistogramFilter->SetHistogramBinMaximum( upperBound );
imageToHistogramFilter->SetHistogramSize( size );
```

**Comment by sarthakpati** [comment]
This has now been added to the following feature families:

- Histogram
- GLCM
- GLRLM

It is difficult to do for the other texture features right now since it is embedded fairly deep in the code.

**Comment by sarthakpati** [comment]
Control mechanism in the parameter file:

```csv
Generic,Quantization_Extent,String,Image:ROI,ROI,Whether the quantization of Intensities is supposed to happen on a per-image basis or on a per-ROI basis
Generic,Quantization_Type,String,Uniform:Equal,Uniform,Uniform: the bins are uniformly distributed across the minimum and maximum extent in the ROI/Image as defined under "Quantization_Extent"; Equal: each bin holds an equal number of intensities
```

**Comment by sarthakpati** [comment]
Done.
