### ISSUE TITLE
Change location of where CWL files get installed

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#608]
**Describe the bug**
Currently, the CWL files are installed in the `bin` directory, which is not in accordance with published standards (reference needed).

**Expected behavior**
They should probably go in `share/cwlFiles`.

**Comment by MarkBergman-cbica** [comment]
https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

**Comment by sarthakpati** [comment]
Done.
