### ISSUE TITLE
DirectionalityEstimate integer parameter error

### ISSUE THREAD

**Issue by jminock** [CBICA/CaPTk#610]
**Describe the bug**
When trying to run DirectionalityEstimate from the command line, an error occurs when passing "-i".  The error reads:
The data type of the requested parameter, 'i' is classified as 'INTEGER' and cannot be returned as a STRING.

I get this error when passing 40,25,60 as an argument (as specified from https://cbica.github.io/CaPTk/Glioblastoma_Directionality.html )
And I get this same error if just passing 40 as an argument

**To Reproduce**
1. Have latest build of CaPTk as of 9:17 am 8/19
2. Run either or both of the following commands
```
C:\CaPTkBuild\Debug\DirectionalityEstimate.exe -l C:\CaPTkBuild\testing\TestData\direst\img_timepoint_1.nii.gz -i 40,25,60 -o C:\CaPTkBuild\testing\TestData\outputs\dirEst.txt
```

```
C:\CaPTkBuild\Debug\DirectionalityEstimate.exe -l C:\CaPTkBuild\testing\TestData\direst\img_timepoint_1.nii.gz -i 40 -o C:\CaPTkBuild\testing\TestData\outputs\dirEst.txt
```

**Expected behavior**
No error would come up, output would be written to dirEst.txt, and application would complete

**CaPTk Version**
1.7.3.nonRelease

**Desktop (please complete the following information):**
 - OS: Windows 7

**Additional context**
CMake 3.14.1
Microsoft Visual Studio Version Community 2017 Version 15.8.2

**Comment by sarthakpati** [comment]
Fixed.
