### ISSUE TITLE
Feature Extraction segmentation error

### ISSUE THREAD

**Issue by jminock** [CBICA/CaPTk#612]
**Describe the bug**
Segmentation fault when running Feature Extraction on the command line.  When running executable (as shown in steps), it gives output:
Single subject computation selected.
Starting computation of selected features.

Then segmentation fault error pops up (see screenshot below)

**To Reproduce**
1. Have CaPTk build version 1.7.3.nonRelease.20190816
2. 
```
C:\CaPTkBuild\Release\FeatureExtraction.exe -n AAAC -i C:\CaPTkBuild\testing\TestData\FeatureExtraction\image.nii.gz -t FL -m C:\CaPTkBuild\testing\TestData\FeatureExtraction\mask.nii.gz -r 1 -l ED -p C:\CaPTkBuild\testing\TestData\FeatureExtraction\params.csv -o C:\CaPTkBuild\testing\TestData\outputs\featEx.csv -vc 1
```

**Expected behavior**
Program completes with no errors and output is written to featEx.csv

**Screenshots**
![FeatureExtractionReleaseError](https://user-images.githubusercontent.com/20047333/63282307-8c793e00-c27c-11e9-8e32-17bc624c21eb.PNG)

**CaPTk Version**
CaPTk 1.7.3.nonRelease.20190816

**Desktop (please complete the following information):**
 - OS: Windows 7

**Additional context**
CMake 3.14.1

**Comment by sarthakpati** [comment]
Fixed.
