### ISSUE TITLE
DICOM conversion does not work when spaces exist in path.

### ISSUE THREAD

**Issue by sbakas** [CBICA/CaPTk#618]
**Describe the bug**
The dicom conversion tool requires specific naming conventions, i.e., no spaces in the pathway/file name

**CaPTk Version**
1.7.2.

**Desktop (please complete the following information):**
Windows 10

**Comment by ashishsingh18** [comment]
@sbakas Can you please give the replication steps? 
I am unable to replicate this issue. 

I have tried Preprocessing->Dicom2Nifti with a path with spaces( ex: C:\workspace\Data\Dicom\dicom path with space\t1 Dicom - Copy) and it works.

**Comment by ashishsingh18** [comment]
Unable to replicate.
