### ISSUE TITLE
CaPTk Test Data download for Docker image

### ISSUE THREAD

**Issue by jminock** [CBICA/CaPTk#620]
**Describe the bug**
When trying to build CaPTk docker image, superbuild completes, but build fails because TestData could not be downloaded. Error gives "Status=9; Access denied to remote source"

**To Reproduce**
Very long and tedious method:
1. Have machine with Docker
2. Include Dockerfile in home directory 
(change Dockerfile.txt to Dockerfile if necessary)
(ensure EOL encoding of file is compatible for OS)
3. ``` sudo docker build --tag=cbica/captk . ```
4. Wait approx. 3-4 hours to get to error

OR
Follow link in browser:
``` ftp://www.nitrc.org/var/homr/groups/captk/downloads/SampleData/TestData.zip ```

**Expected behavior**
CaPTk completes build, all files necessary are downloaded, image is built

**Screenshots**
Error:
![CaPTk_docker_test_data_missing](https://user-images.githubusercontent.com/20047333/63432190-ac307380-c3ee-11e9-9027-d6a78cd10918.PNG)

**CaPTk Version**
1.7.2.Release

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.10 VM

**Additional context**
Here is Dockerfile as .txt (Dockerfile type isn't supported in Markdown)
[Dockerfile.txt](https://github.com/CBICA/CaPTk/files/3525358/Dockerfile.txt)

**Comment by sarthakpati** [comment]
Fixed.
