### ISSUE TITLE
CaPTk_Tests failing

### ISSUE THREAD

**Issue by jminock** [CBICA/CaPTk#622]
**Describe the bug**
When running the EGFRvIII and Geodesic flags for CaPTk_Tests, no output is generated, yet tests fail in Unit Tests

**To Reproduce**
```
C:\CaPTkBuild\Release\CaPTk_Tests.exe -geo C:\CaPTkBuild\testing\TestData\Geodesic\input_flair.nii.gz
```
```
C:\CaPTkBuild\Release\CaPTk_Tests.exe -egfr C:\CaPTkBuild\testing\TestData\EGFRvIII\DSC-MRI_data_changed_rescaled.nii.gz
```

**Expected behavior**
I do not know if output would be generated, but I would assume tests to pass from usage of C;\CaPTk\testing\AllTests.cxx

**CaPTk Version**
Latest build on master as of 8:27am 8/26/2019

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by sarthakpati** [comment]
This is a documentation error on the API. Fixed.
