### ISSUE TITLE
SurvivalPredictor on linux version can't find template

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#627]
**Describe the bug**
The survival predictor gets an error reading template.nii.gz and fails

**To Reproduce**
On cbica cubic-login3:
captk SurvivalPredictor -t 1 -i $PWD/input  -o $PWD/output -m $modeldir  -L $PWD/survival.log

**CaPTk Version**
1.7.2 linux version on cbica cluster

**Desktop (please complete the following information):**
centos, cubic-login3

**Error message**

$ captk SurvivalPredictor -t 1 -i $PWD/input  -o $PWD/output -m $modeldir -L $PWD/survival3.log
Input directory name:/cbica/projects/brain_tumor/Projects/20190903_BTC_GBM/captk_test/input
Output directory name:/cbica/projects/brain_tumor/Projects/20190903_BTC_GBM/captk_test/output
Model directory name:/cbica/home/sakoc/CaPTk/PretrainedModels/SurvivalPredictor_PretrainedModel_1.6.1
Module loaded: Survival Prediction on Existing Model:
Number of subjects with required input: 1
Subject No:0
Error caught: /cbica/software/external/dependency_bundle/centos7/3817/include/ITK-4.13/itkImageFileReader.hxx:143:
 Could not create IO object for reading file ../data/survival/Template.nii.gz
The file doesn't exist. 
Filename = ../data/survival/Template.nii.gz

**Comment by sarthakpati** [comment]
Worked.
