### ISSUE TITLE
GBM Pseudoprogression module not available for loaded scans

### ISSUE THREAD

**Issue by sbakas** [CBICA/CaPTk#633]
Not sure if the functionality is missing by design or not, but since the scans of a subject are loaded on captk, the psp/tp predictor should be providing the functionality to only load a model and provide results.

**CaPTk Version**
1.7.2 (Windows)

**Comment by sarthakpati** [comment]
Is still an issue, @saimarathore?

**Comment by sarthakpati** [comment]
Duplicate of #218, closing this.
