### ISSUE TITLE
FeatureExtraction.exe help message is inconsistent with online documentation, please update the documentation

### ISSUE THREAD

**Issue by nwschurink** [CBICA/CaPTk#647]
**Is your feature request related to a problem? Please describe.**
I am trying to perform feature extraction on a batch of images. However, the documentation online and the help message showed by the FeatureExtraction.exe module is inconsistent and/or incomplete.

The [documentation](https://github.com/CBICA/CaPTk/blob/07b4f2e5469da765c6a68425d972504d25d3168f/3_HowToGuides.txt#L343) states an example batch process file can be found in 'share/featureExtractionBatch/batch_featureExtraction.csv'. The headers in this file differ from the required headers that are reported by the FeatureExtraction.exe module:

Header of batch_featureExtraction.csv:
```
PATIENT_ID | Images | Modalities | ROIFile | SELECTED_ROI | ROI_LABEL
-- | -- | -- | -- | -- | --
```

Help message from FeatureExtraction.exe:
```
[  -b, --batchFile]         Input file with Multi-Patient Multi-Modality details

                            Header format is as follows:
                            'PATIENT_ID,IMAGES,MASK,ROI,SELECTED_ROI,ROI_LABEL,
                            SELECTED_FEATURES,PARAM_FILE'
                            Delineate individual fields by '|'
                            Expected Type  :: FILE
                            Expected Range :: .csv
```

**Describe the solution you'd like**
I'd like the documentation to be consistent. It would be nice if the documentation explains what the input for each of the header would be. 
Some of the header names that are mentioned in FeatureExtraction.exe help have the same name as some of the optional parameters that are the input for FeatureExtraction.exe. Therefor, I suppose these headers correspond and should adhere to the format that's described for these optional parameters. (e.g. MASK corresponds to option --maskPath).

However, what's for example the difference between "ROI" and "SELECTED_ROI", there is only one "--roi" option for FeatureExtraction.exe. When do I use which? What do I fill in? I can't find any documentation on that. 
Also, why is the header "MASK" mentioned in FeatureExtraction.exe help and is the columnname "ROIfile" used in batch_featureExtraction.csv? Also, usually these column names are case-sensitive. Do I use "IMAGES" of "Images" as column name. Then again, why are some of the headers described in FeatureExtraction.exe omitted in the example batch process csv?

**Comment by nwschurink** [comment]
In addition to this, the [documentation](https://cbica.github.io/CaPTk/tr_FeatureExtraction.html#tr_fe_math) of the feature exctraction customization is inconsistent with the example parameterfiles that can be found in the "\data\features" folder.

For example, in the parameter file "1_params_default.csv" the number of bins are regarded to as "Bins" whereas this parameter is refered to as "Num_Bins" in the online documentation.

Also some Lattice extraction parameters are implemented in the abovementioned parameter file, however there is no documentation about these parameters online.

**Comment by sarthakpati** [comment]
Thank you for bringing this to our attention. We will address this in our next release.

**Comment by sarthakpati** [comment]
The latest fixes to address the issues you mentioned. Regarding Lattice, we will wait for the subject matter experts to weigh in @gastouna. 

NGLDM will not be documented till we verify the results, unfortunately. Thank you.

**Comment by sarthakpati** [comment]
Closing because all issues have been addressed. Please reopen if you feel that something is missing/unclear. 

Thank you for using CaPTk!

**Comment by nwschurink** [comment]
Thanks alot! And keep up the great work :)
