### ISSUE TITLE
FeatureExtraction.exe returns NaN for GLCM, GLRLM and NGLDM features

### ISSUE THREAD

**Issue by nwschurink** [CBICA/CaPTk#649]
**Describe the bug**
The feature extraction module returns NaN values for all features that are associated with GLCM, GLRLM and NGLDM. This is the case for running the extraction from command line, as well as from within the CaPTk gui on a case by case basis.

**To Reproduce**
1. Preprocess image to have mean pixel intensity = 300 and pixel standard deviation = 100. Resample image to isotropic (1x1x1mm) pixel dimensions.
2. Load image in CaPTk together with a registered mask defining the ROI (1 at ROI, 0 elsewere)
3. Go to Feature Extraction
4. Use default settings (i.e. Custom in the Customization box, everything checked).
5. Open the results.csv -> find NaN values for GLCM, GLRLM and NGLDM features.

Another step to reproduce the behavior:
Perform steps 1 and 2 from above.
3. Run FeatureExtraction.exe from commandline using batch processing and following parameter file:
![image](https://user-images.githubusercontent.com/12720130/66327494-31360480-e92b-11e9-82a5-e929852a6e7c.png)
or as plain text:
```
FeatureName | ParamName | Type | Range | Default | Comments
-- | -- | -- | -- | -- | --
Generic | Quantization_Extent | String | Image:ROI | ROI | Whether the quantization of Intensities is supposed to happen on a   per-image basis or on a per-ROI basis
Generic | Quantization_Type | String | FixedBinNumber:FixedBinSize:Equal | FixedBinSize | FixedBinNumber (FBN): the bins are uniformly distributed across the   minimum and maximum extent in the ROI/Image as defined under   "Quantization_Extent"; FixedBinSize (FBS): bins are added in a   fixed step between the minimum and maximum extent in the ROI/Image as defined   under "Quantization_Extent" the requested size is provided in   'Bins'; Equal: each bin holds an equal number of intensities
Generic | Resampling | mm | 00:10 | 0 | Resamples all images and masks to this value of voxel/pixel resolution   before computations (0: no resampling): reduce this number of more accuracy
Generic | ResamplingInterpolator_Image | mm | Nearest:Linear:BSpline | Bspline | Type of interpolator to use if resampling is happening
Generic | ResamplingInterpolator_Mask | mm | Nearest:NearestLabel:Linear:BSpline | Nearest | Type of interpolator to use if resampling is happening
Intensity |   |   |   |   |  
Morphologic | Range | Int | (0:25) | 0 | 0:largest connected component in ROI; N: all connected components larger   than (N*10^-6) of total image size are taken into account
Volumetric | Dimension | String | [2D:3D] | 3D | For calculating 2D slice (maximum area along specified axis) or full 3D   volume features
GLCM | Bins | Int |   | 5 | The number of bins (FBN) or size of each bin (FBS) to calculate for the   Histogram
GLCM | Radius | Int | (1:9) | 1 | Radius around the center voxel which can be in mm as well (needs to be   defined as float in same space as input image/mask)
GLCM | Offset | String | [Individual:Average:Combined] | Average | Either individual offset values or averagedcomputation for individual   offsets might not work)
GLRLM | Bins | Int |   | 5 | The number of bins (FBN) or size of each bin (FBS) to calculate for the   Histogram
GLRLM | Radius | Int | (1:9) | 1 | Radius around the center voxel which can be in mm as well (needs to be   defined as float in same space as input image/mask)
GLRLM | Offset | String | [Individual:Average:Combined] | Average | Either individual offset values or averaged
GLSZM | Bins | Int |   | 5 | The number of bins (FBN) or size of each bin (FBS) to calculate for the   Histogram
GLSZM | Radius | Int | (1:9) | 1 | Radius around the center voxel
NGTDM | Bins | Int |   | 5 | The number of bins (FBN) or size of each bin (FBS) to calculate for the   Histogram
NGTDM | Radius | Int | (1:9) | 1 | Radius around the center voxel
NGTDM | Offset | String | [Individual:Average] | Average | Either individual offset values or averaged
NGLDM | Bins | Int |   | 5 |  
NGLDM | Radius | Int | (1:9) | 1 | Radius around the center voxel
NGLDM | Offset | String | [Individual:Average] | Average | Either individual offset values or averaged
```

**Expected behavior**
Meaningful feature values for the GLCM, GLRLM and NGLDM feature classes.

**Screenshots**
Some examples of correctly and incorrectly calculated features:
![image](https://user-images.githubusercontent.com/12720130/66327702-90941480-e92b-11e9-8921-4f4bd7c4db20.png)

![image](https://user-images.githubusercontent.com/12720130/66327788-b1f50080-e92b-11e9-8a16-0bc425aba3f3.png)

**CaPTk Version**
Tried in versions v1.7.2 and v1.7.3.nonRelease.20190912

**Desktop (please complete the following information):**
 - OS: WIndows 7 Enterprise 64-bit (6.1, Build 7601)

**Comment by nwschurink** [comment]
update: currently testing CaPTk version v1.7.0 and it seems that feature extraction (of especially NGLDM matrix) takes a lot longer. Either the code got heavily optimized after v1.7.0 or perhaps it got altered and a bug was introduced. I will let the extraction complete and give an update about the results.

**Comment by sarthakpati** [comment]
So, **NGLDM** is currently not tested and we are in the process of validating it. If possible, could you please provide the mask that you are using?

**Comment by nwschurink** [comment]
Ah ok, I didn't see anything about that so if that's still in testing phase I understand that the NGLDM might have some issues. However, It's still weird the GLCM and GLRLM also produce NaN's right?

As for the mask, I have attached one here:
[TUMOR.nii.gz](https://github.com/CBICA/CaPTk/files/3701411/TUMOR.nii.gz)

**Comment by nwschurink** [comment]
Indeed working on the latest dev build, thanks for pointing out!
