### ISSUE TITLE
Linux installer fails to install to target dir and installs on ~/CaPTk/VERSION

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#671]
**Describe the bug**
_title_

**To Reproduce**
```./CaPTk_1.7.3.Alpha_Installer.bin --target /home/$USER/Programs/CaPTk```

- Everything is installed on ~/CaPTk/VERSION, except 'LICENSE', 'linux-makeself' and 'version' files that go in the target dir.

**Expected behavior**
The application should install only on the specified directory.

**CaPTk Version**
1.7.2 & 1.7.3.alpha installers

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.2

**Comment by sarthakpati** [comment]
Also can be replicated on Ubuntu 18.04

**Comment by dboun** [comment]
Is this fixed?

**Comment by PhucNgo1711** [comment]
Yes
