### ISSUE TITLE
macOS custom install location should not be there since it doesn't work

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#674]
**Describe the bug**
The macOS installer has an option to "change install location" but it does not work.

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by sarthakpati** [comment]
Is still an issue, @PhucNgo1711?

**Comment by PhucNgo1711** [comment]
Yeah it’s a built in .pkg behavior in macOS that everything goes into Applications. The location selector only gives you the disk. This can be solved by using a different installer, like the one @ashishsingh18 suggested.

**Comment by sarthakpati** [comment]
So that is out of scope, at the moment. Closing this with appropriate tag.
