### ISSUE TITLE
nifti to dicom: image flips

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#676]
**Describe the bug**
When you do:
(1) Convert nifti to dicom
(2) Convert the (1) output dicom back to nifti
The image flips.

**To Reproduce**
```bash
$ Utilities -i 3_mask_rt1ce_LPI.nii.gz -o $PWD/dcm_out -n2d $PWD/dcm_t1ce
$ dcm2niix -o $PWD -z y $PWD/dcm_out (this outputs: 20070121115759_t1_axial_stealth-post_7_dcm_out.nii.gz)
```

I put files for your reference at: ```/cbica/home/sakoc/comp_space/Sarthak/20191031```

**CaPTk Version**
1.7.3 Alpha

**Desktop (please complete the following information):**
 - OS: centos7, cbica-cluster

**Comment by sarthakpati** [comment]
Can I ask which image flips? Is it the DICOM in step (1) or is it the NIfTI in step (2)?

**Comment by chiharusako** [comment]
It's in step (1)

**Comment by sarthakpati** [comment]
This should be fixed, now. *BUT*, the output DICOM has the *exact* same information as the reference DICOM. I have put a separate issue (#684) for this.

**Comment by sarthakpati** [comment]
Fixed.
