### ISSUE TITLE
Error in screen layout when dragging images onto fresh install

### ISSUE THREAD

**Issue by waltman** [CBICA/CaPTk#681]
**Describe the bug**
I did a fresh install of the 1.7.3 Alpha to my desktop Ubuntu box. Then I dragged the 4 images you gave me during this morning's testing session (FLAIR.nii.gz, T1.nii.gz, T1CE.nii.gz, and T2.nii.gz) onto the CaPTk window. I saw the same screen layout issue we saw this morning.

**To Reproduce**
1. Fresh install of the 1.7.3 Alpha.
2. Run it with `~/CaPTk/1.7.3.Alpha/captk&`.
3. Drag the 4 images into CaPTk window.
4. Layout looks like in the first screenshot (15-08-06).

Steps to clear the behavior:
1. Click anywhere on the window.
2. Layout changes to look like the second screenshot (15-15-22) which I assume is how it's supposed to look.

**Expected behavior**
This is my first time using CaPTk but I assume the 15-15-22 screenshot is how it's supposed to look.

**Screenshots**

**CaPTk Version**
1.7.3 Alpha

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 18.04)
![Screenshot from 2019-10-31 15-08-06](https://user-images.githubusercontent.com/98597/67979135-0f5e3380-fbf2-11e9-92d6-05004abf03f6.png)
![Screenshot from 2019-10-31 15-15-22](https://user-images.githubusercontent.com/98597/67979147-138a5100-fbf2-11e9-8556-55f47ed4cea1.png)

**Additional context**

**Comment by sarthakpati** [comment]
Thanks for the report! 

I have tagged @ashishsingh18 for this issue, who handles our interface-side coding.

**Comment by ashishsingh18** [comment]
Fixed.
