### ISSUE TITLE
Utilities -or option changes origin when reoriented back

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#682]
**Describe the bug**
When you reorient and reorient back, the origin changes

**Question/suggestion**
Could we add a reference image when we reorient, so the origin exactly matches?

**To Reproduce**

(1) First reorient and reorient back (I'm using a dummy mask here to simplify)
$Utilities -i test_mask_LPI.nii.gz -o test_mask_LPI_RAI.nii.gz -or RAI
$Utilities -i test_mask_LPI_RAI.nii.gz -o test_mask_LPI_RAI_LPI.nii.gz -or LPI

(2) Then apply the mask to image:
This works:
$Utilities -i 0_t1ce_originalLPI.nii.gz -m test_mask_LPI.nii.gz -o test_out1.nii.gz
But this doesn't:
$Utilities -i 0_t1ce_originalLPI.nii.gz -m test_mask_LPI_RAI_LPI.nii.gz -o test_out2.nii.gz
The origin in dimension[0] of the image_1 (test_mask_LPI_RAI_LPI.nii.gz) and image_2 (0_t1ce_originalLPI.nii.gz) doesn't match.
The input mask and mask are not in the same space.

$ Utilities -inf -i test_mask_LPI.nii.gz 
Non-DICOM file detected, will print out ITK Image information.
Property,Value
Dimensions,3
Size,192x256x192
Total,9437184
Origin,95.392044x99.350403x-74.675415
Spacing,0.976562x0.976562x1.000000
Component,unsigned_short
Pixel Type,scalar

$ Utilities -inf -i test_mask_LPI_RAI_LPI.nii.gz
Non-DICOM file detected, will print out ITK Image information.
Property,Value
Dimensions,3
Size,192x256x192
Total,9437184
Origin,95.412354x99.335144x-74.675415
Spacing,0.976562x0.976562x1.000000
Component,float
Pixel Type,scalar

Files are here for your reference:
/cbica/home/sakoc/comp_space/Sarthak/20191031

**CaPTk Version**
1.7.3 alpha

**Desktop (please complete the following information):**
centos 7, cbica-cluster

**Comment by sarthakpati** [comment]
Unfortunately, this is a limitation in the NIfTI system. Well documented: https://github.com/CBICA/CaPTk/issues/624, https://github.com/InsightSoftwareConsortium/ITK/issues/1042

**Comment by chiharusako** [comment]
I forgot to go through the .mha first as it was suggested before.
I re-tried this by reorienting the to .mha first, then convert to nii.gz, then do the same back, but the result is the same:

original LPI nii.gz
Origin,95.392044x99.350403x-74.675415
original LPI nii.gz -> RAI mha -> RAI nii.gz -> LPI mha -> LPI nii.gz
Origin,95.412354x99.335144x-74.675415

If there is a way to get around this, it would be much appreciated.

**Comment by sarthakpati** [comment]
Per our discussion, as soon as the conversion to NIfTI happens, the information gets garbled. So, there are 2 solutions:

1. Keep all processing in MHA
2. After doing re-orientation to original space, perform a single affine registration (which should be super quick using CaPTk)

I am closing this ticket, for now. We can reopen if circumstances change. Please reply as needed. :)
