### ISSUE TITLE
macOS calling complied executables through CaPTk command line fails to parse cwl extension correctly

### ISSUE THREAD

**Issue by PhucNgo1711** [CBICA/CaPTk#686]
**Describe the bug**
Calling the complied executables through CaPTk on the command line will try to find the executable.cwl file in bin location, but cwl files are located at a different directory

**To Reproduce**
1. Run CaPTk through the command line
2. `./{Path_To_CaPTk_exec}/{CaPTk_executable} DeepMedic -u`
3. `sh: /{Path_To_CaPTk{version}.app/Contents/Resources/bin/DeepMedic.cwl: No such file or directory`

**Expected behavior**
The executable should run without any issue

**CaPTk Version**
1.7.3.Alpha

**Desktop (please complete the following information):**
 - OS: macOS
 - Version (including Build information, if any): All versions

**Comment by PhucNgo1711** [comment]
Rolling in a fix with PR GH-687

**Comment by sarthakpati** [comment]
Fixed?

**Comment by PhucNgo1711** [comment]
Fixed

**Comment by PhucNgo1711** [comment]
DeepMedic couldn't find modelConfig.txt. Looks like there is another bug with the directory parsing process. 

Running `-u` works because it found the executable, but when running the actual executable, applications like DeepMedic that need to read files from another location will throw an error.

<img width="882" alt="Screen Shot 2019-11-11 at 12 54 46 PM" src="https://user-images.githubusercontent.com/14838084/68609173-9f1da080-0482-11ea-8912-74d54f972ee9.png">

```
Phucs-MacBook-Pro:~ phucngo$ /Applications/CaPTk_1.7.3.Beta.app/Contents/MacOS/CaPTk_1.7.3.Beta DeepMedic 
-t1 /Users/phucngo/Downloads/SurvivalPredictor_1.6.1/samples/AABM/CONVENTIONAL/T1.nii.gz 
-t2 /Users/phucngo/Downloads/SurvivalPredictor_1.6.1/samples/AABM/CONVENTIONAL/T2.nii.gz 
-t1c /Users/phucngo/Downloads/SurvivalPredictor_1.6.1/samples/AABM/CONVENTIONAL/T1CE.nii.gz 
-fl /Users/phucngo/Downloads/SurvivalPredictor_1.6.1/samples/AABM/CONVENTIONAL/FLAIR.nii.gz 
-o Downloads/SurvivalPredictor_1.6.1/
'modelConfig.txt' was not found in the directory, please check.
Finished successfully.
```

**Comment by sarthakpati** [comment]
You need to pass the model directory using ```-md```.

**Comment by PhucNgo1711** [comment]
Ah that fixed it. Will test around a bit more then I'll close this.

**Comment by sarthakpati** [comment]
Great!
