### ISSUE TITLE
opacity/overlay functionality is not working

### ISSUE THREAD

**Issue by sbakas** [CBICA/CaPTk#688]
**Describe the bug**
opacity/overlay functionality is not working

**To Reproduce**
Load 2 images.
Click on Opacity radio button
check "change opacity"
slider does not show both 2 images but is just slightly changes the intensity of 1 image

**CaPTk Version**
1.7.2

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by sarthakpati** [comment]
This is also present in 1.7.3.Beta

**Comment by sarthakpati** [comment]
Duplicate of #431

**Comment by ashishsingh18** [comment]
Done.
