### ISSUE TITLE
Docker image should be able to show the interface

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#691]
**Is your feature request related to a problem? Please describe.**
The Docker build makes life easier but it doesn't show the interface properly. 

**Describe the solution you'd like**
Enable the visualization layer on Docker.

**References**
- https://stackoverflow.com/a/35040140/1228757
- https://stackoverflow.com/a/55989420/1228757
- https://dev.to/darksmile92/run-gui-app-in-linux-docker-container-on-windows-host-4kde

**Comment by ashishsingh18** [comment]
Can you please add a screenshot?

**Comment by sarthakpati** [comment]
> Can you please add a screenshot?

The Docker image currently available is not able to show the interface at all.

**Comment by sarthakpati** [comment]
Fixed.
