### ISSUE TITLE
Linux installer

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#692]
**Describe the bug**
```--target dir``` doesn't work with or without ```--keep```.  The installer uncompresses everything to target dir and then moves it to ~/CaPTk/1.7.3.alpha (also notice the "alpha" part), except for linux-makeself, version, and LICENSE.

**To Reproduce**
Something like:
```
./CaPTk_1.7.3.Alpha_Installer.bin --target ~/Documents/Programs/CaPTk-1.7.3-beta --keep
```

**Expected behavior**
Just install on the target dir without creating anything on the $HOME directory.

**CaPTk Version**
1.7.3.beta

**Desktop (please complete the following information):**
 - Linux Mint 19.2 (basically Ubuntu 18.04)

**Comment by PhucNgo1711** [comment]
Found the reason why. Also applies to #671 
Working on the a solution now

**Comment by dboun** [comment]
Is this fixed?

**Comment by PhucNgo1711** [comment]
Yes

**Comment by dboun** [comment]
So the installer now works with --target, but if you don't specify it it doesn't install it anywhere (the old behaviour was to install in $HOME/CaPTk

@ashishsingh18 @AlexanderGetka-cbica

**Comment by PhucNgo1711** [comment]
@dboun can you check if it installs to where the installer was downloaded? So without specifying --target it would install to the same directory as the installer

**Comment by dboun** [comment]
> @dboun can you check if it installs to where the installer was downloaded? So without specifying --target it would install to the same directory as the installer

It does not

**Comment by PhucNgo1711** [comment]
The Linux installer now installs CaPTk at the same directory of the `./{captk_installer}.bin` if `--target` is not specified, else will install at the directory of `--target {dir}`
