### ISSUE TITLE
mask and image are flipped for SBRT

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#694]
**Describe the bug**
Mask shows as flipped in SBRT. Please see attached screenshot.

**To Reproduce**
1. Run SBRT Lung Field Segmentation
2. Run SBRT Lung Nodule Segmentation
3. Run SBRT Prognostic modeling.

**Expected behavior**
Mask and image should be properly aligned

**Screenshots**

![image](https://user-images.githubusercontent.com/43445206/68610841-b8c0e700-0486-11ea-801b-b3dba133da17.png)

CaPTk Version : 1.7.3 beta

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise

**Comment by sarthakpati** [comment]
Fixed with https://github.com/sarthakpati/CaPTk/commit/a7364c12c39cdbdc976bde468d9707df7dce5e62
