### ISSUE TITLE
"First launch" window doesn't go away easily on Linux

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#695]
**Describe the bug**
There is no 'X' button. The only way to close it is to click 'Never show again' and then ESC.

**CaPTk Version**
1.7.3.beta

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.2 (Cinnamon)

**Comment by sarthakpati** [comment]
Could you provide more details? Such as the window manager and the desktop being used.

**Comment by dboun** [comment]
WM is the default of cinnamon, called muffin, that I think is based on the one gnome uses

**Comment by ashishsingh18** [comment]
Can you also attach a screenshot of how it looks on Mint?

**Comment by dboun** [comment]
This issue is Cinnamon-only
