### ISSUE TITLE
ITK Snap doesn't open

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#696]
**Describe the bug**
ITK Snap doesn't open

**To Reproduce**
1. Load an image
2. Load ROI
3. Click on ITK Snap

A pop up appears and goes away immediately. But ITK Snap doesn't open.

**Expected behavior**
ITK Snap should open up.

CaPTk Version: 1.7.3 Beta

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise

**Comment by PhucNgo1711** [comment]
<img width="258" alt="Screen Shot 2019-11-13 at 10 27 18 AM" src="https://user-images.githubusercontent.com/14838084/68777916-66a3d100-0600-11ea-875c-1afaeef67d05.png">

I'm seeing the same issue with this error message

**Comment by sarthakpati** [comment]
Fixed.
