### ISSUE TITLE
Common function to guess image type should be present for entire application

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#704]
**Is your feature request related to a problem? Please describe.**
#699 

**Describe the solution you'd like**
The function ```guessImageType``` should be moved under ITK Utilities to take information from DICOM as well.

**Describe alternatives you've considered**
N.A.

**Comment by sarthakpati** [comment]
The function ```cbica::guessImageType``` has been added to utilities. Usage needs to be propagated within CaPTk GUI.

**Comment by ashishsingh18** [comment]
Done, courtesy of @sarthakpati
