### ISSUE TITLE
pseudo-progression application testing module not generating results

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#710]
pseudo-progression application testing module not generating results with the sample data.

**Comment by ashishsingh18** [comment]
@saimarathore This needs more details. If this is working now, can we close this?

**Comment by sarthakpati** [comment]
I am still seeing something similar (email sent with cluster-specific paths to @saimarathore).

**Comment by sarthakpati** [comment]
This should be fixed with #1173
