### ISSUE TITLE
Feature extraction module generating nan values

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#712]
Feature extraction module writes many features with nan values for all the images.
I am using brain tumor images with three ROIs, coming from DeepMedic output. 
Windows
CaPTk 1.7.3

**Comment by sarthakpati** [comment]
Would it be possible for you to share the files (input images, segmentation and feature parameters) in question (either here or securely directly to my email)?

**Comment by dboun** [comment]
I was able to replicate this accidentally. I will send you the data I used

**Comment by sarthakpati** [comment]
Is this replicable for the input data on the current master or my fork? Please check the results using ```~patis/testing/captkMyForkInstall/bin/FeatureExtraction``` and let me know. 

If it does not work, I'd need the following information to replicate:

- Input image(s)
- Mask
- ROI value(s) used
- Parameter file

**Comment by sarthakpati** [comment]
I extracted the features and the ones giving NaN are expected (they are for features where the standard deviation is coming to '0' and the feature calculation involves division by std-dev).

**Comment by dboun** [comment]
> I extracted the features and the ones giving NaN are expected (they are for features where the standard deviation is coming to '0' and the feature calculation involves division by std-dev).

Understandable, but maybe we should inform the user that "some of the features contain nan values and that's because

**Comment by dboun** [comment]
(reopened accidentally, but please see my comment above)

**Comment by sarthakpati** [comment]
> > I extracted the features and the ones giving NaN are expected (they are for features where the standard deviation is coming to '0' and the feature calculation involves division by std-dev).
> 
> Understandable. Maybe we can offer an option on how to treat anavoidable nan values? Like "keep", "remove samples that contain nan values", "remove features that contain nan values". Also we should inform the user when it happens, regardless

Sure! Please put this in as a new feature request and cite this issue.
