### ISSUE TITLE
Feature values mixed when we have different number of ROIs

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#713]
Feature values get mixed when we have different number of ROIs. 
if i have 1|2 for patient 1 and 1|2|3 for patient 2. it would write headers only for 1|2 and not 3. 
if i have 1|2|3 for patient 1 and 1|3 for patient 2. it would write features of label 3 for patient 2 under the features of label 2 of patient 1, without even notifying the user. 
confusing. i needed to go back and had to manually set everything after i got my feature file.

**Comment by sarthakpati** [comment]
I don't think I am following this. Could you give an example?

**Comment by sarthakpati** [comment]
So, after reviewing the requirement, I have decided not to extend this functionality as it would entail having to go through the entire list file and keeping a correlation with the ROI values that are being requested. 

The utility of the batch mode is to give features that can be trained by SVM or some other classical ML algorithm, which basically means that the training set needs to be consistent, i.e., same # of features. 

I am closing this by adding the appropriate tag. Can re-explore once the MITK migration has happened, if needed.
