### ISSUE TITLE
Feature extraction module extracts the same number of features for different configurations

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#716]
Feature extraction module extracts the same number of features no matter if we select the option of 'all images' or 'selected images'
Windows
CaPTk 1.7.3

**Comment by sarthakpati** [comment]
Would it be possible for you to share the files (input images, segmentation and feature parameters) in question (either here or securely directly to my email)?

**Comment by sarthakpati** [comment]
Unable to replicate in current master; closing.
