### ISSUE TITLE
Preferences: select larger font size: messes up interface

### ISSUE THREAD

**Issue by eac-upenn** [CBICA/CaPTk#721]
Use `Preferences` to change the font size larger than 10 pts. Interface gets messed up. See screenshots.

![image](https://user-images.githubusercontent.com/43213897/69992431-a67f1980-1517-11ea-8040-857f57e71b54.png)

![image](https://user-images.githubusercontent.com/43213897/69992452-b139ae80-1517-11ea-83bf-c3be69d1dd5b.png)

![image](https://user-images.githubusercontent.com/43213897/69992465-b7c82600-1517-11ea-8c51-3ed4db565dc0.png)

![image](https://user-images.githubusercontent.com/43213897/69992543-e1814d00-1517-11ea-9808-621b6790e268.png)

Note how on the last screenshot the interface is cut off at the right edge of the screen.

Happens on both internal (3840 x 2160) and external (1920 x 1080) screens.

CaPTk v.1.7.3

OS Name Microsoft Windows 10 Home
Version 10.0.18362 Build 18362

System Manufacturer HP
System Model HP Spectre x360 Convertible
System Type x64-based PC

Processor Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date American Megatrends Inc. F.07, 14-Apr-16
SMBIOS Version 2.8
Embedded Controller Version 38.22
BIOS Mode UEFI

**Comment by ashishsingh18** [comment]
There is no easy way to fix this. All other major software such as Slicer, MITK workbench behave the same way. Others do not give an option to change font at all. We knew this issue before implementation. @sarthakpati and I also discussed about it before implementation. We show a preview of the effect as the new font selection happens so the assumption is that the user knows what is being done. Besides, the user has an option to change the font back.

Tagging @sarthakpati @MarkBergman-cbica @dboun

**Comment by eac-upenn** [comment]
I'm 100% that the efficient way to fix this is just to not let the user change the UI font or size. If we want to get fancy in the future, offer Normal and Large, or even Small,. Normal, and Large UI options. But if we're offering more customizability than the Windows UI we're bending over backwards.

(Mind you, this assumes that we deal gracefully with high density monitors.)

**Comment by AlexanderGetka-cbica** [comment]
This has been addressed with PR #822. 
Considering the concerns of accessibility and usability, the following change has been applied:

When you apply changes in the preferences window, you now get a windows-style "Are you sure you want to keep these changes?" preview (of the actual application, not just some sample text) with a confirmation dialog. The confirmation dialog itself uses only default style settings, so it _should_ be both visible and readable no matter what... and if not, it auto-reverts the changes after a few seconds if the user doesn't explicitly confirm they want to keep them.

Closing this.
