### ISSUE TITLE
drag nested folders of images into Captk window -- freezes Captk

### ISSUE THREAD

**Issue by eac-upenn** [CBICA/CaPTk#724]
Drag a folder containing two or more folders each containing `.nii.gz` files into Captk window. Import progress bar freezes at 100%. Captk is frozen, must quit application.

## Steps to Reproduce the Problem
Have any file structure similar to
```
    foo
        bar
            file1.nii.gz
        baz
            file2.nii.gz
```
Drag `foo` into Captk window.

## Specifications

CaPTk v.1.7.3

OS Name Microsoft Windows 10 Home
Version 10.0.18362 Build 18362

System Manufacturer HP
System Model HP Spectre x360 Convertible
System Type x64-based PC

Processor Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date American Megatrends Inc. F.07, 14-Apr-16
SMBIOS Version 2.8
Embedded Controller Version 38.22
BIOS Mode UEFI

**Comment by ashishsingh18** [comment]
Done.
