### ISSUE TITLE
Drawing: can't Undo sphere

### ISSUE THREAD

**Issue by eac-upenn** [CBICA/CaPTk#725]
## Steps to Reproduce the Problem

  1. Open file `. . . \SurvivalPredictor\SurvivalPredictor_1.6.1\samples\AAOG\CONVENTIONAL\FLAIR.nii.gz`. (Or really any image.)
  2. Select `Drawing` tab.
  3. Change `Marker Size` to `9x9`.
  3. Select the `Sphere` tool.
  2. Click `Undo`.

Nothing happens. The sphere never disappears. (At least, I waited 10 minutes. . . .)

`Clear Selected Label` and `Clear All Labels` will get rid of the sphere.

`Undo` works on all the other drawing tools.

## Specifications

CaPTk v.1.7.3

OS Name Microsoft Windows 10 Home
Version 10.0.18362 Build 18362

System Manufacturer HP
System Model HP Spectre x360 Convertible
System Type x64-based PC

Processor Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date American Megatrends Inc. F.07, 14-Apr-16
SMBIOS Version 2.8
Embedded Controller Version 38.22
BIOS Mode UEFI

**Comment by sarthakpati** [comment]
I have not worked on this, so I should not be assigned this task. Unassigned.

**Comment by ashishsingh18** [comment]
@sarthakpati Sphere drawing implementation was done by you.

**Comment by sarthakpati** [comment]
Argh, forgot about that (#412). Anyway, investigating...

**Comment by sarthakpati** [comment]
For some weird reason, the following piece of code is getting invoked twice during sphere drawing:

> fMainWindow::UpdateAction

Which messes up the undo function. Investing why this is happening.

**Comment by sarthakpati** [comment]
Followed the chain of all drawing events:
```
SlicerManager::Execute -->
	SlicerManager::ActionAdded -->
		fMainWindow::UpdateActionInMain --> 
			fMainWindow::UpdateActionQ -->
				fMainWindow::UpdateAction -->
					fMainWindow::mActions incremented
```

For some reason, there are **2** ```mActions``` getting added for Sphere drawing but **1** for all the others. No idea why this is happening and I need some help in tracking this down.

**Comment by sarthakpati** [comment]
Done. Thanks, @ashishsingh18

**Comment by ashishsingh18** [comment]
Welcome @sarthakpati, A good side effect - the unwanted memory allocation for shapebuffer was also handled.

**Comment by sarthakpati** [comment]
> Welcome @sarthakpati, A good side effect - the unwanted memory allocation for shapebuffer was also handled.

Reference: https://github.com/CBICA/CaPTk/pull/781/commits/05e5523323980f1da199b0f092c8293eea0e544e#diff-e6517bfa16157ee163eb8b82a705e758R300
