### ISSUE TITLE
the icon is a brain

### ISSUE THREAD

**Issue by eac-upenn** [CBICA/CaPTk#728]
Whereas I think the project is moving towards being more general?

**Comment by rmsppu** [comment]
What icon do you propose?

**Comment by eac-upenn** [comment]
> What icon do you propose?
Hadn’t thought that far ahead. If we want the icon to say “medical imaging analysis” in the space of a few pixels, maybe a greyscale brain MRI (although not a brain) is as good a shorthand as any. But, also, it’s not an urgent issue so we can afford to take the time to come up with better ideas?

— Eric.

Eric A. Cohen   |   Eric.Cohen@pennmedicine.upenn.edu
Data Analyst
Computational Breast Imaging Group
University of Pennsylvania

**Comment by ashishsingh18** [comment]
Done, courtesy @sarthakpati 
Refer #1194
