### ISSUE TITLE
Can crash application calculating features

### ISSUE THREAD

**Issue by eac-upenn** [CBICA/CaPTk#730]
## Description

Under some circumstances -- I think it has to do with an invalid ROI -- feature extraction will crash the app.

## To Reproduce

  1. Open an image, though not an ROI.
  This doesn't happen with all images, but it happens with all images I've tested in `SurvivalPredictor_1.6.1`.
  For instance, open `C:\Users\CohenE\Downloads\SurvivalPredictor\SurvivalPredictor_1.6.1\samples\AAAE\CONVENTIONAL\T2.nii.gz`
  1. In the `Drawing` tab draw a *two-dimensional* region. Not a sphere. For instance, a circle:
  ![image](https://user-images.githubusercontent.com/43213897/70145196-882b3200-166d-11ea-8350-dc9c7237db13.png)
  1. In the `Feature Extraction` tab, turn off any or all of the features, except for `1st Order Statistics` which is mandatory.

  1. Keep `Lattice Computation` checked. This is necessary.

  1. `Compute + Save`

![image](https://user-images.githubusercontent.com/43213897/70145498-3931cc80-166e-11ea-84b3-ead60acfcb84.png)

### Comment

I guess trying to compute this isn't meaningful, but it still shouldn't crash.

## Log file

Is not informative.
`2019-12-04.log`
```
2019:12:04,07:49:41;CaPTk;CohenE;applying DARK theme
2019:12:04,07:49:42;CaPTk;CohenE;file reading succeeded, qss file path = C:/CaPTk_Full/1.7.3/bin/../data/../etc/captk.qss
2019:12:04,08:00:00;CaPTk;CohenE;applying DARK theme
2019:12:04,08:00:00;CaPTk;CohenE;file reading succeeded, qss file path = C:/CaPTk_Full/1.7.3/bin/../data/../etc/captk.qss
2019:12:04,08:04:01;CaPTk;CohenE;applying DARK theme
2019:12:04,08:04:01;CaPTk;CohenE;file reading succeeded, qss file path = C:/CaPTk_Full/1.7.3/bin/../data/../etc/captk.qss
2019:12:04,08:11:56;CaPTk;CohenE;applying DARK theme
2019:12:04,08:11:56;CaPTk;CohenE;file reading succeeded, qss file path = C:/CaPTk_Full/1.7.3/bin/../data/../etc/captk.qss

```
## Specifications

  - CaPTk v.1.7.3  
  - Windows 7 Enterprise
  - SP 1
  - 64-bit
  - Intel Core 15-4570
  - 20GB RAM

**Comment by sarthakpati** [comment]
Fixed. Please reopen/comment if this persists in the new build(s).
