### ISSUE TITLE
default feature save in hidden directory?

### ISSUE THREAD

**Issue by eac-upenn** [CBICA/CaPTk#734]
When I do feature extraction, my default save location for `features.csv` is to `C:/Users/<username>/.CaPTk/1.7.3/features.csv`. Won't `.CaPTk` be invisible on Linux and MacOS machines? Someday someone will go looking for their `features.csv` and get confused . . . ?

## Specifications

  - CaPTk v.1.7.3

  - Windows 7 Enterprise
  - SP 1
  - 64-bit
  - Intel Core 15-4570
  - 20GB RAM

**Comment by sarthakpati** [comment]
So, the idea is that the users see this location and change to some place appropriate. Do you have a suggestion as to where else the default should be?

**Comment by sarthakpati** [comment]
Closing issue; please reopen with suggestion for another save location.

**Comment by eac-upenn** [comment]
How about the home directory? It exists in both Windows and Linux, lots of applications default there, and it's cluttered but at least not invisible.

**Comment by sarthakpati** [comment]
Sure!
