### ISSUE TITLE
DOC: dead link from Feature Extraction to Technical Reference page

### ISSUE THREAD

**Issue by eac-upenn** [CBICA/CaPTk#735]
`How To Guides > Feature Extraction`, `https://cbica.github.io/CaPTk/ht_FeatureExtraction.html`:

Link from 

>For more information on the defaults of the feature extraction and how to customize it, please see our technical reference page.

`https://cbica.github.io/CaPTk/tr_fe_defaults.html` leads to Page not found.

**Comment by sarthakpati** [comment]
Fixed.
