### ISSUE TITLE
The render windows can be small or huge depending on resolution

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#739]
**Describe the bug**
The application is unusable on HD screens (aka most older/cheaper laptops). This would normally be fixed from the UI files, but in our case there could be code that runs the first time the application launched that always make the render window take 70% of the vertical real estate.

**Expected behavior**
The render window size should always be the same percentage of the screen (and maybe even adjustable?)

**CaPTk Version**
1.7.3

**Additional context**
Kind of related to issue #137.

**Comment by ashishsingh18** [comment]
Can you attach a screenshot please?

**Comment by dboun** [comment]
![captk_resolution](https://user-images.githubusercontent.com/39439832/70835374-e4f3be80-1dca-11ea-81fe-7ad5ab1a23ff.png)

1366x768 (16:9)

**Comment by ashishsingh18** [comment]
workaround with #759

**Comment by ashishsingh18** [comment]
Automatic undock of images panel on lower resolution provides a workaround for this issue. There is also a way now to manually undock if needed.

**Comment by ashishsingh18** [comment]
Done.
