### ISSUE TITLE
How does captk decide when an image is eligible for `Preprocessing > Mammogram Preprocessing`?

### ISSUE THREAD

**Issue by eac-upenn** [CBICA/CaPTk#752]
![Capture](https://user-images.githubusercontent.com/43213897/70565897-05204500-1b61-11ea-9c39-92c6f4f877c5.PNG)

![image](https://user-images.githubusercontent.com/43213897/70565909-0c475300-1b61-11ea-8e0a-9d66d1065975.png)

Source files:

  - Sample data, `. . . \LIBRA\LIBRA_1.6.0\1\Case1.dcm`
  - `http://www.dclunie.com/pixelmedimagearchive/upmcdigitalmammotomocollection/index.html` file `MammoTomoUPMC_Case2.tar.bz2` unpacked and converted by Captk to Nifti,

**Comment by MarkBergman-cbica** [comment]
> Sample data, . . . \LIBRA\LIBRA_1.6.0\1\Case1.dcm

Does this mean you're using CaPTk 1.6.0?

If so, please try the latest release (1.7.3): https://www.nitrc.org/frs/?group_id=1059

**Comment by sarthakpati** [comment]
The modality can be changed. Please see related documentation: https://cbica.github.io/CaPTk/Getting_Started.html#gs_imageLoading

**Comment by sarthakpati** [comment]
I have elaborated the error message to be the following:

> You have tried running an application that is only valid for mammogram images. Please load the correct image type or change the modality using the combo-box beside the image name.

Is this more acceptable, @eac-upenn?

**Comment by sarthakpati** [comment]
Closing; please reopen if issue persists.
