### ISSUE TITLE
Opening very large file wedges machine

### ISSUE THREAD

**Issue by eac-upenn** [CBICA/CaPTk#753]
Dragged `http://www.dclunie.com/pixelmedimagearchive/upmcdigitalmammotomocollection/index.html
` 

`. . . \MammoTomoUPMC_Case2\Case2 [Case2]\20071120 080520 [ - MAMMOGRAM DIGITAL SCR BILAT]\Series 73200000 [MG - R MLO Breast Tomosynthesis Image]\1.3.6.1.4.1.5962.99.1.2280943358.716200484.1363785608958.406.0.dcm` 

919,574 KB

into Captk window.

Machine became unresponsive, even to ctrl-alt-del, needed hard power cycle.

EDIT: Dragged 159,000KB Nifti that resulted from converting that Dicom to Nifti (converted by Captk) and same crash resulted.

## Expected Behavior

Doesn't do that.

## Desired Behavior

It's okay if I can't do that, it would be better if it failed more gracefully,

## Specifications
 
  - CaPTk v.1.7.3
  - Windows 7 Enterprise
  - SP 1
  - 64-bit
  - Intel Core 15-4570
  - 20GB RAM

**Comment by ashishsingh18** [comment]
@eac-upenn I am able to load the image into CaPTk on my machine. Since the image is big it takes time to load but eventually the image shows up. However my machine has 32GB RAM.

**Comment by eac-upenn** [comment]
Good to know. Yeah, it’s fine if it doesn’t load on a smaller machine, but it needs to fail more gracefully.


— Eric.

Eric A. Cohen   |   Eric.Cohen@pennmedicine.upenn.edu
Data Analyst
Computational Breast Imaging Group
University of Pennsylvania
