### ISSUE TITLE
BiasCorrection and Denoise-SUSAN crash app on 2-D images

### ISSUE THREAD

**Issue by eac-upenn** [CBICA/CaPTk#758]
## Actual Behavior

  1. Drag a 2-D image into Captk (i.e., any image with third dimension of 1 voxel).

  1. Apply `Preprocessing` > `BiasCorrection` or `Denoise-SUSAN`.

  1. **CaPTk.exe has stopped working**

## Which images?

Not all. At first I thought it was file size, now I think they fail on 2-D but not 3-D images. Further testing would be required to make this definite, and to test Dicom versus Nifti.

## Specifications

 
  - CaPTk v.1.7.3
  - Windows 7 Enterprise
  - SP 1
  - 64-bit
  - Intel Core 15-4570
  - 20GB RAM

**Comment by sarthakpati** [comment]
Done.
