### ISSUE TITLE
How to re-dock control palette?

### ISSUE THREAD

**Issue by eac-upenn** [CBICA/CaPTk#759]
The palette with the `Images` list and drawing and so on: 

  1. Click the doohickey ![image](https://user-images.githubusercontent.com/43213897/70829869-cf779800-1dbc-11ea-90dc-e7df57530888.png) in the upper-right of the palette to undock it.

  1. How do I re-dock it?

(Side note, that doohickey is almost invisible in dark mode: ![image](https://user-images.githubusercontent.com/43213897/70829959-0b126200-1dbd-11ea-9205-ece68c19f55b.png))

## Specifications
 
  - CaPTk v.1.7.3
  - Windows 7 Enterprise
  - SP 1
  - 64-bit
  - Intel Core 15-4570
  - 20GB RAM

**Comment by ashishsingh18** [comment]
Done.
