### ISSUE TITLE
Dicom displays incorrectly

### ISSUE THREAD

**Issue by eac-upenn** [CBICA/CaPTk#761]
## Steps to Reproduce the Problem

  1. Open file `10` from `https://medimodel.com/sample-dicom-files/class-3-malocclusion/`. (Using either `File > Load` or drag and drop.) Actually, I think any of the files from that directory will do this.
  1. Image displays incorrectly (look at the left- and right-hand panels). Maybe this is because `Spacing` is not the same in all three dimensions?
![Captk capture 0001](https://user-images.githubusercontent.com/43213897/70918774-a0943880-1fed-11ea-9dfe-353417dd168a.PNG)
  1. Change the slice by modifying any of the `Current Slice` values and pressing `Update`.
  1. Badness zooms in:
![Captk capture 0002](https://user-images.githubusercontent.com/43213897/70918922-e94bf180-1fed-11ea-93b8-00f569eeb922.PNG)

EDIT: I thought the problem might be that the voxels were not equal dimensions. But the Dicoms from `ftp://medical.nema.org/medical/dicom/Multiframe/CT/` have unequal voxel dimensions, and the images I"ve tested display fine.

## Specifications
 
  - CaPTk v.1.7.3
  - Windows 7 Enterprise
  - SP 1
  - 64-bit
  - Intel Core 15-4570
  - 20GB RAM

**Comment by ashishsingh18** [comment]
@eac-upenn I am not able to replicate the issue on v1.7.3 with the dataset you mentioned(https://medimodel.com/sample-dicom-files/class-3-malocclusion/). The images appear to be fine. Please see the screenshot below. 

![image](https://user-images.githubusercontent.com/43445206/71424487-015fe880-2660-11ea-92ae-fbad3f967919.png)

Can you re-check please?

**Comment by ashishsingh18** [comment]
This specific dataset ( [(https://medimodel.com/sample-dicom-files/class-3-malocclusion/](https://medimodel.com/sample-dicom-files/class-3-malocclusion/) ) loads in 1.8.0Alpha as well.

Closing this, please re-open if you see the issue again.
