### ISSUE TITLE
Is it worth figuring out why these Dicom files won't load?

### ISSUE THREAD

**Issue by eac-upenn** [CBICA/CaPTk#762]
## Observed behavior

Try to open any file downloaded (and unzipped) from [https://genesisdigital.com/sampleimages.php](url) `Carestream Vita - Sample DICOM Images`.

`Dicom Load Failed`

I mean, we don't know where those images came from or whether they're well-formed or what. But, anyway, they won't load.

## Specifications

  - CaPTk v.1.7.3
  - Windows 7 Enterprise
  - SP 1
  - 64-bit
  - Intel Core 15-4570
  - 20GB RAM

**Comment by ashishsingh18** [comment]
We have limited dicom support at the moment primarily for structural MR images and some MG and CT modalities. The carestream images are for CR modality and have never been tested. The next major version of CaPTk will have better dicom support and will perhaps support CR modality as well.

**Comment by eac-upenn** [comment]
Okay. A more informative fail message would be nice. And the limits on DICOM support should be in the doc.

**Comment by ashishsingh18** [comment]
Done.
