### ISSUE TITLE
Current Slice invalid value is still displayed

### ISSUE THREAD

**Issue by eac-upenn** [CBICA/CaPTk#763]
## Steps to Reproduce the Problem

  1. Enter an invalid (out-of-range) value in the X, Y, or Z field of `Current Slice`.

  1. Press `Update`.

  1. View does not change (as coordinate was invalid). But invalid value stays in the field where you entered it.

## Specifications

  - CaPTk v.1.7.3
  - Windows 7 Enterprise
  - SP 1
  - 64-bit
  - Intel Core 15-4570
  - 20GB RAM

**Comment by AlexanderGetka-cbica** [comment]
This is fixed and will be in my next PR.
