### ISSUE TITLE
Resampling rate error for feature extraction

### ISSUE THREAD

**Issue by kavifatania** [CBICA/CaPTk#766]
## Actual Behavior
When using the feature extraction function, I keep getting an error message which says 'The resampling rate is set to 3.0 for computation efficiency, please reduce it to increase accuracy of extracted features'. I get this message despite changing the resampling rate.

## Steps to Reproduce the Problem

  1. Load T1,T1+c, T2, FLAIR images
  2. Load ROI 
  3. Use extract features function

## Specifications

  - Version: 1.7.2 
  - Platform: Windows
  - Subsystem:

**Comment by sarthakpati** [comment]
I think this has been fixed in 1.7.3. Please comment/reopen if you are able to reproduce this in the latest release. Thank you.
