### ISSUE TITLE
Image registration

### ISSUE THREAD

**Issue by kavifatania** [CBICA/CaPTk#768]
**Describe the bug**
When using the image registration for brain mri, an error message comes up 'Couldn't register with the default parameters; please use command line functionality'. Using command line doesn't solve the problem.

**To Reproduce**
1. Load T1, T2, FLAIR, T1+gd images downloaded from TCIA. Images are not volumetric sequences.
2. Click on 'Preprocessing', Select 'Registration'
3. Select 'Affine', use default parameters
4. Target image is T1+gd, moving images are the other sequences (T1, T2, FLAIR)

**Expected behavior**
To register the T1, T2, FLAIR sequences to the T1+gd sequence

**CaPTk Version** 1.7.3

**Desktop (please complete the following information):**
 - OS: Windows
 - Version (including Build information, if any): Windows 7 Enterprise

**Comment by sarthakpati** [comment]
This should be fixed. Please reopen if issues persist after current nightly.
