### ISSUE TITLE
Existance of Git Submodules is not clear in the documentation

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#773]
**Describe the bug**
CaPTk contains two git submodules [[what is a submodule?]](https://git-scm.com/book/en/v2/Git-Tools-Submodules) [[where they are defined in the repo]](https://github.com/CBICA/CaPTk/blob/07b4f2e5469da765c6a68425d972504d25d3168f/.gitmodules). If they are not init'd and updated the build of CaPTk fails. 

**To Reproduce**
1. Clone CaPTk using ```git-lfs clone https://github.com/cbica/captk.git``` (```git lfs``` under Windows)
2. Build
3. 💥

**Solution**
Just change the documentation from:
```
git clone https://github.com/cbica/captk.git
```
to:
```
git-lfs clone --recurse-submodules https://github.com/cbica/captk.git (use "git lfs" instead on Windows)
```

**CaPTk Version**
1.7.3

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.2 (but this is probably relevant on Win too?)

**Disclaimer**

I have never tried the command suggested, and I'm not sure if ```--recurse-submodules``` works with lfs.

**Comment by dboun** [comment]
@ashishsingh18 @Getkablue

This was one of the issues yesterday, right?

**Comment by Getkablue** [comment]
Yes, this caused the build to fail yesterday

**Comment by sarthakpati** [comment]
LFS and submodules are separate things in the Git world. This issue has been fixed with https://github.com/sarthakpati/CaPTk/commit/69d156c269831ccf9f2c5d7a873f0ff17897a14f
