### ISSUE TITLE
Can't drag n drop images to the undocked image panel.

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#782]
**Describe the bug**
Can't drag n drop images to the undocked image panel. Drag n dropping only works for the main window

**To Reproduce**
1. Undock image panel
2. Drag n drop images to it (doesn't work)
3. Drag n drop images to the main window behind it (works)

**Expected behavior**
Users usually/naturally will try to drag n drop images to the image panel.

**CaPTk Version**
1.7.3

**Desktop (please complete the following information):**
Linux Mint 19.3

**Comment by AlexanderGetka-cbica** [comment]
Fixed in PR#803
