### ISSUE TITLE
running the pseudoprogression infiltration index crashes CaPTk 

### ISSUE THREAD

**Issue by AlexanderGetka-cbica** [CBICA/CaPTk#787]
**Describe the bug**
CaPTk crashes when you try to run the glioblastoma pseudoprogression infiltration index

**To Reproduce**
1. Open CaPTk
2. Go to Applications -> Glioblastoma PseudoProgression Infiltration Index
3. Click the "Pseudo-Progression estimation on a batch of subjects" radio button
4. Enter appropriate model and test directories (instructions for file structure are at https://cbica.github.io/CaPTk/Glioblastoma_Pseudoprogression.html)
5. Enter an appropriate output directory
6. Click "confirm". If the program doesn't throw an error about the directories you provided, then the program will soon crash (with an assertion failure).

**Expected behavior**
The pseudo-progression module would run without crashing immediately.

**Screenshots**

**CaPTk Version**
1.7.2

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Version (including Build information, if any): 18.04

**Additional context**
PseudoProgressionEstimator::ReadAllTheModelParameters() seems to call an out-of-bounds value in a matrix. Not yet sure why, as it seems to load the size information from that matrix first.

**Comment by dboun** [comment]
Similarly, when I try to run it on Linux Mint 19.3 (similar to ubuntu 18.04) I get

```The specified directory does not have model files.```

but I'm pretty sure I supplied the correct model dir

**Comment by dboun** [comment]
Survival, which follows the same interface, doesn't work for my either, it says:

```No patient inside the given input directory has required scans```

**Comment by dboun** [comment]
@saimarathore LOOKHERE

**Comment by dboun** [comment]
> Similarly, when I try to run it on Linux Mint 19.3 (similar to ubuntu 18.04) I get
> 
> `The specified directory does not have model files.`
> 
> but I'm pretty sure I supplied the correct model dir

![Screenshot from 2020-01-23 16-06-24](https://user-images.githubusercontent.com/39439832/73023878-62631380-3dfa-11ea-8ae7-e99240b1401e.png)

@saimarathore I tried on the current master of CaPTk. Survival did work. Pseudoprogression **didn't**, see screenshot

**Comment by ashishsingh18** [comment]
This works fine in 1.8.0Alpha.
