### ISSUE TITLE
FeatureExtraction fails when multiple processes try to access same parameter file

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#798]
**Describe the bug**
When multiple processes try to use the same parameter file, FE crashes and messes the file up.

**Additional context**
Reported by Omid when trying to run 20k FE jobs together.

**Comment by sarthakpati** [comment]
This can be solved be checking for File locks.

**Comment by sarthakpati** [comment]
Perhaps this could be a solution: https://en.cppreference.com/w/cpp/thread/shared_lock/lock

**Comment by sarthakpati** [comment]
> Perhaps this could be a solution: https://en.cppreference.com/w/cpp/thread/shared_lock/lock

This is only an **in-process** lock and doesn't work globally. We need a cross-platform, global solution that doesn't rely on pulling in Boost.

**Comment by sarthakpati** [comment]
Really wary of putting this functionality. This answer sums up what I have found, so far: https://stackoverflow.com/a/2059059/1228757

**Comment by dboun** [comment]
@sarthakpati Honestly, at this point I think you should go for https://doc.qt.io/qt-5/qlockfile.html

Qt is already part of the repo anyway, you aren't saving anything by not using (unless you do a build with static libraries, but still it's way easier than anything else)

**Comment by sarthakpati** [comment]
This commit (https://github.com/sarthakpati/CaPTk/commit/f45f85221f5cfae7ce626bb64bacc9dbf53358e3) provides a temporary workaround. This issue still needs a solid concurrency solution.

**Comment by sarthakpati** [comment]
The parameter file writing is now removed (https://github.com/CBICA/CaPTk/pull/802/commits/5f761fd58823530c07f587c3a85f1e0a3ad72f77)
