### ISSUE TITLE
Feature Extraction with segmentation labels in only one slice

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#808]
**Describe the bug**
With 3D image + 3D mask. Draw on mask on only one slice. Feature extraction crashes.

**To Reproduce**
1. Load a (real) 3D image to CaPTk
2. Go to "drawing tools" > choose "Circle" > draw a circle in only one slice 
3. Run lattice feature extraction > crash

**Expected behavior**
If there is actually no lattice points in the thin slice as I am assuming happens, then CaPTk shouldn't crash but inform the user.

**Output**
```bash
Starting computation of selected features.
[>                                                                                        [==================================================>                                      [==================================================>                                                 ] 50% 0s
Finished calculating features, writing the output.
Received signal 11 SEGV_MAPERR 7ffe7756e000
#0 0x7f4be6a98a4f <unknown>
#1 0x7f4be6a98e4b <unknown>
#2 0x7f4be6a994ce <unknown>
#3 0x7f4be28b5890 <unknown>
#4 0x00000132e733 <unknown>
#5 0x00000104680a <unknown>
#6 0x000000f8ad98 <unknown>
#7 0x000000f8cce9 <unknown>
#8 0x00000105e115 <unknown>
#9 0x7f4be2f7d8a9 QMetaObject::activate()
#10 0x7f4be3ede022 QAbstractButton::clicked()
#11 0x7f4be3ede224 QAbstractButtonPrivate::emitClicked()
#12 0x7f4be3edfdbe QAbstractButtonPrivate::click()
#13 0x7f4be3edff15 QAbstractButton::mouseReleaseEvent()
#14 0x7f4be3e35828 QWidget::event()
#15 0x7f4be3df7b3c QApplicationPrivate::notify_helper()
#16 0x7f4be3dff30f QApplication::notify()
#17 0x7f4be2f51e28 QCoreApplication::notifyInternal2()
#18 0x7f4be3dfe24a QApplicationPrivate::sendMouseEvent()
#19 0x7f4be3e4f231 QWidgetWindow::handleMouseEvent()
#20 0x7f4be3e51eeb QWidgetWindow::event()
#21 0x7f4be3df7b3c QApplicationPrivate::notify_helper()
#22 0x7f4be3dfed30 QApplication::notify()
#23 0x7f4be2f51e28 QCoreApplication::notifyInternal2()
#24 0x7f4be35bb767 QGuiApplicationPrivate::processMouseEvent()
#25 0x7f4be35bcd15 QGuiApplicationPrivate::processWindowSystemEvent()
#26 0x7f4be35989fb QWindowSystemInterface::sendWindowSystemEvents()
#27 0x7f4bd739a81a xcbSourceDispatch()
#28 0x7f4bd9b59417 g_main_context_dispatch
#29 0x7f4bd9b59650 <unknown>
#30 0x7f4bd9b596dc g_main_context_iteration
#31 0x7f4be2fa91ef QEventDispatcherGlib::processEvents()
#32 0x7f4be2f5078a QEventLoop::exec()
#33 0x7f4be2f59190 QCoreApplication::exec()
#34 0x000000440366 <unknown>
#35 0x7f4be0d24b97 __libc_start_main
#36 0x0000004782a9 <unknown>
  r8: 0000000000000001  r9: 000000001b8b26b6 r10: 0000000005e78010 r11: 0000000000000002
 r12: 0000000000000000 r13: 0000000000000087 r14: 00007ffe77565b58 r15: 00007ffe77564760
  di: 000000001b9e5610  si: 0000000005e78048  bp: 0000000000008498  bx: 0000000000000086
  dx: 00000000000000f0  ax: 00007ffe77565b68  cx: 0000000000000004  sp: 00007ffe77560e60
  ip: 000000000132e733 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 00007ffe7756e000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

```

**CaPTk Version**
1.7.3

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3

**Additional context**
I actually noticed this when porting ROIConstruction to MITK. I tried to run it on a similar slice but the ROIProperties vector contained **a lot** of elements where the "label" was gibberish. However ```GetNumberOfValidLatticePoints()``` seems to return 0 in such cases? Not super sure though

( paging @sarthakpati )

**Comment by sarthakpati** [comment]
Is this still an issue on the newer builds?

**Comment by ashishsingh18** [comment]
@dboun can you try this on version 1.7.5?

**Comment by sarthakpati** [comment]
This is still there in the new builds; I just confirmed. 

Is there an easy way to detect such a mask in ITK?

**Comment by sarthakpati** [comment]
Running 1.7.3:

![image](https://user-images.githubusercontent.com/11719673/73214039-5db29e00-411f-11ea-8cfd-76ce3e9e330e.png)

Features successfully generated.

**Comment by sarthakpati** [comment]
Running on 1.7.3 (all defaults):

![image](https://user-images.githubusercontent.com/11719673/73214511-5a6be200-4120-11ea-9c48-b3c0b4b85836.png)

Features successfully extracted:

![image](https://user-images.githubusercontent.com/11719673/73214547-6c4d8500-4120-11ea-9c05-7973fb101c75.png)

It would be helpful to provide the mask.

**Comment by dboun** [comment]
@sarthakpati 
I tried to run it on 1.7.6 but couldn't because of #810 

As far as 1.7.3 goes, I realized that my 1.7.3 was a beta and not the stable one, that may play a role.

I tried it on 1.7.5 and it worked, so I'm closing this as maybe-fixed/non-reproducable
