### ISSUE TITLE
Feature Extraction doesn't work at all in 1.7.6

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#810]
**Describe the bug**
It says error: "No valid images selected!"

**To Reproduce**
1. Load 1+ (brain?) images
2. Load their segmentation
3. feature extraction panel > 'Compute + Save'

**Screenshots**
![CaPTk-FE-issue](https://user-images.githubusercontent.com/39439832/73279275-e03c6b80-41ba-11ea-9d05-5de2f2c6325b.png)

**CaPTk Version**
1.7.6 (stable)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3

**Comment by sarthakpati** [comment]
Fixed.

**Comment by dboun** [comment]
@sarthakpati 

While it doesn't crash now, it doesn't produce features either.

My output file is empty

```csv
SubjectID | Modality | ROILabel | FeatureFamily | Feature | Value | Parameters
-- | -- | -- | -- | -- | -- | --
```

(if you have the brats dataset, try Brats18_2013_2_1_flair.nii.gz + seg, and choose to FE on label 1

**Comment by sarthakpati** [comment]
Done. Please check by compiling the [related fork](https://github.com/sarthakpati/CaPTk/tree/fix_810) instead of waiting for this to get merged and reopen issue if needed. Thanks.

**Comment by dboun** [comment]
> Please check by compiling the [related fork](https://github.com/sarthakpati/CaPTk/tree/fix_810) instead of waiting for this to get merged

Haha that's what I did the last time, but I had to do a complete rebuild and it got approved before I had the chance to test it!
