### ISSUE TITLE
Mask Opacity defaults to 0.1, but it should be 1.0

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#811]
**Describe the bug**
The mask opacity does not get initialized properly.

**To Reproduce**
1. Load image + ROI

**Expected behavior**
Mask Opacity should default to 1.0.

**Screenshots**
If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/11719673/73283173-b2f2bc00-41c0-11ea-8d1b-6fc6fd33424b.png)

**CaPTk Version**
1.7.6

**Comment by AlexanderGetka-cbica** [comment]
Oops, I messed this up when I was fixing the previous opacity change problem.
Pushing a fix for this to my branch.
