### ISSUE TITLE
deepmedic model incompatible

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#816]
**Describe the bug**
When running deepmedic, it says:
The version of model is incompatible with this version of CaPTk.

**To Reproduce**
in cubic-login2:

[braintumoruser@cubic-login2 ACUD_2019.06.13]$/cbica/home/patis/projects/captk_myFork/bin/install/appdir/usr/bin/DeepMedic -t1 ACUD_2019.06.13_t1_LPS_rSRI.nii.gz -t1c ACUD_2019.06.13_t1ce_LPS_rSRI.nii.gz -t2 ACUD_2019.06.13_t2_LPS_rSRI.nii.gz -fl ACUD_2019.06.13_flair_LPS_rSRI.nii.gz -o $PWD -md /cbica/home/patis/projects/captk_myFork/bin/install/appdir/usr/data/deepMedic/saved_models/skullStripping/
The version of model is incompatible with this version of CaPTk.
Finished successfully.

**Expected behavior**
run and give segmentation

**CaPTk Version**
CaPTk v1.7.7.nonRelease.20200129
-rwxr-xr-x. 1 patis cbica 10771472 Jan 28 14:36 /cbica/home/patis/projects/captk_myFork/bin/install/appdir/usr/bin/DeepMedic*

**Desktop (please complete the following information):**
cbica cluster

**Comment by sarthakpati** [comment]
This has been fixed in https://github.com/CBICA/CaPTk/commit/073610b49ba6d01ac142257453f4fe97b82dbc41. I will re-compile my fork on the cluster.
