### ISSUE TITLE
PseudoProgressionEstimator result is empty

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#818]
**Describe the bug**
output results.csv only includes header

> cat results.csv
> SubjectName,Score (Pseudo), Score (Recurrence)

**To Reproduce**
> qsub -j y -o $PWD/psp_20200130.log  -l h_vmem=36G  -b y /cbica/home/CaPTk/myFork/bin/PseudoProgressionEstimator -t 1 -i input/ -o output_20200131/ -m ~/CaPTk/PretrainedModels/PseudoProgressionEstimator_PretrainedModel_1.7.5/

**Expected behavior**
results.csv includes distances to hyperplane

**CaPTk Version**
CaPTk v1.7.6 on cbica-cluster
/cbica/home/CaPTk/myFork/bin/PseudoProgressionEstimator
merged from master on 1/27/2020

**Comment by chiharusako** [comment]
I am now using the cluster-wide install, and results.csv is still empty. Now it does not have the header information either.

**To Reproduce**
qsub -j y -o psp_20200207.log -b y -l h_vmem=36G /cbica/software/lab/captk/centos7/1.7.6/bin/PseudoProgressionEstimator -t 1 -i ./input -o ./output_20200206_captk176/ -m ~/CaPTk/PretrainedModels/PseudoProgressionEstimator_PretrainedModel_1.7.6 

**Result**
wc -l ./output_20200206_captk176/*

     63 PSU_SelectedTestFeatures.csv
     63 REC_SelectedTestFeatures.csv
     0 results.csv
     63 scaledtestingfeatures.csv
     63 testingfeatures.csv


**CaPTk Version**
/cbica/software/lab/captk/centos7/1.7.6/bin/captk

**Also requesting**
Please add headers for the 4 output feature csv files

**Comment by ashishsingh18** [comment]
@chiharusako Could you please share the data and model you were using for this?

Were you using model from 1.7.5 or 1.7.6? I see 1.7.5 from the first comment.

**Comment by chiharusako** [comment]
I'm using the 1.7.6 model. I did though just notice that it crashed at h_vmem=32G, so I ran with h_vmem=64G and it gave non-empty results.

However, the results.csv does not look right as the distances are very similar for all subjects. This should not be the case for these subjects. Can you please take a look?

input: 
/cbica/home/sakoc/comp_space/lab/Saima/20200117_captk175test/psp/2_HA63/input 

output: 
/cbica/home/sakoc/comp_space/lab/Saima/20200207_catpk176test/psp/2_HA63/output

model:
/cbica/home/sakoc/CaPTk/PretrainedModels/PseudoProgressionEstimator_PretrainedModel_1.7.6

log: 
/cbica/home/sakoc/comp_space/lab/Saima/20200207_catpk176test/psp/2_HA63/psp.log

**Comment by ashishsingh18** [comment]
> 
> 
> I'm using the 1.7.6 model. I did though just notice that it crashed at h_vmem=32G, so I ran with h_vmem=64G and it gave non-empty results.
> 
> However, the results.csv does not look right as the distances are very similar for all subjects. This should not be the case for these subjects. Can you please take a look?
> 
> input:
> /cbica/home/sakoc/comp_space/lab/Saima/20200117_captk175test/psp/2_HA63/input

@chiharusako I cannot find the input folder. Is the path correct?

**Comment by chiharusako** [comment]
Sorry, I forgot about this and moved the link. I jut put it back and it should be there now.

**Comment by ashishsingh18** [comment]
@chiharusako Is the input folder a 'link'? I am now getting weird errors just loading the data. I am working on windows and the code is not able to find any of the data that you shared although the data is there in the folder. Could you please confirm if the data is a link or not?

**Comment by chiharusako** [comment]
Yes, it is a link. I made a hard copy here:
/cbica/home/sakoc/comp_space/lab/Saima/20200207_catpk176test/psp/2_HA63/input

The link works on the cluster, command line, and reads all 63 subjects.

**Comment by ashishsingh18** [comment]
@chiharusako I am able to run this now. What are the expected results for these subjects? Is there a version of CaPTk that produced correct results?

**Comment by ashishsingh18** [comment]
@chiharusako This is isn't working on both 1.6.2 and 1.7.6 with the updated filenames. I am on Windows though.

**Comment by chiharusako** [comment]
I just tried on 1.6.2 on my windows and it works. Are you using the correct input?
/cbica/home/sakoc/comp_space/lab/Saima/20200207_catpk176test/psp/2_HA63/input

it also works on 1.7.6 on cluster.

**Comment by chiharusako** [comment]
@ashishsingh18 FYI, the output and log for running all 63 on 1.6.2 is here:
/cbica/home/sakoc/comp_space/lab/Saima/20200207_catpk176test/psp/2_HA63/output_w162

**Comment by sarthakpati** [comment]
The testing is now fixed. Training needs to be worked on; @saimarathore has been informed accordingly via email. Closing this.
