### ISSUE TITLE
Help dialogue not scaling

### ISSUE THREAD

**Issue by vishnubashyam** [CBICA/CaPTk#821]
## Expected Behavior
When rescaling the help dialogue, the toolbar should remain consistent and the text area should increase.

## Actual Behavior
Help dialogue does not scale upon resizing. Only the toolbar gets bigger.
![test-helpbug](https://user-images.githubusercontent.com/20879448/73695889-07a6a300-46a9-11ea-9dd4-3d013771152d.png)
## Steps to Reproduce the Problem

  1.  Go to the toolbar -> Help -> Usage

## Specifications

  - Version: 1.7.6
  - Platform: Linux
  - Subsystem: Ubuntu

**Comment by ashishsingh18** [comment]
This happens when the dialog gets resized vertically.
