### ISSUE TITLE
CLI Feature Extraction Problem

### ISSUE THREAD

**Issue by vishnubashyam** [CBICA/CaPTk#827]
**Describe the bug**
I am not sure if I am doing something else wrong but when attempting to run the feature extraction with CLI as a batch job, I am getting an error. 

**Here is my command:**
```bash
./captk FeatureExtraction  -p ~/Research/Brain_Tumor_Survival/List/Batch_and_parameter_files_for_FE_using_CaPTk/params_ibsi_mr_pruned.csv -o ./FE.csv -b /home/vishnu/Research/Brain_Tumor_Survival/List/Batch_and_parameter_files_for_FE_using_CaPTk/survival_batch_features_segmDM.csv 
```

**Here is the error I am getting:**
MULTIPLE INPUT PROVIDED
Please provide either a patient id or path to csv file containing patient details

 - CaPTk Version: 1.7.6
 - OS: Ubuntu Linux

**Comment by sarthakpati** [comment]
Hey Vishnu, thank you for posting! 

I was not able to find the batch file you are passing. If you could send it to me on email, I might be able to take a stab at debugging this. Thanks!

**Comment by vishnubashyam** [comment]
Sure no problem! I emailed you this.

**Comment by sarthakpati** [comment]
Possibly already addressed with https://github.com/CBICA/CaPTk/commit/7f87b2afbf206f5648b8bbacc5f2f9fc0b97fde0. @vishnubashyam, could you try running the same command from my home directory, ```/cbica/home/patis/testing/captkMyForkInstall/bin/```? Thanks.

**Comment by vishnubashyam** [comment]
Oh great, it is working from here. Thanks!
