### ISSUE TITLE
Converting DIcoms to Nifti using Command line gives Segmentation Fault 

### ISSUE THREAD

**Issue by parthsharma853** [CBICA/CaPTk#828]
**Describe the bug**
As I tried to convert the dicoms to nifti on the cluster using the captk documentation given in  https://cbica.github.io/CaPTk/preprocessing_dcm2nii.html 
It produced a segmentation fault

**To Reproduce**
I tried to run the Utilities with the following command:

./Utilities -i /Absolute_path_of_Directory_containing_Dicoms/ -d2n

It produces the following error:

HDF5-DIAG: Error detected in HDF5 (1.8.17) thread 0:
  #000: /cbica/home/patis/libs/captkDepends_dcmtk/ITK-source/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5F.c line 439 in itk_H5Fis_hdf5(): unable open file
    major: File accessibilty
    minor: Not an HDF5 file
  #001: /cbica/home/patis/libs/captkDepends_dcmtk/ITK-source/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Fint.c line 558 in itk_H5F_is_hdf5(): unable to locate file signature
    major: File accessibilty
    minor: Not an HDF5 file
  #002: /cbica/home/patis/libs/captkDepends_dcmtk/ITK-source/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDint.c line 146 in itk_H5FD_locate_signature(): unable to read file signature
    major: Low-level I/O
    minor: Unable to initialize object
  #003: /cbica/home/patis/libs/captkDepends_dcmtk/ITK-source/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDint.c line 211 in itk_H5FD_read(): driver read request failed
    major: Virtual File Layer
    minor: Read failed
  #004: /cbica/home/patis/libs/captkDepends_dcmtk/ITK-source/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDsec2.c line 707 in H5FD_sec2_read(): file read failed: time = Wed Feb  5 16:43:53 2020
, filename = '/**Absolute_path_of_Directory_containing_Dicoms/**', file descriptor = 3, errno = 21, error message = 'Is a directory', buf = 0x7ffc4de513b0, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0
    major: Low-level I/O
    minor: Read failed
Segmentation fault

**Desktop (please complete the following information):**
Linux on cluster

**Comment by ashishsingh18** [comment]
This is a documentation issue.

**Comment by ashishsingh18** [comment]
Fixed
