### ISSUE TITLE
PseudoProgressionEstimator: cannot get link to Penn model through command-line

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#830]
**Describe the bug**
The downloading of the pretrained model is only available from the GUI, and not on the command line. Can we please add the link in the -h?

**CaPTk Version**
/cbica/software/lab/captk/centos7/1.7.6/bin/captk

**Desktop (please complete the following information):**
cubic-login4

**Comment by MarkBergman-cbica** [comment]
Adding CLI downloads directly is an enhancement that's out-of-scope for the next release.

However, the CLI should provide documentation that the download can be down via the GUI, and the link should be added to the CLI help.

**Comment by sarthakpati** [comment]
Done.
