### ISSUE TITLE
CLI feature extraction on cluster

### ISSUE THREAD

**Issue by vishnubashyam** [CBICA/CaPTk#833]
**Describe the bug**
When running the CLI feature extraction on the cluster I am getting the following error:

Checking for compatible OpenGL - this will happen only once.
QOpenGLFunctions created with non-current context
Segmentation fault

**To Reproduce**
1. Log on to cluster with "ssh -X -Y ..."
2. module load captk/1.7.6
3. captk FeatureExtration [specify -o -p -b files]

1.7.6 on cluster

**Comment by sarthakpati** [comment]
To be clear, this is not related to #827.

Anyway, @vishnubashyam, could you try running ```captk FeatureExtraction -u``` in a session where you haven't added ```-XY``` to the ssh session?

**Comment by vishnubashyam** [comment]
When I run this, I am getting the expected output for the FE help message:

_Executable Name: FeatureExtraction v1.7.6_

_Usage:_

_Required parameters:_

_[  -o, --outputDir]         Absolute path of directory to save results_ 
                            _Result can be a CSV or Feature Maps (for lattice)_

...

**Comment by sarthakpati** [comment]
> When I run this, I am getting the expected output for the FE help message:
> 
> _Executable Name: FeatureExtraction v1.7.6_
> 
> _Usage:_
> 
> _Required parameters:_
> 
> _[ -o, --outputDir] Absolute path of directory to save results_
> _Result can be a CSV or Feature Maps (for lattice)_
> 
> ...

Did you try on a session where you did not have ```-X -Y``` present, just as a sanity check?

**Comment by vishnubashyam** [comment]
Yes, I should have mentioned this was without -X -Y

**Comment by sarthakpati** [comment]
Hey @vishnubashyam, is this still an issue? I remember having a conversation with you about this and  you mentioned that when you used a different machine, it worked.

**Comment by sarthakpati** [comment]
Closing because of lack of reply. Please re-open if persists.
