### ISSUE TITLE
GUI DICOM to Nifti Error

### ISSUE THREAD

**Issue by vishnubashyam** [CBICA/CaPTk#835]
**Describe the bug**
The DICOM to Nifti conversion on Linux gives the following error:
Couldn't convert the DICOM with the default parameters; please use command line functionality 

**To Reproduce**
1. Toolbar --> Preprocessing --> DICOM to Nifti
2. Specify Directories
3. See error

Ubuntu 18.04 - Linux - 1.7.6

**Comment by ashishsingh18** [comment]
@vishnubashyam Could you please attach a screenshot of the error and also point to what dicom data is giving this error? Please add a link to the data on the cluster if possible.

**Comment by ashishsingh18** [comment]
Just tested, this works fine on Windows. 
@dboun @AlexanderGetka-cbica can you please verify this on Linux?

**Comment by dboun** [comment]
@ashishsingh18 I tried it and it worked. 

The issue probably has to do with the specific data used. Looking through the code a bit, the conversion happens through invoking the CLI. This error message is thrown when the CLI finishes with some error return code.

Look at:

```bash
src/view/gui/fMainWindow.cpp:7620 # error message
src/view/gui/fMainWindow.cpp:72 # startExternalProcess
```

**Comment by dboun** [comment]
![captkerr](https://user-images.githubusercontent.com/39439832/74094378-301a0d00-4aae-11ea-9156-885103c353f4.png)


One way I managed to get the error message, which may or may not be what the issue is, is when I passed a directory that **existed** and was **empty**

**Comment by vishnubashyam** [comment]
Ahh okay, I see it was a problem with my data. I was able to get it working now.

Thanks for the help!
