### ISSUE TITLE
Dock can be permanently closed with Alt+F4

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#836]
**Describe the bug**
_title_ . Possibly linux only, or even Cinnamon DE-specific.

**To Reproduce**
1. Make sure data manager is undocked
2. Make sure data manager is focused by clicking on it
3. Press Alt+F4

**Expected behavior**
The dock window closing should be hijacked (only when undocked!) and should call the main window method, which checks with a messagebox if the user wants to exit CaPTk.

**Screenshots**
![captkerrw](https://user-images.githubusercontent.com/39439832/74094428-28a73380-4aaf-11ea-9625-171cc9281480.png)

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3 Cinnamon

**Comment by AlexanderGetka-cbica** [comment]
I am able to reproduce this on Ubuntu 18.04 running GNOME.
I suspect this has something to do with the windowing flags for the floating dock. Not sure how Qt or the OS handle force-quit on windows, subwindows, etc. 

In any case it should be possible to catch the closeEvent and propagate it to the main window to ask the user for confirmation.

**Comment by ashishsingh18** [comment]
Once the dock is closed, there is no way for the user to get to the dock for example to see the loaded images or access drawing etc.
