### ISSUE TITLE
Perfusion derivatives are wrong when minimum is outside assumed time range

### ISSUE THREAD

**Issue by parthsharma853** [CBICA/CaPTk#839]
**Describe the bug**

The perfusion derivative assumes that the first 0-20% of the timepoint can be considered baseline and 66-88% for recovery.

In the recent Penn scans we found images that have the minimum earlier within the first 20%, and the derivatives is not correct.

 

**To Reproduce**

/cbica/software/lab/captk/centos7/1.7.6/bin/PerfusionDerivatives -i input.nii.gz -e 45 -p 1 -pH 1 -r 1 -o outdir

 

**CaPTk Version**

1.7.6 on cluster

**Comment by sarthakpati** [comment]
Rolled in with #1281, closing.
