### ISSUE TITLE
Reorientation of Bval, Bvec files for dti

### ISSUE THREAD

**Issue by parthsharma853** [CBICA/CaPTk#840]
**Is your feature request related to a problem? Please describe.**
For dti images CaptK can reorient niftii images but not the bval & bvec files. This function will be needed to do the brain tumor pipeline in CaptK.

**Additional context**
Currently this is done manually, outside of CaptK.

**Comment by ashishsingh18** [comment]
@parthsharma853 can you share some data to try this?

**Comment by parthsharma853** [comment]
Hello @ashishsingh18 ,

You can find data at :

/cbica/home/sharmapa/comp_space/Testathon/nifti/ACSL

**Comment by ashishsingh18** [comment]
Fixed.
