### ISSUE TITLE
Investigate alternatives to Pyinstaller

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#843]
Investigate alternatives to Pyinstaller

PyOxidizer:

	https://github.com/indygreg/PyOxidizer
	https://pyoxidizer.readthedocs.io/en/latest/overview.html

Nuitka looks really promising too:
	https://github.com/Nuitka/Nuitka 
	http://nuitka.net/pages/overview.html

Nice comparison page:

	https://pyoxidizer.readthedocs.io/en/latest/comparisons.html

**Comment by sarthakpati** [comment]
Closing.
