### ISSUE TITLE
Rebuild/Repackage DeepMedic to eliminate Pyinstaller vulnerability

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#844]
Rebuild/Repackage DeepMedic to eliminate Pyinstaller vulnerability

**Comment by MarkBergman-cbica** [comment]
@sarthakpati  -- are you investigating this with pyinstaller?

**Comment by sarthakpati** [comment]
I have something for DeepMedic. Waiting for detailed feedback on the precompiled binaries before initiating PR.

**Comment by PhucNgo1711** [comment]
@sarthakpati We actually still used pyInstaller for the most recent update of DM. And for Hausdorff. Seems like @AlexanderGetka-cbica made some progress with Nuitka so maybe we can try it with DM, and Hausdorff?

**Comment by sarthakpati** [comment]
Let's not replicate work. New DM and Hausdorff are built using new PyInstaller so let them be.

**Comment by PhucNgo1711** [comment]
> Let's not replicate work. New DM and Hausdorff are built using new PyInstaller so let them be.

Oh can we use the new PyInstaller for Confetti and Theia then?

**Comment by sarthakpati** [comment]
If it works, I don't see why not. Whatever is easier, to be honest.

**Comment by PhucNgo1711** [comment]
> If it works, I don't see why not. Whatever is easier, to be honest.

So building them with pyinstaller 3.6 should be good right?

**Comment by AlexanderGetka-cbica** [comment]
The pyinstaller vulnerability was specifically for windows. Strictly speaking the new PyInstaller should be sufficient to fix the vulnerability for every application. But that's only if you can get it to build Confetti (which was built in python 2, if I'm not mistaken, and which I believe the new pyinstaller doesn't support.)

**Comment by ashishsingh18** [comment]
Is this done? @AlexanderGetka-cbica

**Comment by PhucNgo1711** [comment]
This was done by @sarthakpati . This can be closed.
