### ISSUE TITLE
Add version check for all models

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#847]
Add version check for all models

**Comment by dboun** [comment]
Why are we specifying maximum version etc?

A "minimum" version on the application side, and a "trained on" version on the model side should suffice for every need. 

If no one touches the code, the model won't suddenly break. If someone updates the code he could bump the minimum version if he makes changes that break past models. Unit tests that try models from each release could help automate this.

**Comment by ashishsingh18** [comment]
@CBICA/devteam We need to add the version check for different applications and also update the version file. Please check the applications you are already working on.
