### ISSUE TITLE
N4 Bias correction giving error

### ISSUE THREAD

**Issue by parthsharma853** [CBICA/CaPTk#848]
**Describe the bug**
After reorienting the images, as I tried to apply N4 Bias Correction, an ITK error was thrown.

**To Reproduce**
 **>Command:**
captk Preprocessing -i  **reoriented_nifti_file.nii.gz** -o **absolute_path_of_output_file** -n4

**>Error:**
terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  /cbica/home/patis/libs/captkDepends_dcmtk/ITK-source/Modules/Filtering/BiasCorrection/include/itkN4BiasFieldCorrectionImageFilter.hxx:157:
itk::ERROR: N4BiasFieldCorrectionImageFilter(0x33f99b0): Number of iteration levels is not equal to the max number of levels.

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
Linux on Cluster

**Comment by sarthakpati** [comment]
Fixed courtesy https://github.com/sarthakpati/CaPTk/commit/3b9be618224cfc3dea8301a50b9139bf1e206a5b#diff-05e49ba6bf4551886b0aac198a8208ad
