### ISSUE TITLE
GUI not responding when running Skull Stripping

### ISSUE THREAD

**Issue by DushyantSahoo** [CBICA/CaPTk#850]
**Describe the bug**
When using Skull Stripping from GUI, GUI shows CaPTk is not responding although the algorithm keeps on running on terminal.

**To Reproduce**
1. Go to 'preprocessing'
2. Click on 'Skull Stripping'
3. Error will come after few minutes

**Expected behavior**
The algorithm should run without forcing GUI to close.

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version (including Build information, if any): 18.04

**Comment by ashishsingh18** [comment]
Needs multi threading

**Comment by ashishsingh18** [comment]
This was addressed by adding a popup message by @sarthakpati. Closing.
