### ISSUE TITLE
[MAC] GUI DICOM to Nifti Documentation Issue

### ISSUE THREAD

**Issue by rongguangwang** [CBICA/CaPTk#852]
**Describe the bug**
The documentation of the conversion is not very clear. In step two, it said "Specify the first DICOM image in series, and the output filename.". However, when we open the directory of the DICOM image series. It is empty inside the folder. Actually, the conversion will work if we just press "Confirm". But it may mislead the users that the software is not working.

**To Reproduce**
1. Launch the tool using the 'Preprocessing' -> 'DICOM to NIfTI' menu option.
2. Specify the first DICOM image in series, and the output filename.
3. See this problem

**Expected behavior**
The DICOM image series in the directory shows up.

**Screenshots**
<img width="945" alt="Screen Shot 2020-02-14 at 10 50 09" src="https://user-images.githubusercontent.com/39313320/74545958-c8cde400-4f17-11ea-8d8a-b365c03442f4.png">

**CaPTk Version**
CaPTk_1.7.6

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.15.3 (19D76)

**Comment by ashishsingh18** [comment]
This is a documentation update. Tagged as 'Major' since it misleads end users.
