### ISSUE TITLE
[MAC] GUI DICOM to Nifti Error

### ISSUE THREAD

**Issue by rongguangwang** [CBICA/CaPTk#854]
**Describe the bug**
The software can't perform DICOM to Nifti conversion with error "Couldn't convert the DICOM with the default parameters; please use command line functionality".

**To Reproduce**
1. Launch the tool using the 'Preprocessing' -> 'DICOM to NIfTI' menu option.
2. Specify the first DICOM image in series, and the output filename.
3. Click on "Confirm".
4. See error.

**Expected behavior**
The converted NIfTI image show up.

**Screenshots**
<img width="426" alt="Screen Shot 2020-02-14 at 11 16 06" src="https://user-images.githubusercontent.com/39313320/74548183-670f7900-4f1b-11ea-8295-75941a5b71b9.png">

**CaPTk Version**
CaPTk_1.7.6

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.15.3 (19D76)

**Comment by ashishsingh18** [comment]
@rongguangwang Is there any specific dataset that is giving this error? Can you please share the data on either "S" drive at :  S:\CBICA\Ashish\Testathon-Feb-2020 or give the path to the data on the cluster?

**Comment by rongguangwang** [comment]
Sure, below is the path to the dataset I used for testing:

`/cbica/home/wangron/tumor/`

**Comment by ashishsingh18** [comment]
I can't access it. Can you please copy it to your comp_space and give permissions so I can copy them ?

**Comment by rongguangwang** [comment]
How about now?

**Comment by ashishsingh18** [comment]
Thanks, I can access it. I also tried the dataset. It was bad and that's why it was giving the error. It is compressed as bz2 and therefore not a valid dicom. Other dicom viewers or slicer or mitk workbench are also not able to handle this data.

We should have caught it though.

**Comment by rongguangwang** [comment]
Hi, Ashish

Many thanks for your input. Actually, I forgot to mention that I have
decompressed the dataset using

bzip2 -d <filename>.bz2

Maybe you can just do

bzip2 -d */*.bz2

to decompress the files.

It turns out that CaPTk can't do the conversion although the data is not
compressed.

Regards,
Rongguang

**Comment by ashishsingh18** [comment]
@rongguangwang It works for me with your data when decompressed. I tried it with one image. 
Can you please try it with one image and let us know if that works?

Also, please let us the know the steps you followed when it failed.

**Comment by rongguangwang** [comment]
I tried to use subject `10_flair`, and it didn't worked. Maybe you can test it?

**Comment by ashishsingh18** [comment]
I just tried one image from 10_flair folder and it works fine.

Please remember that all the dicom files in the input directory must be decompressed.

**Comment by ashishsingh18** [comment]
@rongguangwang  Have you tried this yet? The 10_flair data is working for me.

**Comment by rongguangwang** [comment]
@ashishsingh18 It works for single dicom series for me. But when you trying to consistently convert more series, it fails.

**Comment by ashishsingh18** [comment]
@rongguangwang I tried 4 series consecutively from the data you shared. It works for me. Can you please tell me specifically which dicom series you are tried when gave that error?

**Comment by rongguangwang** [comment]
@ashishsingh18 Somehow, it is working now! I guess there's some updates released?

**Comment by ashishsingh18** [comment]
@rongguangwang There is no new release yet. But I am glad that it is working for you. I will then close this issue.
