### ISSUE TITLE
Change data directory to $HOME/Documents/CaPTk from $HOME/CaPTk

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#857]
**Describe the bug**
Currently the data directory (the one that holds PretrainedModels/ and SampleData/) gets created inside $HOME/. 

This is unconventional and "pollutes" the home directory of the user, which typically contains os defined directories like Desktop/ and Downloads/ etc.

**Expected behavior**
Create it in Documents/ instead

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3

**Additional context:**
Also, does this directory ever get populated? When I click Help>Sample Data>* it opens my browser which downloads the data in Downloads/, like all browser files. The same happens for pretrained models from the various applications.

**Comment by sarthakpati** [comment]
This is no longer getting created #1187
