### ISSUE TITLE
CaPTk is not responding while using deep learning based segmentation

### ISSUE THREAD

**Issue by DushyantSahoo** [CBICA/CaPTk#864]
**Describe the bug**
When the deep learning based segmentation is used, after few minutes CaPTk gives a pop up saying that it is not responding. Also, when I press confirm to run the deep learning based segmentation, it gets stuck there although everything is running fine on the terminal.

**To Reproduce**
1. Go to 'Deep Learning'
2. Click on 'Segmentation'
3. Press Confirm

**Expected behavior**
Everything should run without giving error on GUI

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version (including Build information, if any): 16.04
**Additional context**

**Comment by ashishsingh18** [comment]
Needs multi threading..

**Comment by sarthakpati** [comment]
Addressed by adding a long-running application pop-up. Closing.
