### ISSUE TITLE
Confetti GUI doesn't launch on linux

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#865]
**Describe the bug**
Clicking Applications>Confetti does nothing

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3

**Comment by ashishsingh18** [comment]
@AlexanderGetka-cbica can you please test this with 1.8.0Alpha and close if not reproducible?

**Comment by AlexanderGetka-cbica** [comment]
I tried this from my Ubuntu workstation, sbia-pc152 and I can reproduce this in the 1.8.0.Alpha.

**Comment by AlexanderGetka-cbica** [comment]
Per the above PR, which has been merged, the ConfettiGUI can now actually be called from Linux. 

... But that doesn't necessarily solve the greater issue. The confetti GUI on Linux is run from the Python script directly. That script is written in Python 2.7 and needs several python modules as dependencies. So if the user has Python3 first in path, or doesn't have Confetti's dependencies, it will fail. We can consider using Nuitka to package the Linux version as we do on Windows.

**Comment by sarthakpati** [comment]
Honestly, I don't care if this doesn't get fixed. We have issues that **actually** need our attention.

**Comment by ashishsingh18** [comment]
Closing. Confetti has been disabled on Linux and macOS #1263
