### ISSUE TITLE
CaPTk is not responding while using deep learning based skull stripping

### ISSUE THREAD

**Issue by DushyantSahoo** [CBICA/CaPTk#866]
**Describe the bug**
When the deep learning based skull stripping is used, after a few minutes CaPTk gives a pop up saying that it is not responding. Also, when I press confirm to run the deep learning based skull stripping, it gets stuck there although everything is running fine on the terminal. 

**To Reproduce**
1. Go to 'Deep Learning'
2. Click on 'Skull Stripping'
3. Press Confirm

**Expected behavior**
 Everything should run without giving error on GUI

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version (including Build information, if any): 16.04

**Comment by AlexanderGetka-cbica** [comment]
@DushyantSahoo When the process is done running in the terminal (when it reports that skull stripping is done), does the CaPTk GUI remain frozen/stuck, or does it become usable again?

**Comment by ashishsingh18** [comment]
This seems like a multi threading issue...

**Comment by sarthakpati** [comment]
Addressed by adding a long-running application pop-up. Closing.
