### ISSUE TITLE
Not able to open ZScoringNormalizer

### ISSUE THREAD

**Issue by DushyantSahoo** [CBICA/CaPTk#867]
**Describe the bug**
I am not able to open ZScoringNormalizer option when I click on it.

**To Reproduce**
1. Go to 'Preprocessing'
2. Click on 'ZScoringNormalizer'

**Expected behavior**
Something should come up when I click on ZScoringNormalizer

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version (including Build information, if any): 16.04

**Comment by AlexanderGetka-cbica** [comment]
Duplicate of #858 (but reported on different non-windows platforms).

Both are fixed in my local branch, and a PR will be up shortly.
