### ISSUE TITLE
Documentation errors in command line Deep medic segmentation 

### ISSUE THREAD

**Issue by parthsharma853** [CBICA/CaPTk#869]
**Describe the bug**
The documentation for Deepmedic found at https://cbica.github.io/CaPTk/seg_DL.html has a couple of issues.

1) It says that selecting the pre-trained models is optional but when not specified gives the following error

'modelConfig.txt' was not found in the directory, please check.
Finished successfully.

2) The documentation doesn't specify the location of the pre-trained models

**To Reproduce**
Command:

>captk Deepmedic -t1  t1.nii.gz  -t2 t2.nii.gz -fl flair.nii.gz -t1c t1ce.nii.gz -o maskFinal.nii.gz -md

or
>captk Deepmedic -t1  t1.nii.gz  -t2 t2.nii.gz -fl flair.nii.gz -t1c t1ce.nii.gz -o maskFinal.nii.gz 

Error:

>'modelConfig.txt' was not found in the directory, please check.
Finished successfully.

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
Linux on cluster

**Comment by dboun** [comment]
Some notes: 
- The documentation should have the links to the pre-trained models for all algorithms (they are not included in captk), or explain that they can be obtained through the GUI (that will show people the paper information, which is desired, but it's also a lot of steps).
- The model is never optional. It is mandatory for inference and useless for training new models.

**Comment by ashishsingh18** [comment]
This is fixed
