### ISSUE TITLE
Survival Index Pretrained Model Cannot be Used

### ISSUE THREAD

**Issue by vishnubashyam** [CBICA/CaPTk#870]
**Describe the bug**

The downloadable model for the Survival Index prediction does not load within captk. 
I get the following error:

"The given SVM model directory does not have all the model files"

**Additionally, the file formats do not match those made when training a model from scratch.**

When training from scratch 4 files a produced: 2 .xml and 2 .csv
In the downloadable pretrained model: 4 .csv files

Simply changing the file extensions did not help.

Data to reproduce can be found on the cluster here: 
/cbica/projects/brain_tumor/Projects/Published_studies/2015_NeuroOncology_Survival/captk/1.7.6/1_test_102/input_vt_in_ptspaceonly/

CaPTk Version
1.7.6
Ubuntu 18.04

**Comment by vishnubashyam** [comment]
This seems to be working intermittently for me now. When I see this error, restarting captk seems to fix it. 

Please disregard my comment that the file types do not match. I am able to load both the official pretrained and locally trained models even with the differences in files formats.

**Comment by ashishsingh18** [comment]
@vishnubashyam Is this working for you now? Or is it still intermittent?

**Comment by vishnubashyam** [comment]
It is still intermittent but the problem is not with the pretrained model. Sometimes when I try to load a model (pretrained or locally trained) I am getting the stated error. I can't think of anything I am doing differently between when it works and when it doesn't.

**Comment by viraj28m** [comment]
Everytime i try to use any pretrained model for Glioblastoma survival prediction or GLioblastoma molecular subtype predictor- i get an error : Connection to nitrc failed.
How should i get around this?

**Comment by AlexanderGetka-cbica** [comment]
@viraj28m Can you please open a separate issue for this? Please include all the steps to replicate this behavior and preferably show us a screenshot of the error.

**Comment by saimarathore** [comment]
i could not reproduce the issue on my machine from CLI. Will try on different machines and open again if able to replicate it. @viraj28m can you please open a separate issue explaining the nitrc connection? Seems like a different problem.
