### ISSUE TITLE
Survival Prediction Error During Training

### ISSUE THREAD

**Issue by vishnubashyam** [CBICA/CaPTk#871]
**Describe the bug**
Although this has worked for me in the past I am now getting an error while training a model from scratch in the survival prediction module. I am using the Linux GUI. 

![Sur pred](https://user-images.githubusercontent.com/20879448/74774116-238d7580-5261-11ea-8a14-2b374cdc02d7.png)

Here is the log file mentioned:

2020:02:18,09:52:58;CaPTk;vishnu;applying DARK theme
2020:02:18,09:52:58;CaPTk;vishnu;file reading succeeded, qss file path = /tmp/.mount_captklC3AEF/usr/bin/../data/../etc/captk.qss
2020:02:18,09:56:44;CaPTk;vishnu;applying DARK theme
2020:02:18,09:56:44;CaPTk;vishnu;file reading succeeded, qss file path = /tmp/.mount_captkA6kxkL/usr/bin/../data/../etc/captk.qss
2020:02:18,10:49:11;CaPTk;vishnu;ftp://www.nitrc.org/home/groups/captk/downloads/SampleData_1.6.0/SurvivalPredictor_PretrainedModel.zip
2020:02:18,11:02:16;CaPTk;vishnu;Images size: 1900090
2020:02:18,11:02:16;CaPTk;vishnu;Total RAM: 33366110208
2020:02:18,14:37:25;CaPTk;vishnu;ftp://www.nitrc.org/home/groups/captk/downloads/SampleData_1.6.0/SurvivalPredictor_PretrainedModel.zip
2020:02:18,14:40:22;CaPTk;vishnu;ftp://www.nitrc.org/home/groups/captk/downloads/SampleData_1.6.0/SurvivalPredictor_PretrainedModel.zip
2020:02:18,14:40:33;CaPTk;vishnu;ftp://www.nitrc.org/home/groups/captk/downloads/SampleData_1.6.0/SurvivalPredictor_PretrainedModel.zip
2020:02:18,14:46:22;CaPTk;vishnu;applying DARK theme
2020:02:18,14:46:22;CaPTk;vishnu;file reading succeeded, qss file path = /tmp/.mount_captkxHflsU/usr/bin/../data/../etc/captk.qss
2020:02:18,14:56:29;CaPTk;vishnu;Training on the given subjects failed. Error code : OpenCV(3.4.7) /home/vsts/work/1/s/bin/OpenCV-source/modules/ml/src/svm.cpp:2119: error: (-212:Parsing error) SVM model data is invalid, check sv_count, var_* and class_count tags in function 'write'

2020:02:18,15:05:47;CaPTk;vishnu;Training on the given subjects failed. Error code : OpenCV(3.4.7) /home/vsts/work/1/s/bin/OpenCV-source/modules/ml/src/svm.cpp:2119: error: (-212:Parsing error) SVM model data is invalid, check sv_count, var_* and class_count tags in function 'write'

Here is the data I used:
/cbica/projects/brain_tumor/Projects/Published_studies/2015_NeuroOncology_Survival/captk/1.7.6/1_test_102/input_vt_in_ptspaceonly/

CaPTk 1.7.6
Ubuntu 18.04

**Comment by saimarathore** [comment]
fixed. will be closed after testing by an independent tester.

**Comment by saimarathore** [comment]
fixed and tested.
