### ISSUE TITLE
Survival Prediction Results

### ISSUE THREAD

**Issue by vishnubashyam** [CBICA/CaPTk#872]
**Describe the bug**

I have tested the survival prediction module (Linux GUI) using the following data for training and testing:

train: /cbica/projects/brain_tumor/Brain_Tumor_2020/Projects/20200217_old_Surival_study_inSRI/captk/1.7.6/1_test/input_training

test:
/cbica/projects/brain_tumor/Brain_Tumor_2020/Projects/20200217_old_Surival_study_inSRI/captk/1.7.6/1_test/input_testing

I am getting poor performance: 
AUC ~.55-.60

Perhaps there is a bug somewhere here.

CaPTk 1.7.6
Ubuntu 18.04

**Comment by saimarathore** [comment]
fixed. will be closed after testing by an independent tester.

**Comment by saimarathore** [comment]
fixed and tested.
