### ISSUE TITLE
Azure DevOps builds failing

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#877]
**Describe the bug**
The Xenial builds on DevOps are failing for all PRs:
- https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=1072&view=results
- https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=1075&view=results
- https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=1076&view=results

**To Reproduce**
1. Trigger Azure build

**Expected behavior**
All builds to pass [[ref](https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=1071&view=results)].

**Additional context**
Paging @PhucNgo1711.

**Comment by sarthakpati** [comment]
Stemming from the following message [[ref](https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=1079&view=logs&j=82538e74-49f1-5405-62cc-28b0e28fe542)]: ```##[error]No space left on device```

**Comment by PhucNgo1711** [comment]
With #883 this should be handled.

**Comment by ashishsingh18** [comment]
> 
> 
> With #883 this should be handled.

@PhucNgo1711 This has been working for the last year without #883. Did something change ?

**Comment by PhucNgo1711** [comment]
@ashishsingh18  Nothing on our end. It's Microsoft tweaking their VMs every once in a while.

**Comment by sarthakpati** [comment]
Closing this.
