### ISSUE TITLE
Crosshair vs Current slice information

### ISSUE THREAD

**Issue by sbakas** [CBICA/CaPTk#88]
When the "crosshair" is not visualized (after pressing "h") the "current slice" information should remain populated.

**Comment by ashishsingh18** [comment]
Are there any use cases where we don't want the information to be invisible?

**Comment by ashishsingh18** [comment]
As per discussion with @sbakas , we always want this info to be visible. I am making the modifications.

**Comment by ashishsingh18** [comment]
Done.
