### ISSUE TITLE
'Help > Support Links > Latest Downloads' not working

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#882]
**Describe the bug**
There should be an option for the user to go to the latest downloads page.

**To Reproduce**
1. 'Help > Support Links > Latest Downloads'
2. See nothing

**Expected behavior**
This should pop up a location on GitHub with links to all downloads.

**CaPTk Version**
1.7.6

**Additional context**
Initially reported by @PhucNgo1711.

**Comment by PhucNgo1711** [comment]
Looks like the `QAction` assigned to that option was never set to do anything. The action can be found in `src/view/gui/fMainWindow.cpp`

**Comment by sarthakpati** [comment]
> The QAction name is help_download, but not to be mistaken with the function help_Download in the same file.

Oh so poor choice of variable naming... Working on fixing this right now.

**Comment by sarthakpati** [comment]
Fixed.
