### ISSUE TITLE
Feature extraction didn't generate some of the features in TCGA paper Bakas, S, et al. 2017

### ISSUE THREAD

**Issue by vctorwei** [CBICA/CaPTk#885]
**Describe the bug**
Hi
I tried to reproduce features described in paper 'Advancing The Cancer Genome Atlas glioma MRI collections with expert segmentation labels and radiomic features'
https://www.nature.com/articles/sdata2017117/tables/5
Some feature described in the paper were not produced by Captk 1.7.3/1.5.1, however I need to reproduce all the features in order to compare with TCGA data.

**To Reproduce**
Captk 1.7.3 linux CLI mode batch mode with -d option  on Ubuntu18.04 
I used parameter file from windows' version 1.7.3 captk because somehow the data folder was not generated when installing linux captk.
[params_TCGA.zip](https://github.com/CBICA/CaPTk/files/4238247/params_TCGA.zip)

$captkdir/captk FeatureExtraction.cwl -o $codedir/Features/P309TEST.csv -p $codedir/Features/params_TCGA.csv -b $codedir/P309_batch_featureExtraction_test.csv -d

**Expected behavior**
Features that were described in the paper but not generated by captk 1.7.3 are following:(Some of them are explained in the help doc of 1.7.3 but some are not)
1.  GLCM: Correlation, SumAverage, Variance, Autocorrelation, (Dissimilarity is not in the help doc)
2.  GLRLM: GLV(grey level variance), RLV(run-length variance), those 2 features are not in the help doc of 1.7.3
3. Morphologic_Eccentricity in the paper was a single feature, however, Captk 1.7.3 generated a series of features like Morphologic_Eccentricity_-Label-1, Morphologic_Eccentricity_-Label-2 .... etc
4.  SOLIDITY_ED, SOLIDITY_ET etc, these volumetric features are not in the help doc

5. Spatial feature, DIST_Vent_TC(TC distance to ventricle) etc, this type of features might not be generated by feature extraction function in Captk, I would appreciate it if you could tell me how these type of features were generated.

**Screenshots**

**CaPTk Version**
Linux 1.7.3, Window 1.7.3, Windows 1.5.1

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04/Windows 10

**Additional context**
In the paper the version of Captk was not specified, it only said it was released on the 14th of October 2016, however, on NITRC, the earliest captk was released in 2017, please send me the version of captk or parameter files used in that paper, if the problems were due to the version or the parameters files.
My email is yw500@cam.ac.uk

Thank you.

Wei

**Comment by vctorwei** [comment]
I'm not sure if I should open a new issue, but there are another 2 problems
1. The default parameter files for window captk 1.7.6/1.7.3 are different from the one on github 
[1_params_default.zip](https://github.com/CBICA/CaPTk/files/4238365/1_params_default.zip)
2.  Linux 1.7.6 cannot be installed correctly after the below procedure, the install directory is empty, I cannot find where I installed it
![Screenshot from 2020-02-21 23-00-12](https://user-images.githubusercontent.com/49865495/75078665-1ccf5e80-54fe-11ea-8b4c-f80b2f6531a1.png)

Even after I add -target option and manage to install it in my directory, there are not data folders containing the parameter files for feature extraction or any other data files
![Screenshot from 2020-02-21 23-04-05](https://user-images.githubusercontent.com/49865495/75078941-e6461380-54fe-11ea-9ac9-96546d923373.png)

**Comment by sarthakpati** [comment]
Thank you for the report!

For point 2, please see https://cbica.github.io/CaPTk/FAQ.html#gs_FAQ_5

I will get in touch with you via email about point 1.

**Comment by ashishsingh18** [comment]
@sarthakpati We should be keeping the discussion on GitHub so it might help other users who run into similar issues.
