### ISSUE TITLE
documentation update on image visualization

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#889]
## Issue
It is hard to figure out from the documentation how to zoom a specific area of the image

Documentation notes
1. contrast/brightness: right mouse button click + horizontal/vertical drag on any visualization panel, respectively.
2. windowing of intensities and setting of different visualization type: bottom-right panel.
3. zooming into the image via Ctrl + mouse wheel.

It would greatly help if you add the instructions to 
move the image (Ctrl + left click + drag)

## Specifications

  - Version: 1.7.6
  - Platform: Ubuntu 18.10

**Comment by ashishsingh18** [comment]
Done.
