### ISSUE TITLE
Command line Affine Registration produces deformed image   

### ISSUE THREAD

**Issue by parthsharma853** [CBICA/CaPTk#898]
**Describe the bug**
Affine registration produces deformed image for 1/4 modalities.
The registration worked perfectly for t1ce but not for the rest of the modalities. 

The registration for the same works when done using:

/cbica/home/sakoc/software/greedy/v1.0.1/build/greedy

Greedy Version 1.0.1

  Release date:      Mar 21, 2019

  Compile date:      Jun 04, 2019

  GIT branch:        master

  GIT commit:        2a3f4e4d9812428ccdc73e1ab66dc94825b868fd

  GIT commit date:   2019-05-03 15:49:24 -0400

**To Reproduce**

1)In the cluster go to 

> /cbica/home/sharmapa/comp_space/Testathon/0_reorient/ACSL

2) Run the following command for t1(similarly for all the other modalities):

>captk Preprocessing -i ACSL_2019.02.28_t1_LPS.nii.gz -o ../../2_Registration/ACSL/ACSL_2019.02.28_t1_LPS_rSRI.nii.gz -rFI /cbica/home/sakoc/ATLAS/SRI/spgr_unstrip-RAI.nii.gz -reg

3)Output images found at 
>/cbica/home/sharmapa/comp_space/Testathon/2_Registration/ACSL

4) I've also recorded a log for t1 which can be found at:
>/cbica/home/sharmapa/comp_space/Testathon/2_Registration/ACSL/Error.log

5) For comparison the output using the Greedy mentioned above can be found at:

>/cbica/home/sharmapa/comp_space/Testathon/2_Registration/Chiharu_run_greedy_registration

**Expected behavior**
This is image produced by the greedy which is expected behavior:

![Screenshot from 2020-02-27 10-38-34](https://user-images.githubusercontent.com/58265133/75459593-e7879e00-594d-11ea-8e49-9f3854fcbe82.png)

**Error**
This is the image produced using captk registration.
![Screenshot from 2020-02-27 10-39-16](https://user-images.githubusercontent.com/58265133/75459742-6977c700-594e-11ea-9c12-ed8f81ae6000.png)

 

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
Linux on cluster

**Comment by sarthakpati** [comment]
This is happening in ```SSD``` configuration, sometimes. In the current master, all other configurations, i.e., NMI, NCC, are working fine. Closing the ticket; if I find any explanation about the SSD stuff, I will post here.
