### ISSUE TITLE
Rigid Registration not available on command line captk

### ISSUE THREAD

**Issue by parthsharma853** [CBICA/CaPTk#899]
**Describe the bug**
Command line captk doesn't give an option to perform Rigid registration.

GUI Captk application doesn't give option for deformable registration.

**To Reproduce**
1) Command line documentation provides the following:
Command
>  captk Preprocessing -h

Result

>[-reg, --registration]     The kind of registration to perform 
                           Defaults to 'Affine
                           Can use Mask File
                           Expected Type  :: STRING
                           Expected Range :: Affine | Deformable

Doesn't provide option for rigid registration 

2) In Captk application:

>Click on Preprocessing
>Click on Registration in the drop down.

It doesn't provide any option for Deformable registration.

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
Linux on cluster  |  Ubuntu 18.04.4 LTS

**Comment by sarthakpati** [comment]
Done.
