### ISSUE TITLE
GUI Bias Correction N4 or N3

### ISSUE THREAD

**Issue by vishnubashyam** [CBICA/CaPTk#900]
**Describe the bug**
In the GUI there could be an indication which bias correction is applied (N4 or N3) or some way to specify between them. 

Version 1.7.6
Ubuntu 18.04

**Comment by AlexanderGetka-cbica** [comment]
Just as a note, it seems like the GUI internally calls (the GUI-specific implementation of) N3 bias correction no matter what.

**Comment by ashishsingh18** [comment]
@AlexanderGetka-cbica Is this resolved?

**Comment by AlexanderGetka-cbica** [comment]
Yep, forgot to close this one too.
