### ISSUE TITLE
Cross Validated Scores for Predictors

### ISSUE THREAD

**Issue by vishnubashyam** [CBICA/CaPTk#901]
**Is your feature request related to a problem? Please describe.**
It is difficult to estimate the performance of a user trained model on any of the prediction modules.

**Describe the solution you'd like**
When training models on user-provided data it would be very helpful to have the cross-validated scores on the training data. This would allow users to evaluate the performance before applying it to new data without ground truth.

**Comment by dboun** [comment]
Cross-validation is an option in the training module. But for me it didn't, the Training Module window just closed when I clicked "Confirm" and nothing happened.

**Comment by saimarathore** [comment]
i have done the first part, mentioned by Vishnu, where he suggested to calculate SVM scores on the training data as well. Made that part of the PR#981. k-fold cross-validation and split-train-test both the options work from CLI. Will check from GUI once OpenGL issue is resolved. Keeping the issue open as of now.

**Comment by saimarathore** [comment]
this has been done as suggested.
