### ISSUE TITLE
Command line N-3 Bias Correction doesn't execute

### ISSUE THREAD

**Issue by parthsharma853** [CBICA/CaPTk#903]
**Describe the bug**
After executing the command specified in the documentation, system just freezes with no messages and doesn't respond until manual exit using Ctrl+Z

**To Reproduce**
Command:
>captk Preprocessing -i input_image.nii.gz -o output_dir/N3biascorrected.nii.gz -n3

Result:
There is no response on the screen and the program doesn't exit the execution until done so manually.

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
Linux on Cluster

**Comment by AlexanderGetka-cbica** [comment]
In my attempts to reproduce this, I have found that, on both my personal installation (Ubuntu 18.04) and on the cluster, N3 bias correction from the command line takes significantly longer than from the GUI. 
From the command line, using the "time" command, it took just over 3 minutes on the cluster and approximately 45 seconds on my machine.
On the GUI this took maybe 3 seconds max. Most of that was probably loading the image into CaPTk's visualizer, so essentially negligible. This disparity may be why it appears that the program has frozen.
@parthsharma853  can you please try to run it again, on a single image, and check it ~5 minutes later? It would be helpful to see if it is actually stuck/frozen or if it's just taking a really long time. It's still a problem either way, but it is useful to know which.

**Comment by parthsharma853** [comment]
Hi @AlexanderGetka-cbica ,

I tried it again on the cluster again and this was the result. It ran for approx. 27 minutes without any output at which point I terminated it. 

Here is the summary for reference:

I ran it in  /cbica/home/sharmapa/comp_space/Testathon/0_reorient/ACSL 

 time -p captk Preprocessing -i ACSL_2019.02.28_t1_LPS.nii.gz -o ../../5_N3biascorrection/ACSL/ACSL_2019.02.28_t1_LPS_N3biascorr.nii.gz -n3
^Z
[1]+  Stopped                 captk Preprocessing -i ACSL_2019.02.28_t1_LPS.nii.gz -o ../../5_N3biascorrection/ACSL/ACSL_2019.02.28_t1_LPS_N3biascorr.nii.gz -n3
real 1626.04
user 0.00
sys 0.00

**Comment by AlexanderGetka-cbica** [comment]
Okay, I am able to reproduce this using the same input. Investigating.

**Comment by AlexanderGetka-cbica** [comment]
Update: with this file, the N3 bias correction takes 38 minutes(!) to finish on the cluster. 
This image is 13 MB, while the image I tried initially is around 3 MB. 
However, on the GUI, the bias correction for this still takes almost no time at all.

**Comment by sarthakpati** [comment]
The implementations on the CLI and GUI should be the same. #900

**Comment by AlexanderGetka-cbica** [comment]
Just FYI, the GUI implementation's extra steps are derived exactly from those used in [ANTs. ](https://github.com/ANTsX/ANTs/blob/master/Examples/N3BiasFieldCorrection.cxx)
This is the tool that the analysts use, which is a fair indicator that the N3BiasCorrection.h code called from the GUI is the preferred implementation. I'm working on integrating that functionality into the CLI while making sure user-passed parameters still work right.

**Comment by sarthakpati** [comment]
Would it be possible to make the Bias correction schema generic so that one could pass either N3 or N4 and have a single ```cbicaBiasCorrection``` class to call with the rest of the parameters (i.e, filter width, noise level and so on) as options?

**Comment by AlexanderGetka-cbica** [comment]
Sure, I can do this.
