### ISSUE TITLE
Recurrence Infiltration Index Missing Data Error [GUI]

### ISSUE THREAD

**Issue by vishnubashyam** [CBICA/CaPTk#904]
**Describe the bug**
For the Recurrence Infiltration Index, I am getting this error even when I am providing a segmentation file with the correct labels:

![image](https://user-images.githubusercontent.com/20879448/75565476-ffc5ee80-5a1b-11ea-9a16-ed61035f1af0.png)

Input data can be found here: 
/cbica/home/sakoc/20200203_captktesting/input/Vishnu/Recurrence/input/

1.7.6
Ubuntu 18.04

**Comment by vishnubashyam** [comment]
This does work when specifying a folder in the batch mode.

**Comment by saimarathore** [comment]
Segmentation file needs to loaded as a mask, not as an image. 
Could not test from the front-end due to OpenGL issues, however, works from the command-line. Keeping it open until final testing. @ashishsingh18 @vishnubashyam

**Comment by ashishsingh18** [comment]
Tested this from GUI, it works fine. Segmentation needs to be added via File->Load->ROI
Tagging @vishnubashyam @saimarathore

**Comment by ashishsingh18** [comment]
Closing this.
