### ISSUE TITLE
EGFRvIII PHI Estimator Data Missing Error [GUI]

### ISSUE THREAD

**Issue by vishnubashyam** [CBICA/CaPTk#905]
**Describe the bug**

![image](https://user-images.githubusercontent.com/20879448/75565686-6519df80-5a1c-11ea-8037-cfd72aa45d32.png)

When running the EGFRvIII PHI Estimator, the GUI asks for nearfar labels even when they are present.

The documentation says that this Label file is command line only (not sure what that means):
![image](https://user-images.githubusercontent.com/20879448/75565693-6814d000-5a1c-11ea-9938-bc0627464ac1.png)

Data can be found here: 
~sakoc/20200203_captktesting/input/Vishnu/PHI/0_correct_input/

1.7.6
Ubuntu 18.04

**Comment by ashishsingh18** [comment]
@vishnubashyam could you please tell how you are loading the mask? The mask needs to be loaded via File->Load->ROI

**Comment by ashishsingh18** [comment]
@vishnubashyam I tried this with the data you mentioned and it worked without any errors.

**Comment by ashishsingh18** [comment]
@AlexanderGetka-cbica @dboun Can one of you try this on Ubuntu, since that is the OS mentioned in the initial bug report? I have tried this and it works fine on Windows.

**Comment by AlexanderGetka-cbica** [comment]
From the GUI, I attempted this with the EGFRVIII surrogate index (PHI estimator) sample data  after loading the near-far ROI through the File->Load->ROI menu and it seemed to work correctly.
The documentation for this should be clearer that these images and the ROI need to be loaded into CaPTk's image panel ahead of time.

**Comment by ashishsingh18** [comment]
@AlexanderGetka-cbica Have you tried with the data mentioned by @vishnubashyam ?

**Comment by AlexanderGetka-cbica** [comment]
@ashishsingh18 I lack the correct permissions to access that directory. 

@chiharusako  is it possible for you to allow read/execute access to that directory 
( /cbica/home/sakoc/20200203_captktesting/input/Vishnu/PHI/0_correct_input/ )
 for the purposes of testing whether this functionality fails with that data?

**Comment by chiharusako** [comment]
I put a copy here:
/cbica/home/sakoc/comp_space/lab/captk/1.7.6/PHI/0_correct_input

This data gives output in command-line (tested on cluster; result below), so I am thinking it is either a GUI issue on loading the data or documentation.

PHI Value = 0.106882
Peak Height Ratio = 1.6165
Number of near voxels used = 562
Number of far voxels used = 669
Finished successfully.

**Comment by ashishsingh18** [comment]
@chiharusako The mask needs to be loaded via File->Load->ROI

**Comment by vishnubashyam** [comment]
Ahh okay, I didn't know to use the File->Load->ROI. This fixed it for me.

It would be a good idea to put this in the documentation though.

**Comment by ashishsingh18** [comment]
Great..
