### ISSUE TITLE
PsP Estimator Data Error [GUI]

### ISSUE THREAD

**Issue by vishnubashyam** [CBICA/CaPTk#906]
**Describe the bug**
The PsP Estimator is not working with the pretrained model or when training a new model. When trying both features I am getting the following error even though the correct files are present:

![image](https://user-images.githubusercontent.com/20879448/75565943-e6717200-5a1c-11ea-911d-befc839ececb.png)

Data can be found here:
testing: /cbica/home/sakoc/20200203_captktesting/input/Vishnu/PsP/1_test_no_featurefile/input
training: /cbica/home/sakoc/comp_space/lab/Saima/20200117_captk175test/psp/3_Train40/input_HA40

GUI 1.7.6
Ubuntu 18.04

**Comment by vishnubashyam** [comment]
Also the testing does not work with the features.csv file included.
Data can be found here:
/cbica/home/sakoc/20200203_captktesting/input/Vishnu/PsP/2_test/input

**Comment by ashishsingh18** [comment]
@vishnubashyam **For testing:** The perfusion data that you are using at "1_test_no_featurefile/input" has incorrect name of 'AAMA_perf_truncated.nii.gz". Because the name is different than what is expected, you are getting that message.

**Comment by ashishsingh18** [comment]
> 
> 
> Also the testing does not work with the features.csv file included.
> Data can be found here:
> /cbica/home/sakoc/20200203_captktesting/input/Vishnu/PsP/2_test/input

@vishnubashyam I just tried this and it works for me just fine and writes the results in the output directory, although I am on Windows.

@AlexanderGetka-cbica can you please try this specific scenario on Ubuntu with the data that @vishnubashyam mentioned?

**Comment by sarthakpati** [comment]
The testing is using the sample data and pretrained model is now fixed #1173
