### ISSUE TITLE
Default param file not found, Feature Extraction for Mammography

### ISSUE THREAD

**Issue by ShyamDesai** [CBICA/CaPTk#910]
**Describe the bug**
Based on the CaPTk documentation, the Feature Extraction module ships with default parameters for 3D and 2D images. I attempted to run Feature Extraction application from the cluster on a processed mammography image and corresponding mask without specifying Feature Extraction params. I experienced the following error:
No default param file was found. Please set it manually using '-p'.

**To Reproduce**
1. ssh -X 
2. module unload captk
3. module load captk/1.7.6
4. /cbica/software/lab/captk/centos7/1.7.6/bin/FeatureExtraction -i /cbica/home/desaish/Tomo/Dx_images_nii/PROC_Mammo/3015854/3015854_L_CC_1.nii.gz -t FFDM -m /cbica/home/desaish/Tomo/Dx_mask_nii/PROC_Mammo/3015854/3015854_L_CC_1.nii.gz -o /cbica/home/desaish/Tomo/Dx_results/PROC_Mammo/output.csv

**Expected behavior**
Would expect something along the lines of Single subject computation, computation of selected features, and then output written to the -o path (output.csv).

**CaPTk Version**
1.7.6 Testathon

**Desktop (please complete the following information):**
Windows 10 Enterprise, Version 1809
OS Build 17763.973

**Additional context**

**Comment by sarthakpati** [comment]
Thanks for the bug report!

CaPTk does indeed ship with default parameter files (see ```${CaPTk_Install_Dir}/data/features/```) which are intended to be guidelines for users to follow to extract features. The idea is that users would customize the parameter file based on their study/data and then perform extraction.

> computation of selected features

The program explicitly does not make assumptions about any selections. One example: if the program decides to calculate texture features when the user only requires intensity, it would create an unnecessary computational overhead. 

Please respond to this issue with comments/queries.
