### ISSUE TITLE
Loading an image into CaPTk on desktop 

### ISSUE THREAD

**Issue by ChitaliaR** [CBICA/CaPTk#912]
**Describe the bug**
When I try to load a Nifti image saved on my cluster drive into CaPTk via the desktop interface, the program crashes

**To Reproduce**
1. Go to 'Load Image'
2. Select file from mapped drive location

**Expected behavior**
The image should load 

**Screenshots**
The program crashes without showing anything

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by ashishsingh18** [comment]
This is working just fine and I am unable to reproduce the issue. Tried it from multiple mapped drives.
