### ISSUE TITLE
Same parameter file produced different number of features by FeatureExtraction

### ISSUE THREAD

**Issue by vctorwei** [CBICA/CaPTk#915]
**Describe the bug**
Hi, There were 2 problems when I used feature extractions
1. I used same feature extraction parameter file but different number of features were extracted for different patients.
2. The other problem is that nan produced for some of the features, including:
NGLDM
Morphologic_X_Eccentricity(both X/Y/Z)
Morphologic_X_EllipseDiameter(both X/Y/Z)
etc...

**To Reproduce**
I tried both command line and batch mode
Code , parameters file and features files are attached.
[FE.zip](https://github.com/CBICA/CaPTk/files/4271779/FE.zip)

**Expected behavior**
I think same parameter should produce the same number of features?

**CaPTk Version**
1.7.3 Linux 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by vctorwei** [comment]
Sorry, I just figured out question 1 myself, the different number of feature was caused by different histogram bin size since I chosed FixedBinSize in the parameter, there will be different number of bin for histogram.

But I STILL need help for the nan values features

Thank you

**Comment by sarthakpati** [comment]
@vctorwei: Most of the features extract features _per-slice_ in addition to the **entire** ROI. For some of these, the per-slice feature result in zero; this is something that is determined by the math. You can completely disregard these features and only consider the ones that have the ```Axis=3D;Dimension=3D``` tag at the end.



@CBICA/devteam: I receive this question fairly regularly. Would it make sense to put the _per-slice_ computation as an option for users?

**Comment by ashishsingh18** [comment]
also, adding it in FAQs would make sense

**Comment by sarthakpati** [comment]
Addressed by https://github.com/sarthakpati/CaPTk/commit/59d64dc458b02add647a31b33198633ac47da8bd
