### ISSUE TITLE
Utilities Changing datatype: -c uchar does not work and documentation update on -c short 

### ISSUE THREAD

**Issue by chiharusako** [CBICA/CaPTk#918]
**Describe the bug**
-c uchar does not work. 
Also documentation does not list the ability to specify datatype to short which is useful.

Documentation:
[  -c, --cast]                Change the input image type 
                              Examples: '-c uchar', '-c float', '-c longlong'
                              Expected Type  :: STRING
                              Expected Range :: (u)char, (u)int, (u)long, (u)longlong, float, double

**To Reproduce**
This does not work
$ captk Utilities -i 1_perf_LPS_r1st.nii.gz -c uchar -o out.nii.gz 
Undefined pixel type cast requested, cannot process.

This does
$ captk Utilities -i 1_perf_LPS_r1st.nii.gz -c short -o out.nii.gz 
Casting completed.

**CaPTk Version**
1.7.6 on cluster

**Comment by sarthakpati** [comment]
Added a small sanity check for this. Please test on ```~patis/testing/captkMyForkInstall/bin/Utilities``` later in the week to see if this re-occurs and then we can open this ticket again.
