### ISSUE TITLE
Mask opacity is not changing

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#919]
**Describe the bug**
The opacity of the mask is not changing.

**To Reproduce**
1. Load images
2. Switch on comparison mode
3. Load ROI
4. Try to change mask
5. No difference in opacity is observed

**Expected behavior**
The opacity should change based on the combo-box under the drawing tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/11719673/75895440-a7b82f00-5e03-11ea-835a-2d95417de957.png)

![image](https://user-images.githubusercontent.com/11719673/75895466-b1419700-5e03-11ea-92a7-3471785b3e22.png)

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10.1909

**Comment by AlexanderGetka-cbica** [comment]
I can reproduce this bug on my machine.
However, there is a workaround in that you can switch back to 3D visualizer mode, change the opacity to the desired level, then change back to comparison mode and the mask opacity will remain at the chosen level.

**Comment by sarthakpati** [comment]
Comparison mode goes to @ashishsingh18
