### ISSUE TITLE
Image dimension mismatch on 2d mammo dicom

### ISSUE THREAD

**Issue by waltman** [CBICA/CaPTk#924]
**Describe the bug**
I'm testing the fixed code referenced in [issue 829](https://github.com/CBICA/CaPTk/issues/829). The good news is that it appears to now be reading in the dicom file. The bad news is that now it's failing with a different bug:

**To Reproduce**
```
$ pwd
/cbica/home/mankowsw/bin
$ /cbica/home/patis/testing/captkMyForkInstall/bin/FeatureExtraction -i /cbica/home/mankowsw/comp_space/captk/3009186_FOR-PROCESSING_L_CC_1/3009186_FOR-PROCESSING_L_CC_1.dcm -m /cbica/home/mankowsw/comp_space/captk/3009186_FOR-PROCESSING_L_CC_1_mask.nii.gz -o /cbica/home/mankowsw/cbig/TextureAnalysis-0.1/outdir_captk_202001/raw_mammo_captk -p 2_params_default_lattice.csv
Single subject computation selected.
Image Dimension mismatch. Return image is expected to be '3'D and doesn't match the image dimension read from the input file, which is '2'.
Segmentation fault
```

**Expected behavior**
I'm not sure since I've never managed to get `FeatureExtraction` to run successfully. But this is at least further along than before. Perhaps now my parameters are wrong?

**Screenshots**
N/A since I'm running from the command line on the cluster.

**CaPTk Version**
Version information is found on Help > About

`Executable Name: FeatureExtraction v1.7.7.nonRelease.20200306.3b75a41`

**Desktop (please complete the following information):**
I'm running this on `cubic-login1`

 - OS: [e.g. Windows/Linux (include detailed distro information)/macOS]
 - Version (including Build information, if any): [e.g. Fedora 22 or Windows 10.1803]

**Additional context**
N/A

**Comment by ashishsingh18** [comment]
@waltman are you using the same data that you used in #829 ? If yes, that data was indeed incorrect. There was a mismatch between the dimension and origin of the mask and input.

**Comment by waltman** [comment]
Yes, they're the same images as before. I just pulled them up in itksnap. I thought based on the discussion that one was facing left and the other right, but that doesn't seem to be the case.

It says that both images are 3328x4096x1. Under orientation, the origin is 0x0x0 and RAI. The mask is -0.065x-0.065x0 and LPI. Which of these is causing the problem?

**Comment by ashishsingh18** [comment]
Here are some of the properties of the 2 datasets you are trying to load. As seen the dimensions and origin for both are different. 
![image](https://user-images.githubusercontent.com/43445206/76130764-00412500-5fda-11ea-9dc6-ab01601dcb98.png)

**Comment by sarthakpati** [comment]
I have added another sanity check for these kinds of inputs. @waltman, could you please retry from ```~patis/testing/captkMyForkInstall/bin/FeatureExtraction```?

**Comment by waltman** [comment]
Now the output I get is
```
Single subject computation selected.
Origin mismatch at dimension '0'
The input image(s) and mask do not have consistent physical dimensions. Please resample and re-try.
```

I'll check with Omid and Aimilia and see if we can tweak how the Texture Pipeline code generates our masks.

**Comment by sarthakpati** [comment]
> Now the output I get is
> 
> ```
> Single subject computation selected.
> Origin mismatch at dimension '0'
> The input image(s) and mask do not have consistent physical dimensions. Please resample and re-try.
> ```
> 
> I'll check with Omid and Aimilia and see if we can tweak how the Texture Pipeline code generates our masks.

Which is exactly correct, if you look at the image information I posted from my previous comment. 

FYI, you can use the ```Utilities -inf``` command to verify the image information to ensure the veracity of generated masks. We have seen similar issues when masks are written from MATALB/Python.

**Comment by waltman** [comment]
After our conversation I went back and checked how I set up the Texture Pipeline. It is using LIBRA to generate the masks. However, LIBRA saves the masks as 2D binary matrices. The pipeline code reads that in, but it's the piece that's generating the nifti, not LIBRA.

**Comment by sarthakpati** [comment]
Unsure about the version of LIBRA. The one bundled with CaPTk produces the mask in the correct physical space.

**Comment by sarthakpati** [comment]
Discussion involves data exchange; happy to continue conversation virtually (email/Skype/whatever).

Not software-related, closing ticket.
