### ISSUE TITLE
[FeatureExtraction] NaN value handling

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#928]
**Describe the bug**
Feature Extraction might output some NaN values because of division by zero etc. Maybe we can offer an option on how to treat anavoidable nan values in Feature Extraction? Like "keep", "remove samples that contain nan values", "remove features that contain nan values". Also we should inform the user when Nan values exist in the output, regardless

Related to #712

**CaPTk Version**
1.7.6

**Comment by sarthakpati** [comment]
> Also we should inform the user when Nan values exist in the output, regardless

This already happens [[ref](https://github.com/sarthakpati/CaPTk/blob/master/src/applications/FeatureExtraction/src/FeatureExtraction.hxx#L1702)] but only for debug mode.

**Comment by sarthakpati** [comment]
Done.
