### ISSUE TITLE
GLRM_Z features returned as NaN 

### ISSUE THREAD

**Issue by ChitaliaR** [CBICA/CaPTk#929]
## Expected Behavior
The feature extraction outputs should all have specific values when running 3D feature extraction

## Actual Behavior
GLRM_Z feature values returning NaNs

## Steps to Reproduce the Problem

  1. Run feature extraction with parameters set for 3D feature extraction 
  2. Generate output file
  

## Specifications

  - Version: 1.7.6
  - Platform: Cluster
  - Subsystem:

**Comment by sarthakpati** [comment]
The per-slice computation has been converted to an optional parameter (https://github.com/CBICA/CaPTk/pull/927/commits/59d64dc458b02add647a31b33198633ac47da8bd). 

If you can provide the input image+mask offline, I can investigate further.

**Comment by sarthakpati** [comment]
Discussion involves data exchange; let's do this via email.

Not software-related, closing ticket.
