### ISSUE TITLE
Morphology_X, _Y, _Z features returning NaN Values

### ISSUE THREAD

**Issue by ChitaliaR** [CBICA/CaPTk#930]
## Expected Behavior
These features should return specific feature values

## Actual Behavior
NaNs are returned in the feature extraction output file

## Steps to Reproduce the Problem

  1. Run feature extraction with 3D parameters (single subject)
  2. Generate output file

## Specifications

  - Version: 1.7.6
  - Platform: Cluster
  - Subsystem:

**Comment by sarthakpati** [comment]
The per-slice computation has been converted to an optional parameter (https://github.com/CBICA/CaPTk/pull/927/commits/59d64dc458b02add647a31b33198633ac47da8bd). 

If you can provide the in put mask offline, I can investigate further.

**Comment by sarthakpati** [comment]
Discussion involves data exchange; let's do this via email.

Not software-related, closing ticket.
