### ISSUE TITLE
batch feature extraction does not seem to work the way it was working in 1.7.1

### ISSUE THREAD

**Issue by saimarathore** [CBICA/CaPTk#936]
**Describe the bug**
Batch feature extraction in 1.7.6 does not seem to work as it was working in 1.7.1. I used the following query to extract features in 1.7.1, and it worked:
C:\CaPTk_Full\1.7.1\bin> .\FeatureExtraction.exe -p \\cbica-cifs\cbica\home\rathores\comp_space\parameters_FE_CaPTk.csv -b \\cbica-cifs\cbica\home\rathores\comp_space\FeatureExtractionCommands_LGG.csv -o \\cbica-cifs\cbica\home\rathores\comp_space\output.csv

however the same query with the same input gave the following error message in 1.7.6. 

MULTIPLE INPUT PROVIDED
Please provide either a patient id or path to csv file containing patient details

**To Reproduce**
C:\CaPTk_Full\1.7.6\bin> .\FeatureExtraction.exe -p \\cbica-cifs\cbica\home\rathores\comp_space\parameters_FE_CaPTk.csv -b \\cbica-cifs\cbica\home\rathores\comp_space\FeatureExtractionCommands_LGG.csv -o \\cbica-cifs\cbica\home\rathores\comp_space\output.csv

Screenshot:
![image](https://user-images.githubusercontent.com/38562504/76899813-a577bb00-686e-11ea-98ff-4b620c245a04.png)

Please advise if there is any change in 1.7.6 in how input should be provided. 

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
 Windows

**Additional context**

**Comment by sarthakpati** [comment]
This has been fixed in the master. Unsure which commit fixes this. Please re-open if you can replicate on the master.
