### ISSUE TITLE
[FeatureExtraction] Cannot run batchmode on local install

### ISSUE THREAD

**Issue by jvbelenky** [CBICA/CaPTk#943]
**Describe the bug**
When attempting to run batchmode on my local machine, I get the following error:
![image](https://user-images.githubusercontent.com/35495855/77090155-21901100-69dd-11ea-80a4-7fd969f9e47c.png)

**To Reproduce**
[batchlist_UW_ser_alt.xlsx](https://github.com/CBICA/CaPTk/files/4355989/batchlist_UW_ser_alt.xlsx)
[3_params_default.xlsx](https://github.com/CBICA/CaPTk/files/4355990/3_params_default.xlsx)
1. Using provided files, type in command line: C:\CaPTk_Full\1.7.6\bin\FeatureExtraction -b H:\UW_Radiomic_Analysis\batchlist_UW_ser_alt.csv -p H:\UW_Radiomic_Analysis\3_params_default.csv -o H:\UW_Radiomic_Analysis\UW_output_ser_param3.csv

**CaPTk Version**
1.7.6

**Desktop:**
 - OS: Windows 10
 - PC: CBIG-KON-PC06

**Additional context**
Batchmode works fine when running on cluster (although only via Sarthak's directory--I remain unable to run feature extraction via the main install in lab/software/etc). Single line computation works correctly on my local machine as well.

**Comment by sarthakpati** [comment]
Hey @jvbelenky, this has been fixed in the master and will be made available in the next release. If you are interested to try out one of the nightly builds, please drop me an email and I will hook you up with the latest.
