### ISSUE TITLE
Overwriting on parameter file causing it to be zero if CaPTk was failing on one image

### ISSUE THREAD

**Issue by omaghsoudi** [CBICA/CaPTk#947]
CaPTk feature extraction module overwrites on the parameter files.
This is so annoying when the CaPTk fails to process the files causing the parameter file to be empty!

**Comment by omaghsoudi** [comment]
This problem has been resolve as:
https://github.com/CBICA/CaPTk/issues/798

**Comment by omaghsoudi** [comment]
w

**Comment by sarthakpati** [comment]
Finished, closed.
