### ISSUE TITLE
Issues for running FE on 2D image

### ISSUE THREAD

**Issue by omaghsoudi** [CBICA/CaPTk#948]
CaPTk feature extraction module mess up when the input image and mask have the same names!

**Comment by omaghsoudi** [comment]
This was an important and simple issue, we checked the cluster, files, and many other things, and we realized that the issue was CaPTk being designed based on considering the file names are different.

This reported as:
https://github.com/CBICA/CaPTk/issues/779

**Comment by sarthakpati** [comment]
Finished, closed.
