### ISSUE TITLE
The need for name of scan

### ISSUE THREAD

**Issue by omaghsoudi** [CBICA/CaPTk#950]
Why do CaPTk feature extraction module need asking for extra information? 
"-n" and "-t" are not needed for many studies.

Please exclude them and add initial values for these two parameters as it can be annoying.

**Comment by omaghsoudi** [comment]
I am not sure this issue has been resolved or not, but this is the same issue:

https://github.com/CBICA/CaPTk/issues/754

**Comment by sarthakpati** [comment]
I did mention you, I guess? 😛 

Finished already with #754, closing.
