### ISSUE TITLE
CaPTk issue for extracting features on large 3D files

### ISSUE THREAD

**Issue by omaghsoudi** [CBICA/CaPTk#952]
CaPTk 1.7.6 fails to extract features for large 3D images (2000*3000 pixels for each slice-- 90 slices).

Despite the CaPTk working on smaller images, it has the following issues for the large images:
1) It cannot generate the lattice-based image
2) extracting features are so slow
3) It needs a huge RAM 1TB or more to do so (resampling is 0.1 mm)

Solution:
CaPTk should have a mod for large images that do patch analysis instead of whole image analysis.

**Comment by sarthakpati** [comment]
Unfortunately, performing "patch-based" analysis will not be consistent with the IBSI protocol. If the images are that big and the parameters selected for performing feature extraction are that fine-grained, the user is expected to provide the corresponding computational power. 

This is a logistics issue and firmly goes in the category of "minimum height to go on the ride".

**Comment by omaghsoudi** [comment]
I get your reasoning but lattice is patch processing. If the image is so large, CaPTk can consider processing the lattice sections separately. This will significantly reduce the required RAM space. What do you think? 

However, I think it would be a mess for coding aspects :D

**Comment by sarthakpati** [comment]
CaPTk is already processing the lattice portions separately 😉. The RAM requirement spikes during the resampling, actually.

**Comment by omaghsoudi** [comment]
This is a nice engineering and geometry problem in my opinion. CaPTk can consider a version of patch processing to break down a large image into smaller images. We can talk about this. I really like this problem. 

You just need how much pixels/voxels of an image is needed to have one segment of lattice (2D/3D). Then you move that needed pixels/voxels on image to generate the new lattice segment.

It can be complicated but so useful for large images.

**Comment by sarthakpati** [comment]
So, I remember seeing the memory usage for one of these images. The processing is not where the OS chokes; it is the resampling (and this is consistent in Window and 2 different Linux distros), which leads me to wonder if this is something that ITK folks should know about...

**Comment by sarthakpati** [comment]
Hey @omaghsoudi, I am closing this ticket; please re-open as needed. 😄
