### ISSUE TITLE
Documentation for parameters file

### ISSUE THREAD

**Issue by omaghsoudi** [CBICA/CaPTk#954]
CaPTk feature extraction documentation is weak in my opinion. It is so hard to understand that feature have combined, individual, .....

Someone should sit and clarify the variables in another file or webpage, rather than briefly describing them in the parameter file that no-one can understand them. Please add some images to clarify what each of the parameters is supposed to do (at least major parameters do). Also, how users should select them.

**Comment by sarthakpati** [comment]
Great point, @omaghsoudi. Once again, paging @gastouna

**Comment by mdv63oda** [comment]
> CaPTk feature extraction documentation is weak in my opinion. It is so hard to understand that feature have combined, individual, .....
> 
> Someone should sit and clarify the variables in another file or webpage, rather than briefly describing them in the parameter file that no-one can understand them. Please add some images to clarify what each of the parameters is supposed to do (at least major parameters do). Also, how users should select them.

**Comment by mdv63oda** [comment]
Hi, I agree with @omaghsoudi . I extracted the features for my digital mamography sample cases but I do not understand what values refer to 
skewness, coarseness, contrast, gray level correlation, fractal dimension, homogeneity, etc. out of 6761 rows of parameters.
Additionally, there are so many #NAME? in my csv worksheet. 
Please help.

**Comment by sarthakpati** [comment]
> I do not understand what values refer to TOTAL skewness, coarseness, contrast, gray level correlation, fractal dimension, homogeneity, etc.

Depending on how you have extracted the features, these would be present as either

`Modality_ROI_FeatureFamily_Feature`

Or

`Modality,ROI,FeatureFamily,Feature`

> There are 6761 rows of parameters

These are the total number of features

> Additionally, there are so many #NAME? in my csv worksheet.

These would be NaNs. Depending on how you have extracted the features, these are completely normal.

**Comment by sarthakpati** [comment]
This should not be addressed thanks to @gastouna and @ChitaliaR
