### ISSUE TITLE
CaPTk feature extraction needs a better description about resampling value selection

### ISSUE THREAD

**Issue by omaghsoudi** [CBICA/CaPTk#955]
I think the CaPTk needs to clarify the importance of resampling value in its calculations. Although this is a general concept, but a user should be able to rely on your documentation and use the software.

Please add an explanation about extrapolation/interpolation methods and it's positive and negative aspects for users.

**Comment by sarthakpati** [comment]
Great point, @omaghsoudi. I wonder where this would provide the maximum impact. I am always torn between having users "be **this** tall to ride" vs "here is something you simply **cannot** mess up".

Paging @gastouna

**Comment by sarthakpati** [comment]
Done.
