### ISSUE TITLE
Cannot run CaPTk feature extraction with multi values for parameters

### ISSUE THREAD

**Issue by omaghsoudi** [CBICA/CaPTk#956]
CaPTk feature extraction does not get multivariable for the parameter file. 

This is a bug to be fixed as I might want to run a feature family with the different parameters at the same time, but CaPTk does not allow me unless I run it again which is not good.

**Comment by sarthakpati** [comment]
Duplicate of #931. I have already implemented the option for users to pass bin and radius in ranged values (i.e., ```Min:Step:Max```). If there are other parameters you think should be added, let me know.

**Comment by omaghsoudi** [comment]
This is really good; so can I apply different LBP radii using Min:step:Max?

**Comment by sarthakpati** [comment]
Yes, sir! Any parameter that takes a radius or bin can be done that way. You can access the latest master from my home directory on the cluster. Can this be closed, then?

**Comment by omaghsoudi** [comment]
Awesome! tnx 👍
