### ISSUE TITLE
Low correlation with similar classes of PyRadiomics features

### ISSUE THREAD

**Issue by ApuSingh** [CBICA/CaPTk#957]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**CaPTk Version**
Version information is found on Help > About

**Desktop (please complete the following information):**
 - OS: [e.g. Windows/Linux (include detailed distro information)/macOS]
 - Version (including Build information, if any): [e.g. Fedora 22 or Windows 10.1803]

**Additional context**
We found the following feature classes to be common between CapTk and PyRadiomics. The classes with number of common features are as follows:
Class Name                                            Number of common features
GLCM                                                        2
Morphological                                          2
GLRLM                                                      4
Intensity                                                   12
GLSZM                                                     16
I double-checked the formula for calculating these features and found that CapTk also used the same formula to compute features as PyRadiomics had used. However, the correlation between the feature groups varied between -0.1 to 0.69.
My doubt here is that if the formula used for computing features is the same, why are the correlation values not higher?

**Comment by omaghsoudi** [comment]
This is also true about the CBIG texture pipeline. The features of the same class are not correlated with CaPTk features which would be interesting to dig deeper. I did 53 features and half were correlated and the other half not.

**Comment by ApuSingh** [comment]
Yes, it is interesting to note that even when same formulae are used for computation, then also the correlation is low.

**Comment by sarthakpati** [comment]
CaPTk's features are highly dependent on the preprocessing and parameters getting passed. Omid and I have had long discussions about this in person (ah, the pre-COVID19 days) and on email. Happy to continue this discussion offline. 

Not software-related. Closing the ticket.

**Comment by omaghsoudi** [comment]
Apurva, as Sarthak said, the resampling can be an important factor for comparison. Even for CBIG texture pipeline comparison with CaPTk, back in the days that I was running the comparisons, I did not keep the resampling and pixel spacing constant.

I will redo the comparison by keeping the resampling as same as pixel spacing to make sure the comparison will be similar between CaPTk and CBIG pipeline. 

For our study, you need to make sure that CaPTk and Pyradiomics looking at the same physical dimension as we have discussed in the meeting. You can ask more from me, Sarthak, or Bardia if needed.
