### ISSUE TITLE
Survival prediction performance of CapTk features not comparable with PyRadiomics

### ISSUE THREAD

**Issue by ApuSingh** [CBICA/CaPTk#958]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**CaPTk Version**
Version information is found on Help > About

**Desktop (please complete the following information):**
 - OS: [e.g. Windows/Linux (include detailed distro information)/macOS]
 - Version (including Build information, if any): [e.g. Fedora 22 or Windows 10.1803]

**Additional context**

Prediction model was built combining all CapTk features and another model built combining all PyRadiomics features.
Kaplan Meier curves were plotted to evaluate both these models.
PyRadiomics model KP curve improved drastically on adding the clinical features (Stage, Gender and Histology). However, CapTk model KP curve remained the same even on addition of clinical features.
![bug_1](https://user-images.githubusercontent.com/62443820/77197786-24adfe80-6abc-11ea-8d3d-cd667063494d.PNG)

**Comment by sarthakpati** [comment]
CaPTk's features are highly dependent on the preprocessing and parameters getting passed. Discussion taken to email in order to share data. 

Not software-related. Closing the ticket.
