### ISSUE TITLE
CaPTk feature extraction will work on default values if it fails reading parameter file

### ISSUE THREAD

**Issue by omaghsoudi** [CBICA/CaPTk#959]
CaPTk feature extraction uses the default features if it fails to read the parameter file for any reason.

This is not good, the software should fail to extract features if a user provides parameter file and either the file is corrupted (empty or in a wrong format) or the file path does not exist.

**Comment by sarthakpati** [comment]
Hmm. I am unable to reproduce this, Omid; even the code doesn't use a default parameter file [[ref](https://github.com/CBICA/CaPTk/blob/master/src/applications/FeatureExtraction/src/FeatureExtraction.cxx#L394)]. Could you please give me an example of this?

**Comment by omaghsoudi** [comment]
This is when the parameter file is empty (exits but with zero size); If the file exists but it is not in the format that CaPTk expects, what does it happen? 

This is based on the following issue:
https://github.com/CBICA/CaPTk/issues/798

however, you fixed the above-mentioned bug (798), the CaPTk FE would still work if the parameter file is corrupted with default values instead of putting an error and stop working.
I can try it again and see how it works with the newer version of CaPTk (1.7.6) and send you an example (I think the issue is still there) ;)

**Comment by sarthakpati** [comment]
> If the file exists but it is not in the format that CaPTk expects, what does it happen?

Ah, I am not sure how this is getting tackled, let me check. #798 was something different, I believe.

**Comment by omaghsoudi** [comment]
Sure Sarthak; tnx for checking it.
