### ISSUE TITLE
Feature Extraction CLI

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#96]
If no ROI_value is passed, the computation should happen for **ALL** available ROIs and they should be used in the csv headers.

**Comment by sarthakpati** [comment]
Fixed.

**Comment by sbakas** [comment]
The CLI does not work for multiple subjects

**Comment by sarthakpati** [comment]
This has been fixed (r.3625) and is pending testing using a real-world example by Sung.

**Comment by sarthakpati** [comment]
That rev seems to have fixed this issue. Closing.
