### ISSUE TITLE
Phenotype analysis shows a lot of collinearity between CapTk features

### ISSUE THREAD

**Issue by ApuSingh** [CBICA/CaPTk#960]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**CaPTk Version**
Version information is found on Help > About

**Desktop (please complete the following information):**
 - OS: [e.g. Windows/Linux (include detailed distro information)/macOS]
 - Version (including Build information, if any): [e.g. Fedora 22 or Windows 10.1803]

**Additional context**
We performed phenotype analysis using unsupervised clustering techniques to visualize the radiomic phenotypes using CapTk and PyRadiomics features.
We saw a discrepancy in the CapTk feature heatmap. It showed that a lot of CapTk features were highly collinear, or maybe have the same values.
![bug_2](https://user-images.githubusercontent.com/62443820/77198523-7d31cb80-6abd-11ea-83a8-bcef3d6b6337.PNG)
![bug_3](https://user-images.githubusercontent.com/62443820/77198527-81f67f80-6abd-11ea-94f3-82ad937f357e.PNG)

**Comment by sarthakpati** [comment]
General feedback and not an issue. Closing.
