### ISSUE TITLE
Getting different numbers of features for batchmode vs single-line feature extraction

### ISSUE THREAD

**Issue by jvbelenky** [CBICA/CaPTk#966]
**Describe the bug**
When running feature extraction on the same dataset with the same parameter file (over cluster), batchmode produces features up to Excel column RF, but single-line computation produces features all the way up to AAX (for a GLRM/GLCM/etc radius of 1) or up to ABN (for a GRLM/GLCM/etc radius of 2 or 4)

**To Reproduce**
This command for batchmode:
```bash
~patis/testing/captkMyForkInstall/bin/FeatureExtraction -b ~/UW_Radiomic_Analysis/batchlist_UW_first.csv -p ~/UW_Radiomic_Analysis/1_params_default.csv -o ~/UW_Radiomic_Analysis/UW_output_first_param1_03.23.csv
```

This one for single-line:
```bash
qsub -t 1-79 CAPTK_feature_extraction.sh UW_inputs_first_03.19.list UW_output_first_1_03.19.list UW_masks_03.19.list 1_params_default.csv 
```

**Expected behavior**
Previous builds had produced features only up to TU or so; that's what Rhea is getting and I'm unsure why I'm not getting the same thing.

**CaPTk Version**
1.7.7.nonRelease.20200321.6d7ad3a

**Desktop (please complete the following information):**
Windows 10, CBIG-KON-PC06

Run with batchmode: [UW_output_first_param1_03.23.xlsx](https://github.com/CBICA/CaPTk/files/4370952/UW_output_first_param1_03.23.xlsx)

Run with single line:  [UW_results_first_1_03.19.xlsx](https://github.com/CBICA/CaPTk/files/4370956/UW_results_first_1_03.19.xlsx)

**Comment by sarthakpati** [comment]
That is because in the current master, the per-slice computation has become optional, so all the ```_X```, ```_Y``` and ```_Z``` features do not get extracted.
