### ISSUE TITLE
Extension Manager doesn't work on linux

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#976]
**Describe the bug**
Extension Manager doesn't work on linux

@PhucNgo1711 

**To Reproduce**
1. Click libra batch mode
2. Click on download etc
3. Wait for it to finish downloading
4. Wait to see that it finishes "inflating" \* in the terminal
5. Click on libra batch mode again
6. It shows the popup from the screenshot that ends in "Do you want to install it?"
7. Click OK
8. The other window that says "captk" shows up and does nothing. Clicking cancel on it causes the whole application to force quit

\* I'm assuming inflating means extracting. It is a lot of lines that say something like
```
  inflating: /home/dimitris/.CaPTk/1.7.7.nonRelease.20200325.e7678660/apps/libra/Mathworks/MCR/v81/uninstall/java/jar/zh_CN/web_connectivity_res.jar  
  inflating: /home/dimitris/.CaPTk/1.7.7.nonRelease.20200325.e7678660/apps/libra/Mathworks/MCR/v81/uninstall/java/splash.png 
```

**Screenshots**
![captk error](https://user-images.githubusercontent.com/39439832/77546927-34ab5100-6eb5-11ea-9269-fdcb4bd7e0de.png)

**CaPTk Version**
1.7.7nonRelease

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3 Cinnamon

**Additional context**
The extracting step should also show some sort of feedback on the GUI and not happen "secretly" in the background

**Comment by ashishsingh18** [comment]
Already handled via #883. Duplicate
