### ISSUE TITLE
Feature extraction: all NGLDM features throwing NaNs in all or nearly all cases

### ISSUE THREAD

**Issue by jvbelenky** [CBICA/CaPTk#998]
**Describe the bug**
For a dataset of 178 cases and 3 different possible parameter files, all cases (for regular post-contrast images) or nearly all cases (for signal enhancement ratio maps) are producing NaNs for all NGLDM features. Other features seem to behave as expected. 

**To Reproduce**
Run these commands located inside directory cbica/home/belenkyv/UW_Radiomic_Analysis (copy over relevant files) 

qsub -t 1-89 CAPTK_feature_extraction.sh UW_case_IDs.list UW_inputs_first.list UW_masks.list 1_params_default.csv UW_output_first_1.list
qsub -t 1-89 CAPTK_feature_extraction.sh UW_case_IDs.list UW_inputs_ser.list UW_masks.list 1_params_default.csv UW_output_ser_1.list 

qsub -t 1-89 CAPTK_feature_extraction.sh UW_case_IDs.list UW_inputs_first.list UW_masks.list 2_params_default.csv UW_output_first_2.list
qsub -t 1-89 CAPTK_feature_extraction.sh UW_case_IDs.list UW_inputs_ser.list UW_masks.list 2_params_default.csv UW_output_ser_2.list

qsub -t 1-89 CAPTK_feature_extraction.sh UW_case_IDs.list UW_inputs_first.list UW_masks.list 3_params_default.csv UW_output_first_3.list 
qsub -t 1-89 CAPTK_feature_extraction.sh UW_case_IDs.list UW_inputs_ser.list UW_masks.list 3_params_default.csv UW_output_ser_3.list 

**Expected behavior**
Values of some sort; not sure which, but don't think every single case (or nearly so) should be throwing NaNs.

**Screenshots**

**CaPTk Version**
Nonrelease version located here ->  /cbica/home/sakoc/CaPTk/myFork/bin/install/bin/FeatureExtraction

**Comment by sarthakpati** [comment]
Thanks for the report! This feature has not been fully implemented and should not be used in the parameter file.
