### ISSUE TITLE
Add option to apply mask in the drawing tab (this is available on Utilities)

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#999]
**Is your feature request related to a problem? Please describe.**
Currently, after getting the skull-stripped mask, there is no way to apply this mask to the image and proceed with tumor segmentation.

**Describe the solution you'd like**
An option to apply the mask to the input image(s) in an easy way (currently, this is present in the Utilities via the CLI).

**Comment by sarthakpati** [comment]
Paging @ashishsingh18 on where this would be the most appropriate.

**Comment by ashishsingh18** [comment]
@sarthakpati I don't understand this fully yet. Where is the segmentation tab?

**Comment by sarthakpati** [comment]
Ah, I actually meant the "Drawing" tab.

**Comment by sarthakpati** [comment]
Basically something like this: 

![Untitled](https://user-images.githubusercontent.com/11719673/79694930-ad49c700-8241-11ea-9a81-95644b1b361f.png)

When the user would click the button, the loaded ROI (all non-zero are treated the same way) would get applied to all loaded images.

**Comment by ashishsingh18** [comment]
Are you referring to the display of mask that happens for instance via readMaskFile() function?

Can you point to where this is available in Utilities?

**Comment by sarthakpati** [comment]
I am talking about tying that button with ```itk::MaskImageFilter``` [[ref](https://itk.org/Doxygen/html/classitk_1_1MaskImageFilter.html)]. We apply the currently displayed/loaded mask (treating it as a binary image) and apply it to all loaded images. 

In Utilities, it is happening [here](https://github.com/CBICA/CaPTk/blob/master/src/applications/Utilities/src/Utilities.cxx#L741).

**Comment by ashishsingh18** [comment]
@sarthakpati How does [this ](https://github.com/ashishsingh18/CaPTk/blob/dea6d23ceb829250eb87517c5d82945d2da7b149/src/view/gui/fMainWindow.cpp#L3132)look? We are applying the mask on all images, saving them in temp directory and reloading them into captk.

**Comment by sarthakpati** [comment]
This works just fine! Thanks.

**Comment by ashishsingh18** [comment]
> 
> 
> This works just fine! Thanks.

Great. I created a PR for this. #1011
